### PR TITLE
Endpoint_Status: Optimize DB (remove redundancy)

### PR DESCRIPTION
**Pull request by kiblik**
|              |                                    | F1(226) | F2(227)            | F3(228)                                  | F4(229)                                | F5(230)                                | F6 (231) mitigated  |
|--------------|------------------------------------|----|---------------|-------------------------------------|-----------------------------------|------------------------------------|---------------|
| Host foo.bar | Endpoint(4) ftp://foo.bar          | x  | x             | x                                   | x                                 | x                                  | x             |
|              | Endpoint(5) http://foo.bar         | x  | mitigated     | not mitigated<br>but false positive | not mitigated<br>but out of scope | not mitigated<br>but risk accepted | x             |
| Host bar.foo | Endpoint(6) http://bar.foo         | x  | mitigated     | x                                   | x                                 | x                                  | x             |
|              | Endpoint(7) https://bar.foo        | x  | not mitigated | x                                   | x                                 | x                                  | x             |
|              | Endpoint(8) <br>https://bar.foo/f6 | x  | x             | x                                   | x                                 | x                                  | not mitigated |

### CODE REVIEW

**Comment by devGregA** [comment]
@kiblik  this is a great PR, are we okay to move out of draft?

**Comment by kiblik** [comment]
> @kiblik this is a great PR, are we okay to move out of draft?

@devGregA, thank you for the feedback but implementation is not ready. Some parts are missing and I need to add also tests.

I didn't have enough time to finish it. I hope it will change soon.

**Comment by kiblik** [comment]
@devGregA, @Maffooch, this PR is ready.

**Comment by devGregA** [comment]
Awesome! @kiblik will make it a priority to review with haste. Early next week will be the soonest as Cody is also out right now.

**Review by Maffooch — APPROVED** [review]
Did a quick live test and everything looks good to me! Great job on this

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
