### PR TITLE
fixed nuclei report parser

### PR DESCRIPTION
**Pull request by yelsanya**
Nuclei seems to change names of variables in json reports, fixed nuclei report parser to match these names

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Thanks. Can you add a unit tests with these new names/tags? And retain support for the old tags as well. We can't support all versions of all parsers, but in this case I think it's quite easy to retain backwards compatability.

**Comment by yelsanya** [comment]
Sure, I will tag you when it will be done

**Review by Maffooch — CHANGES_REQUESTED** [review]
please rebase you changes to the `dev` branch. 
It would also be best to make the parser backward compatible with the old format so that both can be used.

**Comment by StefanFl** [comment]
superseded by #6103

**Pull request closed without merging**
