### PR TITLE
Make PostgreSQL database the default for containerized deploys

### PR DESCRIPTION
**Pull request by Maffooch**
MySQL supports case insensitivity out of the box which makes searches and exact match operations more challenging/ineffective. We have been talking about not supporting MySQL in v3 already as well. This is a good first step to test the waters
[sc-963]

### CODE REVIEW

**Comment by testaccount90009** [comment]
Out of curiosity - for those that are on a docker-compose default mysql deployed version, is there any proposed plan for migrating the mysql data into a postgresql database?

**Comment by Maffooch** [comment]
@testaccount90009 I am speculating here as dojo v3 is still in the design phase, but the migration will more than likely be a generalized process to convert dojo v2 objects into dojo v3 objects. It would probably not matter what database was being used as dojo would be normalizing the data above the db level

**Review by grendel513 — APPROVED** [review]
Looks good

**Review by mtesauro — APPROVED** [review]
Approved

**Review by blakeaowens — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Pull request merged**
