### PR TITLE
Fix UnboundLocalError when user remove all options for password

### PR DESCRIPTION
**Pull request by YuToutCourt**
## Bug description

When attempting to add a new user, a 500 error is generated. This error occurs when all options for creating a difficult password for new users have been removed.
image

## Steps to reproduce
1. Remove all options for new users to create a difficult password.
image
2. Attempt to add a new user.

## Deployment method

    Docker Compose
    nginx

## Environment information

    Operating System: Kali 6.0.0
    DefectDojo version: V2.19.1

____

You can view the issue that I opened for this at: https://github.com/DefectDojo/django-DefectDojo/issues/7673

This is my first time creating a PR, so please let me know if I have missed anything.

### CODE REVIEW

**Review by YuToutCourt — COMMENTED** [review]
Remove whitespace before ':'

**Comment by Maffooch** [comment]
Good find! Please rebase against the bugfix branch

**Comment by damiencarol** [comment]
Launching tests

**Review by blakeaowens — APPROVED** [review]
I tested and this does fix it. Thanks for catching my mistake @YuToutCourt!

**Review by Maffooch — APPROVED** [review]
helm chart tests will not pass unless the base branch is updated to something other than master. This is not impacting outside of releases. Merging

**Pull request merged**
