### PR TITLE
Added steps to reproduce in Jira Description Template

### PR DESCRIPTION
**Pull request by FallenAtticus**
What this PR does:
- Added Steps to reproduce to the jira-description.tpl

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Thanks. Could you:
- update the description to state what this PR does / what it solves
- long description is longer used for JIRA, replaced by a template: issue-trackers/jira-description.tpl
- could you squash your commits (`git reset` -> `git add -u` -> `git commit -m "blabla"` )

**Comment by valentijnscholten** [comment]
Are you seeing `long_desc` being used anywhere? I think it's no longer used.

**Comment by FallenAtticus** [comment]
@valentijnscholten yes your are right, we used an older version before. I removed this line from the PR.

**Comment by valentijnscholten** [comment]
@FallenAtticus if you want you can add it to `jira-description.tpl`

**Review by valentijnscholten — APPROVED** [review]

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
i now see things related to AWS Prowler. Is that intentional? If yes, can you make a separate PR?

**Comment by valentijnscholten** [comment]
jira webhook already fixed in `dev` now.

**Comment by FallenAtticus** [comment]
> i now see things related to AWS Prowler. Is that intentional? If yes, can you make a separate PR?

Yes, I removed it. Sorry for that.

**Comment by valentijnscholten** [comment]
so that leaves only the jira description as the owner/reporter thing was fixed elsewhere in the meantime.

**Review by valentijnscholten — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
