### PR TITLE
Extend APIv2 Findings endpoint and UI filters to accept new date filters

### PR DESCRIPTION
**Pull request by FelixHernandez**
## Extend APIv2 Findings endpoint and UI filters to accept new date filters
[sc-3125]

**Description**

With this feature, the user will be able to filter the finding objects with three new filters:

- On -  return only the findings reported on the given date.
- Before - return only the findings reported before the given date
- After - return only the findings reported after the given date

This filters were added to UI and API endpoints.

**Test results**

- API
image

- UI
image

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by kiblik** [comment]
How does it behave if you use 2 (or 3) of the mentioned filters at the same time?

**Review by Maffooch — APPROVED** [review]

**Review by devGregA — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Comment by Maffooch** [comment]
> How does it behave if you use 2 (or 3) of the mentioned filters at the same time?

The filters will "stack" on top of each other. It would be possible to totally eliminate any results from the query, but that is also true of any other filter as well

**Review by cneill — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Reminder, maybe you forgot to merge this.

**Comment by mtesauro** [comment]
@manuel-sommer 
> Reminder, maybe you forgot to merge this.

Since kiblik asked a question, we wanted to give him some time to respond. This will still make the release on Monday now that we have sufficient approvals while giving kiblik a chance to provide feedback.

**Review by blakeaowens — APPROVED** [review]

**Comment by kiblik** [comment]
Sorry for not responding here :) looks good to me :D

**Pull request merged**
