### PR TITLE
fix deduplication tooltip

### PR DESCRIPTION
**Pull request by manuel-sommer**
fix issue #7337

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by mtesauro** [comment]
BTW, the tests about changing a model without creating a migration seems like a FP for this particular PR.

**Comment by manuel-sommer** [comment]
> BTW, the tests about changing a model without creating a migration seems like a FP for this particular PR.

There was a db mirgration generated. Shall I push it also eventhough it looks like a FP, but rather because django will create db migrations anyway?

**Comment by manuel-sommer** [comment]
Please first merge https://github.com/DefectDojo/django-DefectDojo/pull/9355 
Then, the db migration is also right, based on the other PR.

**Review by grendel513 — APPROVED** [review]

**Comment by Maffooch** [comment]
I am really struggling to figure out why the migration here is not being recognized. Even in the tests that pass, a new migration numbered 0199 is being generated:
image

**Comment by manuel-sommer** [comment]
I have no clue

**Comment by manuel-sommer** [comment]
> I am really struggling to figure out why the migration here is not being recognized. Even in the tests that pass, a new migration numbered 0199 is being generated: image

@Maffooch shall I create another PR to verify the same behavior?

**Comment by mtesauro** [comment]
> > I am really struggling to figure out why the migration here is not being recognized. Even in the tests that pass, a new migration numbered 0199 is being generated: image
> 
> @Maffooch shall I create another PR to verify the same behavior?

@manuel-sommer 
TBH, I've had to do that in the past - sometimes is less work to just start over and repeat what you did in the broken PR in a new one. I say go for it.

**Comment by manuel-sommer** [comment]
Take a look at https://github.com/DefectDojo/django-DefectDojo/pull/9454

**Pull request closed without merging**
