### PR TITLE
Add Code Flows to finding's description for SARIF test results

### LINKED ISSUE #6600: Include code flows in finding description when importing SARIF
Each finding in a SARIF file can contain a [codeFlows property](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317656) that can refer to multiple source code locations relevant to the finding. SAST tools often use this property to document how data flows from input to output. 

Currently, the SARIF parser discards all of this information when building a finding. It includes only the location in the [locations property](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317650).

As a developer investing a finding, having the full data flow makes it much easier to triage an issue. Without it, developers have to determine from potentially many execution flows which one exhibits the reported vulnerability. Having the information in the description would immediately identify the code flow that requires investigation.

### PR DESCRIPTION
**Pull request by fhoeborn-cb**
This adds the "CodeFlows" part of SARIF results to the findings description (partly resolves #6600) to make the finding more understandable.

### CODE REVIEW

**Comment by Maffooch** [comment]
@fhoeborn-cb Please fix flake8 errors

**Comment by fhoeborn-cb** [comment]
@Maffooch Sorry, oversaw that - fixed now

**Review by Maffooch — APPROVED** [review]
Looks good to me
@damiencarol what do you think?

**Review by damiencarol — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Comment by damiencarol** [comment]
This is a good patch. thanks for your contribution!

**Pull request merged**
