### PR TITLE
Settings/notification: localization + refactoring

### PR DESCRIPTION
**Pull request by shipko**
Added support localization for settings/notification page. Also I did some refactor

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]

**Comment by shipko** [comment]
Some problem with check "Lint Helm chart / Lint chart (pull_request)".

@damiencarol can you help me?

**Comment by StefanFl** [comment]
@shipko Please rebase your branch against dev, we have fixed a problem with the helm charts

**Comment by shipko** [comment]
@StefanFl done!

**Comment by damiencarol** [comment]
@shipko seems good now. @StefanFl  could you check again?

**Review by StefanFl — APPROVED** [review]

**Pull request merged**
