### PR TITLE
Update localization in all PRs

### PR DESCRIPTION
**Pull request by kiblik**
This PR force developer to run `./manage.py makemessages` on all PRs (as we run flake8 or unit tests).

If any change can affect localization but the developer does not commit also update of `django.po`, test fails.

Commit with missing update of `django.po` like [this](https://github.com/DefectDojo/django-DefectDojo/pull/7457/commits/bd80b35cf23d9147c68f09768d7e3a5ddbdeb1bc) will fail like [this](https://github.com/DefectDojo/django-DefectDojo/actions/runs/3960062363/jobs/6783689824#step:7:205).

### CODE REVIEW

**Comment by kiblik** [comment]
@shipko, how do you see this?

**Comment by kiblik** [comment]
We should add `--add-location file`. It will remove line numbers - because it could require too many changes in `django.po` (almost in every PR).

**Comment by CharlieSears** [comment]
I dig it! I'm a big fan of adding `--add-location file` as well. Though it feels like hijacking the unit tests for source control. If someone is just running unit tests, won't they get a failure for localization when that may be coming after they've solved their test issue?

Would it be possible to add an action to detect a lack of localization updates? Like [test-helm-chart](https://github.com/DefectDojo/django-DefectDojo/blob/master/.github/workflows/test-helm-chart.yml)?

**Comment by kiblik** [comment]
> I dig it! I'm a big fan of adding `--add-location file` as well. Though it feels like hijacking the unit tests for source control. If someone is just running unit tests, won't they get a failure for localization when that may be coming after they've solved their test issue?

Unittests designed to run locally (`docker/entrypoint-unit-tests-devDocker.sh` and `docker/unit-tests.sh`) will only update the content of `django.po`. So it will not fail (you can run unit test without updating `django.po`), it will prepare changes in `django.po` and then you can commit prepared changes.
> 
> Would it be possible to add an action to detect a lack of localization updates? Like [test-helm-chart](https://github.com/DefectDojo/django-DefectDojo/blob/master/.github/workflows/test-helm-chart.yml)?

Unittest which runs as GitHub action on PRs (`docker/entrypoint-unit-tests.sh`) will fail if there is missing update of `django.po`.

This behaviour copies behaviour with `manage.py makemigrations`. It will generate migration and not fail if you run it locally however it fails if it was committed and pushed with `django.po` update.

We are not able to identify if the developer forgot to add `_(...)` or `{% trans "..." %}` because it is hard to determine. If he/she/they used `_(...)` or `{% trans "..." %}`, we are able to detect if an update of `django.po` wasn't performed.

Does it answer questions? Is it acting as you asked or did I miss something?

**Comment by shipko** [comment]
@kiblik a great idea!

I absolutely agree with add `--add-location file` - it optimize our process. 

But I think this idea that we should require to update locale file on every changes `_(...)` or `{% trans "..." %}` is not so good. Because:
1. We raise the entry threshold for providing PR, requiring additional manipulations
2. We add more commit history that raise size of git repo
3. We raise a time to market metric for some PR

My suggestion is to make a new repo `defectDojo-translation` that will run git workflow on every PR `django-DefectDojo`. 
Advantages of this approach:
1. Contributors will not notice any changes in the PR process
2. We can support many another languages without effect (many-many commits) on main repo
3. By default en locale is available in code. If any members will require another locale it can download from `defectDojo-translation` repo

For examples: for my russian locale on every release update I just will copy ru folder and run project. It simple and fast.

**Comment by devGregA** [comment]
I very much like @shipko's idea and approach and can have someone from the core team help facilitate any new repos @Maffooch

**Comment by kiblik** [comment]
I can only agree with these arguments. However, so far I have no knowledge of how to create cross-repository GitHub actions. Somebody with knowledge of designing these think would be helpful here.

**Comment by Maffooch** [comment]
Here is an example of cross repo GHA calls
https://github.com/DefectDojo/django-DefectDojo/blob/master/.github/workflows/submodule-update.yml

**Comment by kiblik** [comment]
@shipko, do I understand correctly that you would like to remove `dojo/locale/en/LC_MESSAGES/django.po` from this repo?

Btw, what about adding `https://github.com/DefectDojo/defectDojo-translation` as submodule "mounted" to `dojo/locale`? Just not sure, when it should be cloned/updated. During building image? It can be too soon because somebody may add new phrases after the official release.

**Comment by shipko** [comment]
@kiblik yes, I suggest to remove dojo/locale/*/*/django.po files from this repo.

Updating the base image when updating the localization file is our ideal pipeline. But is really need us? 

We can update submodule for every release (maybe also bugfix release).
If somebody will want to update locale file in that moment he will can update it manually.

 When container is starting we need to execute `python3 manage.py compilemessages` in entrypoint-initializer.sh

**Comment by peeqonet** [comment]
Any update?
I'm ok to do it manually and i can change the source on my own environment but none of the existing solutions work.

**Comment by Maffooch** [comment]
Closing due to stale

**Comment by kiblik** [comment]
This issue became stale because we have been waiting for the reaction of core developers about the next steps [here](https://github.com/DefectDojo/django-DefectDojo/pull/7457#issuecomment-1398816861) and in [Slack](https://owasp.slack.com/archives/C014H3ZV9U6/p1694030448468349?thread_ts=1694016810.899579&cid=C014H3ZV9U6) as well.

**Pull request closed without merging**
