### PR TITLE
Moved all plot objects into one .js file

### PR DESCRIPTION
**Pull request by blakeaowens**
This was done as an attempt to declutter and reorganize all metrics plots, charts, and graphs.

Nearly all javascript related to plot objects has been moved to one file for centralized organization. All data processing (e.g. counting the number of critical findings) remains in corresponding .html files. This data is then passed to the corresponding plotting function.

This also serves as a reduction of duplicate code, as many metrics pages utilized the same plots and contained a copy paste of exact functions (while some plots are similar, some are slightly different, requiring two similar functions).

### CODE REVIEW

**Comment by valentijnscholten** [comment]
I like cleanups :-) It's quit big though, so not so easy to review. Could you maybe add some screenshots of all the things you've tested?

**Comment by valentijnscholten** [comment]
Error in the unit test probably caused by https://github.com/docker/buildx/issues/681 which will be fixed in the next release of buildkit.

**Comment by blakeaowens** [comment]
Screen Shot 2021-11-17 at 4 08 30 PM
Screen Shot 2021-11-17 at 4 09 52 PM
Screen Shot 2021-11-17 at 4 10 17 PM
Screen Shot 2021-11-17 at 4 11 07 PM

**Comment by blakeaowens** [comment]
> I like cleanups :-) It's quit big though, so not so easy to review. Could you maybe add some screenshots of all the things you've tested?

I have added some screenshots. Nothing has changed anywhere visually.

**Comment by valentijnscholten** [comment]
Thanks. Do you have some screenshots from an instance with some data/findings?

**Comment by blakeaowens** [comment]
> Thanks. Do you have some screenshots from an instance with some data/findings?
Screen Shot 2021-11-23 at 12 39 47 AM
Screen Shot 2021-11-23 at 12 38 36 AM

Here are a few screenshots with a little bit of data imported.

**Review by valentijnscholten — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
