### PR TITLE
make deduplication_on_engagement work with close_old_findings

### PR DESCRIPTION
**Pull request by valentijnscholten**
During #983 and #1002 I realized that deduplication_on_engagement is not yet support with close_old_findings during imports. I think this is needed because otherwise the import could close findings in other engagements and the whole idea of deduplication_on_engagement (I think) is to keep all "duplicate checks" inside the engagement instead of the product.

### CODE REVIEW

**Comment by devGregA** [comment]
Hi @valentijnscholten seeing merge conflicts here.

**Comment by devGregA** [comment]
Not sure what happened. Seemed to pop up once I merged your other PR for some reason.

**Comment by valentijnscholten** [comment]
Probably because I had to fix the same flake8 warnings in all three PRs

**Comment by valentijnscholten** [comment]
Conflicts are resolved now.

**Pull request merged**
