### PR TITLE
[GHA] Lint helm charts

### PR DESCRIPTION
**Pull request by madchap**
Lint helm charts to help with silly errors.

Addresses https://github.com/DefectDojo/django-DefectDojo/issues/3766

### CODE REVIEW

**Comment by madchap** [comment]
Seems like some things will need to be corrected first! ;-)

image

**Comment by madchap** [comment]
` ✖︎ defectdojo => (version: "1.5.1", path: "helm/defectdojo") > Chart doesn't have maintainers`

**Comment by madchap** [comment]
:rofl: 

`✖︎ defectdojo => (version: "1.5.1", path: "helm/defectdojo") > Error validating maintainer 'DefectDojo maintainers': 404 Not Found`

**Review by valentijnscholten — APPROVED** [review]

**Review by alles-klar — APPROVED** [review]

**Comment by damiencarol** [comment]
@madchap awesome work!

**Pull request merged**
