### PR TITLE
Update url_shortner to fix bugs and show more meaningful part of the endpoint

### LINKED ISSUE #3117: GET /finding/<finding_id> 500s when associated Endpoint host is longer than 50 characters
**Bug description**
GET `/finding/<finding_id>` 500s when the associated Endpoint host is longer than 50 characters.

**Steps to reproduce**
1. For a given finding of `<finding_id>`, update one of the endpoints to have a hostname that is greater than 50 characters
2. GET `/finding/<finding_id>`

**Expected behavior**
The `url_shortner` filter should properly handle return values of greater than 50 characters

**Deployment method**
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: macOS Catalina Version 10.15.5
 - DefectDojo Commit Message: `[2020-10-28 09:12:41 +0100] bfcc9fd9: APIv2 findings performance improvements (#3011) [ (HEAD -> dev, upstream/dev)]`

### PR DESCRIPTION
**Pull request by johnlanda**
Fixes #3117

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Thanks, but I don't understand how this fixes it. What error was being thrown? `return_value` already is a string so I don't see how another `str()` would help. But probably I miss something :-)

**Review by valentijnscholten — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Comment by Maffooch** [comment]
Travis didn't even run here, but its equivalent tasks passed. Merging.

**Comment by namloc2001** [comment]
Hi, do you know which release this'll be in? Thanks.

**Comment by valentijnscholten** [comment]
we release every month last tuesday.

**Pull request merged**
