### PR TITLE
Add try-catch for jira webhook processing

### PR DESCRIPTION
**Pull request by madchap**
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/3290

### CODE REVIEW

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
Good to improve the webhook, but I don't like the idea of swallowing exceptions and just return a 200. There may be a temporary problem for which we would like JIRA to retry the webhook, so better to return a 500 when there is an exception.

I also would rather see new method on the jira helper class to find a JIRA_Issue instance in a safe way instead of this huge try-catch thing.

**Comment by madchap** [comment]
> Good to improve the webhook, but I don't like the idea of swallowing exceptions and just return a 200. There may be a temporary problem for which we would like JIRA to retry the webhook, so better to return a 500 when there is an exception.

I am not sure how you'd tell JIRA how to retry a webhook. It would actually have to be supported by JIRA, which I don't think it is looking at the configuration there.

But we can return something other than 200, I agree.
 
> I also would rather see new method on the jira helper class to find a JIRA_Issue instance in a safe way instead of this huge try-catch thing.

Yes, I will see what I can do.

**Comment by valentijnscholten** [comment]
the "official" way to log exceptions is `logger.exception()`

**Comment by valentijnscholten** [comment]
I would also look at what is causing the exception. There is a JIRA_Issue but no finding attached. That means:

- it is an epic attached to an engagement
- somebody removed findings manually without removing JIRA_Issue instances

The first one is a valid case and could use some proper handling (just skip it without errors or 404).
The second one is corner case. If the exception is catched only to log it, it is no different than just letting the exception happen?

**Comment by madchap** [comment]
Superseded by https://github.com/DefectDojo/django-DefectDojo/pull/3321

**Pull request closed without merging**
