### PR TITLE
Working upgrade docker mysql to 8.X. Fixes #1390

### LINKED ISSUE #1390: Upgrade Docker MySQL to LATEST version
**Bug description**
Current docker config/compose is still using MySQL 5.7, whereas there are significant speed improvements on MySQL 8

### PR DESCRIPTION
**Pull request by dougmorato**
Using this compose setting, been able to use the latest version of MySQL.
Fixes 1390

### CODE REVIEW

**Comment by Maffooch** [comment]
Your welcome to use a newer version of MySQL on your installation of DefectDojo but I don't think we're ready to move to a MySQL version for Docker Compose that isn't in the default packages for our target development OS (Ubuntu 18.04 LTS).  While we love (and somewhat prefer) newer deployment models like Docker/Docker Compose and Kubernetes, we have a significant portion of the community doing 'traditional; installs on VMs or iron so pushing back default packages for LTS releases causes that part of our community issues.

I'd like to keep the variety and complexity of the 'official' deployments to a minimum so that we can focus on adding functionality to DefectDojo at the code level vs managing a high diversity of deployments.

Thinking the best solution here would be to attach an archived label, and close it. That way, it can be reopened at a later date when we are ready for the upgrade. With the label attached, it can be filtered to show it, and other PR’s that are of good quality. If you have any questions or concerns, please reach out.

**Comment by mtesauro** [comment]
@Maffooch Agreed.  Good approach.

**Comment by dougmorato** [comment]
@Maffooch Based on the README of the dev branch, I am (or at lease was) under impression that the only supported environments of the new deployments would only be docker & kubernetes, specifically to resolve the environment discrepancies issues that thas long brought inconsistencies (even our bug reporting templates ask for environment details). 

The docker [README](https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md) even says KUBERNETES is the preferred production deployment.

Is the bash setup still going to be supported?

@aaronweaver @devGregA join the party 🎉

**Comment by Maffooch** [comment]
@dougmorato There was no mention of removing any of the currently supported deployments. Correct, the README is accurate in stating that Docker and Kubernetes are the currently supported deployments.

Setup.bash is still supported as it not a deployment. It is an install method. Similarly, docker-compose is not a deployment, but an install method that deploys many Docker containers. 

Repeating the message from above, moving on from a stable LTS version of mysql is not in the best interest for the community. Mysql5.7 will continue to be supported for an additional four years to come. Also repeating myself here, I encourage you to use mysql8.0 on your own instance. 

All that being said, this PR will receive an archived tag and closed. It will be reopened when the project and community are ready for the upgrade to mysql8.0. Thank you again for your contribution.

**Pull request closed without merging**
