### PR TITLE
Update to fontawesome 5

### PR DESCRIPTION
**Pull request by madchap**
Breaking changes there.

### CODE REVIEW

**Comment by madchap** [comment]
@Maffooch I think you have some experience with JS stuff? Any idea why icons and font would not be loading? There is no error in building the nginx image, nor when loading the pages, but things are just not showing. Cheers.

**Comment by Maffooch** [comment]
Sorry It took so long to respond. I don't have a ton of experience with JS, but did take a look at the issue. Console logs say the file at the this url: http://localhost:8080/static/dojo/js/pdfmake.min.js.map
is not there. This file is related to the recent data tables inclusion found in the all findings view. Not sure what the deal is here.

**Comment by Maffooch** [comment]
So it looks like the upgrade is not as simple as once thought. Font Awesome changed a lot of naming conventions and straight up changes the names of some of the icons we were using. I tried changing a few, but still got the empty rectangles. No idea where to go from here.

Link for reference:
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by valentijnscholten** [comment]
For now we should stay at v4. No reason to go for v5 which is a complete rewrite. Also there are lots of javascript issue so I think we need to stabilize first.

i.e. https://github.com/DefectDojo/django-DefectDojo/issues/1999

**Comment by madchap** [comment]
> Console logs say the file at the this url: http://localhost:8080/static/dojo/js/pdfmake.min.js.map
> is not there. This file is related to the recent data tables inclusion found in the all findings view. Not sure what the deal is here.

I think it is unrelated to the move to font-awesome 5. @valentijnscholten brought this up a short while ago even with our current version.

> For now we should stay at v4. No reason to go for v5 which is a complete rewrite. Also there are lots of javascript issue so I think we need to stabilize first.

Agreed. I'll close this and inform dependabot to not bump major if it can listen.

**Pull request closed without merging**
