### PR TITLE
Status Update in DT parser

### PR DESCRIPTION
**Pull request by sahil3112**
**Description**

when I upload the JSON file using API I get the expected result, but then the change the state ex: RESOLVED to NOT_AFFECTED then that status us not updated in        
DefectDojo

I am not sure why the status is not changed

Some vulnerabilities are not affected or resolved  by remove component function used in product

there is already for false positive but there us also a possibility where vulnerability is Not affected the product or Resolved without update the component

**Test results**

Below is the first API call that I used to import report and I get the expected result

root@sahil:~/defect-dojo/ssl# curl -X 'POST'   'http://localhost:8080/api/v2/reimport-scan/'   -H 'accept: application/json'   -H 'authorization: Basic CREDS'   -H 'Content-Type: multipart/form-data'   -H 'X-CSRFToken: TOKEN'   -F 'minimum_severity=Info'   -F 'do_not_reactivate=false'   -F 'scan_type=Dependency Track Finding Packaging Format (FPF) Export'   -F 'file=@response_1677690590638.json;type=application/json'   -F 'product_name=test'   -F 'engagement_name=test'   -F 'test_title=Module 2'   -F 'close_old_findings=true'   -F 'auto_create_context=true'   -F 'false=string'
{"minimum_severity":"Info","active":false,"verified":false,"do_not_reactivate":false,"scan_type":"Dependency Track Finding Packaging Format (FPF) Export","endpoint_to_add":null,"file":null,"product_name":"test","engagement_name":"test","test":3,"test_title":"Module 2","auto_create_context":true,"deduplication_on_engagement":false,"push_to_jira":false,"close_old_findings":true,"close_old_findings_product_scope":false,"api_scan_configuration":null,"lead":null,"create_finding_groups_for_all_findings":true,"test_id":3,"engagement_id":20,"product_id":4,"product_type_id":1,"statistics":{"after":{"info":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"low":{"active":7,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":7},"medium":{"active":18,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":18},"high":{"active":19,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":3,"is_mitigated":7,"risk_accepted":0,"total":26},"critical":{"active":1,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":2,"is_mitigated":3,"risk_accepted":0,"total":4},"total":{"active":45,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":5,"is_mitigated":10,"risk_accepted":0,"total":55}}}}

but when I change the status of one of the component and push it to DD then status is not change
Below Is the 2nd API call

root@sahil:~/defect-dojo/ssl# curl -X 'POST'   'http://localhost:8080/api/v2/reimport-scan/'   -H 'accept: application/json'   -H 'authorization: Basic CREDS'   -H 'Content-Type: multipart/form-data'   -H 'X-CSRFToken: TOKEN'   -F 'minimum_severity=Info'   -F 'do_not_reactivate=false'   -F 'scan_type=Dependency Track Finding Packaging Format (FPF) Export'   -F 'file=@response_1677690590638.json;type=application/json'   -F 'product_name=test'   -F 'engagement_name=test'   -F 'test_title=Module 2'   -F 'close_old_findings=true'   -F 'auto_create_context=true'   -F 'false=string'
{"minimum_severity":"Info","active":false,"verified":false,"do_not_reactivate":false,"scan_type":"Dependency Track Finding Packaging Format (FPF) Export","endpoint_to_add":null,"file":null,"product_name":"test","engagement_name":"test","test":3,"test_title":"Module 2","auto_create_context":true,"deduplication_on_engagement":false,"push_to_jira":false,"close_old_findings":true,"close_old_findings_product_scope":false,"api_scan_configuration":null,"lead":null,"create_finding_groups_for_all_findings":true,"test_id":3,"engagement_id":20,"product_id":4,"product_type_id":1,"statistics":{"before":{"info":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"low":{"active":7,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":7},"medium":{"active":18,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":18},"high":{"active":19,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":3,"is_mitigated":7,"risk_accepted":0,"total":26},"critical":{"active":1,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":2,"is_mitigated":3,"risk_accepted":0,"total":4},"total":{"active":45,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":5,"is_mitigated":10,"risk_accepted":0,"total":55}},"delta":{"created":{"info":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"low":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"medium":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"high":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"critical":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"total":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0}},"closed":{"info":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"low":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"medium":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"high":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"critical":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"total":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0}},"reactivated":{"info":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"low":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"medium":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"high":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"critical":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"total":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0}},"left untouched":{"info":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"low":{"active":7,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":7},"medium":{"active":18,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":18},"high":{"active":19,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":3,"is_mitigated":3,"risk_accepted":0,"total":22},"critical":{"active":1,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":2,"is_mitigated":2,"risk_accepted":0,"total":3},"total":{"active":45,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":5,"is_mitigated":5,"risk_accepted":0,"total":50}}},"after":{"info":{"active":0,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":0},"low":{"active":7,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":7},"medium":{"active":18,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":0,"is_mitigated":0,"risk_accepted":0,"total":18},"high":{"active":19,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":3,"is_mitigated":7,"risk_accepted":0,"total":26},"critical":{"active":1,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":2,"is_mitigated":3,"risk_accepted":0,"total":4},"total":{"active":45,"verified":0,"duplicate":0,"false_p":0,"out_of_scope":5,"is_mitigated":10,"risk_accepted":0,"total":55}}}}

### CODE REVIEW

**Comment by damiencarol** [comment]
@sahil3112 seems good but you need to solve Flake8 anomalies first.

**Comment by sahil3112** [comment]
Hi @damiencarol ,
Flake8 anomalies solved

**Comment by Gby56** [comment]
@sahil3112 It would be even better if you added tests with example report files that have the new status in them, so you can make sure it marks findings as False positive / RESOLVED / NOT_AFFECTED as you wanted

**Review by damiencarol — CHANGES_REQUESTED** [review]
Need new checks in the unit tests

**Comment by sahil3112** [comment]
hi @damiencarol and @Gby56 ,

unit test added

**Comment by Maffooch** [comment]
There is a lot of extra stuff in this PR

**Comment by sahil3112** [comment]
> 
Hi @damiencarol 
Do I need to reduce the count of vulnerabilities in unit test?

**Comment by sahil3112** [comment]
> There is a lot of extra stuff in this PR

Hi @Maffooch ,

Please explain so that i can work on it

**Review by damiencarol — APPROVED** [review]

**Comment by Maffooch** [comment]
> Hi @Maffooch ,
>
>Please explain so that i can work on it

Files changed has more changes than the context of the PR. Please fix

**Comment by sahil3112** [comment]
> > Hi @Maffooch ,
> > Please explain so that i can work on it
> 
> Files changed has more changes than the context of the PR. Please fix

The Commit made the me is only on DT parser, Unit test file for DT and Sample data that are required to implement status in DT parser

**Comment by Maffooch** [comment]
Maybe another branch got merged into your branch? Not sure what happened, but the total number files changed in this PR shows as 8. Only your changes should be in the PR. I will approve when the other files changed are removed

**Comment by g-sahil22** [comment]
Hi @Maffooch ,

please check the below screenshot 
image

and one is made by DD release bot

**Review by damiencarol — CHANGES_REQUESTED** [review]
this PR need a rebase.

**Comment by Maffooch** [comment]
Ahh I must have missed this further above, but I see it now. You are merging the master branch into your branch is that is based against the dev branch.

image

**Comment by shipko** [comment]
Hi @sahil3112 
I see that you don't using django localization feature. It's a bad practice. Please wrap your text in _("") tag.

More information you may see https://docs.djangoproject.com/en/dev/topics/i18n/translation/

**Comment by sahil3112** [comment]
> Hi @sahil3112 I see that you don't using django localization feature. It's a bad practice. Please wrap your text in _("") tag.
> 
> More information you may see https://docs.djangoproject.com/en/dev/topics/i18n/translation/

Hi @shipko ,

please mention which file you are referring, so that i can fix

**Comment by coheigea** [comment]
I'm not sure about this PR, I fixed the problem here: https://github.com/DefectDojo/django-DefectDojo/pull/7872

**Comment by Maffooch** [comment]
@sahil3112 I am closing this one because it is going to get more difficult to untangle to branches as time goes on. If the fix @coheigea made in #7872 does not totally fulfill the status mapping in DT, then another PR is definitely welcome!

**Pull request closed without merging**
