### PR TITLE
uwsgi: increase default buffer-size

### LINKED ISSUE #3241: Cannot submit comment after having used filter for "Similar Findings"
Browse a finding with Similar Findings. Add a comment at the bottom of the page, it's working fine. Now, open the "Similar Findings" panel, change a bit the filters and click on "Apply Filters". You will see the URL changes with all the fields being inside (that could be the root cause).

Now, within that page with long URL, try adding a comment. I got a NGinx error.

**Expected behavior**
I do not expect any effect of the filters used on the ability to submit comments.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

cc @valentijnscholten @madchap

### PR DESCRIPTION
**Pull request by valentijnscholten**
Some pages with complex filter sets get result in requests being over 4096 bytes which trips uwsgi into blocking the request due to the default 4096 buffer-size introduced recently.

fixes #3241 #3223

### CODE REVIEW

**Comment by mtesauro** [comment]
100% agree with this - upped the defaults to that on my install after noticing some issues and hadn't gotten a chance to do a PR like this.  Nice job.

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by valentijnscholten** [comment]
if only k8s would build with it in GHA...

**Comment by valentijnscholten** [comment]
> if only k8s would build with it in GHA...

it does now, saw some weird docker errors in GHA for about an hour.

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
