### PR TITLE
Helm chart linting - pick target branch

### LINKED ISSUE #4176: Helm chart lint: bump version on release or change GHA
Whenever we do a release, the helm chart linting GHA fails because it expects us to increase the version of the helm chart.

Solution options:
- Update version of helm chart automatically or manually when merging a release back into dev, or, 
- Only run linting on PRs that actually change the helm chart similar to flake8.

### PR DESCRIPTION
**Pull request by madchap**
Should fix #4176

On master to take effect.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
What is the idea now with this change? Will it ignore changes made in other branches? I think in general it made sense that the linting complained about the versions as we bumped the defect dojo version.

**Comment by valentijnscholten** [comment]
Read the code again, is it now only raising an error if the chart was actually changed in a pr?

**Comment by madchap** [comment]
> Read the code again, is it now only raising an error if the chart was actually changed in a pr?

Right.

An actual pull request made from a release branch to master for example triggers a push event hence the else part.

**Comment by madchap** [comment]
By default, target_branch was always there, but implicitly always against master.

**Review by valentijnscholten — APPROVED** [review]

**Review by alles-klar — APPROVED** [review]

**Pull request merged**
