### PR TITLE
remove cve field from Findings

### PR DESCRIPTION
**Pull request by manuel-sommer**
This PR removes cve field as all cves were migrated to unsaved_vulnerability_ids. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

### CODE REVIEW

**Comment by manuel-sommer** [comment]
I will not fix Ruff Linter here as this is already covered here: https://github.com/DefectDojo/django-DefectDojo/pull/9903

**Comment by manuel-sommer** [comment]
@Maffooch, can you guide me here?
I don't know how to get rid of the cve field in ./dojo/finding/views.py

**Comment by Maffooch** [comment]
@manuel-sommer I am a little nervous for this change to be processed at the moment. I am closing for now, and we can revisit in the future

**Comment by mtesauro** [comment]
@Maffooch :+1: 
Good call - this wasn't really needed but keeping it for now can't hurt. We got other things I'd rather clean up first...

**Pull request closed without merging**
