### PR TITLE
Add a new field version to the test model

### PR DESCRIPTION
**Pull request by ccojocar**
This field can be used to store the version of the artifcat for which the test was performed (e.g. a container image tag)

Signed-off-by: Cosmin Cojocar <cosmin.cojocar@gmx.ch>

**Note: DefectDojo is now on Python3.5 and Django 2.2.x Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [x] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [x] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR 

Current accepted labels for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies

cc @madchap

### CODE REVIEW

**Comment by ccojocar** [comment]
>Just out of interest, how have you setup your scanning? Most people I've spoken use an engagement for each version/branch to scan.

We have a similar approach but it would be nice to also have the version of the artifact in the `Test`.

> Also, wouldn't you want to display the version field somewhere? I myself have been thinking to also add some more fields to the test, i.e. branch, build_url, commit_id, etc.

I think we want to save it into the Test viewer. I'll make sure that is rendered. 


> Also noted a failure in the unit tests as the code doesn't check if the version is provided in the upload request.

Thanks, I'll look into them.

**Comment by ccojocar** [comment]
I rebased, fixed the unit tests, and made the version filed to be displayed in the views.

**Comment by valentijnscholten** [comment]
The pygithub change/addition in the PR looks weird. Could you rebase or merge dev to make sure we don't mess with requirements.txt?

**Comment by ccojocar** [comment]
@valentijnscholten Thank you for review! I rebased and removed the PyGithub dependency from setup.py. I think that I added there during testing because somehow the github module wasn't found. This is manly because the docker images wasn't rebuilt. I don't think is required.

**Pull request merged**
