### PR TITLE
advance mobsf to also parse exisiting unittestfile

### PR DESCRIPTION
**Pull request by manuel-sommer**
This PR fixes this doing: https://github.com/DefectDojo/django-DefectDojo/blob/d698a7a1ff2a914754a541140b236dd3092d7e8e/unittests/tools/test_mobsf_parser.py#L44

The unittestfile showed 0 vulnerabilities as the parser was not parsing it right.

### CODE REVIEW

**Review by cneill — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Also here, Kubernetes Deployment is failing...

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Could we get this on the road for the next release upcomming Monday? 
@grendel513 and @devGregA ?

**Comment by grendel513** [comment]
> Could we get this on the road for the next release upcomming Monday? @grendel513 and @devGregA ?

hi @manuel-sommer we truly appreciate your contributions, thank you.  Can I kindly ask you to please refrain from requesting individuals review your PRs?  As reviewers we have a very well defined process to organize, prioritize, review, approve and merge PRs.  We would appreciate the room to follow our process to ensure all PRs are discussed, evaluated and tested for inclusion. Asking in this way may negatively affect the process, create rush and limit the time and effort on making sure each PR conforms to standards.  Thank you in advance for your understanding.

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
