### PR TITLE
OS Docs Overhaul - theming change, many new articles

### PR DESCRIPTION
**Pull request by paulOsinski**
This PR changes the base theme from Docsy into the more workable 'Doks' theme.  (It has a dark mode - sold).  It also adds many new tutorials and guides to our docs.

Hugo is still a dependency.  However with this version of the repo there is no need to install the theme as a git submodule.  Instead, `cd` into `docs`, `npm install` to pull the theme and then `npm run dev` to view the docs locally with the new theme in place.

- Instructions on configuring, installing and maintaining an open source repo are now stored under "Open Source DefectDojo".
- Certain OS Docs have been moved to an archive due to redundancy.
- The new docs are focused on describing features, and guides on using a working instance.

Screenshot 2024-11-13 at 6 28 53 PM
Screenshot 2024-11-13 at 6 29 41 PM
Screenshot 2024-11-13 at 6 28 19 PM

### CODE REVIEW

**Comment by kiblik** [comment]
Is it possible to increase the versions of Hugo and Node?
https://github.com/DefectDojo/django-DefectDojo/blob/090b2c7a77a67f02064b158559e5fcdc665c4291/.github/workflows/gh-pages.yml#L17-L26

**Comment by kiblik** [comment]
> Is it possible to increase the versions of Hugo and Node?
> 
> https://github.com/DefectDojo/django-DefectDojo/blob/090b2c7a77a67f02064b158559e5fcdc665c4291/.github/workflows/gh-pages.yml#L17-L26

Note for maintainers: This will need to be adjusted as well https://github.com/DefectDojo-Inc/Documentation/blob/c6e1a446c3dbf2c931972cfbbdaef3ee20df77c8/.github/workflows/deploy-gh-pages-branch.yml#L11-L20

**Comment by mtesauro** [comment]
I agree with @kiblik about making sure we rev the versions as part of this upgrade to the docs site.

Can't wait for docs dark mode :smile:

**Comment by paulOsinski** [comment]
@kiblik yes, that change was done in [this commit](https://github.com/DefectDojo/django-DefectDojo/pull/11258/commits/4532ee0bd9a1a72bb823d39927a76a84d130c837).

**Comment by Maffooch** [comment]
Tests will need to be updated to point at the new doc paths:
- https://github.com/DefectDojo/django-DefectDojo/blob/8b20fa0a3f55691f7707dedab50b46bde90d5c8b/unittests/test_parsers.py#L31
- https://github.com/DefectDojo/django-DefectDojo/blob/8b20fa0a3f55691f7707dedab50b46bde90d5c8b/unittests/test_parsers.py#L106

**Comment by paulOsinski** [comment]
> Tests will need to be updated to point at the new doc paths:
> 
> * https://github.com/DefectDojo/django-DefectDojo/blob/8b20fa0a3f55691f7707dedab50b46bde90d5c8b/unittests/test_parsers.py#L31
> * https://github.com/DefectDojo/django-DefectDojo/blob/8b20fa0a3f55691f7707dedab50b46bde90d5c8b/unittests/test_parsers.py#L106

This should be settled now, thanks!

**Review by Maffooch — APPROVED** [review]
There will likely be some revving on this to make sure the automation is set correctly here

Will have to do that once it is in dev

**Review by hblankenship — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
