### PR TITLE
Don't create finding JIRAs on a bulk update if we are creating a find…

### PR DESCRIPTION
**Pull request by coheigea**
…ing group JIRA

When you create a finding group and select push to JIRA, it creates a finding group JIRA, but it also adds JIRAs for the individual findings.

### CODE REVIEW

**Comment by coheigea** [comment]
@Maffooch Please review

**Review by security101 — APPROVED** [review]
Chances have been applied in my local DD 2.13.1 installation and created as expected a single Jira ticket when findings were grouped and pushed to the Jira test system on my side. Retesting with DD 2.14.0 is planed soon. Comment will be updated accordingly.

**Review by security101 — COMMENTED** [review]
Chance has been manually applied to my local DD 2.13.1 instance and when grouping findings and creating a Jira Ticket as intended the result is in a single JIRA ticket. I will upgrade to DD 2.14.0 soon and redo the test and provide an update.  Sorry for the duplicate entry.

**Comment by coheigea** [comment]
@damiencarol Please review

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
