### PR TITLE
Issue 1720

### PR DESCRIPTION
**Pull request by ThibaudLopez**
**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is flake8 compliant 
- [ ] Your code is python 3.5 compliant
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by ptrovatelli** [comment]
hello @ThibaudLopez .
Can you enlighten us as to what this is ? :)

**Comment by ThibaudLopez** [comment]
> hello @ThibaudLopez .
> Can you enlighten us as to what this is ? :)

Hi @ptrovatelli, it was supposed to be a clean fix for Issue #1720, but I messed up my git commands and the Django migrations, so I have to re-do as per @madchap . Thanks

**Comment by ThibaudLopez** [comment]
closing this PR, will re-do

**Comment by ptrovatelli** [comment]
ok earlier i couldn't find the 1720 issue either so i was lost :)

**Pull request closed without merging**
