### PR TITLE
Docs maintenance: remove external images, article updates

### PR DESCRIPTION
**Pull request by paulOsinski**
This PR is intended to move externally hosted images into the main repo, along with the following docs updates:

**File Changes**
- replace all externally hosted images with images on the repo, and update all image refs to use those hosted images

**Article Changes**
- Add Universal Importer / Dojo-CLI docs
- update DefectDojo Pro Changelog (these changes have already been implemented in Master via [this commit](https://github.com/paulOsinski/django-DefectDojo/commit/032960d57bd1185ac4bc4623ab65fa75ab348b22))
- rework Request A Trial article with updated language
- QA + update articles in Cloud Manager directory

[sc-8918]
[sc-9103]

### CODE REVIEW

**Comment by mtesauro** [comment]
Follow on to #11258

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by paulOsinski** [comment]
some of these filenames were going to break Windows builds as per issue: https://github.com/DefectDojo/django-DefectDojo/issues/11366

I have fixed those references but I imagine I will have to rebase once this hotfix is accepted: https://github.com/DefectDojo/django-DefectDojo/pull/11368

**Comment by paulOsinski** [comment]
I've created a mess here while trying to make some branch changes so I'm going to nuke this and try again.  Sorry!

**Comment by paulOsinski** [comment]
I tried to fix this PR but ended up making things much worse, so I am closing this and retrying here: https://github.com/DefectDojo/django-DefectDojo/pull/11376

Sorry for the inconvenience!

**Pull request closed without merging**
