### PR TITLE
Add do_not_reactivate option to persist triages from triage-less scanners

### PR DESCRIPTION
**Pull request by Gby56**
Explained in https://github.com/DefectDojo/django-DefectDojo/issues/6892

### CODE REVIEW

**Comment by Maffooch** [comment]
@Gby56 this makes sense to me. I think it needs a little extra documentation to make it clear though. Copying the text from the attached issues and putting that somewhere in the docs would mostly likely be enough. Might be a good idea to add a hotlink within the help text to the location in the docs. What are your thoughts on that?

**Comment by Gby56** [comment]
> 

Completely agree, I'll get some more documentation around it and link to it in the helper message, it's not an easy concept to grasp

**Comment by Gby56** [comment]
image
I'm not quite sure how to get a link with mark_safe into the help_text... I'd like to point to the docs website to have the full context

**Comment by Gby56** [comment]
I just realized that I cannot easily implement do_not_reactivate in the importer, I need the reimporter's deduplication to be able to instantly mark the existing findings as untouched. The normal importer does deduplication out-of-band I think, and it should be taken care of in there, which is more complex

**Comment by Gby56** [comment]
image
Adding some notes to explain maybe why a finding was not reactivated.

**Comment by Gby56** [comment]
Okay, the `get_import_meta_data_from_dict()` function calls were broken because of my new variable `do_not_reactivate`, I'm not a fan of python unpacking and usually I work with dicts a lot, I think this should have fixed the unit tests :)

**Comment by Maffooch** [comment]
Hi @Gby56 there are a handful of tests failing here. Likely an issue of there being a new element on the page that throughs off the xpath of other elements

**Comment by Gby56** [comment]
@Maffooch I think the integration tests failing are not from my changes, all of them are 404s on random stuff, no clue how to debug that...
```
{'level': 'SEVERE', 'message': 'http://nginx:8080/static/dojo/img/zoom-in.cur - Failed to load resource: the server responded with a status of 404 (Not Found)', 'source': 'network', 'timestamp': 1668503557057}
{'level': 'SEVERE', 'message': 'http://nginx:8080/static/%20jquery.hotkeys/jquery.hotkeys.js - Failed to load resource: the server responded with a status of 404 (Not Found)', 'source': 'network', 'timestamp': 1668503555671}
```

**Comment by Gby56** [comment]
On my local dev machine btw 
image

**Comment by Gby56** [comment]
God... it was the `black` linter, it's formatting my html file when saving, and it added a bunch of spaces

**Comment by Gby56** [comment]
@Maffooch all green !

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
