### PR TITLE
Add endpoints to scan

### PR DESCRIPTION
**Pull request by alles-klar**
Option to manually add endpoints to scans

In some cases it is helpful to have the opportunity to manually add endpoints to scans. One example is a clair scan which you want to map to a specific server.

on behalf of DB Systel GmbH

---

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [x] Your code is python 3.5 compliant
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [x] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by Maffooch** [comment]
This a pretty cool addition. The only feedback I have is adding an endpoint via gui. When adding an endpoint to a given finding, a popup window appears and a new endpoint is added without ever leaving the page. This would be much less intrusive to the flow if incorporated into import scan.

**Comment by alles-klar** [comment]
@Maffooch I agree with you. I am not sure why the workflow is different from "add endpoints" in ad_hoc_findings. The code seems similar to me: 
dojo/forms.py line 376:
`endpoints = forms.ModelMultipleChoiceField(Endpoint.objects, required=False, label='Systems / Endpoints',
                                               widget=MultipleSelectWithPopPlusMinus(attrs={'size': '5'}))`
vs dojo/forms.py line 874:
`endpoints = forms.ModelMultipleChoiceField(Endpoint.objects, required=False, label='Systems / Endpoints',
                                               widget=MultipleSelectWithPopPlusMinus(attrs={'size': '11'}))`

The output looks different: 
image


image

Does someone has a idea?

**Comment by Maffooch** [comment]
So the ad-hoc-finding as well as editing a finding has some javascript that adds the `add?_popup` part of the url. This needs to be added to the import scan template. Use the product ID as the location the endpoints will be added to similar to the way ad_hoc_finding does It.

**Comment by alles-klar** [comment]
@Maffooch Thanks for you input. Could you checkout if it works like you expect it?

**Pull request merged**
