### PR TITLE
kubernetes: fix node selectors; add limits

### PR DESCRIPTION
**Pull request by ptrovatelli**
- add a nodeselector in the initializer job
- fix nodeSelector in django deployment (was at the root, should be under django as in values.yaml)
- add limits

### CODE REVIEW

**Comment by madchap** [comment]
Don't forget the label... ;-)

**Comment by ptrovatelli** [comment]
> Don't forget the label... ;-)

arf sorry :)

**Comment by ptrovatelli** [comment]
adding limits; sorry for mixing different things but handling different branches is complicated
we used to have requests configured but not limits: requests will tell to which node the pod can be deployed but it won't prevent the pod to take up all RAM in the node. 
limits is here for that.

setting big limits for starters, can be tuned down if necessary.

**Comment by ptrovatelli** [comment]
removed the celery nodeselector and limits now that this pod doesn't exist anymore :)

**Comment by ptrovatelli** [comment]
(rebase + force-push to try and fix travis that fails without a reason)

**Comment by ptrovatelli** [comment]
@madchap @alles-klar care to have a look at this one? thanks!

**Pull request merged**
