### PR TITLE
Adds duroc hog to rusty hog

### LINKED ISSUE #5939: Advance RustyHog to also include DurocHog
Advance RustyHog to also process Duroc Hog files.

### PR DESCRIPTION
**Pull request by manuel-sommer**
Fixes #5939

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@damiencarol could you review this PR?

**Review by Maffooch — APPROVED** [review]
This looks good to me. @damiencarol does this have your blessing?

**Review by damiencarol — APPROVED** [review]
Good work!

**Comment by damiencarol** [comment]
@manuel-sommer don't you want to add the de-duplication configuration?

**Comment by manuel-sommer** [comment]
@damiencarol, I already testet the RustyHog deduplication configuration with PR here https://github.com/DefectDojo/django-DefectDojo/pull/5903

**Pull request merged**
