### PR TITLE
Add parser for Talisman

### PR DESCRIPTION
**Pull request by iamnihal**
**Description**

This PR will add Talisman (https://github.com/thoughtworks/talisman) as a new scanner/importer.

**Documentation**

Documentation included in `docs/content/en/integrations/parsers/file/talisman.md`

**Checklist**

- [x] Make sure to rebase your PR against the very latest `dev`.
- [x] Features/Changes should be submitted against the `dev`.
- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.11 compliant.
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [x] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by iamnihal** [comment]
Issue #6512

**Comment by iamnihal** [comment]
Hi @Maffooch - Any guesses why the checks are getting failed? As I went through the logs, the reason is different from the first attempt.

**Comment by mtesauro** [comment]
You can force the test to re-run if you close and re-open this PR.  Sometimes they just need another run.

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
