### PR TITLE
Include DefectDojo_Engagement_Surveys into the main repo

### PR DESCRIPTION
**Pull request by Maffooch**
**Note: DefectDojo is now on Python3.5 and Django 2.2.x Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

Merge DefectDojo_Engagement_Survey repo into the DefectDojo main. The separation of the two repos caused a lot of issues at install time. 

Required change on users end. Since all survey related objects were stored in the `defectdojo_engagement_survey` tables are now stored in the `dojo_survey` tables, all data will need to be moved over by running the `migrate_surveys` script with the following two methods

docker-compose: `docker exec -it <uwsgi container_name> python3 manage.py migrate_surveys`
on metal: `python3 manage.py migrate_surveys`

Once this script has been run, all data will have been moved over to the appropriate tables with the previous tables being removed. 

- [x] Your code is flake8 compliant 
- [x] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [x] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR 

Current accepted labels for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies

### CODE REVIEW

**Comment by mtesauro** [comment]
Did you get those accesslint issues sorted out?  Wondering if this is another case where accesslint gets confused and doesn't re-evaluate future commits and update it's status.

**Comment by Maffooch** [comment]
Pretty sure I got them all. Guess we’ll never know though!

**Comment by dayal18** [comment]
Hey guys, any thoughts on replacing the word "**Survey**" with "**Questionnaire**". ??

**Comment by dayal18** [comment]
I modified the HTML pages, that looks like this #2271

**Comment by valentijnscholten** [comment]
`django-overextends` officially doesn't support django 2.x and throws warning during installation. I can't see any references to it either in the templates. is it still needed @Maffooch ?

**Comment by Maffooch** [comment]
@valentijnscholten Don't see any evidence of it. Will remove it.
@dayal18 May be worth looking into. Definitely separate pull request material though.

**Comment by dayal18** [comment]
@Maffooch @valentijnscholten You guys are so awesome.. and Thank you so much.. I wish I knew Django to contribute.. guess what I have started learning :)

**Pull request merged**
