### PR TITLE
Dependency Check parser mark suppressed findings as mitigated

### PR DESCRIPTION
**Pull request by AndreVirtimo**
**Description**

The Dependency Check parser currently tags suppressed findings but don't mitigate them. The documentation says they are marked as inactive. But this is not true if you import them via API and the active=true flag.

Suppressing a finding in Dependency Check is usually because these are false positives. So they should be marked as mitigated and not as inactive. When you looking into the code this was also the intended behaviour for the parser (see https://owasp.slack.com/archives/C2P5BA8MN/p1683267640152279).

**Test results**

I have added assertions for the mitigation.

**Documentation**

I have change the documentation: "Suppressed vulnerabilities are marked as mitigated."

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]
You patch is good but the important attribute is `active`.
Anyways, the PR improve things so.

**Comment by Maffooch** [comment]
@AndreVirtimo please pull the latest dev branch. Our unit tests broke and there is a fix on dev now

**Comment by AndreVirtimo** [comment]
@Maffooch updated the PR

@damiencarol thank you for your feedback

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Comment by AndreVirtimo** [comment]
Is it possible to have this fix in an upcoming release?

**Comment by Maffooch** [comment]
Hi @AndreVirtimo 

Looks like this PR was submitted to the dev branch. It will be in the release going out on July 3rd

**Pull request merged**
