### PR TITLE
Notification Enhancements - Only Authorized users will see notification for Product / Engagement / Test - #2738

### PR DESCRIPTION
**Pull request by manav-nagla**
#2738 Added checks to look for authorized user in notifications.

### CODE REVIEW

**Comment by Maffooch** [comment]
Please fix flake8 violations. Otherwise it looks good.

**Comment by dayal18** [comment]
> Please fix flake8 violations. Otherwise it looks good.

@Maffooch Thanks, learnt again something new. It's done.

**Comment by valentijnscholten** [comment]
I had to change this code quite a lot in #2889 to fix some more stuff. And now the issue here (2738) is also fixed in there as the way it works now is different so the issue with authorized users won't occur.
So although we relaly like you contributing, it is better to close this PR now.

**Comment by manav-nagla** [comment]
Closing this PR, much of the large changes are handled in #2889

**Pull request closed without merging**
