### PR TITLE
Nessus: Push CVSSv3 into Impact field if it present.

### PR DESCRIPTION
**Pull request by satandyh**
Nothing more just push CVSSv3 into Impact field if it present of course.
Used only for xml parser version

### CODE REVIEW

**Comment by StefanFl** [comment]
@satandyh There is an attribute in the findings called `cvssv3`. If this is used, the score will be calculated when saving the finding and stored in the attribute `cvssv3_score`. We should populate this field instead of writing the information in the `impact`.

**Comment by damiencarol** [comment]
> @satandyh There is an attribute in the findings called `cvssv3`. If this is used, the score will be calculated when saving the finding and stored in the attribute `cvssv3_score`. We should populate this field instead of writing the information in the `impact`.

I agree, @satandyh  why using another attribute?

**Review by damiencarol — CHANGES_REQUESTED** [review]
Use the dedicated `cvssv3` attribute

**Comment by Maffooch** [comment]
Closing as #5955 adds the CVSS vector to the dedicated CVSS score field

**Pull request closed without merging**
