### PR TITLE
Slack notification: get user by email instead of searching all users

### LINKED ISSUE #4937: slack notification bug to find user profile
**Expected behavior**
In my case, our company workspace has a lot of employees. That means user list has limitation for showing.
so https://slack.com/api/users.list url, it does not work without cursor parameter.

image

I suggest that it should be changed as below

```
res = requests.request(
        method='POST',
        url='https://slack.com/api/users.lookupByEmail',
        data={'token': get_system_setting('slack_token'), 'email': user_email})

users = json.loads(res.text)

    slack_user_is_found = False
    if users:
        if 'error' in users:
            logger.error("Slack is complaining. See error message below.")
            logger.error(users)
            raise RuntimeError('Error getting user list from Slack: ' + res.text)
        else:
            for member in users["user"]:
                if "email" in member["profile"]:
                    if user_email == member["profile"]["email"]:
                        if "id" in member:
                            user_id = member["id"]
                            logger.debug("Slack user ID is {}".format(user_id))
                            slack_user_is_found = True
                            break
                    else:
                        logger.warn("A user with email {} could not be found in this Slack workspace.".format(user_email))

            if not slack_user_is_found:
                logger.warn("The Slack user was not found.")

    return user_id        
```

**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Catalina 10.15.7
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

### PR DESCRIPTION
**Pull request by valentijnscholten**
fixes #4937

### CODE REVIEW

**Review by Maffooch — APPROVED** [review]

**Comment by valentijnscholten** [comment]
I have no idea if this works as I just copied the suggestion into a pr. Anyone able to test it?

**Comment by Maffooch** [comment]
Oh I assumed it was tested before being made a PR. Maybe convert it to a draft so it does not accidentally get merged?

**Comment by valentijnscholten** [comment]
Of you dismiss your review is pretty clear I think with the comments and all.

**Comment by whitespots** [comment]
image

**Comment by whitespots** [comment]
Each time new alert :))

So, on the other side there are such scopes:
image

**Comment by whitespots** [comment]
Actually, even after setting the slack email in user settings we can see just more issues in logs :)
image

**Comment by valentijnscholten** [comment]
your error seems completely unrelated to the one from the original reporter

**Comment by Maffooch** [comment]
@valentijnscholten is the solution you have ready to go? I didn't think it was in working order yet

**Comment by valentijnscholten** [comment]
@hackthesoul Can you test this so we can include it in the release today?

**Comment by valentijnscholten** [comment]
No more time to test this and not many reports, moving to 2.5.0.

**Comment by StefanFl** [comment]
@valentijnscholten What is your recommendation how to proceed with this PR, if we cannot test it?

**Review by devGregA — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
