### PR TITLE
Add Close Engagement Notification

### PR DESCRIPTION
**Pull request by Maffooch**
Currently, the only way to be notified if an engagement has been closed is to enable notifications for all findings to be closed as well since they both fell under the "other" notification type. This PR provides a solitary notifications for when an engagement closes.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
first reaction would be that it might be interesting for the personal notifications on the view_product_defails page to allow people to only get these notifications for select products?

**Comment by Maffooch** [comment]
Not a bad idea. Will look into it.

**Comment by Maffooch** [comment]
Not totally sure what happened on this one..

**Review by madchap — APPROVED** [review]
lgtm - but you need to modify the db migration now, another PR went in before yours.

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
