### PR TITLE
bug: Helm chart wrong indentation

### PR DESCRIPTION
**Pull request by carlosjgp**
The indentation for the resources should be 12.

Currently failing because `requests` is not a valid key for ContainerSpec

Tested locally

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [x] Your code is python 3.5 compliant
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [x] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [x] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by devGregA** [comment]
@alles-klar would you please review?

**Comment by devGregA** [comment]
@carlosjgp would you please submit to dev instead of master?

**Comment by ptrovatelli** [comment]
I'm not too sure about this change. I'm also in the process of deploying to kubernetes. i haven't made this change, although I have made another change on this file. 
I did have this "requests" error and have made this kind of change but in other files (celery-beat-deployment, django-deployment)
I haven't finished testing but my current work is here: 
https://github.com/ptrovatelli/django-DefectDojo/tree/kubernetes-1.16-helm3

**Comment by alles-klar** [comment]
@ptrovatelli I am also not sure if this fix has something to do with the error, but I looked at the file which helm produces and it seem to have the correct intend now.  So I think we should merge it anyway?

**Comment by ptrovatelli** [comment]
if it works for you I don't mind merging. for me it's already not working anyway :)
what version of helm and kubernetes are you using? 

i have a couple of more changes coming on

**Comment by ptrovatelli** [comment]
@carlosjgp can you confirm that the application works fine with this? what version of helm and kubernetes are you using?

**Comment by carlosjgp** [comment]
Hi @ptrovatelli.

That indentation is required if you want to deploy the PODs with CPU and memory resource limits.

I tested the chart as it is on the master branch and I had to make this change and push the chart to our private chart repository to be able to use it

**Comment by carlosjgp** [comment]
> what version of helm and kubernetes are you using?

Helm 2.14 and k8s 1.13.

I found other problems with the deployment but they were related to DB migration problems and also a CPU throttling due to Python 2 using threads and cores without respecting the mentioned limits on the previous comment not the Helm chart itself

**Comment by madchap** [comment]
@ptrovatelli so maybe merging sooner than later is the thing to do here?

**Comment by ptrovatelli** [comment]
okok.. i'm using helm 3 / kubernetes 1.16 and python 3. had to do a couple of more changes before it was working. If it works for you as it is, we can merge.

**Comment by ptrovatelli** [comment]
@carlosjgp can you create a PR based on dev branch please? thanks

**Comment by carlosjgp** [comment]
@ptrovatelli Will do!

Should I close this one in favour of the new one?

**Comment by ptrovatelli** [comment]
Yes I dont think we can change the target branch

**Comment by carlosjgp** [comment]
@ptrovatelli looks like changing the target branch also make it include other changes from `master` that are not on `dev`

Maybe `dev` needs a rebase?

I'll rasie a new PR from a branch created from `dev`

**Comment by carlosjgp** [comment]
Closed in favor of #1727

**Pull request closed without merging**
