### PR TITLE
Adding a parser for Checkov scanner

### PR DESCRIPTION
**Pull request by StefanFl**

### CODE REVIEW

**Comment by StefanFl** [comment]
I couldn't find how to set a label when issuing the pull request. It should be "Import Scans (for new scanners/importers)"

**Comment by valentijnscholten** [comment]
Any data available to set `component_name`? maybe use `resource` for that?

**Comment by StefanFl** [comment]
Good point. After a second look in some actual reports and their sources, I removed source and sink completely. Only location, line number and component name are used. The vulnerability is about a whole definition in a terraform or cloudformation file. The end of a definition is easily visible in the source, so mention it in the finding doesn't add any value. Now the finding is less crowded.

**Review by madchap — APPROVED** [review]
Thanks for the parser :) There a couple conflicts to fix now, due to other merges. Cheers.

**Comment by StefanFl** [comment]
Conflicts are resolved

**Review by valentijnscholten — APPROVED** [review]

**Comment by valentijnscholten** [comment]
https://github.com/DefectDojo/Documentation/pull/127

**Comment by schosterbarak** [comment]
This is awesome! thanks @StefanFl  (p.s. if you have any feedback on checkov feel free to send them my way :) )

**Pull request merged**
