### PR TITLE
Add cve option in findings

### PR DESCRIPTION
**Pull request by dr3dd589**
related to #973
Updated db_migration.

- [x] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes should include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by efficiosoft** [comment]
This has to be rebased onto dev and the migration to be regenerated again I fear, because it contains the change to `hash_code` for which a migration has already been created in dev.

Please unapply the migration locally first before rebasing and deleting the old one:

    $ ./manage.py migrate dojo 0001_initial
    # Rebase.
    $ git rm <your migration>
    $ ./manage.py makemigrations dojo

Regards
Robert

**Comment by dr3dd589** [comment]
done, thanks!

**Comment by valentijnscholten** [comment]
Great, maybe rename the migrations file to something like 003_cve_field or similar?

**Comment by dr3dd589** [comment]
done, thanks! @valentijnscholten

**Comment by efficiosoft** [comment]
Well, the naming would just cause an usability issue, making it impossible to abbreviate migration names when using the `migrate` command.

However, what's important are the dependencies set inside the migration file. The migration in question currently depends on `0002_something`, which would create a branch in django's migration dependency graph since there's another one (`0003_test_title`) depending on that migration as well.

@dr3dd589 So it should work when merged as is right now, but another unmigrate/rebase/makemigrations (the steps I already described earlier today) would make it more sane and maintain a linear migration path without branches.

@aaronweaver  Dealing with these migrations might seem like a lot of work at the moment, but quite some db changes have queued up and need to be persisted in order. I'm sure this will settle soon and we'll all benefit from a clean migration chain.

**Comment by dr3dd589** [comment]
It means I have to make these changes in PR whenever anyone updates DB file until this pr gets merged!!

**Comment by aaronweaver** [comment]
@dr3dd589, @valentijnscholten we good to merge now? All tests look clear. @dr3dd589 thanks for your patience, the migrations included does add additional overhead.

**Comment by efficiosoft** [comment]
@dr3dd589 I double-checked my statement from yesterday again. Migration dependencies actually need to be liniarized, meaning each django app has to have only one migration at the top. This would have had to be merged later manually [1], so it's good you rebased again.

[1] https://docs.djangoproject.com/en/2.2/topics/migrations/#version-control

**Comment by dr3dd589** [comment]
> @dr3dd589, @valentijnscholten we good to merge now? All tests look clear. @dr3dd589 thanks for your patience, the migrations included does add additional overhead.

@aaronweaver yes I think so!

**Pull request merged**
