### PR TITLE
remove coverage from requirements.txt

### PR DESCRIPTION
**Pull request by manuel-sommer**
it looks like coverage is not used anymore

### CODE REVIEW

**Comment by manuel-sommer** [comment]
reopening because of merge conflict failure

**Comment by manuel-sommer** [comment]
I can't see a correlation between the failed tests and the PR @Maffooch. Could you take a look here?

**Comment by mtesauro** [comment]
@manuel-sommer So, coverage isn't *directly* used by DefectDojo but it's used in some of our developer docs which is why we've kept it in requirements.txt

I'm not opposed to removing it since you'd like to think Python developers could easily `pip install` it if they wanted to check coverage for DefectDojo. We just talked about that module a while ago and kept it for the reason above.

So it's optionally 'used' by DefectDojo developers but not 'used' by the app itself.

@Maffooch Do you have an opinion on keeping or removing the coverage module?

**Comment by Maffooch** [comment]
I vote we remove this. It will make docker images slightly smaller as well

If developers would like to test their unit test coverage, install the package is as easy as 
```
pip install coverage
```

**Comment by mtesauro** [comment]
> I vote we remove this. It will make docker images slightly smaller as well
> 
> If developers would like to test their unit test coverage, install the package is as easy as
> 
> ```
> pip install coverage
> ```

Works for me!

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
