### PR TITLE
Update parser.py

### LINKED ISSUE #4504: Clair Scan file upload fails when parsing
**Be informative**
When I try to upload a Clair Scanner (json) file, it fails with server 500 code error.
when I look at the logs I can see: 
"TypeError: string indices must be integers"

**Bug description**
Clair Scan can't be imported due to an error.
This is cause by an improper json file parsing. I'll submit a pull request on this to fix it.

**Steps to reproduce**
1. Go to 'Clair Scan' test type
2. Try to upload or re-upload a Scan file
3. See error

**Expected behavior**
The upload will fail

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Debian (Docker)
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

### PR DESCRIPTION
**Pull request by devsecopsale**
This is to fix #4504 . 'tree' variable should start from 'vulnerabilities' subtree.

### CODE REVIEW

**Review by damiencarol — CHANGES_REQUESTED** [review]
This modifications crash Clair unit tests.

**Comment by devsecopsale** [comment]
> This modifications crash Clair unit tests.

Hi. I so that some unit tests failed but I couldn't access the details on them. Do you have any data about it?

**Comment by damiencarol** [comment]
```
2021-05-13T16:33:54.4924184Z [36muwsgi_1         |[0m ======================================================================
2021-05-13T16:33:54.4925327Z [36muwsgi_1         |[0m ERROR: test_many_findings (dojo.unittests.tools.test_clair_parser.TestClairParser)
2021-05-13T16:33:54.4926578Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2021-05-13T16:33:54.4927440Z [36muwsgi_1         |[0m Traceback (most recent call last):
2021-05-13T16:33:54.4928456Z [36muwsgi_1         |[0m   File "/app/dojo/unittests/tools/test_clair_parser.py", line 17, in test_many_findings
2021-05-13T16:33:54.4929515Z [36muwsgi_1         |[0m     findings = parser.get_findings(my_file_handle, None)
2021-05-13T16:33:54.4930509Z [36muwsgi_1         |[0m   File "/app/dojo/tools/clair/parser.py", line 19, in get_findings
2021-05-13T16:33:54.4931406Z [36muwsgi_1         |[0m     subtree = tree['vulnerabilities']
2021-05-13T16:33:54.4932346Z [36muwsgi_1         |[0m TypeError: list indices must be integers or slices, not str
2021-05-13T16:33:54.4933075Z [36muwsgi_1         |[0m 
2021-05-13T16:33:54.4933706Z [36muwsgi_1         |[0m ======================================================================
2021-05-13T16:33:54.4935238Z [36muwsgi_1         |[0m ERROR: test_no_findings (dojo.unittests.tools.test_clair_parser.TestClairParser)
2021-05-13T16:33:54.4936576Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2021-05-13T16:33:54.4937479Z [36muwsgi_1         |[0m Traceback (most recent call last):
2021-05-13T16:33:54.4938555Z [36muwsgi_1         |[0m   File "/app/dojo/unittests/tools/test_clair_parser.py", line 10, in test_no_findings
2021-05-13T16:33:54.4939692Z [36muwsgi_1         |[0m     findings = parser.get_findings(my_file_handle, None)
2021-05-13T16:33:54.4940747Z [36muwsgi_1         |[0m   File "/app/dojo/tools/clair/parser.py", line 19, in get_findings
2021-05-13T16:33:54.4941731Z [36muwsgi_1         |[0m     subtree = tree['vulnerabilities']
2021-05-13T16:33:54.4942752Z [36muwsgi_1         |[0m TypeError: list indices must be integers or slices, not str
```

**Comment by devsecopsale** [comment]
duplicated

**Pull request closed without merging**
