### PR TITLE
SARIF parser: Process CWE field for njsscan

### PR DESCRIPTION
**Pull request by kokhanevych-macpaw**
- Add processing of CWE field for njsscan reports
Example in njsscan report:
`"properties": {
            "owasp": "A9: Using Components with Known Vulnerabilities",
            "cwe": "CWE-327: Use of a Broken or Risky Cryptographic Algorithm"
          },`

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]

**Comment by valentijnscholten** [comment]
Can you add/extend the tests?

**Comment by damiencarol** [comment]
I agree, could you add a report with njsscan that have these data in the report and unit tests that check that?

**Comment by kokhanevych-macpaw** [comment]
The test and report already present:
https://github.com/DefectDojo/django-DefectDojo/blob/36a12fa4eb53d62ba3b339814c44ce649633a339/dojo/unittests/tools/test_sarif_parser.py#L183
https://github.com/DefectDojo/django-DefectDojo/blob/36a12fa4eb53d62ba3b339814c44ce649633a339/dojo/unittests/scans/sarif/njsscan.sarif#L53

**Comment by valentijnscholten** [comment]
But is there an `assert` that checks that the correct CWE value is set by the parser?

**Comment by damiencarol** [comment]
I agree, for now the unit tests only test that cve is `None`

https://github.com/DefectDojo/django-DefectDojo/blob/36a12fa4eb53d62ba3b339814c44ce649633a339/dojo/unittests/tools/test_sarif_parser.py#L195

**Comment by damiencarol** [comment]
Seems to not work 
```
2021-06-18T16:30:24.6916656Z [36muwsgi_1         |[0m ======================================================================
2021-06-18T16:30:24.6917767Z [36muwsgi_1         |[0m FAIL: test_njsscan (dojo.unittests.tools.test_sarif_parser.TestSarifParser)
2021-06-18T16:30:24.6919459Z [36muwsgi_1         |[0m Generated with opensecurity/njsscan (https://github.com/ajinabraham/njsscan)
2021-06-18T16:30:24.6920686Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2021-06-18T16:30:24.6921614Z [36muwsgi_1         |[0m Traceback (most recent call last):
2021-06-18T16:30:24.6922683Z [36muwsgi_1         |[0m   File "/app/dojo/unittests/tools/test_sarif_parser.py", line 197, in test_njsscan
2021-06-18T16:30:24.6923740Z [36muwsgi_1         |[0m     self.assertEqual(327, finding.cwe)
2021-06-18T16:30:24.6924612Z [36muwsgi_1         |[0m AssertionError: 327 != 0
```

**Comment by kokhanevych-macpaw** [comment]
@damiencarol now should work. Check, please.

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
