### PR TITLE
[ENHANCEMENT] AWS Security Hub parser: include more vulnerability details

### PR DESCRIPTION
**Pull request by tomaszn**
**Description**

This merge request changes the AWS Security Hub parser to include more vulnerability details.

The first commit includes the following changes:

* Capturing related vulnerabilities from `RelatedVulnerabilities`. This follows up after discussion in #5904, where possibility of adding more vulnerability identifiers was implemented. Currently, the Grype report parser already makes use of this. The [documentation](https://docs.aws.amazon.com/inspector/v2/APIReference/API_Vulnerability.html) doesn't precisely explain this field, but from what I observe, it's used for listing other advisories related to the vulnerability (so "aliases", according to the Dependency-Track terminology).
* Capturing "vendor URL" from the vulnerability details and appending it to the references list.
* Updating the unit tests to reflect these changes and ensure the new functionality is working as expected. Additional tweaks were also made to test currently existing functionality.

~The next commit adds type hints and other tweaks that facilitate working on the parser.~

The next commit implements:

* Capturing several details from findings coming from ECR scanning. Finally, the repository name will be visible in the "Impact" field.
* Changing the title of ECR findings. Instead of ending with `Resource - <image digest>`, they will end with `Image - <repository name>/sha256:<image digest>`, which is consistent with AWS Inspector output, and clearly shows the repository affected.
* A new file with ECR samples is added, with vulnerabilities containing eight different "PackageManager" values. In future, it would be good to take a closer look how remediation instructions could be improved based on available fields.

The last commit changes the category of findings from the default, dynamic (DAST) to static (SAST). This matches how AWS Inspector and AWS Config works. In future, this should be adjusted to the the tool that generated the the finding.

**Test results**

Passed.

**Documentation**

No changes needed.

### CODE REVIEW

**Comment by Maffooch** [comment]
Please pull latest dev branch. Release bugaboos had a fix from other branches not merged into dev

**Comment by tomaszn** [comment]
@Maffooch, @kiblik, please review

**Comment by kiblik** [comment]
I see no problem :)
Just one question: Can you provide information on how exactly AWS assets are scanned? I'm just not sure that all findings will be from the SAST category.

**Comment by tomaszn** [comment]
@kiblik: SecurityHub is an aggregator of findings, just like DefectDojo, and any kind of findings can be uploaded with [batch-import-findings](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/securityhub/batch-import-findings.html).

I'm assuming that for most users findings will come from built-in AWS integrations [listed here as "Sends findings"](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-internal-providers.html):

image

Most of them are checking some kind of configuration or contents of AWS resources. Exceptions include AWS Firewall Manager, which "also sends findings [...] when an attack is identified", but I would not upload such findings to DefectDojo.

There are also [integrations with third-party sources of findings](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-partner-providers.html), some of which can report DAST issues, e.g. ([source](https://qualys.my.site.com/discussions/s/article/000005831)):

> By integrating Qualys with AWS Security Hub, vulnerabilities that are active and detected via the Qualys network scanners [...] are automatically shared with AWS Security Hub as 'findings'.

Tweaks for these can be easily added later.

That's my reasoning behind marking SecurityHub findings as SAST by default. There is no option to mark them as SCA, so I'm also treating them as SAST. What do you think about it?

**Comment by kiblik** [comment]
Well, I'm a little bit sad that the AWS Security Hub does not provide this kind of information. And I'm not sure if I would be able to handle it in a better way.

**Comment by tomaszn** [comment]
@damiencarol, @blakeaowens, please review

**Comment by tomaszn** [comment]
@cneill, would you take a look?

**Comment by tomaszn** [comment]
@devGregA, please review

**Comment by tomaszn** [comment]
@mtesauro, @grendel513, I'd appreciate your review

**Comment by tomaszn** [comment]
@Maffooch, rebased just now, would you review and merge?

**Comment by tomaszn** [comment]
@kiblik, @dsever, @alles-klar, please review

**Comment by kiblik** [comment]
I have already given you my feedback. Unfortunately, I have no permission in this project to give you approval.

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by tomaszn** [comment]
@cneill, would you approve this PR?

**Comment by tomaszn** [comment]
@Maffooch, do you think this could be approved and merged?

**Review by Maffooch — CHANGES_REQUESTED** [review]
Hi @tomaszn please remove the type annotations. We are not ready to start down this track yet

**Review by cneill — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
