### PR TITLE
Fix risk acceptance celery handler + align @task decorators

### PR DESCRIPTION
**Pull request by madchap**
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/3865

Now shows

```
$ docker-compose exec celerybeat sh -c 'celery -A dojo inspect registered'
[15/Feb/2021 09:12:31] INFO [dojo.models:3356] disabling audit logging
-> celery@9f983fab23f5: OK
  [...]
    * dojo.risk_acceptance.helper.expiration_handler
  [...]
```

and command runs

```
$ docker-compose exec uwsgi /bin/bash -c 'python manage.py risk_acceptance_handle_expiration'
[15/Feb/2021 09:12:55] INFO [dojo.models:3356] disabling audit logging
[15/Feb/2021 09:12:58] INFO [dojo.risk_acceptance.helper:141] expiring 0 risk acceptances that are past expiration date
[15/Feb/2021 09:12:58] INFO [dojo.risk_acceptance.helper:150] notifying for 0 risk acceptances that are expiring within 10 days
```

### CODE REVIEW

**Comment by valentijnscholten** [comment]
The problem seems to be that the fully qualified task name is used in `settings.dist.py`, which might be why the cron job is not working (It is working for me locally BTW).

image


To fix that, you could/should just use `@task` without any name because the name you specified is the default name chosen by celery if you don't specify any.

**Comment by madchap** [comment]
Right - but we have spelled it out in the past for the others?

**Comment by valentijnscholten** [comment]
I think that is what led me to chosing the wrong name. "It's just a name so pick something nice". In reality it must match what you chose in the celery cron settings. I vote for removing the name and just use the defaults.

**Comment by madchap** [comment]
OK. Attempting to move to automatic naming produces the following diff:

``` diff -u ~/tmp/celerytask_initial.txt ~/tmp/celerytask_final.txt                       
--- /home/fblaise/tmp/celerytask_initial.txt	2021-02-15 20:11:42.716651336 +0100
+++ /home/fblaise/tmp/celerytask_final.txt	2021-02-15 20:10:52.443889217 +0100
@@ -1,4 +1,3 @@
-    * celery_status
     * dojo.celery.debug_task
     * dojo.jira_link.helper.add_comment
     * dojo.jira_link.helper.add_epic
@@ -6,12 +5,16 @@
     * dojo.jira_link.helper.close_epic
     * dojo.jira_link.helper.update_epic
     * dojo.jira_link.helper.update_jira_issue
+    * dojo.notifications.helper.send_mail_notification
+    * dojo.notifications.helper.send_msteams_notification
+    * dojo.notifications.helper.send_slack_notification
     * dojo.risk_acceptance.helper.expiration_handler
     * dojo.tasks.add_alerts
     * dojo.tasks.async_custom_pdf_report
     * dojo.tasks.async_dupe_delete
     * dojo.tasks.async_pdf_report
-    * dojo.tasks.async_sla_compute_and_notify
+    * dojo.tasks.async_sla_compute_and_notify_task
+    * dojo.tasks.celery_status
     * dojo.tasks.cleanup_alerts
     * dojo.tools.tool_issue_updater.tool_issue_updater
     * dojo.tools.tool_issue_updater.update_findings_from_source_issues
@@ -23,7 +26,4 @@
     * dojo.utils.reopen_external_issue
     * dojo.utils.update_external_issue
     * imagekit.cachefiles.backends._generate_file
-    * send_mail_notification
-    * send_msteams_notification
-    * send_slack_notification```

**Comment by valentijnscholten** [comment]
I didn't say you should change all of them :-D But as long as you check/update the names in `settings.dist.py` and other places referring to tasks, it should work. Some tasks are just methods called from other code so the name doesn't really matter there.

**Comment by madchap** [comment]
Yea, I am checking. So far so good ;-)

While I am at it...

**Comment by madchap** [comment]
Seems good, between manually launched manage.py commands (and small amend to settings.dist.py) and checking the system settings page for celery status, and checking code.

**Comment by damiencarol** [comment]
Awesome work @madchap . I like those clean-up pull requests.

**Review by damiencarol — APPROVED** [review]

**Comment by valentijnscholten** [comment]
Now that we are cleaning up / harmonizing anyway, is there a reason some tasks have @task and others have @app.task and other have @app.task(bind=True)? I think from reading the docs they all should be OK with just @task.

**Comment by madchap** [comment]
Yea, I had noticed that too, but then, not necessarily, see https://docs.celeryproject.org/en/stable/getting-started/first-steps-with-celery.html#application

When using `@app.task` we're using the instance we instantiate in `celery.py`. I would actually want to use that one, as it relates to our app context.

When using only `@task`, it seems we're actually go backward in time (e.g. celery 3). I see the examples are still given in the docs in some places, but :man_shrugging: .

**Comment by madchap** [comment]
The regular `@task` seems to be shared between apps by default. We don't care so much in our case, so I would say the two way are achieving the goal.

However, in the spirit of standardizing, I would use `@app.task` so that we bind these tasks to the dojo app.

**Comment by madchap** [comment]
After these last changes, everything looks good as before.

```
docker-compose exec celerybeat sh -c 'celery -A dojo inspect registered'
[18/Feb/2021 06:08:38] INFO [dojo.models:3356] disabling audit logging
-> celery@b9d9eac4ec30: OK
    * dojo.celery.debug_task
    * dojo.jira_link.helper.add_comment
    * dojo.jira_link.helper.add_epic
    * dojo.jira_link.helper.add_jira_issue
    * dojo.jira_link.helper.close_epic
    * dojo.jira_link.helper.update_epic
    * dojo.jira_link.helper.update_jira_issue
    * dojo.notifications.helper.send_mail_notification
    * dojo.notifications.helper.send_msteams_notification
    * dojo.notifications.helper.send_slack_notification
    * dojo.risk_acceptance.helper.expiration_handler
    * dojo.tasks.add_alerts
    * dojo.tasks.async_custom_pdf_report
    * dojo.tasks.async_dupe_delete
    * dojo.tasks.async_pdf_report
    * dojo.tasks.async_sla_compute_and_notify_task
    * dojo.tasks.celery_status
    * dojo.tasks.cleanup_alerts
    * dojo.tools.tool_issue_updater.tool_issue_updater
    * dojo.tools.tool_issue_updater.update_findings_from_source_issues
    * dojo.utils.add_external_issue
    * dojo.utils.close_external_issue
    * dojo.utils.do_apply_rules
    * dojo.utils.do_dedupe_finding
    * dojo.utils.do_false_positive_history
    * dojo.utils.reopen_external_issue
    * dojo.utils.update_external_issue
    * imagekit.cachefiles.backends._generate_file
```

Except that now, we use our own celery app instance for all tasks, which seems to be the way forward. Since all our tasks are dojo specific and there is no intent to share them anyways, it's my take that they're better bound through our `@app.task`.

**Comment by madchap** [comment]
Also noticed that

`When using multiple decorators in combination with the task decorator you must make sure that the task decorator is applied last (oddly, in Python this means it must be first in the list)` at https://docs.celeryproject.org/en/stable/userguide/tasks.html @valentijnscholten 

Therefore, I may re-order some of your decorators?

**Comment by madchap** [comment]
I guess doing that threw a wrench in the cog.

**Comment by valentijnscholten** [comment]
The order needs to stay as is because we do the conversion from models to IDs and that needs to happen before celery kicks in.

**Comment by madchap** [comment]
> The order needs to stay as is because we do the conversion from models to IDs and that needs to happen before celery kicks in.

Yea, that's what I wondered. Unit testing locally before pushing again.

**Comment by madchap** [comment]
Still have some weird errors in unittests that will require more digging.

Like, first error is:

```
======================================================================
ERROR: test_notes_create (dojo.unittests.test_swagger_schema.EngagementTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/dojo/unittests/test_swagger_schema.py", line 395, in test_notes_create
    response = self.client.post(format_url(f"/engagements/{id}/notes/"), data, format='json')
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 296, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 234, in generic
    method, path, data, content_type, secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/dojo/api_v2/views.py", line 192, in notes
    private = new_note.validated_data['private']
KeyError: 'private'
```

then it goes to crap with things like 

```
======================================================================
FAIL: test_patch_endpoint (dojo.unittests.test_swagger_schema.AppAnalysisTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/dojo/unittests/test_swagger_schema.py", line 661, in test_patch_endpoint
    super().test_patch_endpoint()
  File "/app/dojo/unittests/test_swagger_schema.py", line 55, in wrapper
    f(self, *args, **kwargs)
  File "/app/dojo/unittests/test_swagger_schema.py", line 273, in test_patch_endpoint
    self.check_schema(schema, obj)
  File "/app/dojo/unittests/test_swagger_schema.py", line 203, in check_schema
    schema_checker.check(schema, obj)
  File "/app/dojo/unittests/test_swagger_schema.py", line 173, in check
    assert not self._has_failed, "\n" + '\n'.join(self._errors) + "\nFailed with " + str(len(self._errors)) + " errors"
AssertionError: 
tags#item0 should be of type string but value was of type <class 'dojo.api_v2.serializers.TagList'>
Failed with 1 errors
```

Unsure what that is yet. Will push here to show the errors.

**Comment by valentijnscholten** [comment]
Are those the tests expected to fail as they were created to show which parts of the swagger spec are incorrect?
All tests are passing according to GHA.

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
