### PR TITLE
Setting a duplicate without a parent_finding

### PR DESCRIPTION
**Pull request by Apipia**
Will keep from receiving a 500 error when viewing the Finding.

### CODE REVIEW

**Comment by Apipia** [comment]
Will resolve Issue #2121

**Comment by valentijnscholten** [comment]
I find the naming of this relation very confusing:

```
    duplicate_finding = models.ForeignKey('self', editable=False, null=True,
                                          related_name='original_finding',
                                          blank=True, on_delete=models.CASCADE)
```

If I understand the code correctly the field is called duplicate_finding, but it stores actually the original finding that is being duplicated here? So we have the names duplicate_finding for the field, but when accessing the relation you need to use original_finding? 

From what I can see this PR makes the if statement wrong. If a finding is marked as duplicate, but there are actually no duplicates, it will switch to returning original findings? As I said I don't understand how it works because of the namings, but shouldn't it be something like:

```
    def duplicate_finding_set(self):
        if self.duplicate:
			if self.duplicate_finding is not None:
				return Finding.objects.get(id=self.duplicate_finding.id).original_finding.all().order_by('title')
			else:
				return []
        else:
            return self.original_finding.all().order_by('title')
```

**Comment by Apipia** [comment]
@valentijnscholten To be honest, I am very much confused about the model and that code. I've made the change that you suggested and there seems to be no difference in the UI about how information is displayed one way or the other. 

Before the logic to me seemed like 
```
IF it is a duplicate and we can actually get those Findings,
    List those duplicate findings
ELSE
    ? List the original finding ?
```
And the change is now:
```
IF it is a duplicate
    If we can get those duplicate findings:
        List them
    ELSE
        Empty list
ELSE
    ? List original finding ?
```

I'm not really sure what ` return self.original_finding.all().order_by('title')` actually does.
This function is called in the template:
```
{% if finding.duplicate_finding_set %}
    <td>
        <div class="align-top">
        <div class="dropdown">
            Duplicate List <a href="#" data-toggle="dropdown">&nbsp;<i class="fa fa-ellipsis-v"></i>&nbsp;</a>
             <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              {% for duplicate in finding.duplicate_finding_set %}
                    <li>
                     <a class="" href="{% url 'view_finding' duplicate.id %}">
                     <i class="fa fa-bug"></i> {{ duplicate.title }}, <i>{{ duplicate.date }}</i>
                     </a>
                      </li>
               {%  endfor %}
               </ul>
          </div>
       </div>
    </td>
```
You would think an empty list would still show the **Duplicate List** text somewhere on the page but I couldn't find it. Maybe I'm just not sure I understand how this logic works.

**Comment by Apipia** [comment]
Maybe `{% if finding.duplicate_finding_set}` resolves to False if it returns an empty list?

**Comment by valentijnscholten** [comment]
Yeah, empty lists are {{False}} according to Python. Looking at it again, I think the else part of this if will result in an error. The original_finding field will return 1 single finding, which doesn't have an all() function.
With the original version of this PR I think it would get None as original_finding so would return another error. I think this is a left over from the PR that changed some fundamentals regarding duplicates.
I think this PR is now as good as it can get :-)

**Comment by valentijnscholten** [comment]
@Apipia Can I suggest to put this into 1.6.1? Otherwise we risk to have it open for a long time, get conflicts maybe, etc.

**Comment by valentijnscholten** [comment]
just to be sure: you need to rebase and change the base branch of the PR.

**Pull request closed without merging**
