### PR TITLE
fix(imp-options): Wrong type-checker in validate_api_scan_configuration

### PR DESCRIPTION
**Pull request by kiblik**
Fix for
- #10343
- https://owasp.slack.com/archives/C2P5BA8MN/p1717610907551889
- https://owasp.slack.com/archives/C2P5BA8MN/p1717611262044439

### CODE REVIEW

**Review by Maffooch — APPROVED** [review]
Thank you for taking care of this one

**Comment by manuel-sommer** [comment]
https://github.com/DefectDojo/django-DefectDojo/issues/10343

**Comment by kiblik** [comment]
2 notes:
- I wrote a fix only based on the error message. I do not have access to SQ right now so I'm not able to perform an end-to-end test of this fix.
- I suppose `dojo/importers/options.py` might need some tests

**Comment by Maffooch** [comment]
> I wrote a fix only based on the error message. I do not have access to SQ right now so I'm not able to perform an end-to-end test of this fix.

This is my situation as well, and the main reason this bug was introduced

> I suppose dojo/importers/options.py might need some tests

Most cases should be covered by the existing test suite as these options are invoked each time the importer class is defined. The issue is that we do not have a reliable way to test API based parsers that would use the `api_scan_configuration` field. I would say that this is an isolated incident

**Review by cneill — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
