### PR TITLE
phpcs_security_audit_v2 fix on inclusion of the warnings along with e…

### PR DESCRIPTION
**Pull request by urand0m**
Small fix to phpcs_security_audit_v2 plugin to include warnings alongside errors in the report.

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [x] Your code is python 3.5 compliant
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by urand0m** [comment]
Hi It seems the build is blocked for some other errors including token for snyk, is it possible to relaunch the build?

**Comment by madchap** [comment]
The snyk step does not fail the build, even if marked failed (actually @aaronweaver we just want to take it out, I don't remember when that thing worked).

There are failed tests, which are actually failing the build. Please go to Travis and extend that part to see them.

**Comment by urand0m** [comment]
I see, @madchap thanks for the point, will fix the tests. I am pretty new to travis so sorry for the missing.

**Comment by Maffooch** [comment]
Once the unit test is fixed, please apply your fix on the dev branch and submit the PR to the dev branch. Im closing this one since you'll have to make the changes on the dev branch of your fork.

**Pull request closed without merging**
