### PR TITLE
Fix bug in redirect function call

### PR DESCRIPTION
**Pull request by damiencarol**
According to `dojo/utils.py`, the function `redirect` has 2 parameters.
https://github.com/DefectDojo/django-DefectDojo/blob/279debf699ed2512f0af53696df5b95bcf02597f/dojo/utils.py#L1670-L1674 
This means that these calls are bugs:
https://github.com/DefectDojo/django-DefectDojo/blob/279debf699ed2512f0af53696df5b95bcf02597f/dojo/endpoint/views.py#L445
https://github.com/DefectDojo/django-DefectDojo/blob/279debf699ed2512f0af53696df5b95bcf02597f/dojo/reports/views.py#L321

### CODE REVIEW

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
good find. but can you make PR to only change those 2 lines and not reformat all the import lines.

**Comment by damiencarol** [comment]
I used `isort`. all the imports in all files are a mess. can we start to clean them?

**Comment by valentijnscholten** [comment]
yes, but in a dedicated PR.

**Comment by damiencarol** [comment]
@valentijnscholten fixed

**Review by valentijnscholten — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
