### PR TITLE
Adding Betterscan.io scan type to SARIF parser

### PR DESCRIPTION
**Pull request by marcinguy**
**Description**

Adding Betterscan.io as a new "Scan Type"

https://github.com/DefectDojo/django-DefectDojo/issues/7354

Used current SARIF implementation

**Test results**

Use SARIF parsing, so no need for test

**Documentation**

Not needed, since explained in the UI

### CODE REVIEW

**Review by Maffooch — DISMISSED** [review]

**Comment by damiencarol** [comment]
1) @marcinguy could you add a SARIF report generated by Betterscan.io ?
2) I still think this PR is not a good way to proceed. Our SARIF Parser take into account the TestType if it's define in the report.
This give this label for ex for a report generated by LGTM.com:
image
You should work on your side to generate report data that clearly show that Betterscan.io generated the report.

Something like this:
```JSON
{
   "$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
   "version":"2.1.0",
   "runs":[
      {
         "tool":{
            "driver":{
               "name":"Betterscan.io",
               "organization":"Betterscan",
               "version":"1.2.9",
 <...>
```

It's better to improve your soft and let DefectDojo do the job instead of relying on a specific code in DefectDojo to support better Betterscan.io reports.

The maximum we can do is specify in the documentation (only!) tha we support Batterscan.io through the SARIF importer.
 
I'm rejecting this PR if this PR change the code instead of only improving documentation.

**Review by damiencarol — CHANGES_REQUESTED** [review]
I'm rejecting this PR because this PR change the code instead of only improving documentation.

**Comment by marcinguy** [comment]
Hi @damiencarol 

The concept was to show "Betterscan.io" as an option in import scan type (Adding Betterscan.io to "Scan type" on "import scan results" - https://github.com/DefectDojo/django-DefectDojo/issues/7354)

So it is here on the list/dropbox/combobox:

https://user-images.githubusercontent.com/20355405/210394447-9aa0af1d-86d8-4caf-9b4a-b361eab49e18.png

1. Sample SARIF (renamed to sample_sarif.txt, since could not upload *.sarif)

[sample_sarif.txt](https://github.com/DefectDojo/django-DefectDojo/files/10528040/sample_sarif.txt)

2.  Yes I generate a valid SARIF. It has those values. So it should show properly.

```
{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Betterscan",
          "informationUri": "https://betterscan.io",
          "semanticVersion": "0.9.9",
          "rules": [
            {
              "id": "0",
              "name": "BetterscanRule",
              "shortDescription": {
                "text": "vmdetect"
```

I hope this provides answers to your questions.

To repeat: This PR is about just this combo box (Scan type)

**Comment by marcinguy** [comment]
Well, do as you wish.

It shows after import:

image

**BUT** not in the scan type before the import:

image

It would have to be selected as SARIF type.

The whole concept was to have it there and be listed in here:

image


If you will not do it, feel free to close.

**Comment by Maffooch** [comment]
This PR may be served in finding a different way to pull the newly created serif Test Types into that drop down list after they are created by the serif parser

**Comment by damiencarol** [comment]
As discussed, better to close it for now.

**Pull request closed without merging**
