### PR TITLE
Typo fix in models.py

### PR DESCRIPTION
**Pull request by SPoint42**
Typo fix for Crital => Critical

### CODE REVIEW

**Comment by valentijnscholten** [comment]
any change in model definitions needs a new migration file.

**Comment by SPoint42** [comment]
> any change in model definitions needs a new migration file.

Even for a minor Typo fix ?

**Comment by valentijnscholten** [comment]
yes, that's how Django works.

**Comment by madchap** [comment]
It would also have to be rebased on dev not master.

**Comment by valentijnscholten** [comment]
@SPoint42 in this case it might work if you also update the 0001_initia.py migration.

**Comment by valentijnscholten** [comment]
@SPoint42 I think in this case it might actually be sufficient if you change `0001_initial.py` to include the same typo fix.

**Comment by madchap** [comment]
Hi @SPoint42 

> @SPoint42 I think in this case it might actually be sufficient if you change `0001_initial.py` to include the same typo fix.

Do you want to do that? Cheers.

**Comment by SPoint42** [comment]
close by https://github.com/DefectDojo/django-DefectDojo/pull/4024

**Pull request closed without merging**
