### PR TITLE
Wrap Up Import Scanner Unit Test

### PR DESCRIPTION
**Pull request by propersam**
#1254 
When submitting a pull request, please make sure you have completed the following checklist:

- [X] Your code is flake8 compliant 
- [X] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by Maffooch** [comment]
@propersam So this is totally complete now? It can be ran without failing?

**Comment by propersam** [comment]
@Maffooch i've fixed the code from this end. There are just some sample files yet to be added to the sample scan files repository which would be the only thing obstructing this test from running.

So I would focus there now as I get sample scan files to add to the repo.

These are the currently missing sample scan files in sample-scanfile-repo:
aws_scout2
mobsf
skf
spotbugs
vcg

**Comment by Maffooch** [comment]
Got it. Whenever you get everything situated, could you make this test and the other unit tests in the tests folder run on travis?

**Comment by propersam** [comment]
> @propersam So this is totally complete now? It can be ran without failing?

it will fail for the missing-sample scan test files. but others work fine.

**Pull request merged**
