### PR TITLE
added oauth support in jira integration

### PR DESCRIPTION
**Pull request by ndenisof**
Hi!
I've added the oauth authentication in jira integrations section.

### CODE REVIEW

**Comment by whitespots** [comment]
It was tested, but required additional development from dojo main team.
Now you can add oauth jira configuration, but can not edit it.

Why is oauth jira configuration important?
Some companies use onprem jira and can not just issue a new login/password service account due to internal rules for issuing service accounts.

**Comment by Maffooch** [comment]
Any way you could remove all the unrelated changes?

**Comment by devGregA** [comment]
Reviewing this as part of our new weekly PR review. We like the idea of this PR, but there are some issues two quick examples: setting debugging to true and chmod changes. @ndenisof are you still interested in working on this?

**Comment by devGregA** [comment]
Closing due to lack or response. Please feel free to re-engage when/if you are able.

**Pull request closed without merging**
