### PR TITLE
Fix wide grants for gitlab auth

### PR DESCRIPTION
**Pull request by shipko**
**Description**
I noticed that DD requires some wide grants than it was needed. This PR is solving this problem.

I remove grants email, profile - this providing grant "openid". Grant "api" is replace to read_repository

### CODE REVIEW

**Comment by Maffooch** [comment]
Good idea. Adding to the docs would be a good idea too so people are not quite as surprised if their SSO no longer works. In the upgrade notes would prolly be best

**Comment by shipko** [comment]
@Maffooch agree with you. If developer enable gitlab_auto_import_project setting this functional will not working. I will write it in documentation.

**Comment by shipko** [comment]
@Maffooch  done!

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by devGregA — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Pull request merged**
