### PR TITLE
:sparkles: implement krakend audit parser

### PR DESCRIPTION
**Pull request by manuel-sommer**
Implement a parser for KrakenD audits

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@Maffooch why is this unittest failing? And: Since a couple of releases I can't test unitests locally anymore. 
I always get the following error:

`
ERROR: unittests (unittest.loader._FailedTest.unittests)
----------------------------------------------------------------------
ImportError: Failed to import test module: unittests
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/loader.py", line 162, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'unittests'
`

**Comment by manuel-sommer** [comment]
I just wanted to reopen this to retrigger the pipeline. This is not working anymore. Could you please reopen this @mtesauro ?

**Comment by Maffooch** [comment]
@manuel-sommer Hmm not sure on that one. I have not see it before. Also just ran unit tests a few moments ago on another PR. How are you running unit tests?

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by manuel-sommer** [comment]
> @manuel-sommer Hmm not sure on that one. I have not see it before. Also just ran unit tests a few moments ago on another PR. How are you running unit tests?

@Maffooch I run unittests of a specific parser like this: 
./dc-unittest.sh --profile postgres-rabbitmq --test-case unittests.tools.test_npm_audit_7_plus_parser.TestNpmAudit7PlusParser

**Review by cneill — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
