### PR TITLE
Ingress pathtype fix

### PR DESCRIPTION
**Pull request by dsever**
Fix of broken Ingress specification

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Is there anway we could have detected this error? I think we do linting and we do deployment to minikube, but still all tests were green?

**Comment by dsever** [comment]
teset 

> Is there anway we could have detected this error? I think we do linting and we do deployment to minikube, but still all tests were green?

It was not green https://github.com/DefectDojo/django-DefectDojo/blob/dev/helm/defectdojo/templates/django-ingress.yaml 

As far I can see, test was canceled during the test execution, but still pushed to the dev.

**Comment by valentijnscholten** [comment]
I think this was merged in https://github.com/DefectDojo/django-DefectDojo/pull/4410 with green tests?

**Comment by valentijnscholten** [comment]
old comment, check the results, all green.

**Comment by dsever** [comment]
> old comment, check the results, all green.

In any case, it should fail:

I assume problem is here in command:

--set django.ingress.enabled=false \

**Review by madchap — APPROVED** [review]
Thanks @dsever - indeed the proper thing to do, checked against https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types too.

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
