### PR TITLE
Fix for mobsfscan parser

### PR DESCRIPTION
**Pull request by hvechtomov**
Hello!
Fix for #7630. This error appeared due to the fact that in the new report, mobsfscan `CWE` was written in lower case.
Thank you!

### CODE REVIEW

**Review by damiencarol — CHANGES_REQUESTED** [review]
Please don't modify existing data, just add a new unit test for the new files.

**Comment by hvechtomov** [comment]
@damiencarol fixed

**Comment by Maffooch** [comment]
Please base against the dev or bugfix branch. Also update the unit tests to actually run that new file with the lower case CWEs

**Comment by hvechtomov** [comment]
@Maffooch rebased on bugfix, added test run, fixed merge conflict.

**Comment by hvechtomov** [comment]
@damiencarol @Maffooch could you help me please, is everything good with PR? Needa this fix soon)

**Comment by Maffooch** [comment]
Looks like this is based against master again. If this fix is needed soon, basing against the bugfix branch is the way to go. See the contributing guidelines https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by hvechtomov** [comment]
I will redo PR

**Pull request closed without merging**
