### PR TITLE
Fix #7568 do_not_reactivate notes on each (re)import

### LINKED ISSUE #7568: do_not_reactivate spamming notes on each reimport
This was reported via Slack, I'm the author of the feature in https://github.com/DefectDojo/django-DefectDojo/pull/6893

It was an oversight, the logic keeps adding notes on each reimport where the `do_not_reactivate` option is enabled, which will definitely be a problem for automated scanners and daily scans.

### PR DESCRIPTION
**Pull request by Gby56**
**Description**

Fix for https://github.com/DefectDojo/django-DefectDojo/issues/7568

**Checklist**

This checklist is for your information.

- [X] Make sure to rebase your PR against the very latest `dev`.
- [X] Features/Changes should be submitted against the `dev`.
- [X] Bugfixes should be submitted against the `bugfix` branch.
- [X] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ ] Your code is flake8 compliant.
- [ ] Your code is python 3.11 compliant.
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by Maffooch** [comment]
Got some extra stuff in here. I think most would be fine, but I am hesitant about the helm chart lock thing

**Comment by Gby56** [comment]
Is that because I changed from the dev branch to bugfix ?...
Also the reimporter.py file is completely changing, I have auto-format on save with black, and it looks like the file was not properly formatted before, no idea how...

**Comment by Maffooch** [comment]
Most likely yes. The helm lock action is new and only affects the dev branch. No idea on the black formatter thing either

**Comment by Gby56** [comment]
Crap... what do i do then ? should I make another PR from my fork's bugfix branch, to remove all these other changes ?

**Comment by Gby56** [comment]
I changed the target branch to dev @Maffooch , so it's only changing the reimporter.py file

**Review by Maffooch — APPROVED** [review]
Took me a while to find the change 😉

**Comment by coheigea** [comment]
Shouldn't it go into bugfix?

**Comment by Maffooch** [comment]
Yes, but will make it back into dev on Monday

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
