### PR TITLE
docker: update to python 3.6

### PR DESCRIPTION
**Pull request by valentijnscholten**
docker: update to python 3.6

### CODE REVIEW

**Comment by valentijnscholten** [comment]
These were just some tests to see what the test suite in travis would do. It's on the agenda for next meeting.

**Comment by valentijnscholten** [comment]
swtiched the latest to make sure it pulls 3.6. We can add a SHA later, but I am not a fan of it.

**Comment by ptrovatelli** [comment]
yeah I thought of something like, in dev branch use the latest and pin on master, but I don't know how we could do that. It would mean to manually edit all the dockerfiles when merging to master, it won't be done and stuff won't be pinned

pinning is the only way to guarantee repoducibility; we have enough issues with travis right now to not add that kind of noise.

**Comment by ptrovatelli** [comment]
@valentijnscholten I think you're good to go further with this. @madchap has already created a PR for the associated documentation https://github.com/DefectDojo/django-DefectDojo/pull/2274

can you check my comments? adding the sha will not change anything in most case. in rare case only the maintainers will overwrite the tag so we won't be "more up to date" if we pin to the minor and remove the sha. however it will always rule out a source of possible randomness that can generate different behavior from one build to another

if we'd want to be "more up to date" on dev, then we'd need to pull "python 3" for example, but that will generate randomness in the dev build and we'd need to set a procedure to pin that before merging to master.

**Comment by valentijnscholten** [comment]
I think even if we pin to the sha, dependabot will alert is for new (minor) versions. So I think pinning to 3.6#sha would be ok.

**Comment by valentijnscholten** [comment]
So this was merged before travis build was completed resulting in a broken dev branch. New PR raised to revert the changes.

**Pull request merged**
