### PR TITLE
Added HTTPS in docker and local storage

### PR DESCRIPTION
**Pull request by mrP4nd4**
…der.

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [N/A] Your code is flake8 compliant 
- [X] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [N/A] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [N/A] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by mrP4nd4** [comment]
I've added HTTPS in docker ( even it's for dev). Also, the local storage will be stored inside the root folder ( in ./data), this allows to help with the debugging.

**Comment by Maffooch** [comment]
Hey @mrP4nd4 this a good contribution, but I don't believe this is the right place for it. 

There is a well documented procedure for setting up a secure connection to DefectDojo via HTTPS. We decided to take this direction as users would likely prefer flexibility in SSL certificate signage. In this case that option is taken away from them, and creates additional work to revert it to its original state. On another note, posting a private key to a public repository is a huge vulnerability that could provoke a man in the middle attack. If this a real key that you use, I highly suggest scrapping it and making a new one.

For users that are not as concerned about the issues mentioned above, this would fit in very nicely in the [community contribution](https://github.com/DefectDojo/Community-Contribs) repository. 

Thank you again for your contribution.

**Comment by mrP4nd4** [comment]
Hi @Maffooch! 
Thanks for your quick reply. I didn't found the documented procedure you referred about the secure connection for docker container, I suggest then to mention it on the README (apologies if is there and I didn't found it).

On the other hand, the certificate and the key are the same that are inside the docker folder.  I guess are for there for testing purposes.  

I don't really understand why is under SSL in docker folder but the default image couldn't be with SSL, this is the real bad practice.

Thanks anyway for the SW and maintaining it.

**Comment by Maffooch** [comment]
Hey @mrP4nd4 

DefectDojo has a slew of other documentation sources outside the readme. There is actually a link to the docs within the readme. Here it is for [future reference](https://github.com/DefectDojo/django-DefectDojo/blob/master/README.md#documentation). As for the tutorial for running in production, it can be found in the documentation [at this location](https://defectdojo.readthedocs.io/en/latest/running-in-production.html#running-in-production).

Im very relieved to hear that those were not your actual keys. You are correct about the keys in the docker folder, those are there for _testing_ purposes only and to demonstrate that it could be done using docker-compose. 

To your last point, it is totally possible to use SSL certificates on the default image. The documentation on running in production was in fact written from the default image. 

I hope this information can be of help to you, and thank you for using DefectDojo.

**Pull request closed without merging**
