### PR TITLE
fix #905

### LINKED ISSUE #905: git ignores files unter dojo/static/dojo/
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
Git ignores files unter dojo/static/dojo/ if you check in the project in a new git repository. After building DefectDojo some files like logo.png where not found.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 16.04 / Windows 10 / Gitlab 11.4

### Install

- [ ] setup.bash
- [x] docker

### DefectDojo Version
1.5.4 (dev branch)

### Steps to Reproduce
- checkout repository
- commit to a new repository
- checkout new repository
- build defectdojo

## Fix
Change line 86 in .gitignore !dojo/static/dojo/* -> !dojo/static/dojo/

### PR DESCRIPTION
**Pull request by alles-klar**
Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant (Dojo's code isn't currently flake8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by devGregA** [comment]
Hi @alles-klar this change doesn't make sense to me or Aaron. Why would you be more selective in limiting the .gitignore?

**Comment by alles-klar** [comment]
Hi @devGregA for me, the aim of the !dojo/static/dojo/* line is not to ignore files in this folder? Is that right?
But if someone wants to add, for example a new logo, it will be ignored:
```
# cp dojo/static/dojo/img/logo.png dojo/static/dojo/img/logo-test.png
# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
# git add dojo/static/dojo/img/logo-test.png
The following paths are ignored by one of your .gitignore files:
dojo/static/dojo/img/logo-test.png
Use -f if you really want to add them.
```

Without the asterisk, it is possible to add the new logo.

If I misunderstood the aim of the !dojo/static/dojo/* line, feel free to close this issue.

**Comment by devGregA** [comment]
Hi @alles-klar the git ignore is only for the git command tool. So for instance, if someone did a `git add .` it wouldn't add ignored files to a pull request. Dojo itself doesn't ignore any files if that makes sense.

**Comment by alles-klar** [comment]
Hi @devGregA that is true. But why are files under dojo/static/dojo/ ignored. That does not make sense for me.  

In my case, I pushed DefecDojo to a Git repository from my company. Building DefectDojo from there ends with a frontend without any logos. It took me a while to understand, that simply the static files where missing because of the gitignore.

**Comment by devGregA** [comment]
Hi @alles-klar our static aggregator, yarn, should be managing all the static files for you. Maybe it didn't run correctly.

**Comment by hendrikhalkow** [comment]
Good work, @alles-klar. I like it that we use the slim images.

**Pull request closed without merging**
