### PR TITLE
Anchore Grype parser: add deduplication

### PR DESCRIPTION
**Pull request by damiencarol**
Work done:
- [x] activate de-duplication algorithm
- [x] add more details on findings like paths that match for component detection
- [x] add more unit tests

### CODE REVIEW

**Comment by valentijnscholten** [comment]
unable to approve, getting github error.

**Review by Maffooch — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]

**Comment by valentijnscholten** [comment]
added hash_code_update_needed label, maybe we should already add something to the upgrading docs now to say that `dedupe` command must be run for the anchore grype parser? that will be possible with #3753

**Comment by damiencarol** [comment]
@valentijnscholten not sure it is mandatory as this parser is configured to use uniq id from tool (DEDUPE_ALGO_UNIQUE_ID_FROM_TOOL)

**Comment by opperpanter** [comment]
Goog point, forget my comment :-)

**Comment by valentijnscholten** [comment]
Good point, forget my comment, shouldn't review PRs before coffee :-)

**Pull request merged**
