### PR TITLE
Veracode parser: remove lxml dependency

### LINKED ISSUE #3636: Investigate warning in Veracode parser
```
uwsgi_1         | test_parse_file_with_multiple_finding (dojo.unittests.test_veracode_parser.TestVeracodeScannerParser) ... /app/dojo/tools/veracode/parser.py:37: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
```

### LINKED ISSUE #4043: Time data parsing in Veracode SAST XML report import fails
`time data '' does not match format '%Y-%m-%d %H:%M:%S %Z'`

Seems like some reports I'm trying to import do not contain any `first_found_date` but I'm seeing `date_first_occurrence` elements though.

The report I'm using is version 1.5 `report_format_version="1.5"`

@damiencarol I saw you worked on dynamic parser infrastructure, is that fixed in a part 3 maybe ?
Thanks a lot !
https://github.com/DefectDojo/django-DefectDojo/blob/6a2b0e5939155554a284f90f58e6287632436ce8/dojo/tools/veracode/parser.py#L243

### PR DESCRIPTION
**Pull request by damiencarol**
Work:
- [x] remove `lxml` dependency and switch to `defusedxml`
- [x] fix wrong values for `component_name` and `component_version`
- [x] fix description of vulnerable components when `first_found_date is` missing (crash)
- [x] fix/modify mitigated status
- [x] implements CVE (both for SCA and flaws)
- [x] fixes CWE hard-coded values

Also:
- [x] fixes #3636
- [x] fixes #4043

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]

**Comment by madchap** [comment]
I see one last checkbox to be ticked. Is it ready for review or you still want to bring some changes here?

**Comment by damiencarol** [comment]
@madchap I waiting for a report with mitigation to fix this part.

**Comment by damiencarol** [comment]
waiting more data to test the mitigated part

**Comment by damiencarol** [comment]
@madchap ready to go!

**Review by madchap — APPROVED** [review]

**Pull request merged**
