### PR TITLE
pip-2020: test with new dependency resolver

### PR DESCRIPTION
**Pull request by valentijnscholten**
https://discuss.python.org/t/announcement-pip-20-2-release/4863

testing the soon-to-become-new-default-dependency-resolver in pip using `pip  --use-feature=2020-resolver`

image

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Currently build fails due to a version mismatch of `python-dateutil` in `django-auditlog`. This will be resolved in the next version of `django-auditlog`. So I guess we'll have to wait a bit.
https://github.com/jazzband/django-auditlog/blob/master/requirements.txt

**Comment by mtesauro** [comment]
Wow, this was far less dramatic than I anticipated.

Thanks for running the check

**Comment by valentijnscholten** [comment]
can be picked up again once #3639 has been merged.

**Comment by valentijnscholten** [comment]
We made some progress by updating the `django-auditlog`  and `PyJWT` packages, but in return we get two problematic packages:
```
ERROR: pygithub 1.54.1 has requirement pyjwt<2.0, but you'll have pyjwt 2.0.1 which is incompatible.
ERROR: djangorestframework-jwt 1.11.0 has requirement PyJWT<2.0.0,>=1.5.2, but you'll have pyjwt 2.0.1 which is incompatible.
```

**Comment by valentijnscholten** [comment]
So let's put it on hold again. Our current python base images don't even have the new resolver yet, so we have some time.

**Comment by damiencarol** [comment]
Rebased on the last `dev`

**Comment by valentijnscholten** [comment]
pygithub is now using pyjwt 2+ https://github.com/DefectDojo/django-DefectDojo/pull/4356

**Comment by valentijnscholten** [comment]
Still no luck, but I don't understand the build failure as according to pipdeptree it should be good.

```
django-saml2-auth==2.2.1
  - django-rest-auth [required: Any, installed: 0.9.5]
    - Django [required: >=1.8.0, installed: 2.2.20]
      - pytz [required: Any, installed: 2021.1]
      - sqlparse [required: >=0.2.2, installed: 0.3.1]
    - djangorestframework [required: >=3.1.3, installed: 3.12.4]
      - django [required: >=2.2, installed: 2.2.20]
        - pytz [required: Any, installed: 2021.1]
        - sqlparse [required: >=0.2.2, installed: 0.3.1]
    - six [required: >=1.9.0, installed: 1.15.0]
  - djangorestframework-jwt [required: Any, installed: 1.0.1]
    - Django [required: >=1.3, installed: 2.2.20]
      - pytz [required: Any, installed: 2021.1]
      - sqlparse [required: >=0.2.2, installed: 0.3.1]
    - djangorestframework [required: >=2.3.11, installed: 3.12.4]
      - django [required: >=2.2, installed: 2.2.20]
        - pytz [required: Any, installed: 2021.1]
        - sqlparse [required: >=0.2.2, installed: 0.3.1]
    - PyJWT [required: >=0.1.8, installed: 2.0.1]

```

**Comment by valentijnscholten** [comment]
Hmm could be that 3.6 is too old for some packages, let me try 3.7.

**Comment by valentijnscholten** [comment]
It builds on 3.7. Probably best to combine into the next release, which maybe 2.0.0 if we stick to our plan to skip 1.16.0 and do a bigger cleanup release.

**Comment by valentijnscholten** [comment]
python 3.7 still doesn't use the new pip resolver by default, so we need to leave the explicit pip upgrade if we want to test the new resolver.

**Comment by valentijnscholten** [comment]
with dev now on Python 3.8, which uses pip 21.1 and thus the new dependency resolver, we can close this. PR.
for the record, the old resolver can be enabled by doing:
`pip install -r requirements.txt --use-deprecated legacy-resolver`

**Pull request closed without merging**
