### PR TITLE
add logic if external redis is used

### PR DESCRIPTION
**Pull request by sandroded**
hi guys!
I've discovered the issue, that secret name for message broker is hardcoded in the helm chart when redis is used. I've added the logic to fix it.
I fixed the a typo in the values.yaml:  name for the django debug value, and added name of the key in the rabbimq secret.

This is a duplicate of https://github.com/DefectDojo/django-DefectDojo/pull/5533 but with merged recent changes from dev branch.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Some issue with the chart:
```
==> Linting helm/defectdojo
Error:  templates/: template: defectdojo/templates/django-deployment.yaml:160:19: executing "defectdojo/templates/django-deployment.yaml" at <eq .Values.rabbitmq.enabled "true">: error calling eq: incompatible types for comparison

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by sandroded** [comment]
thank you @valentijnscholten, I've fixed helm lint issues.

**Comment by devGregA** [comment]
requesting @alles-klar  takes a look as I don't have the experience nor do I use the helm charts.

**Review by alles-klar — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]
echoing @alles-klar 's approval

**Pull request merged**
