### PR TITLE
Add support to use external redis-sentinel as celery broker

### PR DESCRIPTION
**Pull request by tks98**
This PR adds support to utilize an external [redis-sentinel](https://redis.io/docs/manual/sentinel) instance as the celery broker. 

https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/redis.html#configuration
https://docs.celeryq.dev/en/stable/userguide/configuration.html#broker-transport-options

Changes:
- adds CELERY_BROKER_TRANSPORT_OPTIONS configuration to settings.dist.py and helm values
- adds redis sentinel scheme to helpers.tpl and helm values
- adds documentation

Tested via building changes and deploying defect-dojo to Kubernetes and connecting to a redis-sentinel instance also running on Kubernetes. 

```
[12/Oct/2022 21:35:05] INFO [celery.worker.consumer.connection:22] Connected to sentinel://:**@redis-sentinel-redis-sentinel:26379//
[12/Oct/2022 21:35:05] INFO [celery.worker.consumer.mingle:40] mingle: searching for neighbors
[12/Oct/2022 21:35:06] INFO [celery.worker.consumer.mingle:49] mingle: all alone
[12/Oct/2022 21:35:06] INFO [celery.apps.worker:176] celery@defect-dojo-defectdojo-celery-worker-77569d5564-g5j5l ready.
```

I am new to the project and Django overall, so if there is a better way to add support for this, please let me know.

### CODE REVIEW

**Comment by damiencarol** [comment]
@tks98 Pr needs to be against `dev` branch.

**Comment by damiencarol** [comment]
@tks98 you have some linter alerts.

**Comment by tks98** [comment]
@damiencarol I addressed the linter alerts, please let me know if anything else is required on my end

**Comment by alles-klar** [comment]
@tks98 some of the tests are failing. Please take a look.

**Comment by tks98** [comment]
@alles-klar I added a check to see if the transport options env var is set before trying to load it via json. This fixed the failing unit test, and should fix the remaining workflows once they are run.

**Comment by alles-klar** [comment]
@tks98 To me the PR looks good but it is in draft state. If it is ready and you want get it merged please remove the draft state.

**Review by alles-klar — APPROVED** [review]

**Comment by tks98** [comment]
> @tks98 To me the PR looks good but it is in draft state. If it is ready and you want get it merged please remove the draft state.

@alles-klar I removed the draft state, thank you.

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
