### PR TITLE
refactor generic parser

### PR DESCRIPTION
**Pull request by manuel-sommer**

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Review by hblankenship — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Conflicts are resolved, ready to be merged :-)

**Comment by mtesauro** [comment]
@manuel-sommer This is ready to merge once the merge conflict is fixed.

**Comment by manuel-sommer** [comment]
Done @mtesauro , you can merge

**Pull request merged**
