### PR TITLE
Fix spelling errors in Blackduck Parser

### PR DESCRIPTION
**Pull request by mike-lloyd03**
**Description**

The Blackduck parser had `Remdediation` two times. This has been corrected to `Remediation`.

### CODE REVIEW

**Comment by mike-lloyd03** [comment]
Oh and I reformatted with Black.

**Comment by StefanFl** [comment]
Hi @mike-lloyd03, thank you for your contribution. Please have a look at https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md#submitting-pull-requests. Your branch needs to be rebased to `dev` and the PR needs to be submitted to `dev`.

**Comment by mike-lloyd03** [comment]
Okay my apologies. Will do.

**Comment by damiencarol** [comment]
@mike-lloyd03 @StefanFl fixed conflicts and switching to dev.

**Review by StefanFl — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
