### PR TITLE
:tada: implement ms defender parser #8908

### PR DESCRIPTION
**Pull request by manuel-sommer**
Implement MS Defender Parser. See #8908

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@kiblik could you take a look at that PR?
Also: I don't know how to fix the unittest problem right now. Could you give me a hint?

**Comment by manuel-sommer** [comment]
Hi @mtesauro,

as you have closed https://github.com/DefectDojo/django-DefectDojo/pull/8914, I made this PR. Could you review this? I would love to see this in the next release.

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by manuel-sommer** [comment]
Oh nice, awesome :-) Two more to go.

**Review by grendel513 — APPROVED** [review]

**Review by devGregA — APPROVED** [review]

**Pull request merged**
