### PR TITLE
fix static and dynamic type finding.

### LINKED ISSUE #990: "Dynamic finding" is always ticked
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description

I'm using https://defectdojo.herokuapp.com that is running 1.5.4 as of now

### Steps to Reproduce

Case OK
- Create a Finding
- Tick the "Dynamic finding" check box
- Save
- Edit the Finding
- The "Dynamic finding" check box is ticked => OK

Case KO
- Edit the Finding
- Untick the "Dynamic finding" check box
- Save
- The "Dynamic finding" check box is ticked => KO

### PR DESCRIPTION
**Pull request by dr3dd589**
fix #990 

Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
In models.py, couldn't you just say
```
self.static_finding = self.test.test_type.static_tool
self.dynamic_finding = self.test.test_type.dynamic_tool
```
And as such get rid of the if statement?

**Comment by dr3dd589** [comment]
I don't think this will work. Can you suggest the changes I'm not able to understand what you actually want to change?

**Comment by valentijnscholten** [comment]
Yeah it might be safer to leave as you made it.

**Comment by valentijnscholten** [comment]
Not sure if I was clear, I didn't mean to leave as is and close the PR. I meant that we should stick to the if statement in your PR.

**Comment by dr3dd589** [comment]
oh no!! sorry, this is my mistake I deleted the wrong branch.

**Comment by valentijnscholten** [comment]
maybe add a more descriptive name to the branch ;-)

**Pull request closed without merging**
