### PR TITLE
feat: allowed hosts based on cidr

### PR DESCRIPTION
**Pull request by fcecagno**
**Description**

This modification install django-allow-cidr (https://pypi.org/project/django-allow-cidr/) so Django allowed hosts can be set as CIDR instead of domain name or IP address. This is very important for Kubernetes deployments: if Django metrics are enabled and we configure a ServiceMonitor to fetch metrics, an arbitrary pod will fetch the metrics from the Django pods, which typically won't be allowed:

```
defectdojo-django-77df897865-qldpd uwsgi [03/Jul/2024 04:14:43] ERROR [django.security.DisallowedHost:125] Invalid HTTP_HOST header: '10.244.2.56:8080'. You may need to add '10.244.2.56' to ALLOWED_HOSTS.
defectdojo-django-77df897865-qldpd uwsgi Traceback (most recent call last):
defectdojo-django-77df897865-qldpd uwsgi   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
defectdojo-django-77df897865-qldpd uwsgi     response = get_response(request)
defectdojo-django-77df897865-qldpd uwsgi                ^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-77df897865-qldpd uwsgi   File "/usr/local/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
defectdojo-django-77df897865-qldpd uwsgi     response = self.process_request(request)
defectdojo-django-77df897865-qldpd uwsgi                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
defectdojo-django-77df897865-qldpd uwsgi   File "/usr/local/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
defectdojo-django-77df897865-qldpd uwsgi     host = request.get_host()
defectdojo-django-77df897865-qldpd uwsgi            ^^^^^^^^^^^^^^^^^^
defectdojo-django-77df897865-qldpd uwsgi   File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 152, in get_host
defectdojo-django-77df897865-qldpd uwsgi     raise DisallowedHost(msg)
defectdojo-django-77df897865-qldpd uwsgi django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.244.2.56:8080'. You may need to add '10.244.2.56' to ALLOWED_HOSTS.
defectdojo-django-77df897865-qldpd uwsgi [03/Jul/2024 04:14:43] WARNING [django.request:241] Bad Request: /django_metrics/metrics
defectdojo-django-77df897865-qldpd nginx 10.244.3.193 - monitoring [03/Jul/2024:04:14:43 +0000] "GET /django_metrics/metrics HTTP/1.1" 400 12865 "-" "Prometheus/2.52.0" "-"
```

Setting `extraConfigs.DD_ALLOWED_CIDR_NETS: '10.244.0.0/16'`, the request will work and the problem will go away. If `DD_ALLOWED_CIDR_NETS` is not set, the previous behavior is kept.

### CODE REVIEW

**Comment by kiblik** [comment]
Can you include also some unit tests? Maybe similar to:
https://github.com/DefectDojo/django-DefectDojo/blob/659f50b129cef6568028c0422fe6157539012a74/unittests/test_remote_user.py#L135-L163

**Comment by mtesauro** [comment]
@fcecagno No problem with this change but agree with kiblik about the need for a unit test before it gets reviewed/approved.

**Comment by fcecagno** [comment]
Thanks for the review, I agree with you and will work on this.

**Comment by mtesauro** [comment]
Closed as stale. 

We're happy to have you reopen this PR if you're ready to complete the missing parts.

**Pull request closed without merging**
