### PR TITLE
Add redis transit encryption

### PR DESCRIPTION
**Pull request by KarstenSiemer**
enables the use of a tls secured connection to a redis cluster, elasticache for example

### CODE REVIEW

**Comment by KarstenSiemer** [comment]
I have no clue why the unit test failed, can someone help with it?

**Comment by valentijnscholten** [comment]
> I have no clue why the unit test failed, can someone help with it?

It's because of #3455. Can you rebase against dev, or merge dev into your branch? It's fixed in dev.

**Comment by KarstenSiemer** [comment]
@valentijnscholten ah great! Looks good now 👍

**Review by valentijnscholten — DISMISSED** [review]
I believe the term typically used for this is `TransportEncryption`. Could you rename your variables to reflect that?

**Review by madchap — APPROVED** [review]
Looks ok to me. I am fine with the `transitEncryption` term as it's what I see when quickly googling around. Not sure if you had something else in mind @valentijnscholten ?

**Comment by valentijnscholten** [comment]
either 'transport encryption' or 'in transit encryption'

**Review by madchap — CHANGES_REQUESTED** [review]
Thinking a bit more into it, the change in the helm template helper probably warrant a minor bump in the Chart.yaml as well (e.g. to 1.4.3) to notify of the change.

**Comment by KarstenSiemer** [comment]
I also fought with myself when naming it transitEncryption. But this is how it is referred to everywhere in aws.
I am fine however with both, since I think everybody will understand what it is about.
We could also simply name it "tls". Whatever is floats your boat

**Review by madchap — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]
Didn't realize transit it's the term used by aws. And didn't turn up on my google bubble.

**Comment by KarstenSiemer** [comment]
This PR was sponsored by SDA SE Open Industry Solutions

**Pull request merged**
