### PR TITLE
Fix Endpoint clean in migration

### PR DESCRIPTION
**Pull request by kiblik**
- fix bug #4861
- add test
- description into documentation

### CODE REVIEW

**Comment by Maffooch** [comment]
I think a better solution would be to add a note in the upgrade docs to run the [endpoint migration script](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/management/commands/endpoint_migration.py) rather then making a duplicate migration.

**Comment by zakrush** [comment]
@Maffooch In my case endpoint migration didn't help me when I upgraded to 2.0.3.

**Comment by kiblik** [comment]
@zakrush, @Maffooch was referring to migration which I wrote as part of this PR

@Maffooch, I removed migration and added description in to documentation

**Review by Maffooch — APPROVED** [review]
@zakrush correct. There was a bug in the endpoint migration fix. This PR corrects the bug.

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
