### PR TITLE
Support "_FILE" environmental variables

### PR DESCRIPTION
**Pull request by kiblik**
Follow the security recommendation for Kubernetes deployments: https://django-environ.readthedocs.io/en/latest/tips.html#docker-style-file-based-variables

Local test:

```diff
diff --git a/docker-compose.override.debug.yml b/docker-compose.override.debug.yml
index 40bb4e4c3..2c651eff1 100644
--- a/docker-compose.override.debug.yml
+++ b/docker-compose.override.debug.yml
@@ -8,8 +8,12 @@ services:
     environment:
       DD_DEBUG: 'True'
       DD_ADMIN_USER: "${DD_ADMIN_USER:-admin}"
-      DD_ADMIN_PASSWORD: "${DD_ADMIN_PASSWORD:-admin}"
+      DD_ADMIN_PASSWORD_FILE: "/run/secrets/dd_admin_password"
       DD_EMAIL_URL: "smtp://mailhog:1025"
+      DD_SECRET_KEY_FILE: "/run/secrets/dd_secret_key"
+    secrets:
+      - dd_admin_password
+      - dd_secret_key
     ports:
       - target: ${DD_DEBUG_PORT:-3000}
         published: ${DD_DEBUG_PORT:-3000}
@@ -20,7 +24,16 @@ services:
       - '.:/app:z'
     environment:
       DD_EMAIL_URL: "smtp://mailhog:1025"
+      DD_SECRET_KEY_FILE: "/run/secrets/dd_secret_key"
+    secrets:
+      - dd_admin_password
+      - dd_secret_key
   celerybeat:
+    environment:
+      DD_SECRET_KEY_FILE: "/run/secrets/dd_secret_key"
+    secrets:
+      - dd_admin_password
+      - dd_secret_key
     volumes:
       - '.:/app:z'
   initializer:
@@ -28,7 +41,11 @@ services:
       - '.:/app:z'
     environment:
       DD_ADMIN_USER: "${DD_ADMIN_USER:-admin}"
-      DD_ADMIN_PASSWORD: "${DD_ADMIN_PASSWORD:-admin}"
+      DD_ADMIN_PASSWORD_FILE: "/run/secrets/dd_admin_password"
+      DD_SECRET_KEY_FILE: "/run/secrets/dd_secret_key"
+    secrets:
+      - dd_admin_password
+      - dd_secret_key
   nginx:
     volumes:
       - './dojo/static/dojo:/usr/share/nginx/html/static/dojo
'
@@ -57,3 +74,8 @@ services:
         published: 8025
         protocol: tcp
         mode: host
+secrets:
+  dd_admin_password:
+    file: ./secrets/admin_password
+  dd_secret_key:
+    file: ./secrets/secret_key
diff --git a/secrets/admin_password b/secrets/admin_password
new file mode 100644
index 000000000..b3d42a4e5
--- /dev/null
+++ b/secrets/admin_password
@@ -0,0 +1 @@
+thisIsMyPassword
\ No newline at end of file
diff --git a/secrets/secret_key b/secrets/secret_key
new file mode 100644
index 000000000..627d4834b
--- /dev/null
+++ b/secrets/secret_key
@@ -0,0 +1 @@
+thisIsMySecretKey
\ No newline at end of file
```

```python
$ docker exec -it django-defectdojo-uwsgi-1 ./manage.py shell
...
>>> from django.conf import settings
>>> settings.SECRET_KEY
'thisIsMySecretKey'
```

```shell
curl -X 'POST' 'http://localhost:8080/api/v2/api-token-auth/' -H 'Content-Type: application/json' \
  -d '{"username": "admin","password": "thisIsMyPassword"}'
{"token":"9df486ed37c82ccd4df82fb05270135839dfa232"}%       
```

### CODE REVIEW

**Comment by kiblik** [comment]
Hi @grendel513 / @mtesauro / @devGregA / @Maffooch / @cneill / @blakeaowens. I would like to ask for a review.

**Comment by mtesauro** [comment]
@kiblik Mind looking at those shellcheck failures

https://github.com/DefectDojo/django-DefectDojo/actions/runs/7363234009/job/20042494957?pr=9069

**Comment by kiblik** [comment]
> @kiblik Mind looking at those shellcheck failures
> 
> https://github.com/DefectDojo/django-DefectDojo/actions/runs/7363234009/job/20042494957?pr=9069

@mtesauro, shellcheck errors have been there introduced in #9119 and will be probably fixed in #9147. It is not there because of this PR.

**Comment by mtesauro** [comment]
@kiblik Ahh, forgot about the timing of this PR vs those other two.  Thanks for setting me straight. :+1:

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
