### PR TITLE
Add django_saml2_auth for SAML2 authentication

### PR DESCRIPTION
**Pull request by UilianM**
Add django_saml2_auth for SAML2 autentication.

This template is for your information. Please clear everything when submitting your pull request.

**Note: DefectDojo is now on Python3.6 and Django 2.2.x. Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ ] Your code is flake8 compliant.
- [ ] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

Moderators: Labels currently accepted for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- performance
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies
- New Migration (when the PR introduces a DB migration)
- settings_changes (when the PR introduces changes or new settings in settings.dist.py)

# Contributors: Git Tips
## Rebase on dev branch
If the dev branch has changed since you started working on it, please rebase your work after the current dev.

On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
 git mergetool
 git rebase --continue
 ```

When everything's fine on your local branch, force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

To cancel everything: 
```
git rebase --abort
```

## Squashing commits
```
git rebase -i origin/dev
```
- Replace `pick` by `fixup` on the commits you want squashed out
- Replace `pick` by `reword` on the first commit if you want to change the commit message
- Save the file and quit your editor

Force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

### CODE REVIEW

**Comment by valentijnscholten** [comment]
@Maffooch is this as intended that these applications are enabled in settings.dist.py always even if not used?
If yes, @UilianM can you rebase against `dev`?

**Comment by Maffooch** [comment]
Hello @UilianM, a SAML2 integration was made in version 1.7.0. Check out the [docs](https://defectdojo.readthedocs.io/en/latest/social-authentication.html#saml-2-0) to see if that works for you. In addition, please make pull requests on the `dev` branch as requested by the PR template.

**Comment by Maffooch** [comment]
Didn't see the your question when I responded to this. Adding entries to installed apps creates table(s) for the that app in the db. The package we used had a step in the instructions that this PR addresses, but it is not totally necessary. I elected to leave it out on the original integration. Here's the [package](https://github.com/fangli/django-saml2-auth) for reference.

**Comment by UilianM** [comment]
I am using a docker compose and when I enable SAML2 the button in console not it is enable. I did access the container and the lib is not installed. How I enable thi lib (django-saml2-auth) using docker compose?

**Comment by UilianM** [comment]
Add 'django_saml2_auth' to INSTALLED_APPS

INSTALLED_APPS = [
    '...',
    'django_saml2_auth',
]

**Comment by Maffooch** [comment]
Is this a fresh install or an upgrade? The library was added to the master branch last week. Also be sure the to set DD_SAML2_ENABLED=(bool, True) in the environment variables section of settings.py (not settings.dist.py). They are near the top of the file.

**Comment by UilianM** [comment]
It is a new instalation.

I am using this compose:

---
version: '3.7'
services:
  nginx:
    image: defectdojo/defectdojo-nginx:1.5.4.1@sha256:7ea70b86a9e8e059af0b2d72c7779503c109c15032078a3da3a7ae55e11cd78e
    depends_on:
      - uwsgi
    ports:
      - target: 8443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - /opt/dojo/certs:/etc/nginx/certs
      - /opt/dojo/nginx/nginx.conf:/etc/nginx/nginx.conf
  uwsgi:
    image: defectdojo/defectdojo-django:1.5.4.1@sha256:389183d22e3681fbf4e844f154d3a036278a0a73bedc2a0cd42bf8b7f2ae1ada
    volumes:
      - type: bind # volume is another, less performant option
        source: /opt/dojo/media
        target: /app/media
    entrypoint: ['/entrypoint-uwsgi.sh']
    environment:
      DD_DEBUG: 'False'
      DD_ALLOWED_HOSTS: ${DD_ALLOWED_HOSTS:-*}
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_USER: ${DD_CELERY_BROKER_USER:-guest}
      DD_CELERY_BROKER_PASSWORD: ${DD_CELERY_BROKER_USER:-guest}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
      DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET: ${DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET}
      DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_ENABLED: ${DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_ENABLED}
      DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID: ${DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID}
      DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY: ${DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY}
      DD_SAML2_ENABLED: ${DD_SAML2_ENABLED}
      DD_SAML2_METADATA_AUTO_CONF_URL: ${DD_SAML2_METADATA_AUTO_CONF_URL}
      DD_SAML2_ASSERTION_URL: ${DD_SAML2_ASSERTION_URL}
      DD_SAML2_ENTITY_ID: ${DD_SAML2_ENTITY_ID}
      DD_SAML2_DEFAULT_NEXT_URL: ${DD_SAML2_DEFAULT_NEXT_URL}
      DD_SAML2_NEW_USER_PROFILE: ${DD_SAML2_NEW_USER_PROFILE}
      DD_SAML2_ATTRIBUTES_MAP: ${DD_SAML2_ATTRIBUTES_MAP}
  celerybeat:
    image: defectdojo/defectdojo-django:1.5.4.1@sha256:389183d22e3681fbf4e844f154d3a036278a0a73bedc2a0cd42bf8b7f2ae1ada
    entrypoint: ['/entrypoint-celery-beat.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_USER: ${DD_CELERY_BROKER_USER:-guest}
      DD_CELERY_BROKER_PASSWORD: ${DD_CELERY_BROKER_USER:-guest}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
  celeryworker:
    image: defectdojo/defectdojo-django:1.5.4.1@sha256:389183d22e3681fbf4e844f154d3a036278a0a73bedc2a0cd42bf8b7f2ae1ada
    entrypoint: ['/entrypoint-celery-worker.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_USER: ${DD_CELERY_BROKER_USER:-guest}
      DD_CELERY_BROKER_PASSWORD: ${DD_CELERY_BROKER_USER:-guest}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
  initializer:
    image: defectdojo/defectdojo-django:1.5.4.1@sha256:389183d22e3681fbf4e844f154d3a036278a0a73bedc2a0cd42bf8b7f2ae1ada
    entrypoint: ['/entrypoint-initializer.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_ADMIN_USER: ${DD_ADMIN_USER:-admin}
      DD_ADMIN_MAIL: ${DD_ADMIN_USER:-admin@defectdojo.local}
      DD_ADMIN_FIRST_NAME: ${DD_ADMIN_FIRST_NAME:-Admin}
      DD_ADMIN_LAST_NAME: ${DD_ADMIN_LAST_NAME:-User}
      DD_INITIALIZE: ${DD_INITIALIZE:-false}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
  rabbitmq:
    image: rabbitmq:3.7.25@sha256:2e8ebfd211396d0f2d26f1cd540a793904cd5ebbc790ad021a2dbc83aa3aea2a

**Comment by UilianM** [comment]
This variable DD_SAML2_ENABLED is not set in settings.py.

**Comment by valentijnscholten** [comment]
Looks like you're using a very old version of Defect Dojo. Please try again with 1.7.1.

**Comment by UilianM** [comment]
I am using this deploy procediment:
https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

**Comment by Maffooch** [comment]
from the readme of that repo:
"This guide was written using the DefectDojo 1.5.4.1 release. Newer releases should also work if you update the docker-compose.yml file as needed." 

This should be what you need to do. Looks to be pulling images from our [dockerhub](https://hub.docker.com/u/defectdojo).  I think if you update the images in docker-compose.yml, you should be good to go. Then follow DefectDojo's documentation I linked above to set up SAML2.

**Comment by UilianM** [comment]
Thanks @Maffooch, I change the docker file for latest images and works.

Thanks.

**Pull request closed without merging**
