### PR TITLE
[ENHANCEMENT] AWS Security Hub parser: organize and extend test cases

### PR DESCRIPTION
**Pull request by tomaszn**
**Description**

This change organizes AWS Security Hub sample reports by prefixing them with the name of the tool that generated findings inside. It also adds a README file in the samples directory, and adds one new test case. Some little improvements were also made, like adding type hints.

This is a base for further work on the parser:
* adding more samples, with focus on tools not yet covered (like AWS GuardDuty),
* parsing additional information, like CVE advisory numbers,
* tagging the findings, so they can be filtered easier.

**Test results**

Relevant test cases were updated to match new names of the sample reports, and a new test case was added for the additional report. Tests pass without warnings.

**Documentation**

No changes needed. This changeset is a base for further work on SecurityHub parser.

### CODE REVIEW

**Comment by Maffooch** [comment]
@tomaszn good stuff here. The further work proposed makes sense to me and will improve the support for the suite of AWS tools

Running the tests now and will approve when everything turns green

**Review by Maffooch — APPROVED** [review]

**Comment by tomaszn** [comment]
@mtesauro, @cneill, please review

**Review by cneill — APPROVED** [review]

**Comment by tomaszn** [comment]
@grendel513, @blakeaowens: please review

**Review by blakeaowens — APPROVED** [review]

**Comment by tomaszn** [comment]
@devGregA, @kiblik, please review

**Review by damiencarol — APPROVED** [review]

**Comment by kiblik** [comment]
Maybe a little bit late :)
Looks fine to me. Just not sure if you wanted to put README to unittests. I suppose it might need to be in the documentation or in the parser.

**Pull request merged**
