### PR TITLE
:bug: fix severity in sonarqube scan detailed

### PR DESCRIPTION
**Pull request by manuel-sommer**
see #10150

### CODE REVIEW

**Review by Maffooch — APPROVED** [review]

**Review by cneill — CHANGES_REQUESTED** [review]
The change + test look fine, but can you cut down the size of the example scan file? >3MB seems excessive to test this

**Comment by manuel-sommer** [comment]
Done @cneill

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]
Thanks!

**Review by grendel513 — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
