### PR TITLE
Docs: Split upgrade notes

### PR DESCRIPTION
**Pull request by kiblik**
Solution for https://github.com/DefectDojo/django-DefectDojo/pull/8975#issuecomment-1808462202

image

image

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

Awesome job on this!

**Review by cneill — CHANGES_REQUESTED** [review]
Just a few little tweaks here. Thanks for doing this!

**Comment by kiblik** [comment]
> Just a few little tweaks here. Thanks for doing this!

Thank you. I accepted the changes and applied them to existing notes as well.

**Review by cneill — APPROVED** [review]
Awesome - thanks!

**Review by grendel513 — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
