### PR TITLE
Close/reopen an engagement from API

### PR DESCRIPTION
**Pull request by twsagarcia**
Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [X] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.).
- [X] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.

### CODE REVIEW

**Comment by adracea** [comment]
@valentijnscholten I think you're more familiar with this area since I haven't used api_v2 as much , at first glance it looks good .

**Comment by valentijnscholten** [comment]
I like the addition, but would like to see the logic moved out of the api file and maybe reuse the logic in engagement/views.py or have shared logic somewhere else. The existing logic also closed the epic in JIRA, so I think that should be performed as well when closing/opening via API.

**Comment by twsagarcia** [comment]
@valentijnscholten that's a good idea. 

There are a lot of possible ways to do it, what does suit better for you guys?

To move out the common logic: 
- as methods at the Engagement model. e.g. def close(self) / def reopen(self).
- in a new module in engagements or in engagements.__init__.py. Any proposal for naming the module? The methods would be something like: def close(eng) / def reopen(eng).
- in new methods in engagements/views.py. Any proposal for naming these methods?
- somewhere else. Proposals?

**Comment by jpescalona** [comment]
@twsagarcia i would suggest to create this logic on a common module on views. Model is not the correct place to handle logic. You should not overthink where to place the logic, it just a matter of the concept of [domain model](https://stackoverflow.com/questions/12578908/separation-of-business-logic-and-data-access-in-django/12579490#12579490), probably a helper module under engagements will be okay for this purpose.

**Comment by twsagarcia** [comment]
Updated PR with @jpescalona and @valentijnscholten proposals. 
Please review.

**Comment by valentijnscholten** [comment]
Great, indeed no need to overthink but very good that "logic" like this in one place.

**Comment by jpescalona** [comment]
Great job @twsagarcia!

**Comment by devGregA** [comment]
@aaronweaver would you please review & merge if it looks good to you.

**Pull request merged**
