### PR TITLE
added healthcheck middleware for ALBs

### PR DESCRIPTION
**Pull request by lme-nca**
## :warning: Note on feature completeness :warning:

We are narrowing the scope of acceptable enhancements to DefectDojo in preparation for v3. Learn more here:
https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Description**

This fixes the following bug: https://github.com/DefectDojo/django-DefectDojo/issues/9506 

**Test results**

We are running this in our AWS deployment of AWS, if fixes the ALB unhealthy status and stops many ERROR log statements

**Documentation**

added commented out Annotation in HELM chart to indicate that his is available for AWS deployments

**Checklist**

This checklist is for your information.

- [ ] Make sure to rebase your PR against the very latest `dev`.
- [ ] Features/Changes should be submitted against the `dev`.
- [ ] Bugfixes should be submitted against the `bugfix` branch.
- [ ] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ ] Your code is flake8 compliant.
- [ ] Your code is python 3.11 compliant.
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

**Extra information**

Please clear everything below when submitting your pull request, it's here purely for your information.

Moderators: Labels currently accepted for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- performance
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies
- New Migration (when the PR introduces a DB migration)
- settings_changes (when the PR introduces changes or new settings in settings.dist.py)

# Contributors: Git Tips
## Rebase on dev branch
If the dev branch has changed since you started working on it, please rebase your work after the current dev.

On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
 git mergetool
 git rebase --continue
 ```

When everything's fine on your local branch, force push to your `myOrigin` remote:
```
git push myOrigin --force-with-lease
```

To cancel everything:
```
git rebase --abort
```

## Squashing commits
```
git rebase -i origin/dev
```
- Replace `pick` by `fixup` on the commits you want squashed out
- Replace `pick` by `reword` on the first commit if you want to change the commit message
- Save the file and quit your editor

Force push to your `myOrigin` remote:
```
git push myOrigin --force-with-lease
```

### CODE REVIEW

**Comment by Maffooch** [comment]
Is there another place where this health check can live? Having it in the middleware is an extra check on every single request. I understand the reasoning is to eliminate modifying the allowed hosts lists

**Comment by lme-nca** [comment]
> Is there another place where this health check can live? Having it in the middleware is an extra check on every single request. I understand the reasoning is to eliminate modifying the allowed hosts lists

I dont think so, part of the problem is that the "ALLOWED_HOST" list check is triggered in the middleware on every check, specifically by this call: https://github.com/django/django/blob/9c5e382b981608a26f2c55f1259d9e823fee5f15/django/middleware/common.py#L48 in the "common" middleware. 

Also see the original error I put in the Issue: 
`File "/usr/local/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in call
with context.bind_template(self):
File "/usr/local/lib/python3.11/contextlib.py", line 137, in enter
return next(self.gen)
^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/template/context.py", line 254, in bind_template
response = self.process_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**File "/usr/local/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
updates.update(processor(self.request))
host = request.get_host()**
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 152, in get_host
^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/context_processors.py", line 38, in bind_alert_count
if request.user.is_authenticated:
^^^^^^^^^^^^
raise DisallowedHost(msg)``

So @Maffooch unless you know another way to intercept this request before it reaches the Middleware, I think it kind of has to be fixed here.

**Comment by mtesauro** [comment]
@lme-nca Really appreciate the PR but I agree with Cody here about the use of middleware.

I also have concerns about this being a vendor specific change that negatively impacts any one who doesn't happen to use AWS by having a potentially unnecessary middleware check on every request.

We've been working to ensure that all features of DD can be tested by our GH Actions and having vendor specific changes means to truly test that, we need an AWS account, launch infra, etc. This is why we stopped taking new API integrations - they can't be tested and we want the DefectDojo that the community uses to be as rock solid as possible.

With that said, we're not going to accept this PR for the reasons outlined above.

**Comment by lme-nca** [comment]
Hi @mtesauro, @Maffooch, I cant say im not a little disappointed by that decision, please take into consideration the following points:

 I don't think this is a "vendor" specific change.... This change merely introduces a "HEALTH" endpoint that does not get blocked by the "ALLOWED_HOST" list. Currently most liveness checks in the Kuberenets deployment use the login url and synthetically set the correct host header (see https://github.com/DefectDojo/django-DefectDojo/blob/738dca4534382049ca7587a60fb6b33715213943/helm/defectdojo/templates/django-deployment.yaml#L215 ). This is even though these healthchecks don't call these endpoints using this hostname at all, but rather the internal ip. Imho they should/could also be using this health endpoint. I would therefore propose to use this /health endpoint for all the liveness checks, that way this becomes a generic change to introduce a /health endpoint that is not bothered by "ALLOWED_HOST" checks...

I also wonder about the "performance" impact of this change, Middleware already runs on every request so i dont really understand how 1 IF statement could have a big impact on performance in this regard.

As for testing this can easily be tested outside of AWS, just call the health endpoint without the correct host set and see that you receive a valid response...

Lastly, I admit this isn't the prettiest change, but even Django themselves fixed this problem by introducing Middleware, see: https://github.com/mozmeao/infra/issues/735 and https://pypi.org/project/django-allow-cidr/ . The only difference is that they whitelist a complete range for all endpoints........ So if you reject my solution I would like to ask you to come up with an alternative that can solve this problem ? I would then happily try and implement this.

**Comment by HackityAnn** [comment]
Have to say that I agree with @lme-nca , his proposed solution would be the Django way for this (and the way that I will hack this in on our own DD instance). Rock solid also means being able to handle health checks in a good way, middleware gives us that solution.

**Comment by kiblik** [comment]
Is it possible to reconsider this PR? To be honest, I suppose the only "vendor-specific" part in this PR is the title and comments. Publication of a super simple health check does not expose any sensitive information and this endpoint might be valuable also for other environments that can benefit from it (not only ALB).

**Pull request closed without merging**
