### PR TITLE
Add more findings info to engagement/test views

### PR DESCRIPTION
**Pull request by madchap**
Addresses https://github.com/DefectDojo/django-DefectDojo/issues/3001

I always find myself wondering how many mitigated findings or active/verified are in the engagements when looking at a glance.
With so many CI/CD imports, at a glance look become important.

This PR adds a couple columns when viewing engagements,

image

and drilling to tests

image

- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by madchap** [comment]
I can't reproduce any JS error locally :thinking: 

`integrationtest_1  | {'level': 'SEVERE', 'message': "http://nginx:8080/static/jquery/dist/jquery.js 4054:2 Uncaught TypeError: Cannot read property 'mData' of undefined", 'source': 'javascript', 'timestamp': 1602955753210}`

**Comment by valentijnscholten** [comment]
we should really prefetch those counts

**Comment by Maffooch** [comment]
+1 on the prefetching. Annotate those counts to test query set and reference them directly in the template.

**Comment by devGregA** [comment]
I always like more info. It seems like the only one not included at this point is false positive count?

**Comment by madchap** [comment]
> I always like more info. It seems like the only one not included at this point is false positive count?

False-positives are also marked as mitigated, so will fall within that count. I think not putting every single status in there matters just as much as putting enough (like "mitigated" overall regardless of the specific status). Wdyt?

**Review by valentijnscholten — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
