### PR TITLE
Slimmer docker images

### PR DESCRIPTION
**Pull request by alles-klar**
Adding a new build image to build the django and nginx image. This removes the dependency
between the django(release) image and the nginx image.

Also adding a condition which breaks the pipeline when the docker build fails.

Last discussion about this topic: #1044

### CODE REVIEW

**Comment by aaronweaver** [comment]
@ptrovatelli can you review? Also, @alles-klar I believe we still need postgresql-client for those that use postgres with Kubernetes.

**Comment by alles-klar** [comment]
@aaronweaver the postgresql test in travis were successfull. If the tests does not determine these kind of problems, we should definitely improve them.  Also I personally use a postgresql database with a similar dockerfile and had not problems yet.

**Comment by aaronweaver** [comment]
Thanks for confirming @alles-klar

**Comment by ptrovatelli** [comment]
@alles-klar(@aaronweaver) can you update DOCKER.md please? this needs to be added before the other 2
`docker build -t defectdojo/defectdojo-build -f Dockerfile.build .`

Might be the occasion to add info about proxies: 
`docker build  --build-arg http_proxy=http://proxyserver:8080 --build-arg https_proxy=http://proxyserver:8080 -t defectdojo/defectdojo-build -f Dockerfile.build .`

Other than that it seems to work; i haven't checked the size of the images
I think this is new though: many warnings during image building and running about dependency issues: 
```

initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | Installed 1 object(s) from 1 fixture(s)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | Installed 2 object(s) from 1 fixture(s)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | Installed 29 object(s) from 1 fixture(s)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | Installed 476 object(s) from 1 fixture(s)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | Installed 228 object(s) from 1 fixture(s)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | Installed 3 object(s) from 1 fixture(s)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | Installed 13 object(s) from 1 fixture(s)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
initializer_1   | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
initializer_1   |   RequestsDependencyWarning)
```

**Comment by alles-klar** [comment]
@ptrovatelli  and @aaronweaver I created a new pull request #1096 with the updated documentation.

**Comment by ptrovatelli** [comment]
the urllib3 version issue is fixed by https://github.com/DefectDojo/django-DefectDojo/pull/1105/

**Pull request merged**
