### PR TITLE
Added unique_id_from_tool for "to mitigate" logic for Checkmarx

### PR DESCRIPTION
**Pull request by dshraddha23**
**Note: DefectDojo is now on Python3.5 and Django 2.2.x Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

To tag a finding as "Mitigated" for scan_type "Checkmarx Scan detailed" the current logic does not have "unique_id_from_tool" as a distinct identifier. Adding the unique_id_from_tool correctly identifies the previous mitigated finding during re-import of scan.

### CODE REVIEW

**Comment by ptrovatelli** [comment]
ideally we should use the deduplication configuration to know if a finding is the same as another, so that it works for all scanners and all configuration. As in sync_dedupe function in utils.py. 
that would require a bit of work though, together with refactoring the duplicated code pointed by Valentijn

**Comment by ptrovatelli** [comment]
@dshraddha23 if you can solve the conflict i'm fine to merge as is; it's a start :)
thanks

**Comment by valentijnscholten** [comment]
I think this should be based on the dedupe config of the parsers?

**Comment by damiencarol** [comment]
@dshraddha23 hello, do you have any update on this one? it seems that there is a merge conflit now

**Comment by damiencarol** [comment]
Tried to rebase on the last dev with success but @dshraddha23 didn't authorize reviewers to modify the pull request so only @dshraddha23 could "finish" it. Hard to help moving forward with this pull request.
I will close for now.

**Comment by ptrovatelli** [comment]
this is more or less the same issue as https://github.com/DefectDojo/django-DefectDojo/issues/3675 . i'm looking into it.

**Pull request closed without merging**
