### PR TITLE
Rev actions to latest ubuntu version per deprecation

### PR DESCRIPTION
**Pull request by Maffooch**
https://github.com/actions/runner-images/issues/6002

### CODE REVIEW

**Review by blakeaowens — APPROVED** [review]
Looks good to me.

**Comment by damiencarol** [comment]
@Maffooch do we want that? it will force us to do maintenance on the doc part.

**Comment by Maffooch** [comment]
Unfortunately do not have much of a choice tbh :/ the deprecation is happening either way

The gh-pages action will be phased out eventually after a few more versions as the the docs are being built in another repo that deploys too https://documentation.defectdojo.com. the gh-pages action is keeping https://defectdojo.github.io/django-DefectDojo/ alive for folks on older releases.

**Comment by damiencarol** [comment]
ok, so moving forward

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
