### PR TITLE
:bug: fix typo in settings.disty.py, #10529

### PR DESCRIPTION
**Pull request by manuel-sommer**
see #10529

### CODE REVIEW

**Comment by mtesauro** [comment]
Closing and re-opening to try to make Flake8 happy.

**Review by cneill — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by MarMoriMem — APPROVED** [review]

**Comment by MarMoriMem** [comment]
Approved

**Review by chalkyfuller — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Please don't forget to merge ;-)

**Pull request merged**
