### PR TITLE
Tag filtering + general search improvements

### LINKED ISSUE #3451: Search using tag on Test/Engagement
**Is your feature request related to a problem? Please describe**
In our instance, we are using tags. We are using them with external scripts to do various stuff from reporting to auto-managing the findings.

On the finding, we are using tags about the status inside our internal process.

On the test, we are using tags about specific part of the products impacted.

On an engagement, we are using tags to separate the source of the scan, between customer, our team, other team, etc.

**Describe the solution you'd like**
We would like to do a search for existing finding with any of the tags on the parent levels. 
E.g. finding about CVE-XXX, inside a test with given tag or equivalent for an engagement.
That will help us reduce the number of results of the search that are not directly useful for us.

**Describe alternatives you've considered**
The current workaround is to look at the full list of result and due to the size of the search results it's quickly annoying.

cc @valentijnscholten @madchap

### PR DESCRIPTION
**Pull request by valentijnscholten**
based on #3333 so merge that one first!

Fixes #3451 

Sometimes the most important tags are on Tests/Engagements/Products and not on Findings. 
For example if all ci/cd enagements are marked ci/cd and you want to filer on or search findings in those engagements only. Currently that is not possible because you can only filter/search on tags that are attached to findings.

This PR adds some more tags search boxes to also filter on tags on Tests/Engagements/Products:

image

Please note this also works on the "simple (but becoming more advanced) search"

And you can also search on
- `tag:magento`
- `product-tag:magento`
- `engagement-tag:cicd`
- `test-tag:stupid_test`

same for `tags` (plural).

any `tag` will do a string based `contains` (so specify 1 word/tag)
any `tags` will to a many to many `in` (so can have multiple csv tags)

the filters are everywhere where `OpenFindingsFilter` or `SimilarFindingFilter` are used.

also reworked the query parsing a bit so there can be combinations like

`tag:cloud jquery`
`product-tags:saas jboss`

also CVE filtering now goes directly to the CVE column to make it more reliable.

### CODE REVIEW

**Comment by madchap** [comment]
@valentijnscholten we would like to test this PR, but there are too many conflicts showing :-D Could you please let us know?

**Comment by valentijnscholten** [comment]
hmm that's because we squash PRs on merge. Did a quick merge, hopefully it's all good. Will double check later.

**Comment by valentijnscholten** [comment]
looks like nothing works as expected anymore.

**Comment by valentijnscholten** [comment]
looks good now.

**Review by devGregA — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
