### PR TITLE
UI v2: Main page

### PR DESCRIPTION
**Pull request by uditmishra128**
experiment for a new UI based on react

### CODE REVIEW

**Comment by ptrovatelli** [comment]
hello @uditmishra128 . Can you edit the description to explain what this is doing please? :)
Thanks

**Comment by uditmishra128** [comment]
Do you mean to say the Read Me file?

**Comment by ptrovatelli** [comment]
the PR description is empty. I have no clue what this PR is doing.

**Comment by ptrovatelli** [comment]
is this related to https://github.com/DefectDojo/django-DefectDojo/pull/3808 ?

**Comment by damiencarol** [comment]
@ptrovatelli this PR is part of https://github.com/DefectDojo/django-DefectDojo/issues/3807

**Comment by damiencarol** [comment]
As we moved code to another repository https://github.com/DefectDojo/ui2-incubating , I'm closing this one.

**Pull request closed without merging**
