### PR TITLE
risk acceptance: fix notes bugs

### PR DESCRIPTION
**Pull request by valentijnscholten**
two bugs fixed:
- when adding a risk acceptance with a note, a many2many relationship related error occurred
- the 'e' keydown event (to edit the risk acceptance) conflicted with the notes textarea (works fine on every other page we use the same construct)

### CODE REVIEW

**Review by madchap — APPROVED** [review]
lgtm, thanks :)

**Review by Maffooch — APPROVED** [review]

**Comment by wurstbrot** [comment]
Note for others:
In case the finding is not correctly stored (my developers say that the error is sometimes not shown but maybe in the background), it might lead to think the finding got accepted (because it is shown) and it is true. The process of setting the status to inactive is not applied and therefore the finding will be shown again.

Attached "Correct application of acceptance" and "Bad application of acceptance":
Screenshot from 2021-03-16 09-24-00
Screenshot from 2021-03-16 09-24-26

**Comment by valentijnscholten** [comment]
@wurstbrot Is this a new bug you are seeing or are you just adding info to the old/fixed bug?

**Comment by wurstbrot** [comment]
Just adding info to the old/fixed bug.
I haven't tried the new version with this bug fix, but I belive that my described behaivor is fixed by this PR.

**Pull request merged**
