### PR TITLE
docker-compose not working

### PR DESCRIPTION
**Pull request by wurstbrot**
For dev env. it is given to copy the settings.py.

I could not make it work without the copy step in docker-compose test env., too.

### CODE REVIEW

**Comment by ptrovatelli** [comment]
Hi @wurstbrot. Thanks for sharing. What do you mean by "docker-compose test env"? What environment are you using? can you check with: 
`docker/setEnv.sh`
or 
`ls -l docker-compose.override.yml`

You have added the comment in the quickstart instructions which is the "release" env by default.
Also you have commited this on master. Are you using the master branch? Usually we ask to create PRs on the dev branch alghough being just a doc push it can be discussed; still will need to be integrated to dev branch is confirmed. 

Thanks!

**Comment by wurstbrot** [comment]
It is the same as https://github.com/DefectDojo/django-DefectDojo/pull/1474

**Comment by ptrovatelli** [comment]
@wurstbrot I think you probably have a docker-compose.override.yml link remaining which is why you're seing this issue. 
It may be related to this: https://github.com/DefectDojo/django-DefectDojo/pull/1479
What's your OS? some OSes may checkout this file as a working symbolic link. 
For me  (linux) it was checked out with in contents the name of the destination (docker-compose.override.dev.yml)
If you remove the file, you shouln't have a problem.

**Comment by ptrovatelli** [comment]
the missing "settings.py" issue is only present when mounting the docker volume (in dev setup) if the unix user inside of the container fails doing that copy. 
the easy fix is to do the copy manually before starting the app but this is only required when the volume is mounted. 
the "clean" fix is setting a coherent unix user id in Dockerfile.django but this depends on each host! 
it's here:
`USER 1001`
that uid needs to be the one running the application on the host (see https://github.com/DefectDojo/django-DefectDojo/pull/1045#issuecomment-482736718 )

this was discussed in 
https://github.com/DefectDojo/django-DefectDojo/issues/1036
https://github.com/DefectDojo/django-DefectDojo/issues/1026
https://github.com/DefectDojo/django-DefectDojo/pull/1028

**Comment by wurstbrot** [comment]
you are right, for master it is working after changing fullcalendar version.

**Pull request closed without merging**
