### PR TITLE
Change CVSS calculator to use CVSSv3.1

### PR DESCRIPTION
**Pull request by HomeSen**
**Description**

This PR replaced the relevant static JavaScript code to upgrade from CVSSv3.0 to v3.1, as requested in #7528 
As source, the sample files from first.org had been used, just like it was for CVSSv3.0

### CODE REVIEW

**Comment by Maffooch** [comment]
@HomeSen please rebase against the `dev` branch

**Comment by HomeSen** [comment]
@Maffooch: I've run `git rebase dev cvss31` as well as a `--force-with-lease` push, now. Apparently, this doesn't change the merge target (but rather added a whole lot new commits and tags to this PR). Is this expected, or should I start from a fresh fork and submit a new PR based on the dev branch?

**Comment by damiencarol** [comment]
@HomeSen fixed your base pbs

**Comment by HomeSen** [comment]
Thank you, @damiencarol

**Comment by damiencarol** [comment]
@Maffooch are you able to test it? I can't these days, I'm testing another branch

**Comment by mtesauro** [comment]
@blakeaowens Mind testing this out?

**Review by blakeaowens — APPROVED** [review]
@mtesauro  I have tested this PR and everything works as expected. Approved.

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
