### PR TITLE
API: Check missing endpoints

### PR DESCRIPTION
**Pull request by kiblik**
Missing endpoints
 - [ ] dojo.models.Contact
 - [ ] dojo.models.Product_Line
 - [ ] dojo.models.Report_Type
 - [ ] dojo.models.CWE
 - [ ] dojo.models.BurpRawRequestResponse
 - [ ] dojo.models.FileAccessToken
 - [x] dojo.models.Announcement
 - [ ] dojo.models.UserAnnouncement
 - [ ] dojo.models.BannerConf
 - [ ] dojo.models.GITHUB_Conf
 - [ ] dojo.models.GITHUB_Issue
 - [ ] dojo.models.GITHUB_Clone
 - [ ] dojo.models.GITHUB_Details_Cache
 - [ ] dojo.models.GITHUB_PKey
 - [ ] dojo.models.Tool_Product_History
 - [ ] dojo.models.Objects_Review
 - [ ] dojo.models.Objects_Product
 - [ ] dojo.models.Testing_Guide_Category
 - [ ] dojo.models.Testing_Guide
 - [ ] dojo.models.Benchmark_Type
 - [ ] dojo.models.Benchmark_Category
 - [ ] dojo.models.Benchmark_Requirement
 - [ ] dojo.models.Benchmark_Product
 - [ ] dojo.models.Benchmark_Product_Summary
 - [x] dojo.models.Rule
 - [x] dojo.models.Child_Rule
 - [x] dojo.models.FieldRule
 - [ ] dojo.models.Choice

### CODE REVIEW

**Comment by kiblik** [comment]
`dojo.models.GITHUB_*` part is needed by https://github.com/DefectDojo/django-DefectDojo/issues/8819

**Comment by kiblik** [comment]
Hi @grendel513 / @mtesauro / @devGregA / @Maffooch / @cneill / @blakeaowens. I would like to ask for a review.

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Comment by mtesauro** [comment]
Not sure why AccessLint is stuck, going to merge this.

**Pull request merged**
