### PR TITLE
Revert "Updated all dockerfiles to match the django dockerfile so UID/GIDs are consistent across dockerfiles"

### PR DESCRIPTION
**Pull request by Maffooch**
Reverts DefectDojo/django-DefectDojo#5691

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by Maffooch** [comment]
Waiting until tests pass.

**Comment by Maffooch** [comment]
K8's work now, but integration tests do not. They should work after reverting #5681 

Merging this now so the other can be reverted

**Comment by dsever** [comment]
> K8's work now, but integration tests do not. They should work after reverting #5681
> 
> Merging this now so the other can be reverted

What is the problem with k8s?

**Comment by Maffooch** [comment]
After #5691 was merged, K8 test did not pass any longer on the dev branch. Reverting #5691 made sure the unit tests for K8 deploys works again.

**Comment by dsever** [comment]
Probably hadcoded djangosecuritycontext defined in helm values.

**Pull request merged**
