### PR TITLE
Helm Chart: Fix indentation for ingressClassName

### PR DESCRIPTION
**Pull request by MeNsaaH**

### CODE REVIEW

**Comment by dsever** [comment]
PR should be agains the dev repo

**Comment by MeNsaaH** [comment]
@dsever  are helm releases released with defectDojo? I feel like they should be two different releases/pipelines since the helm release doesn't impact the code 🤔

**Comment by dsever** [comment]
> @dsever are helm releases released with defectDojo? I feel like they should be two different releases/pipelines since the helm release doesn't impact the code thinking

Not sure that I follow you, if you are raising concerns that the version of the helm chart is not strictly tied to a particular app version, then you are right. This is something I'm currently working on.

**Review by dsever — APPROVED** [review]
Approved

**Comment by MeNsaaH** [comment]
> > @dsever are helm releases released with defectDojo? I feel like they should be two different releases/pipelines since the helm release doesn't impact the code thinking
> 
> Not sure that I follow you, if you are raising concerns that the version of the helm chart is not strictly tied to a particular app version, then you are right. This is something I'm currently working on.

This is what I was trying to raise 🙂🙂

**Review by alles-klar — APPROVED** [review]

**Pull request merged**
