### PR TITLE
Refresh lock file on helm changes

### PR DESCRIPTION
**Pull request by dsever**
**Description**

When a contributor pushes any changes to the helm, it will detect and automatically refresh chart.lock file.

### CODE REVIEW

**Review by Maffooch — APPROVED** [review]
@alles-klar final approval up to you

**Comment by alles-klar** [comment]
For the history: We have three options:

1. check if the chart has been changed and update on PR to the dev lock file (have no idea how to do it)
2. As part of the test detect that the chart file has been changed but lock file hasn't
3. Completely drop lock file, so if a consumer wants to use helm from repo code directly needs to do helm dep update manually. 

I would prefer option 1 and integrate it in the current release workflow: https://github.com/DefectDojo/django-DefectDojo/blob/dev/.github/workflows/release-2-tag-docker-push.yml

The current implementation will run on every helm related pull request, which will result in many merge conflicts.

**Comment by dsever** [comment]
The idea is to have fresh lock file not in a release, in dev as well, in case we will track only charm.yaml then amount of conflicts will not be so significant.

**Comment by alles-klar** [comment]
Well, let's try.

**Review by alles-klar — APPROVED** [review]

**Pull request merged**
