### PR TITLE
Add an importer for kube-bench reports

### LINKED ISSUE #2907: Add an importer for kube-bench reports
kube-bench (https://github.com/aquasecurity/kube-bench) checks whether Kubernetes is deployed according to security best practices as defined in the CIS Kubernetes Benchmark.

Please assign this issue to me, I will provide the importer.

### PR DESCRIPTION
**Pull request by StefanFl**
Resolves #2907

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]
thanks!

**Review by devGregA — APPROVED** [review]

**Comment by StefanFl** [comment]
Is it ok, when I add the documentation for the kube-bench importer to the documentation pull request of the Checkov importer? Then I would avoid a merge conflict later.

**Comment by valentijnscholten** [comment]
Yes

**Comment by StefanFl** [comment]
Done

**Pull request merged**
