### PR TITLE
Add parser for Xanitizer's XML findings list report format

### PR DESCRIPTION
**Pull request by jankuehl**
[Xanitizer ](https://www.xanitizer.com) is a commercial SAST tool which scans Java and Scala code for security vulnerabilities, mainly via taint analysis (see last entry at [OWASP Source Code Analysis Tools](https://www.owasp.org/index.php/Source_Code_Analysis_Tools#Commercial_Tools_Of_This_Type)).
This PR adds a parser to import a Xanitizer generated findings list report in XML format into DefectDojo.

### CODE REVIEW

**Comment by dr3dd589** [comment]
hello, @jankuehl  great work!! thanks for the pr. Can you please submit sample files here also?? [sample-files](https://github.com/DefectDojo/sample-scan-files)

**Comment by jankuehl** [comment]
Hi @dr3dd589. We have prepared four files for the sample files repository. The first two files (with and without details) are an excerpt from the OWASP WebGoat project containing 12 findings which are also used in the unit tests (dojo/unittests/scans/xanitizer). The second two files (with and without details) are the XML findings list report for the OWASP Benchmark project containing nearly 2.000 findings. Therefore the XML file without details has a size of 2.7 MB and the the XML file with details has a size of 16.5 MB. Before committing these four files into the samples-files repository, I would like to ask if we should remove the report for the OWASP Benchmark from the commit?

**Comment by adracea** [comment]
@aaronweaver @devGregA

**Comment by devGregA** [comment]
Hi @jankuehl, those are acceptable file sizes to submit. We decouple sample scans from the actual code :) for that reason, great question!

**Comment by devGregA** [comment]
Oh! I'm sorry I didn't realize we were storing scans in the repo. I think the 2.7Mb one is fine. For the repo. This is something I should discuss with the other folks about splitting out.

**Comment by jankuehl** [comment]
Pull request for the example scan file to the sample-scan repository [has been created](https://github.com/DefectDojo/sample-scan-files/pull/43).

**Comment by jankuehl** [comment]
Pull request for adding Xanitizer to list of scanner parsers [has been created](https://github.com/DefectDojo/Documentation/pull/71).

**Comment by jankuehl** [comment]
Thanks @Maffooch. I have created a pull request for the requested changes to the [sample-scan](https://github.com/DefectDojo/sample-scan-files/pull/43) and [documentation repository](https://github.com/DefectDojo/Documentation/pull/71).

**Pull request merged**
