### PR TITLE
Dockerfile: don't upgrade pip

### PR DESCRIPTION
**Pull request by valentijnscholten**
as discussed (#3385)

### CODE REVIEW

**Review by madchap — APPROVED** [review]

**Comment by Maffooch** [comment]
I got this error trying to build
```
Step 5/26 : RUN pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt --use-deprecated=legacy-resolver
 ---> Running in 0c3431be35c6

Usage:   
  pip3 wheel [options] <requirement specifier> ...
  pip3 wheel [options] -r <requirements file> ...
  pip3 wheel [options] [-e] <vcs project url> ...
  pip3 wheel [options] [-e] <local project path> ...
  pip3 wheel [options] <archive url/path> ...

option --use-deprecated: invalid choice: 'legacy-resolver' (choose from )
ERROR: Service 'uwsgi' failed to build: The command '/bin/sh -c pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt --use-deprecated=legacy-resolver' returned a non-zero code: 2
```

**Comment by valentijnscholten** [comment]
Yeah, I was too fast. That command line option must be removed as well.

**Comment by madchap** [comment]
Fwiw, this is also that error I got that forced me to clear all local docker images to pull fresher python base image, that we were talking at the mods meeting.

**Review by Maffooch — APPROVED** [review]
Just finished a fresh build and it seems to be working just fine!

**Pull request merged**
