### PR TITLE
Remove Rules Framework and Google Sheets Integration

### PR DESCRIPTION
**Pull request by Maffooch**
Removing these features as they have been marked for removal for a long time
[sc-711]

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Review by blakeaowens — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Review by devGregA — APPROVED** [review]

**Comment by damiencarol** [comment]
Happy to see very old unmaintained feature be removed.

**Comment by marcnnn** [comment]
Hello,

I was researching Knowledge Base Security report Management for a University seminar.
And found this project.
I was interested in how helpful a rule base System can be.
Do I interpret this PR correctly that the Rule Framework is removed?
It is still prominently promoted on the Project website?

Thanks,
Marc

**Comment by Maffooch** [comment]
A rules based system would be incredibly helpful! However, the one that was implemented here was incredibly dangerous. There were practically no guard rails around the capabilities of the rules framework. It was initially hidden with deprecation methods, and then recently removed for users protection.

**Comment by mtesauro** [comment]
@marcnnn +1 to what Cody said.

The rules framework, while powerful, allowed direct access to DefectDojo's internal objects and, if you weren't very knowledgeable about DefectDojo's internals, it was quite easy to corrupt your database into an unusable state.

I honestly forgot it was listed on that website and we can remove the reference from the website. we missed that when we removed the code portion of the rules framework.

**Pull request merged**
