### PR TITLE
Add request/response pairs to finding APIv2 calls

### PR DESCRIPTION
**Pull request by Maffooch**
**Note: DefectDojo is now on Python3.5 and Django 2.2.x Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

Add BurpRawRequestResponse pairs to findings when collected from APIv2. Also included endpoints to retrieve pairs from a specific finding as well as adding new pairs to a specific finding. This addition requested by @mtesauro 

- [x] Your code is flake8 compliant 
- [x] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR 

Current accepted labels for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Useful, but my first though is... should there be a small test in the rest api test for this?

**Comment by Maffooch** [comment]
A test would be nice. Where are other rest api tests at? I have not seen them before.

**Comment by valentijnscholten** [comment]
One of them is https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/unittests/test_rest_framework.py

**Comment by Maffooch** [comment]
I've spent about 2 hours trying to get a working test but still coming up short. Payloads that work on the UI refuse to work on the unit tests. I don't get it.

**Comment by Maffooch** [comment]
Being a git noob again, nuking.

**Pull request closed without merging**
