### PR TITLE
Notifications: Split templates per type

### PR DESCRIPTION
**Pull request by kiblik**
This change should give more freedom in the customisation of notification engines (and implementation of a new one). Some notifications could be more customised only for some specific engine (in other engines, default template (other.tpl) will be used).

Note:
Command for the update of `django.po`: `./manage.py makemessages -l en --no-obsolete --extension html,txt,py,tpl`

### CODE REVIEW

**Comment by shipko** [comment]
@kiblik I think this part of defect dojo is require a localization support. Please add it

**Comment by kiblik** [comment]
I agree with adding localization. I can add it. But it was missing until now. Can we merge this PR and I will add localization in the next iteration?

**Comment by shipko** [comment]
Of course! But you PR was planned for 2.19 version. You have a 1 month for adding new commits :)

**Comment by kiblik** [comment]
@shipko, localization is ready. I would like to run `./manage.py makemessages ...` but I'm waiting for https://github.com/DefectDojo/django-DefectDojo/pull/7352

**Comment by shipko** [comment]
@kiblik nice job! 👍👍👍

**Comment by kiblik** [comment]
I suppose, we are ready for merge.

**Review by Maffooch — APPROVED** [review]
This is a very good step for organization. Great work @kiblik

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
