### PR TITLE
Fortify Parser Overhaul

### PR DESCRIPTION
**Pull request by Apipia**
# Changes
Fortify parser now contains the following information:
1. Abstract details (short definition)
2. Explanation (of finding)
3. Snippet
4. Source details (if available)
5. Mitigation with Recommendation and Tips (if available)

Fortify parser now also creates a single Finding from each issue in the XML (rather than trying to collect them all into buckets)

# Screenshots
findings_list
List of Findings

finding_details
Details of a finding

desc_explanation
Description containing an Explanation

mitigation
Mitigation information for a finding

# Testing
I used [this](https://github.com/JoyChou93/java-sec-code) code to create an FPR with Fortify, generated the XML and uploaded it for a total of 324 Findings. (334 were created, 10 were removed for deduplication, which I verified and am satisfied with). The XML is also added to the repo for unit tests, but I'll include it here:
[java-sec-code.txt](https://github.com/DefectDojo/django-DefectDojo/files/3975415/java-sec-code.txt)

# Notes
There are some details in the README located in the dojo/tools/fortify folder that provide information on how to generate an XML from an FPR with _all issues_. I have even included the XML for the ReportGenerator that one can use to with ReportGeneration to get all issues. Shout-out to @dougmorato for help with that.

### CODE REVIEW

**Comment by madchap** [comment]
Dumb question probably, are the changes proposed here backward compatible? If not, should they?

**Comment by Apipia** [comment]
> Dumb question probably, are the changes proposed here backward compatible? If not, should they?

Great question. Not they’re not _entirely_ backwards compatible. Since the original version creates one finding per “bucket” and (attempts to) put details of each individual instance (line no and file path) in the description. This change would make an individual finding for each issue. Which feels more like how defect dojo is intended to be used since each finding has a file path and line number. 

As far as “should it be backwards compatible”, Its not really possible. But I feel this is the most appropriate way to implement it. Definitely open to suggestions and feedback though.

**Comment by Maffooch** [comment]
This is a huge improvement. It doesn't seem like backwards compatibility would be an issue here since the format of the fortify scans hasn't changed. Looks like this is just reorganization of everything in a more useful manner. Is that correct @Apipia?

**Comment by Apipia** [comment]
> This is a huge improvement. It doesn't seem like backwards compatibility would be an issue here since the format of the fortify scans hasn't changed. Looks like this is just reorganization of everything in a more useful manner. Is that correct @Apipia?

Well if you had findings imported from fortify already, when this gets merged those will probably need to be deleted. If you had multiple files/line_no's of a vulnerability, say: "Password Management: Password in Configuration File Environment", the current fortify parser would create ONE finding called "Password Management: Password in Configuration File Environment" and place all line numbers, file paths, etc, into the description. (though it was slightly bugged).
Now it will create a separate finding for each file/line_no combination, each called: "Password Management: Password in Configuration File Environment - file.java: 23" with a file and line number.

So it's a grey area, but I believe it does a better job than the previous parser, especially given a concern I've seen already in bug #1657, as this WILL create a finding for each issue.

The question is simply this: Would we (the community) prefer a Finding be an individual issue (line number and file pair)? Or a type of vulnerability (Say SQLi) and the description contain all of the line numbers and file paths? Personally I prefer the former.

**Comment by Maffooch** [comment]
Gotcha. The former is definitely preferred in my opinion. This would also allow for deduplication here as well. Im onboard!

**Comment by devGregA** [comment]
This seems like an improvement. It won't effect previous findings dedupe just won't work on 'legacy' fortify findings. Happy to merge. @madchap @Maffooch anyone second?

**Comment by ashishf6** [comment]
@Apipia Can you provide me the command to generate report in xml format from fpr in fortify.

**Pull request merged**
