### PR TITLE
:sparkles: implement google cloud artifact scan

### PR DESCRIPTION
**Pull request by manuel-sommer**
see issue #8552

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Comment by cneill** [comment]
Reviewing [one of your other PRs](https://github.com/DefectDojo/django-DefectDojo/pull/9329/files), I remembered that we want to start putting more details in the parser documentation about how to generate findings files and where to find sample files. Could you add a blurb to that effect in the Markdown doc?

**Comment by cneill** [comment]
Great, thanks @manuel-sommer !

**Review by grendel513 — APPROVED** [review]

**Comment by anthonwellsjo** [comment]
Hi @manuel-sommer 👋🏻 

Do you mind providing the gcloud command/endpoint you used to get the json output that you provided [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/gcloud_artifact_scan/many_vulns.json)?

**Pull request merged**
