### PR TITLE
Automated reporting framework (sponsored by Panasonic) 

### PR DESCRIPTION
**Pull request by JamesCullum**
Hey everyone,

As with the previous PR, this development is sponsored by Panasonic Informations Systems Company Europe.

The idea of this framework is to allow automated reporting within DefectDojo. Reminding users about open findings, reminding owners about upcoming or done engagements etc are possible to automate with this update.

Documentation and tests have been created. 

Please notice that there are some commits that are duplicate with the outstanding ones from the other PR. This is done to prevent bugs that have been fixed already and to work with a consistent state.

- [X] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [X] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [X] Model changes should include the necessary migrations in the dojo/dd_migrations folder.
- [X] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by devGregA** [comment]
@JamesCullum looks like there are still some flake8 issues: https://travis-ci.org/DefectDojo/django-DefectDojo/builds/523367868?utm_source=github_status&utm_medium=notification

**Comment by JamesCullum** [comment]
Hey @devGregA, 

Because it's mostly minor, I didn't want to push again. Just pushed the fixes, but the `invalid escape sequence` is a bug within flake8 detection and I don't know of any good fix (apart from disabling this check).

**Comment by JamesCullum** [comment]
@aaronweaver Probably merge this into sec_automation as well?

**Comment by JamesCullum** [comment]
So whats the status on this? Can you elaborate on the closure - is it tracked somewhere else?

**Comment by aaronweaver** [comment]
When the branch was renamed for the move to Python3 the PR's were automatically closed. Feel free to resubmit.

**Pull request closed without merging**
