### PR TITLE
hotfix for nuclei to get it back working #9017

### PR DESCRIPTION
**Pull request by manuel-sommer**
see issue #9017

### CODE REVIEW

**Comment by manuel-sommer** [comment]
Please review @Maffooch, @madchap, @dsever, @blakeaowens 
Should be merged before the next release to get nuclei back on track.

**Comment by kiblik** [comment]
This kind of PR might go to `bugfix`, not `dev`. It would be released earlier.

**Comment by kiblik** [comment]
+ can you add test for this case?

**Comment by manuel-sommer** [comment]
@kiblik it fixes this: https://github.com/DefectDojo/django-DefectDojo/pull/8963 
So branch dev is fine here. 
How do I add tests for this case as unittests already passed?

**Comment by kiblik** [comment]
> @kiblik it fixes this: #8963 So branch dev is fine here. How do I add tests for this case as unittests already passed?

You are right about the branch. Sorry.

Regarding the test: How it is possible that unittest from #8963 passes the real live test not? What is different?

**Comment by manuel-sommer** [comment]
See at the linked issue. There, I described the missbehavior

**Comment by kiblik** [comment]
Ok, I see. I'm not sure, how to test it better.

**Comment by manuel-sommer** [comment]
Could you approve this fix @kiblik ?

**Comment by manuel-sommer** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/9026 --> Here a first unittest, but can be improved.

**Review by Maffooch — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Review by kiblik — APPROVED** [review]

**Comment by manuel-sommer** [comment]
@mtesauro and @grendel513 could you approve this?

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Comment by manuel-sommer** [comment]
please merge @grendel513

**Pull request merged**
