### PR TITLE
ORT security tool parser: add license path in finding description

### PR DESCRIPTION
**Pull request by devsecopsale**
This will add feature #4222

 - [x] A new value is added to the model in order to allow the finding path to be found: license id number.
 - [x] A new function is added in order to find the path of a license id number in a given findings list.
 - [x] A condition was added in order to capture the cases where findings are present and the path value is applicable (i.e. can be found in the file).

### CODE REVIEW

**Comment by damiencarol** [comment]
@devsecopsale could you add a check in one unit tests that test the description with the new data?

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
as per damiens request

**Comment by devsecopsale** [comment]
> @devsecopsale could you add a check in one unit tests that test the description with the new data?

Hi. sorry the late. I've been on leave. I'll try to take care of this next week.

**Comment by StefanFl** [comment]
@devsecopsale Are you still considering to add a check for the new functionality in the unit tests?

**Comment by Maffooch** [comment]
> Are you still considering to add a check for the new functionality in the unit tests?

@devsecopsale

**Comment by devsecopsale** [comment]
> > Are you still considering to add a check for the new functionality in the unit tests?
> 
> @devsecopsale

Hi, sorry, I'm not sure which kind of unit test I should add to it. Isn't the standard unit test for the parser enough to cover it?

**Comment by valentijnscholten** [comment]
> > > Are you still considering to add a check for the new functionality in the unit tests?
> > 
> > 
> > @devsecopsale
> 
> Hi, sorry, I'm not sure which kind of unit test I should add to it. Isn't the standard unit test for the parser enough to cover it?

nothing is checked yet at https://github.com/valentijnscholten/django-DefectDojo/blob/e515c0e4030efec056e0ab5536ffe7b6fcf715db/dojo/unittests/tools/test_ort_parser.py#L19, so ideally we add some checks for file path and other fields.

**Comment by damiencarol** [comment]
> @devsecopsale could you add a check in one unit tests that test the description with the new data?

@devsecopsale do you need help to complete this PR?
A simple thing could be to test if the license path is in the description. I can help on this one, you can contact me in Slack.

**Pull request closed without merging**
