### PR TITLE
Add support for JSON output of Clair scans

### PR DESCRIPTION
**Pull request by benno001**
Clair scans Docker images and can output findings in JSON. Added support for importing said findings.

### CODE REVIEW

**Comment by aaronweaver** [comment]
@benno001 thanks for adding the Clair importer, that's a fantastic addition.

**Comment by wurstbrot** [comment]
Hi @benno001,

which clair client are you using producing that format?

Cheers,
Timo

**Comment by benno001** [comment]
Hi @wurstbrot, 
I used arminc's clair-scanner (https://github.com/arminc/clair-scanner)

**Comment by wurstbrot** [comment]
@benno001 as there are a lot of clair clients, shouldn't we have a prefix like clair- and the actual name of the client,  e.g 
* clair-scanner
* clair-klar

For clair-scanner it could also be clair-clair-scanner. I am thinking of adding a clair-klar support.

**Comment by benno001** [comment]
@wurstbrot clair-clair-scanner is probably technically correct, but I'd prefer your suggestion clair-scanner for clearness. That, and I don't know other clients specifically called clair-scanner. What do you think?

**Comment by wurstbrot** [comment]
@benno001 yeah, I think so too.
I am writing a clair-klar scanner right now. Why have you choosen that "Unknown" is "Info"? I would assume the worst -> "Ciritical".

**Comment by benno001** [comment]
@wurstbrot  I haven't seen anything with severity 'Unknown' yet. Assuming the worst for an unknown severity is a good way to make yourself very unpopular in lots of environments, so I'd advise against that. 
On the other hand I agree info might be too lax, so maybe we should consider something more in the middle (medium/warning). Now that I'm reviewing my commit, I see we might also need to add translation from Defcon1 severity to critical (see also: https://github.com/coreos/clair/blob/e907e4d263a743f7d4923c177e5db37f656a53b4/database/severity.go#L68).

**Comment by wurstbrot** [comment]
> I haven't seen anything with severity 'Unknown' yet.
As you say it never showed up before, it is not such a big pain.

yes, we have to have a mapping for defcon1.

**Comment by benno001** [comment]
One critical with all the bells and whistles going off may be all it takes to lose credibility. Of course I don't know about your organizational context, we might need some more input on this one.

Created issue #861.

**Pull request merged**
