### PR TITLE
Newlines in SARIF parser code blocks

### PR DESCRIPTION
**Pull request by ahmsec**
**Description**

Bug: The SARIF parser doesn't add a newline after the triple backticks for Markdown code blocks. This breaks code blocks on platforms like Jira, since that line is used for language identifiers. See for example https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting. 

Fix: This PR simply adds newlines to the Markdown code block delimiters.

**Test results**
`./dc-unittest.sh --profile postgres-redis --test-case unittests.tools.test_sarif_parser.TestSarifParser` passes

**Documentation**

**Checklist**

This checklist is for your information.

- [ ] Make sure to rebase your PR against the very latest `dev`.
- [ ] Features/Changes should be submitted against the `dev`.
- [ ] Bugfixes should be submitted against the `bugfix` branch.
- [ ] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ ] Your code is flake8 compliant.
- [ ] Your code is python 3.11 compliant.
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

### CODE REVIEW

**Review by cneill — APPROVED** [review]

**Review by Maffooch — CHANGES_REQUESTED** [review]
Looks like the unit tests need to be updated as well

**Comment by ahmsec** [comment]
@Maffooch Whoops, I updated the unit tests. Could you approve running the workflow?

**Comment by mtesauro** [comment]
@ahmsec Tests have been re-kicked

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by hblankenship — APPROVED** [review]

**Comment by mtesauro** [comment]
@ahmsec This can be merged once the merge conflict is resolved.

**Pull request merged**
