### PR TITLE
Fix processing of test/eng fields during re-import

### PR DESCRIPTION
**Pull request by kiblik**

### CODE REVIEW

**Comment by Maffooch** [comment]
@kiblik I am not sure about this change. I have seen some use cases where an engagement is treated as a development branch, and each test corresponded to a feature branch. This is especially true in the cases of larger repos where product <-> repo relationships are not possible

**Comment by kiblik** [comment]
> @kiblik I am not sure about this change. I have seen some use cases where an engagement is treated as a development branch, and each test corresponded to a feature branch. This is especially true in the cases of larger repos where product <-> repo relationships are not possible

No problem. I understand your argument and it makes sense. If somebody would like to do this kind of update, he still can make another API call for an update of engagement fields.
I accidentally bumped into this implementation part when I was debugging something else.

But in that case, at least
- `test.engagement.version = version` should be removed - it doesn't make any sense under `if branch_tag:`
- `if branch_tag:` should be changed to `if commit_hash:`

**Comment by Maffooch** [comment]
Agreed on the last bit. Something screwy happened there at some point 🥴

**Review by kiblik — COMMENTED** [review]
Dump editing eng

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by blakeaowens — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Pull request merged**
