### PR TITLE
Skip false positives from detect-secrets report

### PR DESCRIPTION
**Pull request by pablosantiagolopez**
This Pull Request includes a fix in [detect-secrets](https://github.com/Yelp/detect-secrets) parser to skip the findings established as False Positive. For that, I check the value of the `is_secret` field:

- If the `is_secret` field is not present, the finding could be a real secret.
- If the `is_secret` field it's true, the finding it's a real secret.
- If the `is_secret` field it's false, the finding it's a false positive.

The reference to the `is_secret` field can be checked in this [link](https://github.com/Yelp/detect-secrets/blob/b206dc29f274839ebd3c522fed19448c9b8f3f70/detect_secrets/core/potential_secret.py#L40).

### CODE REVIEW

**Comment by valentijnscholten** [comment]
I wonder if these should be skipped, or imported as false positive?
Also, could you add/update the testcases to reflect the change?

**Comment by damiencarol** [comment]
@valentijnscholten I think it's better to import them as false positives.
We can have this use case:
1. first import with finding: is_secret is not here because the system detected it
2. second report with same finding but `is_secret` is `true` because it was tagged as false positive in the tool

Could be better for the logic to compare with the same findings.

**Review by damiencarol — CHANGES_REQUESTED** [review]
I think it's better to import them as false positives.
We can have this use case:

    first import with finding: is_secret is not here because the system detected it
    second report with same finding but is_secret is true because it was tagged as false positive in the tool

Could be better for the logic to compare with the same findings.

Could you modify your PR to use the attribute false_p instead of skipping the finding?

**Comment by pablosantiagolopez** [comment]
Solved! Thank you for your feedback @valentijnscholten @damiencarol

**Review by damiencarol — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
