### PR TITLE
Ruff: Add FIX001 and FIX003

### PR DESCRIPTION
**Pull request by manuel-sommer**
Ruff: Add FIX001 and FIX003

### CODE REVIEW

**Comment by kiblik** [comment]
Looks like #10212 was merged in parallel with other PRs that edited `settings.dist.py` but haven't adopted the checker yet.
Thank you for this.

**Comment by manuel-sommer** [comment]
@kiblik : I don't have enough insights into the release process, but maybe it makes sense to add automatic recalculation for the release process. 
Let's assume hash changes in both bugfix and dev branches. Then, then the new release should have new hash codes automatically recalculated and commited for all branches. Is this automatically possible somehow?

**Comment by kiblik** [comment]
> Looks like #10212 was merged in parallel with other PRs that edited `settings.dist.py` but haven't adopted the checker yet. Thank you for this.

😆 it was my other PR: #8824

**Comment by kiblik** [comment]
Thank you for this PR. I would prefer to go with #10241 because it fixes as well one other issue.

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
