### PR TITLE
restore pdf export button and update datatable to 1.0.21

### PR DESCRIPTION
**Pull request by valentijnscholten**
the latest update of datatables was missing the pdf plugin so the pdf export button was lost.
this pr updates datatable to 1.0.21 and now includes the pdf export plugin.

added later:
- export options were lost at some point during the last few months, this PR restores them which mainly means useless columns are excluded from the exports
- simplified the initialization logic as datatables now by default strips html for exports, so less custom export data extractors are needed.

### CODE REVIEW

**Comment by Maffooch** [comment]
I'm still not seeing a pdf button. Fresh build.
image

**Comment by valentijnscholten** [comment]
oh wow, indeed. It works on my machine, but turns out the `dojo/static` folder was on the `.gitignore` list for some reason? Corrected that now!

**Comment by Maffooch** [comment]
Still not appearing :/ Tried removing every single image to rule out older cached versions. Not sure what the deal is!

**Comment by JoseRoman** [comment]
Maybe a cross-browser compatibility issue?

**Pull request merged**
