### PR TITLE
Simplified MRO of API v2 view sets

### PR DESCRIPTION
**Pull request by efficiosoft**
These simplifications make it easier to see what methods are supported per endpoint by using djangorestframework's convenience types.

### CODE REVIEW

**Comment by efficiosoft** [comment]
Maybe one more thing before considering this PR: Is there a reason why types like ``Product``, ``ProductType``, ``StubFinding`` etc. don't support deletion via the API? If not, I'd make these regular CRUD endpoints.

**Comment by valentijnscholten** [comment]
I like this simplification. Deleting products via the UI presents the user with a clear overview of what is going to be deleted, maybe that's why it was considered too risky for the API? I am in favor of making it CRUD. ProductTypes currently cannot be deleted at all via the UI, a PR added that to dev branch recently.

**Comment by valentijnscholten** [comment]
@efficiosoft not sure if you've already seen the build results, but could you look at the failures?

**Comment by efficiosoft** [comment]
@valentijnscholten Thanks, spotted them this morning.

I'd also like to make them all CRUD. That deleting a product triggers a cascade of deletions should be clear, but I could add it to the API docs to be safe.

**Comment by efficiosoft** [comment]
Rebased and resolved conflicts.

**Comment by valentijnscholten** [comment]
Happy to approve but I guess we're still waiting for @aaronweaver to confirm if it's OK to make the others CRUD as well?

**Comment by aaronweaver** [comment]
@valentijnscholten yes let's make them all CRUD. (Just validate permissions on CRUD operations.)

**Comment by efficiosoft** [comment]
@mtesauro Why did you close this PR? It should be reopened.

**Comment by aaronweaver** [comment]
It can be re-opened. When the branch was renamed it auto closed PR's.

**Comment by efficiosoft** [comment]
I just rebased it onto dev. BTW, the PULL_REQUEST_TEMPLATE says that PR's should be based on a branch named python3_dev, which doesn't seem to exist...

**Pull request closed without merging**
