### PR TITLE
Fix date format on Fortify parser

### PR DESCRIPTION
**Pull request by Maffooch**
The date parser on the Fortify parser was not totally accurate because of the punctuation used within the report. The `dateutil` parser would receive an input like `Oct31,2020,` and it would record the date in dojo as October 21, 2021. Instead, the parser will get an input of `Oct.31.2020` and the date will be recorded on the finding correctly.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
any chance for a `self.assertEqual(bla bla)` in the unit test?

**Comment by damiencarol** [comment]
Could you provide a unit tests that show the bug ?

**Comment by Maffooch** [comment]
@damiencarol I don't understand what you're asking. Like have a test that shows it's the date is not being recorded correctly? That would involve not actually fixing anything.

**Review by madchap — APPROVED** [review]

**Comment by damiencarol** [comment]
@Maffooch sometimes it's usefull to create a unit tests in the first commits just to show the bug (like I made for this one #3585) before adding more commits to fix it.
But I saw you added unit tests so 👍

**Review by damiencarol — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
