### PR TITLE
Added GoAST Scanner Import support

### PR DESCRIPTION
**Pull request by raghunath24**
Added the support to import GoAST vulnerability scanner results into the defectdojo portal. 
More details about the scanner results can be found here. 
https://github.com/GoASTScanner/gas

### CODE REVIEW

**Comment by devGregA** [comment]
Hi @raghunath24! Thank you for your PR would you please resolve the merge conflicts and submit a sample scan to: https://github.com/DefectDojo/sample-scan-files so we can test your PR?

**Comment by raghunath24** [comment]
Thanks @devGregA. Fixed the merge conflicts and also raised a pull request of sample file.(https://github.com/DefectDojo/sample-scan-files/pull/1) please check.

**Comment by devGregA** [comment]
Merged. Congrats @raghunath24! Thank you for making DefectDojo better!

**Comment by raghunath24** [comment]
Thank you @devGregA

**Pull request merged**
