### PR TITLE
Add migrations to version control

### PR DESCRIPTION
**Pull request by maennel**
As described in issue #495, Django migrations are now tracked under version control. 
An official documentation of migrations can be found at https://docs.djangoproject.com/en/dev/topics/migrations/#version-control

In my opinion, tracking migrations can prevent issues to happen in future releases and ensure data consistency across new releases. 

This PR includes:
- an initial migration
- a technical way to ensure contributors have added migrations (tests will fail otherwise)
- an upgrading "How-To" guide
- several small bugfixes (mainly wrong settings imports discovered during testing of migrations)
- renamed settings.dist.py to settings_dist.py to make it importable in unittest-settings (adapted all retrieveable occurrences of it, as well)

---
When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [x] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by devGregA** [comment]
@maennel @aaronweaver did some more testing. One more thought. What if you're developing a feature that requires a migration, but ends up not being permanent i.e. I think I need a manytomany when it turns out I just need a foreign key. That extra DB change will be erroneously tracked, would it not?

**Comment by maennel** [comment]
@devGregA Yes, if the migration file makes it to a release, it will be applied on anyone's DB installing the "new" release. There's the possibility to revert (or change) this in a controlled manner with another, subsequent migration, transforming the M2M relationship to a ForeignKey in the example you've given. 

If there weren't any migrations, users would be faced with two conflicting models (assuming they don't keep track of their own migrations locally - which may be the case in a PaaS deployment or a distributed containerized environment). And they would have to figure out a resolution to the problem themselves - or file an issue here. 
As noted in #495, I believe issues #468 and #473 may be such cases.

**Comment by devGregA** [comment]
Hi @maennel still discussing. I definitely see where this could solve some issues, but I think it will very likely cause some issues as well. The Django community seems to be out on whether or not migrations should be tracked. When an application is internal and moves through dev -> staging -> production the case for including migrations is compelling. However, with plugins, extensions, modifications, and changes made to models in dev, We're still not sure. I will try to get @grendel513 's opinion as I think he is stronger in Django core knowledge than any of the current maintainers. However, he is also one of the most busy. Will get back to you as soon as I can.

**Comment by maennel** [comment]
Thanks @devGregA, I appreciate.

**Comment by imohammedzen** [comment]
I second @maennel's opinion, benefits outweigh the risks for migrations. The most important for my perspective is ability to test the change. 

For example, with API v2 I didn't have way to test if it will break something, if I had access to migrations, I would be able to see the breaking changes.

**Comment by devGregA** [comment]
All, closing for now. Regarding API V2, I believe the issue was due to poor travis tests. Having Migrations would not have affected the testing outcome as migrations only manage schema, not the actual data. A pre-populated previous version of Dojo in CI would have caught the issue.

**Pull request closed without merging**
