### PR TITLE
Add configurable disclaimer to notifications and reports

### PR DESCRIPTION
**Pull request by Maffooch**
Add a disclaimer to reports and notifications. This disclaimer is configurable through the system settings. There is an option to add it to all generated reports (HTML/AsciiDoc) while notifications will have the disclaimer if it exists in system settings.

System Settings Field:
image

### Notifications
Alerts:
image

Email:
image

MSTeams:
image

### Reports
Options:
image

Report:
image

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by valentijnscholten** [comment]
Do we want the disclaimer in the alerts inside defect dojo?
I would think it's not needed there and also not in Teams / Slack messages?

**Comment by Maffooch** [comment]
Could remove it from alerts, but not teams/slack. Think of contractors that would need to see that reminder from time to time.

**Review by devGregA — APPROVED** [review]

**Comment by Maffooch** [comment]
@valentijnscholten you good with this?

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
