### PR TITLE
Add support for GitLab Dependency Scanning reports

### LINKED ISSUE #3533: New importer - GitLab Dependency Scanner
**Scanner Name**
I would like to request a new importer for [GitLab Dependency Scanner](https://docs.gitlab.com/ee/user/application_security/dependency_scanning/) reports. This importer is a bit different from the current GitLab SAST importer available in DefectDojo. The generated reports from both scanners are slightly different

**Sample File**
The file format is JSON.
[gl-dependency-scanning-report-example-1.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/5734997/gl-dependency-scanning-report-example-1.json.txt)

### PR DESCRIPTION
**Pull request by macedogm**
Fix #3533.
Basically the GitLab Dependency Scanning reports are quite similar to the SAST reports, except for:
1. `vuln['category']` is `dependency_scanning`.
2. The analyzers used by GitLab don't provide the `scanner_confidence` property.

It seemed to make sense to create a new importer, despite the fact that the changes were only 2 compared to the current SAST importer. The changes might increase in the future.

Please let me know if this make sense or not. Best regards.

### CODE REVIEW

**Comment by macedogm** [comment]
Two notes:
1. I'm not really sure about the purpose and need of file `dojo/fixtures/test_type.json`.
2. If the PR is merged, we need to update the docs to reflect the new importer.

**Comment by valentijnscholten** [comment]
`test_type.json` is to populate the database table with the test types, this fixture is loaded by the initializer.
Can you rebase or merge `dev`, that will fix integration tests.

**Comment by macedogm** [comment]
Rebased and all checks passed 👍🏻 
Thanks for the help @valentijnscholten !

**Comment by madchap** [comment]
@macedogm there is a conflict that got introduced by a recent merge. Could you please rebase from dev and append your test_json stanza with the following pk number? (190 normally). Thanks!

**Comment by macedogm** [comment]
@madchap thanks for the note! PR rebased and conflict resolved.

**Review by damiencarol — APPROVED** [review]
LGTM 👍

**Review by madchap — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
