### PR TITLE
Centospostgresfix2

### PR DESCRIPTION
**Pull request by eik18**
Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by eik18** [comment]
related to https://github.com/DefectDojo/django-DefectDojo/issues/51

**Comment by eik18** [comment]
related to https://github.com/DefectDojo/django-DefectDojo/issues/516

**Comment by devGregA** [comment]
@ekelson-bcove sorry for the delay. @mtesauro could you review? This one is a little more in your wheelhouse than mine.

**Comment by mtesauro** [comment]
@devGregA I'm OK with this.  Merge away.

**Comment by devGregA** [comment]
@eik18, for some reason, when merged this broke dev. Very strange since the PR passed. Need to temporarily revert. Please see: https://travis-ci.org/DefectDojo/django-DefectDojo/builds/390581862?utm_source=github_status&utm_medium=notification

**Comment by eik18** [comment]
Saw that.  It looks like the initial SQL connection was fine (where it
created everything) but the subsequent connection failed.  Very odd

**Comment by devGregA** [comment]
@eik18 I think a dependency may have rev'd as the reversion also failed. Investigating.

**Pull request merged**
