### PR TITLE
chore(helm): implement readinessProbe and startupProbe for uwsgi container

### PR DESCRIPTION
**Pull request by fcecagno**
**Description**

This PR makes it configurable all probes on the uwsgi container, including the startupProbe, which could be useful to speed-up Django launch on Kubernetes.

### CODE REVIEW

**Comment by kiblik** [comment]
@fcecagno, can you try to rebase this PR? I suppose the issue responsible for failing the test might be gone.

**Comment by Maffooch** [comment]
It looks like there has not been any activity here for a while. In order to keep the list of pull requests in a manageable state, we are closing this one for now. If we are making a mistake here, please reopen the pull request, and leave us a note 😄

**Comment by fcecagno** [comment]
@Maffooch that's alright. Another option would be to merge it, since it looks like it's still an improvement.

**Comment by Maffooch** [comment]
Whenever you are ready, please convert the pull request from draft to open 😄

**Comment by fcecagno** [comment]
> Whenever you are ready, please convert the pull request from draft to open 😄

😱
Sorry about that, didn't see it was still a draft. It's definitely ready for review.

**Review by kiblik — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Pull request merged**
