### PR TITLE
Prepare for bugfix branch and release cadence

### PR DESCRIPTION
**Pull request by Maffooch**
As discussed in the moderators meeting, we would like to provide weekly bug fixes to users to prevent them having to wait a month for fixes. Please see the new branching model diagram in the diff

[sc-129]

### CODE REVIEW

**Comment by Maffooch** [comment]
@damiencarol @alles-klar @dsever 

Does everything look clear here? Am I missing anything?

**Review by devGregA — APPROVED** [review]

**Comment by mtesauro** [comment]
FWIW, I like this idea but wanted to give others a chance to chime in so held back on an actual 'approval'

**Review by coheigea — APPROVED** [review]
It will be a good change for the project, to avoid having to wait a month to pick up a fix.

**Comment by damiencarol** [comment]
Seems all good.

**Pull request merged**
