### PR TITLE
Implement support for SCA and KICS data in Checkmarx parser

### LINKED ISSUE #6956: Checkmarx JSON Report Not Parsing
From looking at the parser script for Checkmarx it can't successfully parse the latest JSON reports from Checkmarsx One. 

When adding the standard vulnerability report from Checkmarx One it has difficulty parsing which vulnerabilities to import. There's three scanning modules that we have access to; SAST, SCA and KICS. Currently the script seems to only support SAST. Can we get support for SCA and KICS as well? 

Within the report for SAST there is an error to retrieve these these results in `_get_findings_json` function. It cannot parse the report because the SAST field of the report is not specifically specified. 

Also within the SAST report the field for  `date` has changed from:
`"firstFoundDate": "2022-02-25T21:55:06Z"`
to:
`"firstFoundDate": { "seconds": 1651835167 }`

**Deployment method** *(select with an `X`)*
- [ X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: AWS Linux 2 
 - DefectDojo version: v. 2.14.3 
 
**Logs** 
Returns generic parser error

**Sample scan files**

**Screenshots**

**Additional context** (optional)

### PR DESCRIPTION
**Pull request by damiencarol**
**Description**

Implement support for SCA and KICS data in Checkmarx reports and update the parser to support more recent versions of Checkmarx.

**Test results**

Add a new recent report that shows the new data and generate bug in the old code.

**Documentation**

Updated doc to notify the data supported.

**Checklist**

This checklist is for your information.

- [x] Make sure to rebase your PR against the very latest `dev`.
- [x] Features/Changes should be submitted against the `dev`.
- [x] Bugfixes should be submitted against the `bugfix` branch.
- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.11 compliant.
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [x] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [x] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

**Extra information**

- a bug was encountered during the implementation of this PR: the `verified` flag was no well supported (wrong attribute)

- Fixes #6956 
- add new tags to make search easier:
image

### CODE REVIEW

**Comment by damiencarol** [comment]
@adamtimmins please take a look.

**Review by Maffooch — APPROVED** [review]

**Comment by mtesauro** [comment]
@damiencarol Leaving the 2nd approval to you since you had feedback earlier.

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by devcoisa** [comment]
Any reason why it wasn't merged on the main branch and released ? Has been one year that Damien featured this. 
We would like to deploy it on our DD implementation but we don't know how to do it.

**Comment by mtesauro** [comment]
@devcoisa The Dev branch is used to create a release every month. This one was merged after the Feb release (2.31.0) - monthly releases target the first Monday of the month. It will be part of the 2.32.0 release in March - target date 2024-03-04

**Pull request merged**
