### PR TITLE
implement hadolint

### PR DESCRIPTION
**Pull request by manuel-sommer**
Implement a github action for hadolint when you do a change in your PR in a dockerfile. 

https://github.com/jbergstroem/hadolint-gh-action/blob/main/USAGE.md

### CODE REVIEW

**Review by Maffooch — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Reminder, do we want to implement this @mtesauro and @Maffooch ?

**Comment by mtesauro** [comment]
@manuel-sommer I'd like to wait at least until after 2.38.0 so that we no longer have MySQL and RabbitMQ in play and the dockerfiles have been adjusted for those deprecations.

I'm trying to avoid double work if possible.

**Comment by manuel-sommer** [comment]
Reminder @mtesauro

**Comment by Maffooch** [comment]
Let's reopen this after the image hardening and simplification is completed

**Comment by manuel-sommer** [comment]
Hi @Maffooch ,
do we want to reopen this?

**Comment by manuel-sommer** [comment]
Hi @Maffooch ,
do we want to reopen this?

**Comment by manuel-sommer** [comment]
Hi @mtesauro , 
how about reopening this?

**Pull request closed without merging**
