### PR TITLE
Migrate to Django 4.x

### LINKED ISSUE #7385: Upgrade Django to 4.1.5
Upgrade to Django 4.1.5

Based upon this pip dependency graph, upgrading from Django 3.2 to 4.1 should not be too troublesome from a deep perspective

```
(env) django-DefectDojo $: pipdeptree | grep Django -B 1
django-auditlog==2.2.1
  - Django [required: >=3.2, installed: 3.2.16]
--
django-extensions==3.2.1
  - Django [required: >=3.2, installed: 3.2.16]
--
django-filter==21.1
  - Django [required: >=2.2, installed: 3.2.16]
--
django-polymorphic==3.1.0
  - Django [required: >=2.1, installed: 3.2.16]
--
django-slack==5.18.0
  - Django [required: >=3.2, installed: 3.2.16]
--
django-tagulous==1.3.3
  - Django [required: >=2.2, installed: 3.2.16]
--
  - defusedxml [required: >=0.4.1, installed: 0.7.1]
  - Django [required: >=2.2,<5, installed: 3.2.16]
--
drf-spectacular==0.25.1
  - Django [required: >=2.2, installed: 3.2.16]
```

### PR DESCRIPTION
**Pull request by Maffooch**
Fixes #7385 
Migration involved the following

- Replace `django.utils.http.urlquote` with `urllib.parse.quote` [django 3.x deprecations](https://docs.djangoproject.com/en/4.1/releases/3.0/#id3)
- Replace `django.utils.encoding.force_text` with `from django.utils.encoding.force_str` [django 3.x deprecations](https://docs.djangoproject.com/en/4.1/releases/3.0/#django-utils-encoding-force-text-and-smart-text)
- Forked [django-tagging](https://github.com/Fantomas42/django-tagging) as it needed Django 4 support. A PR was opened on 12/12/2021 to make the migration, but never received attention. We use this repository solely for migration 0066, and cannot remove the library. It is forked [here](https://github.com/DefectDojo/django-tagging) with the changes required to install
- Forked [django-multiselectfield](https://github.com/goinnn/django-multiselectfield) as it needed Django 4 support. Two PRs were opened (08/09/22022 and 12/01/2022), but neither received attention from someone who could merge. We use the library heavily, and alternatives are not readily available. It is forked [here](https://github.com/DefectDojo/django-multiselectfield) with the changes required to install and use.
- Migration is a mystery to me. It is being auto created, but does not appear to break anything

- [ ] https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/remote_user.py#L51 - I can check and test this part
- [x] https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L653

### CODE REVIEW

**Comment by kiblik** [comment]
Please add to TODO list:
- [ ] https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/remote_user.py#L51 - I can check and test this part
- [ ] https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L653

**Comment by Maffooch** [comment]
@kiblik I do not think anything needs to change on the `CSRF_TRUSTED_ORIGINS`. Let me know if you agree/disagree

**Comment by kiblik** [comment]
> @kiblik I do not think anything needs to change on the `CSRF_TRUSTED_ORIGINS`. Let me know if you agree/disagree

I check the note in the documentation and you are right. 
At least, that note in the file can be removed/updated.

**Comment by Maffooch** [comment]
Okay thanks for confirming. Removing

**Comment by kiblik** [comment]
@Maffooch https://github.com/Maffooch/django-DefectDojo/pull/5
Mentioned lines could be removed without any impact on functionality.

**Comment by Maffooch** [comment]
Thank @kiblik you rock

**Review by mtesauro — APPROVED** [review]
Approved.

Nice job handling the upgrade to 4.x - an before we were under the gun ;-)

**Review by devGregA — APPROVED** [review]

**Comment by damiencarol** [comment]
@kiblik awesome work. glad we made it.
we will need to work on removing github ref in the requirements.txt

**Pull request merged**
