### PR TITLE
Set flag for auto refresh of alert/counts

### PR DESCRIPTION
**Pull request by Maffooch**
Add the option to disable the notification recount through the `alerts/count` endpoint. Also add a manage.py command to remove alerts from the database with the options of removing the entire table, just system alerts, or alerts belonging to specific users. They tend to add up quickly with many users!

### CODE REVIEW

**Comment by valentijnscholten** [comment]
I thought about this as well, what is your reason to disable it? I get constant logging messages, but that could be resolved otherwise.

**Comment by Maffooch** [comment]
It ties up a thread. When multiple users are logged it once, the `alerts/count` endpoint is hit every 10 seconds for each user logged in. It adds up quickly.

**Comment by valentijnscholten** [comment]
maybe at some point we could look at websockets: https://medium.com/@ksarthak4ever/django-websockets-and-channels-85b7d5e59dda

**Comment by valentijnscholten** [comment]
I think it should be on by default though, especially when using JIRA any errors will occur there. if people start F5-ing all the time your server load might be even higher?

**Comment by Maffooch** [comment]
Oh darn. I intended to default to true but forgot to change it back after testing. Good catch.

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
