### PR TITLE
Add deduplication_level to engagement #757

### PR DESCRIPTION
**Pull request by wurstbrot**
Please see https://github.com/DefectDojo/Documentation/pull/12 for documentation.

As long as the other PRs which also change API-Upload are not merged, I wait. Afterwards I will create tests.

### CODE REVIEW

**Comment by aaronweaver** [comment]
@wurstbrot Would you mind changing the migrations as there are some that have customized migrations. In order to account for this a [new option](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/settings/settings.dist.py#L84) has been added to track migrations in a different folder.

**Comment by wurstbrot** [comment]
Is there an example where I can see how to add migrations in DefectDojo?

**Comment by wurstbrot** [comment]
@aaronweaver I guess the code is good to go now?

**Comment by aaronweaver** [comment]
@wurstbrot would you mind making the field deduplication_level a boolean? I chatted with @devGregA and once that's complete we'll merge this request up. Thanks for making DefectDojo better.

**Comment by wurstbrot** [comment]
done.

**Comment by aaronweaver** [comment]
Done thanks @wurstbrot

**Pull request merged**
