### PR TITLE
Dockerfile for integration tests

### PR DESCRIPTION
**Pull request by alles-klar**
A Dockerfile to simply run the integration tests.

On behalf of DB Systel GmbH

### CODE REVIEW

**Comment by valentijnscholten** [comment]
There are now 3 different names used in this PR: `integrationtest`, `integration_tests` and `integration-tests`. Might be small change to align them to being the same?

**Comment by madchap** [comment]
(I like underscores best :P)

**Comment by alles-klar** [comment]
> There are now 3 different names used in this PR: `integrationtest`, `integration_tests` and `integration-tests`. Might be small change to align them to being the same?

I just oriented at the unit tests and named them in the same way. Not sure what is the best way to go because different technologies use different names and have different requirements. We have the same Problem for "False" in Django and "false" in helm/kubernetes/bash.

Maybe we better discuss it in a separate Issue/PR/Meeting?

**Comment by valentijnscholten** [comment]
OK let's leave it then, it's not super imporant. Don't want to change existing things too much now.

**Pull request merged**
