### PR TITLE
fix npm audit JFrog Artifactory import bug

### PR DESCRIPTION
**Pull request by TheRealArlie**
We are using JFrog Artifactroy as NPM repository. Here we encountered problems while parsing the npm audit results in Defect Dojo. We could nail it down to the problem that Artifactroy seems to write `"cwe": null` in some advisories. We could fix the problem by adapting the code as seen in the PR. Please feel free to comment. We would love to see the fix being merged into the DoJo code.

### CODE REVIEW

**Review by Maffooch — CHANGES_REQUESTED** [review]
Please add a new unit test that can test a redacted report with cwe=null so that this bug can be tested for in the future

**Comment by TheRealArlie** [comment]
Sure, sry the project is so complex and huge. Could you please guide me to the file where I can add the test?

**Comment by TheRealArlie** [comment]
Never mind, I guess I found the right place. Please have a look at them and decide if this fits your needs.

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
