### PR TITLE
docs(helm): add documentation about installation and external databas…

### PR DESCRIPTION
**Pull request by leofvo**
Hello, 

After installing the helm chart and set up an external database connection, I feel like it's a bit tricky, and we could make it more straight forward with a little documentation. 

So I wrote the documentation from my own experience installing the helm chart and set up an external database.

Feel free to give feedback.

### CODE REVIEW

**Comment by kiblik** [comment]
It might be better to place it into https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/KUBERNETES.md (it is the place described in the official documentation: https://documentation.defectdojo.com/getting_started/installation/#kubernetes)

`README.md` might point to this document as well.

**Comment by kiblik** [comment]
PR should point to `dev` or `bugfix` branch (as described in https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md#submitting-pull-requests)

**Comment by mtesauro** [comment]
@LeoFVO kiblik is correct here - we only take PRs against the dev or bugfix branches. This seems like a dev branch type of PR IMHO.

**Comment by LeoFVO** [comment]
> PR should point to `dev` or `bugfix` branch (as described in https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md#submitting-pull-requests)

I edited to target branch as `dev`

**Comment by LeoFVO** [comment]
hey, I just merged the readme in the docs, and created a symlink to explicit the documentation location.
I did a proposal in the second commit to update the external postgresl docs as it was not really impllemented for cluster external ressources.

**Review by kiblik — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by hblankenship — APPROVED** [review]

**Pull request merged**
