### PR TITLE
[Helm] Fix typo in  ingress netpol

### PR DESCRIPTION
**Pull request by C4tWithShell**

### CODE REVIEW

**Review by cneill — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Comment by kiblik** [comment]
Hi. Is it possible to merge this in to `bugfix`, please?

**Comment by C4tWithShell** [comment]
> Hi. Is it possible to merge this into `bugfix`, please? I know it will need rebase but it would be nice to have it available.

Sure, but I will create new PR. Will send a link here

**Comment by C4tWithShell** [comment]
@kiblik @cneill @Maffooch @mtesauro 
New PR to bugfix - https://github.com/DefectDojo/django-DefectDojo/pull/10898

**Pull request closed without merging**
