### PR TITLE
update result template in nuclei parser

### PR DESCRIPTION
**Pull request by fadhilthomas**
These updates related to breaking changes on nuclei
https://github.com/projectdiscovery/nuclei/releases/tag/v2.5.3

### CODE REVIEW

**Comment by valentijnscholten** [comment]
There's already a PR in progress: https://github.com/DefectDojo/django-DefectDojo/pull/5664, but that seems to have stalled.
Are you able to update your PR to:
- support both old and new version of nuclei
- have unit tests for both versions

**Comment by tequreq** [comment]
yes please upgrade parser because parser is not working.  @valentijnscholten

**Comment by damiencarol** [comment]
@fadhilthomas could you add data for the new version and add unit tests?

**Comment by fadhilthomas** [comment]
@damiencarol sure, will add the unit test.

**Comment by damiencarol** [comment]
Last time was #5689 but it could be something as simple as checking first `template-id` and fall back to `templateID` if the first one is not here. (same logic for "matched at" change)
Also some parser check the version in the meta data of the report. There is no automatic way to do it. Just keep it simple.

**Comment by StefanFl** [comment]
superseded by #6103

**Pull request closed without merging**
