### PR TITLE
Fix dojo version

### PR DESCRIPTION
**Pull request by madchap**
That appears in footer

This template is for your information. Please clear everything when submitting your pull request.

**Note: DefectDojo is now on Python3.5 and Django 2.2.x Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant.
- [x] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
I think it should only become 1.6.0 when merging into master. I think current status should be
master: 1.5.4
release/1.6.0: 1.6.0-rc (or .rc or RC or something)
dev: 1.7.0-dev (as dev will become 1.7.0 if I understand correctly)

**Comment by madchap** [comment]
OK, so I don't like your proposal :-P 

What would eventually be a more painless alternative yet agnostic enough, to the way the version is currently retrieved?

**Comment by valentijnscholten** [comment]
I am open to be convinced, but why would it make sense to have dev branch the same version number as master and rc branch?

**Comment by alles-klar** [comment]
For me the dev branch is for developing the next version, so at the moment we could use 1.7.0 there. The master is the latest version - at the moment 1.5.x and the current release branch has version 1.6.0. 

Otherwise we need to automate this process because we have to update the version very often.

**Comment by valentijnscholten** [comment]
I think we should stick what everybody else is doing and not invent something different. a dev branch is not a version or anything, so it should just be called dev or something like 1.7.0-dev to make clear it's a dev version and not a stable pinpointed version number. Same for RC it should be 1.6.0-rc in this case. Master should be 1.5.4 and when we release it should become 1.6.0. And then when a hotfix branch is there it should be 1.6.1-hotfix and master becomes 1.6.1 when released.
Changing the version number is the least of our problems and one of the reasons the person doing the releases should have write access to all branches.

**Comment by alles-klar** [comment]
For me it isn't super important how we do it, but we need a concept and should document it. The version from @valentijnscholten is also great for me.

**Comment by madchap** [comment]
OK, this is fine. I modified the file. We will need a way to "think" about it, or not.

**Pull request merged**
