### PR TITLE
Intsights fix for zero alerts

### PR DESCRIPTION
**Pull request by 37b**
**Description**

The IntSights parser was throwing an error when the number of alerts in the uploaded file was zero. This prevented the closing of open findings when the number of findings drops below 1.

**Test results**

No changes. 

**Documentation**

Please update any documentation when needed in the [documentation folder](https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs))

**Checklist**

This checklist is for your information.

- [✔️] Make sure to rebase your PR against the very latest `dev`.
- [ ] Features/Changes should be submitted against the `dev`.
- [✔️] Bugfixes should be submitted against the `bugfix` branch.
- [✔️] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [✔️] Your code is flake8 compliant.
- [✔️] Your code is python 3.11 compliant.
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

**Extra information**

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]
This is a good patch.

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by damiencarol** [comment]
@37b it reminds me that we should check **all** parsers to see if we have the same pattern and remove it.

**Comment by 37b** [comment]
> @37b it reminds me that we should check **all** parsers to see if we have the same pattern and remove it.

I can take a stab at that

**Pull request merged**
