### PR TITLE
Typo fix for Crital => Critical

### PR DESCRIPTION
**Pull request by SPoint42**
Typo fix for Crital => Critical

### CODE REVIEW

**Comment by SPoint42** [comment]
@madchap  : is it ok or should I create a spécific migration file for this ?

**Comment by valentijnscholten** [comment]
it will be OK if you also update `models.py`. the migrations and models.py need to be in sync.

**Review by valentijnscholten — APPROVED** [review]

**Comment by valentijnscholten** [comment]
@SPoint42 can you revert that last commit containing gitleaks stuff?

**Review by damiencarol — CHANGES_REQUESTED** [review]
Some stuff around gitleak parser needs to be removed

**Comment by valentijnscholten** [comment]
@SPoint42 You need to make sure that for every feature / change you create a new branch in your repositories. And then create 1 PR per 1 branch. It looks like you are now doing multiple things on your dev branch.

**Comment by SPoint42** [comment]
Yes, I hav'nt synchro between multiple notebook. will close this and start from a fresh new from dev

**Pull request closed without merging**
