### PR TITLE
Add a tag for each vulnerability

### PR DESCRIPTION
**Pull request by shubhindia**
This adds a tag for each Trivy vulnerability which is present in the report json.
Which makes it easy to filter the vulnerabilities according to their `Type`
e.g. `python-pkg, node-pkg, debian`

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Please base your PR against `dev`

**Comment by shubhindia** [comment]
@valentijnscholten done

**Comment by Maffooch** [comment]
@shubhindia you've got one extra file in your changes log

**Comment by shubhindia** [comment]
Closing this as it is no longer a general use-case. We have made the changes to our specific use and this doesn't seem relevant enough for general use.

**Pull request closed without merging**
