### PR TITLE
Bulk edit rework

### PR DESCRIPTION
**Pull request by Sh1nZ0u**
**Description**

A little changes to bulk edit front logic:
- remove "disable" mechanic
- add "under review" field
- a little fix of status auto-select logic

### CODE REVIEW

**Comment by Maffooch** [comment]
Looks good to me. Adding a gif for other mods to see


https://user-images.githubusercontent.com/46459665/233744661-6acf3d57-0ccf-412c-aced-19d1f241708c.mov

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by shipko** [comment]
Hi! Why this PR is not merging? Maybe someone have a questions?

**Review by devGregA — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Comment by mtesauro** [comment]
@shipko 
> Hi! Why this PR is not merging? Maybe someone have a questions?

Github was failing the merge conflict test generally for the last day or so. Seems like it cleared up today.

**Pull request merged**
