### PR TITLE
add delete option in product-type.

### PR DESCRIPTION
**Pull request by dr3dd589**
add an option to delete product type and beautify the code of product_type/views.py according to flake8.

Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is flake8 compliant (Dojo's code isn't currently flake8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by devGregA** [comment]
Need to go through this one more throughly will come back to it.

**Comment by dr3dd589** [comment]
hello, @devGregA Can you review this one. please? :smiley:

**Comment by devGregA** [comment]
CI tests are failing https://travis-ci.org/DefectDojo/django-DefectDojo/builds/499149082?utm_source=github_status&utm_medium=notification

**Comment by devGregA** [comment]
Oh okay, I remember this one now. Lot going on here. Don't worry about CI right now. Will get back to you.

**Comment by dr3dd589** [comment]
yeah sorry for that. Its old one and that time I don't know how Travis-CI works. And I have deleted old forked repo so I can't change anything in this PR. One thing I can do close this PR and submit a new one. So is this ok or I should submit a new one?

**Comment by dr3dd589** [comment]
Going to close this one. and submit a new PR with CI tests pass.

**Pull request closed without merging**
