### PR TITLE
Upgrade Django to 4.2.13

### PR DESCRIPTION
**Pull request by kiblik**
Upgrade to Django 5.x https://github.com/DefectDojo/django-DefectDojo/pull/9258 might be quite complated but we need to go to at least 4.2.13 because 4.1.x is not supported anymore (check https://www.djangoproject.com/download/)

Needs to be checked/considered:
- [ ] https://docs.djangoproject.com/en/4.2/howto/upgrade-version/#deployment
- [ ] https://docs.djangoproject.com/en/5.0/releases/4.2/
       - Might be handy: _[CharField.max_length](https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.CharField.max_length) is no longer required to be set on PostgreSQL, which supports unlimited VARCHAR columns._
       - We might need to change some lines for `makemigrations`: _The [makemigrations --check](https://docs.djangoproject.com/en/5.0/ref/django-admin/#cmdoption-makemigrations-check) option no longer creates missing migration files._

### CODE REVIEW

**Comment by Maffooch** [comment]
I think the best approach here is to remove tests for MySQL by removing the following [entry from the integration tests](https://github.com/DefectDojo/django-DefectDojo/blob/738dca4534382049ca7587a60fb6b33715213943/.github/workflows/integration-tests.yml#L39C19-L39C35) and then [replace all the mysql references with Postgres](https://github.com/DefectDojo/django-DefectDojo/blob/738dca4534382049ca7587a60fb6b33715213943/.github/workflows/rest-framework-tests.yml#L35C1-L51C104)

**Comment by kiblik** [comment]
@Maffooch, noticed that you implemented https://github.com/DefectDojo/django-DefectDojo/pull/5899.
Now `errors.append(ValidationError('Query "{}" has invalid format - It contains the NULL character. The following action was taken: {}'.format(old_value, action_string)))` breaks test.
If correction (`query.replace(remove_str, '%00')`) was performed, is it still necessary to raise `ValidationError`?
I'm considering change it to `logger.error`.

**Comment by kiblik** [comment]
Help needed

I'm facing unusual behavior. Based on unittests, in `test_rest_framework.py` I adjusted results for `deleted_objects`. For `Language_Type` from `2` to `1` and for `TestType` from `18` to `5`.
At first, this kind of adjustment should not be done (if there is no change in the data of the algorithm). But I wanted to see the results.

Now, the complicated part:
- Why it happen?
- Why unittests for `Alpine` pass but for `Debian` fail (with a request to roll back from `5` to `18` for `TestsTest` and not mentioning `Language_Type`)

**Comment by Maffooch** [comment]
@kiblik this is a very strange error, and I do not understand why it is happening. I am hoping to get some time in the near future to pull this PR down and play around with it

**Comment by kiblik** [comment]
@Maffooch, it looks like the mentioned issue is not connected to the upgrade to Django 4.2 but to migration tests from MySQL to Postgres
This fails in the same way https://github.com/DefectDojo/django-DefectDojo/pull/9885

**Review by Maffooch — APPROVED** [review]

**Comment by kiblik** [comment]
I'm happy that we are ready, just be careful with timing:
> **Dropped support for MySQL 5.7**
> Upstream support for MySQL 5.7 ends in October 2023. Django 4.2 supports MySQL 8 and higher.
> Source: https://docs.djangoproject.com/en/5.0/releases/4.2/#dropped-support-for-mysql-5-7

Docker-compose.yml uses `mysql:5.7.44` right now.

**Comment by Maffooch** [comment]
@kiblik I am glad you mentioned this in this PR :) this is a good opportunity to link to the discussion where this change is announced by @mtesauro 

https://github.com/DefectDojo/django-DefectDojo/discussions/9690

**Comment by cneill** [comment]
Since our version of MySQL isn't supported by the version of Django we're moving to and it's our intention to deprecate MySQL with the next release, should we go ahead and remove it entirely as part of this PR?

**Comment by mtesauro** [comment]
> Since our version of MySQL isn't supported by the version of Django we're moving to and it's our intention to deprecate MySQL with the next release, should we go ahead and remove it entirely as part of this PR?

I'd prefer to keep this PR only about the Django update and have a separate PR to remove MySQL from the various places.
This PR is complicated enough without adding to it's scope.

FWIW, I'll be working on a PR to remove MySQL & RabbitMQ from the compose files over the weekend.

**Review by cneill — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
