### PR TITLE
Remove date feature in Fortify parser

### LINKED ISSUE #6260: Import of XML report of fortify 20.1.1 failed
Scan the code with fortify version 20.1.1 and generate the XML report with the following command (provided that the FPR file has been successfully generated):

./path/to/ReportGenerator -format xml -f /path/to/output. xml -source /path/to/downloaded/artifact. fpr -template DefaultReportDefinitionAllIssues. xml

The generated XML file is uploaded through the defectdojo page,

Click: all product - > select a product - > engagements - > View engagements - > select the specified engagement - > type I to open the upload interface and fill in the parameters:

Minimum severity:Low

Scan type:Fortify Scan

Environment:Default

Choose report file: select the file to upload

The final filled interface is shown in the following screenshot:

image

Click Import to display:

An exception error occurred during the report import:Unknown string format: 2022-5-6. a.source

The following screenshot:
image

By analyzing the source code of defectdojo and the unit test file of fortify, it is found that there is an error in the date parsing of the text tag in the XML file of fortify. The date format generated by the fortify version I use is 2022-5-6, Screenshot:

image

The format of defectdojo parsing is Dec 17, 2019, screenshot:

0880c4c80710f1b09d02

Therefore, there is an error in parsing. The parsing can be successfully uploaded by modifying the format

### PR DESCRIPTION
**Pull request by damiencarol**
Date in the report are not reliable. Better to remove this part to make the parser more robust.

Added also more checks in the unit tests.

Fixes #6260

### CODE REVIEW

**Review by StefanFl — COMMENTED** [review]
@damiencarol I am not comfortable with this new test file. There is a lot of Chinese text in it and we can't be sure it doesn't contain confidential information. The existing test cases are good enought to make sure the date from the scan report is not used anymore.

**Comment by Maffooch** [comment]
Agreed with @StefanFl

**Comment by damiencarol** [comment]
1) The data were provided by a user in an issue , so the data are already public.
2) The Chinese texts are common description of vulnerabilities, like explaining what a SQL injection is etc.
This is because Fortify was configured in Chinese. It's not linked to the data analyzed (mostly examples generated by Fortify) .
3) the part that is specific to the project scanned is limited. (Few folder/file names, few methods, few snippets, that's it)
We can obfuscate the file if you want. But it's always better to have real data for unit tests.
It's a small report (16 findings)

**Comment by StefanFl** [comment]
ok

**Review by StefanFl — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
