### PR TITLE
Docker-compose: use variables for depends_on

### PR DESCRIPTION
**Pull request by kiblik**
Fix https://github.com/DefectDojo/django-DefectDojo/issues/8303

### CODE REVIEW

**Comment by mtesauro** [comment]
@kiblik Just merged Celery 5.3.4 which reverts breaking changes in 5.3.2 and 5.3.3

Can you please rebase?  Thanks!

**Review by mtesauro — APPROVED** [review]
Approved

**Review by blakeaowens — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Comment by kiblik** [comment]
I thought that this would be merged before releasing `2.26.0`. This issue is blocking multiple users which use `docker-compose`. I will rebase it to propose PR against `bugfix` to speed up the release of this feature.

**Comment by mtesauro** [comment]
I guess the other approvers are busy - let me poke them.

I do agree with the bugfix branch. :+1:

**Review by grendel513 — APPROVED** [review]

**Comment by testaccount90009** [comment]
This introduced the following linked error:
https://owasp.slack.com/archives/C2P5BA8MN/p1695063859155169

Please review.

**Comment by testaccount90009** [comment]
Thanks to @kiblik for https://github.com/DefectDojo/django-DefectDojo/pull/8683/files -- seems to have fixed the issue.

**Pull request merged**
