### PR TITLE
remove aws scout2 parser 

### PR DESCRIPTION
**Pull request by manuel-sommer**
As we don't have a clear timeline for 3.X.X, we could remove awsscout2 parser earlier as the notification to merge to Scout2 was first published in January 2023.

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@Maffooch, this is a followup

**Comment by manuel-sommer** [comment]
I will not fix Ruff Linter here as this is already covered here: https://github.com/DefectDojo/django-DefectDojo/pull/9903

**Comment by mtesauro** [comment]
@manuel-sommer That just got merged so hopefully it's no longer an issue for PRs :crossed_fingers:

**Comment by manuel-sommer** [comment]
Thank you for the hint @mtesauro . Rebasing is done.

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by cneill** [comment]
We can probably remove it [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L219-L220) as well if we're removing the parser entirely. It looks like `PARSER_EXCLUDE` should work as expected even if its value is empty ([ref](https://github.com/DefectDojo/django-DefectDojo/blob/83fae48bf00d4f1299d4c1cacba23bffb2b57781/dojo/tools/factory.py#L36-L42)).

**Comment by manuel-sommer** [comment]
Done @cneill, thank you for the hint.

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Review by hblankenship — APPROVED** [review]

**Comment by mtesauro** [comment]
@manuel-sommer This is ready to merge once the merge conflicts are fixed.

**Comment by manuel-sommer** [comment]
Ready to get merged @mtesauro

**Pull request merged**
