### PR TITLE
SARIF: support date of findings

### PR DESCRIPTION
**Pull request by damiencarol**
## Work
- [x] support date of findings form the report
ex: https://github.com/DefectDojo/django-DefectDojo/blob/ec47390ef2f8893b2a35c2bf8cbf4dd36584b5fe/dojo/unittests/scans/sarif/appendix_k.sarif#L150
- [x] add more tests (output of a new tool njsscan https://github.com/ajinabraham/njsscan which showed some bugs)

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Is the past around PASSED, lastobservedat and mitigated findings no longer needed? It looks like it was copied from another parser (aws?)

**Review by madchap — APPROVED** [review]

**Comment by damiencarol** [comment]
@valentijnscholten yes you're right. bad code. didn't saw that because everything was good in UI and unit tests

**Comment by valentijnscholten** [comment]
> @valentijnscholten yes you're right. bad code. didn't saw that because everything was good in UI and unit tests

so it is correct that it is removed? or should it be put back?

**Comment by damiencarol** [comment]
It's useless code. there is no mitigation in SARIF format. I tested 6 different sources. So we need to remove it.

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
