### PR TITLE
Dependabot config - target_branch

### PR DESCRIPTION
**Pull request by madchap**
Addresses #1678 

Dependabot should issue PR against `dev` and not `master`.

This config would normally work for python and yarn dependencies.

### CODE REVIEW

**Comment by alles-klar** [comment]
Can we also use dependabot to update the dockerfiles?

**Comment by madchap** [comment]
@alles-klar we can, yet this would go against the recent decision to pin the version of the parent image with sha256 hashes.

**Comment by alles-klar** [comment]
I think we pinned the version because we do not want to use a new version without testing or even know  it. But with dependabot we get a PR and can test the new version bevor merging. At least for security reasons we should periodically update the docker container.

**Comment by Maffooch** [comment]
I like the idea of using Dependabot for Dockerfiles too. As with pip packages, somebody will check out the release notes and do a test drive to ensure it won't wreck the project. Packages we are intentionally keeping a bit dated, like python, can simply be declined for updates. I didn't see anything about Dependabot supporting Debian packages though.

**Comment by madchap** [comment]
Alright then. Full disclosure, I have never used it for docker.

**Comment by madchap** [comment]
We will need to change the Dockerfile to use regular tags again then to remove the sha256.

**Comment by madchap** [comment]
Getting some tests done on my fork, I guess it's working good enough. docker OK, npm seems ok, python django not showing up, wondering why actually :thinking: 

image

**Comment by madchap** [comment]
Also, note this change would have to be pushed to the default branch to take effect, which I am assuming to be `master` here.

**Comment by ptrovatelli** [comment]
Hi guys, 
Regarding the version pinning in dockerfile with sha256: I put that in place because this was the advised way to have a reproducible build at a time where build failed due to an evolution in a docker image. found on an article edited by the renovate bot team. 
i have discussed this on the PR at the time. I wanted to add "renovate bot" who is able to automatically create PR to update those version but i think only the project owner can add renovate bot. 
I didn't notice at the time that we already have a bot that updates versions. I don't know if dependabot is able to update dockerfile version, i haven't see any PR from his doing that. 

this article explains why it's a good idea to pin dockerfile using sha256, due to the mu mutable nature of docker images: https://renovatebot.com/blog/docker-mutable-tags

more documentation: 
https://github.com/marketplace/renovate
https://renovatebot.com/docs/

I have started testing that bot and it seemed fine. i can do more test and tune up the configuration to help it's integration if dependabot isn't able to handle dockerfile dependencies

**Comment by madchap** [comment]
Well, actually dependabot handles the sha256 just fine, so no need to change anything if we want to do that, updates will happen. See https://github.com/madchap/django-DefectDojo/pull/11 for an example.

The other deps updates came in just a bit afterwards. I believe we can move forward there. You can look at PRs done on my fork for full examples.

**Comment by ptrovatelli** [comment]
great! so it's just a bit of configuration on dependapot files? 
regarding this python dependency though, there was another discussion :) as stated in the comments in dockerfile.django, we left it at 3.5.7 on purpose in order not to break infrastructures that wouldn't support python 3.6 and 3.7. 
However what we can do is upgrade to the latest 3.5.x hash. do you know if dependabot support this? 

also we need to be careful with the yarn dependencies; we have given a quick look at https://github.com/DefectDojo/django-DefectDojo/issues/1605 and when trying to update yarn dependencies it seemed to break the gui. hopefully selenium will pick that kind of issue but i'm not sure.

**Comment by madchap** [comment]
> great! so it's just a bit of configuration on dependapot files?
> regarding this python dependency though, there was another discussion :) as stated in the comments in dockerfile.django, we left it at 3.5.7 on purpose in order not to break infrastructures that wouldn't support python 3.6 and 3.7.
> However what we can do is upgrade to the latest 3.5.x hash. do you know if dependabot support this?

Yes. We can tell it to ignore with a comment, and it will not bother us again unless we tell it to.

> also we need to be careful with the yarn dependencies; we have given a quick look at #1605 and when trying to update yarn dependencies it seemed to break the gui. hopefully selenium will pick that kind of issue but i'm not sure.

Indeed. We will have to do due diligence and not blindly accept all its PRs :)

**Comment by madchap** [comment]
So, we want to try? Need one more approval.

**Comment by madchap** [comment]
> @madchap Why do you choose update_schedule: weekly for docker and live for the other?

I guess just what I see in most files I look at.

**Pull request merged**
