### PR TITLE
fix drheader parser #8281

### PR DESCRIPTION
**Pull request by manuel-sommer**
fix drheader parser #8281

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@madchap could you retrigger the pipeline? 
The PR is ready to review.

**Comment by kiblik** [comment]
I'm not sure, this is way, how "empty reports" should be processed.
I suppose, it should be handled this way
```python
        try:
            data = json.load(filename)
        except ValueError as err:
            data = {}
```

**Comment by manuel-sommer** [comment]
Your opinions @mtesauro or @Maffooch ?

**Comment by damiencarol** [comment]
@manuel-sommer : Not sure the pb is from dojo side. DrHeader should not produce empty files. Empty files are not valid JSON files.

**Comment by manuel-sommer** [comment]
@damiencarol: I use drheader the following:
`drheader scan single targetasdf.de > output.json 
`
If the target is not available at the time of scanning, output.json is empty. I will look at the recommended way to use jq.

**Comment by Maffooch** [comment]
Creating a finding in the case of an empty file is not good here. Adding the try catch in case of an empty file to report 0 findings for the sake of not throwing 500s in a pipeline is a good compromise as @kiblik suggested

**Comment by manuel-sommer** [comment]
@Maffooch could you review?

**Review by Maffooch — APPROVED** [review]

**Comment by manuel-sommer** [comment]
@grendel513 could you review this PR?

**Comment by manuel-sommer** [comment]
@mtesauro could you review this PR?

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Comment by damiencarol** [comment]
I maintain that we should push upstream, the current version is not good:
```
try:
            data = json.load(filename)
        except ValueError as err:
            data = {}
```
If the command line generate an error or anything, the report will be invalid JSON and dojo will close all findings in the scenario of re-import (because 0 findings as output).

**Pull request merged**
