### PR TITLE
Set finding is_Mitigated on finding update

### LINKED ISSUE #3026: Un-marking findings active shows them as "Mitigated", but do not set "is_Mitigated"
**Bug description**
When one unmarks an Active finding, it goes to "Inactive, Mitigated". 
However, the `is_Mitigated` is not set to `True`.

However, in bulk edit for example, marking findings as "Mitigated" is possible and sets that field.

This results in discrepancies.

### PR DESCRIPTION
**Pull request by madchap**
fix #3026

This template is for your information. Please clear everything when submitting your pull request.

**Note: DefectDojo is now on Python3.6 and Django 2.2.x.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by madchap** [comment]
For some reasons, I think I may be missing something obvious. Definitely works for my use-case through the UI, have to look elsewhere too. @valentijnscholten ?

**Comment by valentijnscholten** [comment]
Bulk edit and API come to mind

**Comment by madchap** [comment]
> Bulk edit and API come to mind

They seem work well when testing.

**Comment by valentijnscholten** [comment]
When searching for `.active = False` I see lots of results and I think 40% of them do not set `is_Mitigated`.
image

**Comment by madchap** [comment]
I think this one already fixes a couple issues known so far. I'd be in favor of merging, and see if we experience any more side effects of it not getting set?

**Comment by valentijnscholten** [comment]
I don't remember all the details from the status discssion some months ago. But if "not active" always means "is_Mitigated", then we wouldn't need 2 booleans? I think we decided back then we need 2 booleans because "not active" is not always the same as "is_Mitigated", and vice versa. If that is the case, I think we should have them seperate everywhere and always let the user decide the value for both independently. 

The good thing about this PR is that it only adds 'is_Mitigated = False' in those places where we were already settings `mitigated = False`. So PR is good IMHO.

**Review by valentijnscholten — APPROVED** [review]

**Comment by devGregA** [comment]
I'd like to ask a potentially silly question. Why is the 'M' capitalized?

**Comment by devGregA** [comment]
Not related to PR on previous quesiton, approving.

**Comment by madchap** [comment]
> I'd like to ask a potentially silly question. Why is the 'M' capitalized?

Aha! yup... I didn't git blame, because I don't want to know.

**Review by devGregA — APPROVED** [review]

**Comment by madchap** [comment]
> The good thing about this PR is that it only adds 'is_Mitigated = False' in those places where we were already settings `mitigated = False`. So PR is good IMHO.

`mitigated` is actually a timestamp. Otherwise yes, no risk.

**Comment by valentijnscholten** [comment]
I think we could do a migration that renames the field (in a future PR).

**Pull request merged**
