### PR TITLE
Add support for tolerations

### PR DESCRIPTION
**Pull request by mikeanth-dev**
The `django-initializer` pod had no support for setting tolerations previously. This PR should fix that and add the ability to specify tolerations right in the `values.yml` file,  such as:

``` yaml
[...]
initializer:
  affinity: ...
  nodeSelector: ...
  tolerations: ...
```
[...]

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Thanks, can you reggae against the 'dev' branch please?

**Comment by valentijnscholten** [comment]
thanks, but seems to contain some phantom commits :-)

**Comment by mikeanth-dev** [comment]
@valentijnscholten I am unsure how those commits sneaked up in there... Is it because i made my changes on the `master` branch and i am trying to merge into `dev`?
How should i go about removing them from this PR?

**Comment by valentijnscholten** [comment]
easier to make a new PR

**Comment by mikeanth-dev** [comment]
Fair enough. Will close this one and make new PR.

**Pull request closed without merging**
