### PR TITLE
Use the product name as the description in the importer

### PR DESCRIPTION
**Pull request by coheigea**
**Description**

When using the importer, you can create a product with no description. Then if you try to edit the product in the UI it errors if you don't add a description. I think description should be optional in the UI as well.

### CODE REVIEW

**Comment by Maffooch** [comment]
I think it would be a better idea to make the product have a description via the importer rather than making it non required in the other places.

**Comment by coheigea** [comment]
@Maffooch Can do, but this will break every API client who is not setting the description

**Comment by Maffooch** [comment]
I don't think it would break anything really. This is only applicable for the auto create context on the re/import endpoints. Just set the description to the same thing as the title.

**Comment by damiencarol** [comment]
@Maffooch I think the patch to make it optional was good. Mandatory description is weird IMO.

**Comment by coheigea** [comment]
I've already change the PR to just re-use the description in the importer - let me know if I should revert :-)

**Comment by Maffooch** [comment]
The PR as it stands currently is good for a bugfix in the upcoming release, but setting the field to not required should go in dev under the next release

**Comment by coheigea** [comment]
Yep sounds good @Maffooch

**Review by Maffooch — APPROVED** [review]

**Review by devGregA — APPROVED** [review]

**Comment by Maffooch** [comment]
@coheigea I brought this up with Greg to think about changing the description to optional

**Comment by coheigea** [comment]
@Maffooch OK let me know, and I'll submit a new PR

**Pull request merged**
