### PR TITLE
move Entrypoint to seperate file

### PR DESCRIPTION
**Pull request by yaro24**
When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [x] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by devGregA** [comment]
@yaro24 I believe this was addressed by @maennel. Please feel free to reopen or adjust if you disagree

**Comment by maennel** [comment]
@devGregA I think this PR addresses a different thing. With the complexity of the start command, I think it makes sense to move the script out to a dedicated file, as proposed by @yaro24 . This helps also for testability.

**Comment by yaro24** [comment]
@devGregA @maennel which PR are we talking about? I will be happy to look into it.

The purpose behind this change was in fact for easier testing. Moving the Entrypoint to a file allows a user to adjust startup after the Image was built

**Comment by yaro24** [comment]
@devGregA any update here?

**Pull request closed without merging**
