### PR TITLE
Allow Info findings to be pushed to JIRA without SLA

### PR DESCRIPTION
**Pull request by Maffooch**
Findings with an Info severity do not get an SLA. When creating new issues to push to JIRA, a findings SLA is used to set the due date on the JIRA issue. Since Info findings don't have an SLA, trying to add one results in an exception and the issue is not pushed. This added check just ignores that field if it is an Info finding.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
I would expect the find.sla_deadline() to be None and we should check on that to be None and skip duedate setting in JIRA?
We should try to minimize internal logic in the JIRA code.

**Comment by mtesauro** [comment]
Not exactly sure how the internals of the Jira integration work exactly but I can tell you that I was getting a Python exception on info findings being pushed to Jira.  I mentioned this on a chat with Maffooch yesterday and I guess he listened :-)

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by valentijnscholten** [comment]
The fact that it works, doesn't mean it's solved in the best place. To me it feels weird that the JIRA integration code needs to know about that Info findings don't have a sla deadline. Second weird is that the jira code and anyone who reads it needs to know that the get_number_severity method returns False or None (or zero?) for Info findings. Or does it return that for all findings without an sla deadline? 
Apart from that if other integrations would also want to use a duedate / deadline field, thy would need to implement the same logic and we would have the same logic in multiple places (github integration, sla notifications, future bugtrackers, ...)

So what I am saying is that finding.sla_deadline() should return None if there is no deadline. The JIRA then only needs to do a simple ìf` wihtout knowing anything about the relationship between SLA's, severities, numerical severities, etc.

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
The fact that it works, doesn't mean it's solved in the best place. To me it feels weird that the JIRA integration code needs to know about that Info findings don't have a sla deadline. Second weird is that the jira code and anyone who reads it needs to know that the get_number_severity method returns False or None (or zero?) for Info findings. Or does it return that for all findings without an sla deadline? 
Apart from that if other integrations would also want to use a duedate / deadline field, thy would need to implement the same logic and we would have the same logic in multiple places (github integration, sla notifications, future bugtrackers, ...)

So what I am saying is that finding.sla_deadline() should return None if there is no deadline. The JIRA then only needs to do a simple ìf` wihtout knowing anything about the relationship between SLA's, severities, numerical severities, etc.

**Review by devGregA — APPROVED** [review]

**Comment by devGregA** [comment]
I believe this complies with Valtenjin's suggestion. Can adjust if that is not the case.

**Comment by valentijnscholten** [comment]
Better yes, thanks!

**Pull request merged**
