### PR TITLE
Better separation of vulnerabilieties in tenable scan 

### PR DESCRIPTION
**Pull request by WojTecH94**
No longer aggregate different endpoints into single vulnerability because it complicates finding management and reporting. More info:
https://github.com/DefectDojo/django-DefectDojo/discussions/9669

(2nd PR approach because it appears that changes in xml_parser cause too many unittests failures and it have to be done separately)

### CODE REVIEW

**Comment by lme-nca** [comment]
Please dont merge this! imho the way the parser works now is wanted behaviour and we rely on it, and as already mentioned you could use the https://github.com/DefectDojo/django-DefectDojo/discussions/9669#discussioncomment-8669293 view for this use case.

**Comment by WojTecH94** [comment]
Here is my point of view https://github.com/DefectDojo/django-DefectDojo/discussions/9669#discussioncomment-9238369

**Review by mtesauro — CHANGES_REQUESTED** [review]
Keeping this from being merged while discussion is ongoing

**Review by manuel-sommer — CHANGES_REQUESTED** [review]
Hi @WojTecH94,
could you take a look at this issue and fix it on the fly if the issue is a true positive reported bug? 
https://github.com/DefectDojo/django-DefectDojo/issues/10051

**Comment by mtesauro** [comment]
Closed as stale

**Pull request closed without merging**
