### PR TITLE
Fix exception when running dedupe management command

### PR DESCRIPTION
**Pull request by madchap**
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/4426

### CODE REVIEW

**Comment by valentijnscholten** [comment]
What I had as a bug a while ago is that I forgot to pass in the `fields` parameter somewhere, causing no fields to be updated. So I made it mandatory, but forgot dedupe.py it seems. I prefer to make the parameter mandatory, as having no fields is a non-default case and it would be good to force people to pass in `fields=None` if they don't want any fields to be updated.
i.e. change `dedupe.py` instead of `utils.py` :-)

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
adf

**Comment by madchap** [comment]
That's what I thought first, but then I got lazy.

**Comment by valentijnscholten** [comment]
I can fix it as it was my bug

**Comment by madchap** [comment]
It's ok, you fix enough of mine :)

**Review by valentijnscholten — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
