### PR TITLE
Multiple Endpoint object query fix

### PR DESCRIPTION
**Pull request by Maffooch**
This quick fix is an extension of #3612 such that a workaround is applied to import and re-import in both the UI and the API. Though this is not a "proper" fix as desired by #3613, it will get the job done in the meantime.

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by valentijnscholten** [comment]
Do we have some example data dumps maybe of instances where we have duplicate entries? Ideally we do the proper fix at some point :-)

**Comment by Maffooch** [comment]
No actually. I've never been able to reproduce. From what I've gathered so far, this only happens in the the event of a race condition like situation such as when two operations use the `get_or_create` method at the exact same time and both end up creating the object. Once the third time comes around, it will then find two objects.

**Comment by valentijnscholten** [comment]
Either way eventually there should be some kind of database constraint to prevent this from happening.

image


https://stackoverflow.com/questions/6586552/django-how-to-do-get-or-create-in-a-threadsafe-way

**Comment by Maffooch** [comment]
Eventually yes.

**Review by devGregA — APPROVED** [review]

**Pull request merged**
