### PR TITLE
remove defusedxml in favor of lxml

### PR DESCRIPTION
**Pull request by manuel-sommer**
I would recommend to either go with lxml or defusedxml, but don't use a mixture of both.
https://discuss.python.org/t/status-of-defusedxml-and-recommendation-in-docs/34762/19

I chose lxml as defusedxml got the last update in March 2021

### CODE REVIEW

**Comment by manuel-sommer** [comment]
I would recommend to either go with lxml or defusedxml, but don't use a mixture of both. 
https://discuss.python.org/t/status-of-defusedxml-and-recommendation-in-docs/34762/19

**Comment by manuel-sommer** [comment]
Remaining files with defusedxml:

- dojo/tools/fortify/parser.py
- dojo/tools/dependency_check/parser.py
- dojo/tools/vcg/parser.py

**Comment by manuel-sommer** [comment]
Last commit fixed 10 unittests

**Review by Maffooch — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Something went wrong with rebasing, sorry for this, I will open up another PR.

**Pull request closed without merging**
