### PR TITLE
Add: dependencies in helm3 style

### PR DESCRIPTION
**Pull request by dsever**
Moving away from helm v1 to helm v2

Would be nice to setup minimal k8s supported version:

kubeVersion: ">= 1.16.0"

### CODE REVIEW

**Comment by madchap** [comment]
Was not that what we tried before and we had issues with the `condition` statements?

**Comment by dsever** [comment]
Yes I remember it, but I tested locally and would say it work properly

**Comment by madchap** [comment]
You'd need to rebase @dsever, not sure what happened to the PR here.

**Comment by dsever** [comment]
@madchap  I will open new PR

**Pull request closed without merging**
