### PR TITLE
Reopen JIRA ticket when an original finding is reopened

### PR DESCRIPTION
**Pull request by FallenAtticus**
This change will force the original finding, having a jira issue linked to it, to update the jira issue as well. Having it that way, the linked jira issue of the orignial finding will be re-opened as well.

### CODE REVIEW

**Review by Maffooch — CHANGES_REQUESTED** [review]
I don't believe this function is JIRA specific. It should not assume that it is. There are some JIRA helper methods at `dojo/jira_link/helper.py` to identify if there is a valid JIRA connection associated with the finding.

**Comment by Maffooch** [comment]
@FallenAtticus Any thoughts on my comment? Will close this in a week otherwise.

**Comment by valentijnscholten** [comment]
I think if a finding gets reopened in JIRA, it makes sense to also reopen it in JIRA. Using save to jira is probably the generic approach to get the issue in jira updated from defect dojo.

**Comment by Maffooch** [comment]
@valentijnscholten doesn't that function reopen duplicates? I don't think duplicates should be pushed to JIRA. I may be misinterpreting here though.

**Comment by valentijnscholten** [comment]
This code is called when a new finding is imported that is a duplicate of an existing (original) finding, which is closed/mitigated. In this case the original gets reactivated. If that original has a jira issue linked, it makes sense to reopen that jira issue as well. But we can't just always say `push_to_jira=True` as it could create a new jira issue if there is none. Also this push to jira is not explicitly chosen by the user, so we may have to push only the status to JIRA and not overwrite the description etc by pushing from save()

**Pull request closed without merging**
