### PR TITLE
fix static and dynamic type finding

### LINKED ISSUE #990: "Dynamic finding" is always ticked
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description

I'm using https://defectdojo.herokuapp.com that is running 1.5.4 as of now

### Steps to Reproduce

Case OK
- Create a Finding
- Tick the "Dynamic finding" check box
- Save
- Edit the Finding
- The "Dynamic finding" check box is ticked => OK

Case KO
- Edit the Finding
- Untick the "Dynamic finding" check box
- Save
- The "Dynamic finding" check box is ticked => KO

### PR DESCRIPTION
**Pull request by dr3dd589**
fix #990 

- [x] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes should include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by dr3dd589** [comment]
@adracea @valentijnscholten  Can you please review this one! suggest me if there is any other way to do it.

**Comment by valentijnscholten** [comment]
I have no idea what the difference between static and dynamic is yet, so I'll have to leave it to the other reviewers.

**Comment by dr3dd589** [comment]
@aaronweaver Can you please review this.

**Comment by dr3dd589** [comment]
done! @Maffooch  thanks. didn't see that I pushed this PR into the master branch.

**Pull request merged**
