### PR TITLE
Add SAML2 support to DefectDojo

### PR DESCRIPTION
**Pull request by cody-m-tibco**
Adds a plugin that makes SAML2 authentication setup very similar to the OAuth suite currently in place. 

[Documentation](https://github.com/DefectDojo/Documentation/pull/102)

- [x] Your code is flake8 compliant.
- [x] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted).
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by alles-klar** [comment]
Seem to be the same discussion as in this PR https://github.com/DefectDojo/django-DefectDojo/pull/1363 and this issue https://github.com/DefectDojo/django-DefectDojo/issues/1661. 

From my point of view saml is very useful and I am using the implementation from https://github.com/DefectDojo/django-DefectDojo/pull/1363 now over one year in production.

**Comment by cody-m-tibco** [comment]
Oh I remember that PR now. Yes, SAML is super useful from an org perspective since it is a little more secure than OAuth. Without any bias, I think this package makes it a little more simple and user friendly at the expense of customization. What do you think?

**Comment by alles-klar** [comment]
@cody-m-tibco did you took a look if saml would work with [social auth](https://python-social-auth.readthedocs.io/en/latest/backends/saml.html?highlight=saml)? To be honest, I didn't because I already had a solution which worked for me.

**Comment by cody-m-tibco** [comment]
I did not! I was under the impression social-auth was primarily OAuth. Probably best to keep SSO configs consistent. Thanks for steering me in the right direction!

**Comment by cody-m-tibco** [comment]
So after trying off and on for a bit, its going to take 3 extra debian packages to get the social-auth SAML backend working. Seems like the one from this PR would be the lightest option.

**Pull request closed without merging**
