### PR TITLE
fix #851

### LINKED ISSUE #851: Installing Dev version of DefectDojo results in an Error
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

## Issue Template
While installing Dev version of DefectDojo from github location https://github.com/DefectDojo/django-DefectDojo/tree/dev, we are facing an issue like the below:

/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 107: cd: /opt/dojo/django-DefectDojo: No such file or directory
==============================================================================
Creating dojo/settings/settings.py and .env file
==============================================================================

/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 124: cd: /opt/dojo/django-DefectDojo: No such file or directory
cp: cannot stat 'dojo/settings/settings.dist.py': No such file or directory
/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 151: cd: /opt/dojo/django-DefectDojo: No such file or directory
DB URL is:
mysql://dojodbusr:OYN%29cVTb%29RMuCIL%290heEb52p@localhost:3306/dojodb
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
==============================================================================
Installing DefectDojo Django application
==============================================================================

Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (18.1)
Directory '.[mysql]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 257: entrypoint_scripts/common/setup-superuser.expect: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 279: cd: components: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

### Steps to Reproduce
1. Clone the github directory https://github.com/DefectDojo/django-DefectDojo/tree/dev 
2. Install on Ubuntu On Windows.

### PR DESCRIPTION
**Pull request by dr3dd589**
If it is necessary to install in "/opt/dojo" then we have to update installation doc in which we should mention creating a dojo directory in "/opt/" and after that clone repo in the dojo and install it. 

if not then this PR is a fix of this issue #851   

Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is flake8 compliant (Dojo's code isn't currently flake8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by devGregA** [comment]
@mtesauro this is out of my area of expertise.

**Comment by valentijnscholten** [comment]
Is this still relevant as #851 is closed as fixed?

**Comment by dr3dd589** [comment]
oh sorry, didn't see that.

**Comment by valentijnscholten** [comment]
No problem, thanks for helping out

**Pull request closed without merging**
