### PR TITLE
Finetune and document release process

### LINKED ISSUE #5754: helm chart version not bumped on bugfix releases
releases `2.6.0`, `2.6.1` and `2.6.2` all have the same helm chart version but different `appVersion `values.

### PR DESCRIPTION
**Pull request by valentijnscholten**
- Fixes #5754 and #5755 
- Documents all the steps of the release process, both for feature releases and bugfix releases.

Please note the steps have changed slightly, so RTFM if you're doing a release in the future :-)

- The main difference is to delete any pre-existing draft release before starting the release process.

Based against `master` so we can use it during the next release.

### CODE REVIEW

**Review by Maffooch — APPROVED** [review]
Very comprehensive! Thank you for doing this. Should be much more difficult to mess up now :)

**Review by damiencarol — APPROVED** [review]
Great improvement

**Comment by damiencarol** [comment]
Accesslint is stuck ?!?

**Comment by damiencarol** [comment]
@accesslint ???

**Pull request merged**
