### PR TITLE
Rules Framework

### PR DESCRIPTION
**Pull request by devGregA**
Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by ananan** [comment]
I was wondering why add rules framework..it's useless now

**Comment by damiencarol** [comment]
@devGregA could you describe a little (update description?) what this Rule Framework is ?

**Comment by devGregA** [comment]
The rules framework allows data manipulation based on selected criteria. When scan data wasn't as good as it is today, this was helpful for normalization and reporting. It can also have catastrophic consequences if used incorrectly. The manner in which it is written is probably not efficient. It may be useful someday, but could definitely be removed and put into the 'rework someday' category.

**Comment by damiencarol** [comment]
maybe something to add to `2.x` list

**Pull request merged**
