### PR TITLE
SAML integration

### PR DESCRIPTION
**Pull request by alles-klar**
Integrate support for SAML

These PR adds all required dependencies to integrate SAML. There is already a example configuration in the settings.dist.py. I do not provide additional documentation, because the djangosaml2 documentation describes already the relevant parameters. Is this sufficient?

In my setup it works fine but I don't know how to provide good tests for this SAML integration. If someone has a good idea feel free to leave a comment.

Related to PR #1141 which was closed during the python3 shift.

---

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is flake8 compliant 
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by aaronweaver** [comment]
@alles-klar Is this building on [social auth ](https://python-social-auth.readthedocs.io/en/latest/backends/saml.html?highlight=saml)or totally separate?

**Comment by alles-klar** [comment]
> @alles-klar Is this building on [social auth ](https://python-social-auth.readthedocs.io/en/latest/backends/saml.html?highlight=saml)or totally separate?

It is totally separate. I already did this work before the socal auth package was integrated. I did not know until now that the social auth package supports saml.

**Comment by mtesauro** [comment]
This looks interesting and is a ton of work but feels redundant since we have the social auth stuff in place.

Maybe move it to the https://github.com/DefectDojo/Community-Contribs so it's not lost and people that want a different SAML implementation can use that instead of social auth?

**Comment by Maffooch** [comment]
Since the community contributions page was not updated with this pull request, I think the next best thing to do here is to add an archived label and close. This way, it can be revisited at a later date. Thanks again for your contribution.

**Pull request closed without merging**
