### PR TITLE
Add flake8 for achieveing pep8, the devops way

### PR DESCRIPTION
**Pull request by secfigo**
This PR adds support for flake8 tests for code quality on Dev Branch. Whenever someone pushes code to dev branch, this code will run and only lint the files which have been changed in that PR request against master branch. 

So Instead of achieving pep8 in one go, we will only check PRs and little by little, we will achieve pep8 :) 

Also this PR ignores the following checks using .flake8 file. Once all the pep8 issues are taken care, we can work on enable those checks. 
 
E501: line too long (> 79 characters)
E127: Continuation line missing indentation or outdented
Scan complexity is set to 10 so it won't go deeper. 

- [x] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)

- [] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by secfigo** [comment]
Please merge #564 and then re-run this travis job.

**Comment by devGregA** [comment]
@secfigo merged as instructed and reran.

**Comment by secfigo** [comment]
@devGregA looks like i missed two entries :)

**Comment by secfigo** [comment]
image

**Pull request merged**
