### PR TITLE
fix(filters): prevent crashes when `start_date == date.min`

### PR DESCRIPTION
**Pull request by p-l-**
**Description**

Some reports may include bogus values for `start_date`, like the `date.min` value. In that situation, DefectDojo would crash; the bug is not really in DefectDojo, but a bit of defensive programming won't hurt, and we want to avoid a crash even with invalid data.

When that happen, we'll use `date.min` as `start_date` rather than `date.min - timedelta(days=1)` which cannot exist in Python.

**Test results**

We do have an (internal, home made) scanner that (used to) produce such invalid result, and this patch fixes the issue.

**Documentation**

N/A

**Checklist**

This checklist is for your information.

- [x] Make sure to rebase your PR against the very latest ~~`dev`~~ `bugfix`.
- [x] Bugfixes should be submitted against the `bugfix` branch.
- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.11 compliant.
- [ ] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by p-l-** [comment]
I cannot add the `bugfix` label to my PR, but that's what it is!

**Comment by kiblik** [comment]
Can you also write a unittest for it? If your report contains sensitive info, feel free to anonymize it.

**Comment by p-l-** [comment]
@kiblik sure thing. Could you guide me a bit on how to do that (or point to a documentation)? Where should I store the scan result to test?

**Comment by kiblik** [comment]
> @kiblik sure thing. Could you guide me a bit on how to do that (or point to a documentation)? Where should I store the scan result to test?

https://documentation.defectdojo.com/contributing/how-to-write-a-parser/

**Comment by p-l-** [comment]
OK I did read that but how can I be sure that the code I'm fixing is already tested somehow? Do I need to write a specific test for that? In the meantime I have added a test sample file anyway.

The provided test file would currently create this 500 error when navigating to e.g. `/finding/open`:
image

**Comment by Maffooch** [comment]
@p-l- your unit test could first create a finding with the "bad date" and then invoke the filter class that you are making the change to in this PR in the same way that the `/finding/open` view does. This would ensure that the exception is handled if the test passes

**Comment by p-l-** [comment]
@Maffooch Thanks. It seems that the results are not sent to the database, so my test won't work. Do you have any idea what the easier way to test it could be?

**Comment by Maffooch** [comment]
Could put your test here: https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/test_finding_model.py

**Comment by mtesauro** [comment]
Closing as stale

**Comment by p-l-** [comment]
Yep sorry @mtesauro @Maffooch I did not find the time to create a working test :-/

**Comment by mtesauro** [comment]
@p-l- 
> Yep sorry @mtesauro @Maffooch I did not find the time to create a working test :-/

No need to apologize - I appreciate the work you did to and we can always pick this back up and write a test. Life happens to everyone - feel free to do a PR anytime in the future. :+1:

**Pull request closed without merging**
