### PR TITLE
Bug fix: Add more unit tests for MobSF import #3479

### PR DESCRIPTION
**Pull request by damiencarol**
#3479 
This pull request is to fix [#3479 ](https://github.com/DefectDojo/django-DefectDojo/issues/3479) 

## Implementation
Fixed some part of the parser that doesn't work with reports for IOS

### Tests
I added 2 more reports from the bug comments.

### CODE REVIEW

**Comment by ZsanettMagyar** [comment]
Could you please change the new test files to the attached ones?
I replaced some unique values for public usage.

[mobsf_json.zip](https://github.com/DefectDojo/django-DefectDojo/files/5710352/mobsf_json.zip)

**Comment by damiencarol** [comment]
@ZsanettMagyar yes sure

**Comment by damiencarol** [comment]
@ZsanettMagyar I updated the test files. I saw that you work in Budapest by the way (or your customer)  :D

**Comment by damiencarol** [comment]
@valentijnscholten @madchap need a review on this one.

**Review by valentijnscholten — APPROVED** [review]
thanks! I believe the unit test results :-)

**Comment by damiencarol** [comment]
@devGregA @aaronweaver @devEricA any review? plz ? I need to close some PR before pushing more on SARIF and Snyk format.

**Comment by ZsanettMagyar** [comment]
Yeah, you are right 👍 thanks for the change, I needed this fix 😅
> @ZsanettMagyar I updated the test files. I saw that you work in Budapest by the way (or your customer) :D

**Review by madchap — APPROVED** [review]

**Pull request merged**
