### PR TITLE
Add user post endpoint to APIv2

### PR DESCRIPTION
**Pull request by Maffooch**
Add a `post` function to APIv2 that creates users.

- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [x] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
This may be me nitpicking, but do we want the `last_login` field to be modifiable via the API?

**Comment by Maffooch** [comment]
Probably not, but how can I restrict that for just the `post` endpoint?

**Comment by valentijnscholten** [comment]
Don't know the best way. You could override `    def perform_create(self, serializer):` but not sure if it's worth the effort.

**Comment by Maffooch** [comment]
Found a way to do it with very little pain. Definitely ready now!

**Review by valentijnscholten — APPROVED** [review]
nice!

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
