### PR TITLE
Set a default environment for tests in DefectDojo

### PR DESCRIPTION
**Pull request by FelixHernandez**
## Set a default environment for tests in DefectDojo
**Description**
tempsnip

During an import, the Environment will default to "Development", reducing clicks for the user

### CODE REVIEW

**Review by grendel513 — APPROVED** [review]
Thank you for your first DD pull request!

**Comment by FelixHernandez** [comment]
@mtesauro the fix is done in the new commit.

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Comment by kiblik** [comment]
This PR breaks DD if the user decides to remove `Development_Environment(name='Development')`: https://github.com/DefectDojo/django-DefectDojo/issues/8636

**Pull request merged**
