### PR TITLE
Parser guidelines Updates

### PR DESCRIPTION
**Pull request by paulOsinski**
New pull request containing parser documentation template, and expanded guide on writing parser documentation

### CODE REVIEW

**Comment by paulOsinski** [comment]
Thank you for your feedback @manuel-sommer !  Added an additional page with a documentation template as per your suggestion.

**Comment by kiblik** [comment]
Can you reflect your proposal to this repo as well, please? https://github.com/DefectDojo/cookiecutter-scanner-parser

**Review by manuel-sommer — CHANGES_REQUESTED** [review]
Hi @paulOsinski,
could you please advance the unittests in order to reflect your new guideline?

For example you could add the following code snipped (you have to extend it yourself to fit the guideline) to: https://github.com/DefectDojo/django-DefectDojo/blob/2a909ecc0f7f3d10fd0f7681ad880def4c775331/unittests/test_parsers.py#L30

                    content = open(doc_file).read()
                    self.assertTrue(re.search("title:", content),
                                    f"Documentation file '{doc_file}' does not contain a title"
                    )
                    self.assertTrue(re.search("toc_hide: true", content),
                                    f"Documentation file '{doc_file}' does not contain toc_hide: true"
                    )

If you use this code snipped and advance it, you also have to "import re"

**Comment by paulOsinski** [comment]
@manuel-sommer I've moved this PR to #9271 .  I've started to incorporate your suggestions and will expand upon them, thanks!

**Pull request closed without merging**
