### PR TITLE
JIRA fixes

### PR DESCRIPTION
**Pull request by madchap**
Some jira fixes for unreferences issues and:
- #2460
- Most of #2458 I guess, but this will be left as an exercise to @dayal18 ;-)

### CODE REVIEW

**Comment by madchap** [comment]
FYI @mestrade: https://github.com/DefectDojo/django-DefectDojo/pull/2462/commits/f844036295a070151dd1157fbe42dd8dff0df1c0

Unsure how the github webhook (probably not used by anyone right now) is used further, but I *think* it may have broken the JIRA webhook. So, just FYIm the url's changed.

**Comment by dayal18** [comment]
Thanks @madchap I'll try to change it locally on my machine and check this.

**Comment by dayal18** [comment]
@madchap 2 issues:

1) When Product level - JIRA is enabled -- Using "Bulk Edit" is creating JIRA ticket, but the JIRA Age and JIRA Change is blank.

image


2) The Webhook didn't work.. :(  JIRA Webhook is critical functionality for our process, any other suggestions, please.

**Comment by dayal18** [comment]
Rest all looks good, the bug icon, + other issues which I mentioned, those are fixed. only the above 2 are still open.

**Comment by dayal18** [comment]
ok another issue.. I'm started getting those JIRA alerts again. something it didn't like..

image


I have Product level JIRA push + Push all Notes..

**Comment by dayal18** [comment]
and it doesn't stop.. as I have only 1 note the speed is less.. unlike last time.. where I have 10 notes.. and 10 alerts were bumping every 10 sec

**Comment by valentijnscholten** [comment]
The alert thing is fixed by #2402 in 1.6.1. The alerts are there for a reason, to give the user feedback if something wrong. So they should stay as not every user has access to the server log files.
The reason there are so many alert now is because the JIRA integration is more less completely broken by the push all issues PR in 1.6.0. So if we fix thare, the alerts will be useful again.

**Comment by madchap** [comment]
> The alert thing is fixed by #2402 in 1.6.1.

Will be fixed, when out ;-)

**Comment by dayal18** [comment]
> The alert thing is fixed by #2402 in 1.6.1. The alerts are there for a reason, to give the user feedback if something wrong. So they should stay as not every user has access to the server log files.
> The reason there are so many alert now is because the JIRA integration is more less completely broken by the push all issues PR in 1.6.0. So if we fix thare, the alerts will be useful again.

Ant idea if this also fixes the JIRA WebHooks? which is not working now?

**Comment by madchap** [comment]
> Any idea if this also fixes the JIRA WebHooks? which is not working now?

Best to read the PR description or the few lines changed to know. It is likely that a PR fixing the webhook will somehow mention it :-)

**Pull request merged**
