### PR TITLE
Refactor API parsers

### PR DESCRIPTION
**Pull request by kiblik**
PR is based on my question in Slack: https://owasp.slack.com/archives/C014H3ZV9U6/p1661299601825669

# Summary

The number of tools/parsers which do not only parse uploaded files but communicate with API is increasing. This PR does some small clean-up and defines a set of rules to keep it maintainable and improve UX for using API parsers (simplified way to add `Tool Type`, `Tool Config` and `ApiScanConfig`).
- [x] a parser which supports API is placed in the directory `dojo/tools/api_<tool>` - yes, this means renames like `sonarqube_api` to `api_sonarqube`
- [x] in documentation, in a list of parsers, a subsection/subheader only for these parsers was created. At the beginning of this section is a manual “how to set ToolType, ToolConfig, ApiScanConfig” to avoid repetition in all parsers. Each parser defines only which values and how should be filled
- [x] add function to parsers `api_scan_configuration_hint` which returns `string` with a hint, which `service_key` and how should be set up
- [x] add function which collects hints from `api_scan_configuration_hint` and print it in `add` and `edit` view
- [x] Add to documentation: “how to write a parser which communicates with API”. Some rules:
       Required parts: api_client, importer, parser
       Write tests
       Optional but recommened functions for api_client: test_connection, test_product_connection
- [x] Update template for “Template Generator”: https://github.com/DefectDojo/cookiecutter-scanner-parser/pull/8
- [x] In almost all api_clients is used `Tool_Type.objects.get_or_create(name='XYZ')`. Parsers should be stateless (they shouldn't create these entries). 
- [x] Integration test for creation of `ToolType`, `ToolConfig` and `ApiScanConfig`

## Example of UI changes

1. Dynamic hints. `Tool Type` for `BlackDuck`, `Cobalt.io` and `Vulners` exist. There is no `Toll Type` for `Bugcrowd`, `Edgescan` and `SonarQube` - I removed them only because of this test. They are by default there with a new or upgraded instance.
Screenshot 2023-01-11 at 20 48 52

2. Description _Parser XXX requires created tool type XXX._ is `<a>`, it is referencing to page where the user can create missing `Tool Type`
Screenshot 2023-01-11 at 20 53 08

3. After clicking on the link, a user is redirected to the page with the prefield form
image

4. Updated description after creating `Tool Type`. The link is now pointing to the page for the `Tool Config` creation
Screenshot 2023-01-11 at 21 01 07

5. `Tool Type` is automatically fielded
Screenshot 2023-01-11 at 21 02 28

6. New `Tool Config` is ready. The description is updated to hint from `api_scan_configuration_hint`
Screenshot 2023-01-11 at 21 04 35

### CODE REVIEW

**Comment by Gby56** [comment]
@kiblik beware of my fix in https://github.com/DefectDojo/django-DefectDojo/pull/7134 I renamed the bugcrowd api importer, you should pull dev again

**Comment by kiblik** [comment]
Hi, I would like to ask about your opinion about this PR (and testing if it is possible).

- [ ] BlackDuck - @damiencarol 
- [ ] Bugcrowd - @Gby56 
- [ ] Cobalt.io - @ericcornelissen 
- [ ] Edgescan - @ShayVD 
- [x] SonarQube - I already did a testing
- [ ] Vulners - @vankyver 

Thanks in advance.

**Review by damiencarol — APPROVED** [review]

**Comment by damiencarol** [comment]
This is good. @kiblik

**Review by ericcornelissen — APPROVED** [review]
Everything looks good and works correctly from Cobalt's side, thanks @kiblik

**Review by Maffooch — APPROVED** [review]
Excellent work as always 🤙🏼

**Pull request merged**
