### PR TITLE
Update slack invite URL to use the OWASP heroku invite rotator app

### PR DESCRIPTION
**Pull request by valentijnscholten**
Update OWASP invite link to https://owasp-slack.herokuapp.com/

### CODE REVIEW

**Comment by AlexanderTyutin** [comment]
@madchap Error after entering email

```
owasp
Failed! Something has gone wrong. Please contact a system administrator.
```

**Comment by valentijnscholten** [comment]
yeah it doesn't seem to work yet, we're depending on those manage the OWASP communication stuff and I don't know who they are.

**Comment by AlexanderTyutin** [comment]
Error changed :)

```
owasp
Failed! missing_scope
```

**Comment by valentijnscholten** [comment]
Little birds tell me it's working now

**Pull request merged**
