### PR TITLE
Add Google/OKTA OAUTH2 Sign-in options

### PR DESCRIPTION
**Pull request by Maffooch**
Tutorial for establishing OAUTH clients can be found in the DefectDojo Documentation. Redirection to that page is default when attempting to login with either method without proper configuration.

When submitting a pull request, please make sure you have completed the following checklist:

- [X] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [X] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes should include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by arkwrn** [comment]
I've already follow exactly the same as the instructions on the docs but instead of login using google it's redirect to https://defectdojo.readthedocs.io/en/latest/social-authentication.html#google

**Comment by Maffooch** [comment]
Hi @arkwrn, I'm glad you found a solution to the issue. Do you happen to be running on the release build? Any changes made to the project can only be applied after either rebuilding everything or doing your solution. If this is not your case, please let me know.

**Comment by arkwrn** [comment]
I run based on latest master (https://github.com/DefectDojo/django-DefectDojo.git)

**Comment by Maffooch** [comment]
From my understanding, you are correct. One way to avoid that is to build your local repo with the modified settings.py, and then launch the images. This way, instead of pulling from the registry, it will pull from the newly created local builds. There is more on that here: [https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md](https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md)

**Pull request merged**
