### PR TITLE
Nikto quick fix

### PR DESCRIPTION
**Pull request by madchap**
Fixes nikto issue reported in https://github.com/DefectDojo/django-DefectDojo/issues/3268

The regex probably needs rework. This PR is to get a working nikto parser before the next release.

### CODE REVIEW

**Comment by madchap** [comment]
The flake8 may/will actually fail because of the regex (which sometimes work).

**Comment by valentijnscholten** [comment]
probably caused by this value in the problematic report:
`<iplink><![CDATA[http://:/favicon.ico]]></iplink>`
maybe include that in the unit tests xml file so if we refactor it in the future, we'll see if it still works with this (stupid) url?

**Comment by madchap** [comment]
I am actually not seeing any unit tests for nikto.

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by valentijnscholten** [comment]
hmm no unit tests, then we should merge. Usually I try to but the data causing the bug in the unit test which then proves that it is fixed. and stays fixed.

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
