### PR TITLE
Slimmer docker image

### PR DESCRIPTION
**Pull request by alles-klar**
Reduces the size of the docker image

---

Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes should include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by ptrovatelli** [comment]
@alles-klar @aaronweaver I think this broke the nginx image build. 
Can be seen in travis logs; We need to improve travis test to end KO in that case :)

https://travis-ci.org/DefectDojo/django-DefectDojo/jobs/519142559
unfold "Sending build context to Docker daemon  7.414MB"

```
Processing triggers for libc-bin (2.24-11+deb9u4) ...
/bin/sh: 1: curl: not found
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c apt-get -y update &&   apt-get -y install apt-transport-https ca-certificates &&   curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - &&   echo "deb https://deb.nodesource.com/node_11.x stretch main" | tee /etc/apt/sources.list.d/nodesource.list &&   curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&   echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&   apt-get -y update &&   apt-get -y install nodejs &&   apt-get -y install --no-install-recommends yarn &&   apt-get clean &&   rm -rf /var/lib/apt/lists &&   true' returned a non-zero code: 255
```

**Comment by aaronweaver** [comment]
I'll back it out. I don't know why the smoke test didn't pick that up. I'm wondering if the kubernetes containers aren't pulling locally even though it's specified to not pull from docker hub.

**Comment by ppiotr3k** [comment]
> @alles-klar @aaronweaver I think this broke the nginx image build.

I agree the build is broken when pulling locally; looks like `python:2-slim` (`Dockerfile.django`) is lacking the following packages `curl` (or `wget`, smaller footprint), `gnupg`, and `git`, needed in `Dockerfile.nginx`.
Should they be added to `Dockerfile.nginx`? If so, I have code ready for PR fixing it that way.


> Can be seen in travis logs; We need to improve travis test to end KO in that case :)

Indeed. Any idea why it's not failing and how to fix it?

**Comment by ptrovatelli** [comment]
about the travis tests, we build the images but don't check the return code. When the build fails we don't notice because the app will probably run with a previously built image, or with the dockerhub one. I'd say we should check the return code to make sure that this "docker build" ends with return code 0, which is most probably not the case when the build fails

**Comment by ptrovatelli** [comment]
maybe it's not that commit the issue actually; i have the same problem in my PR branch https://github.com/DefectDojo/django-DefectDojo/pull/1045 although I don't have your changed code. I don't know where this comes from then, maybe the python:2 image changed and lost curl?

**Comment by ptrovatelli** [comment]
See an example of travis change here to detect errors while building: 
https://github.com/ptrovatelli/django-DefectDojo/compare/a89370bebe8f63d5704a7642df97bb4b6da947a0...fix-docker-with-override
You can ignore the change in the building command though (this PR uses docker-compose to build images)
```
travis/script.sh:
  docker-compose -f docker-compose.yml build
  return_value=${?}
  if [ ${return_value} -ne 0 ]; then
    echo "ERROR: cannot build django or nginx image"
    exit ${return_value}
  fi
```

**Comment by alles-klar** [comment]
> > @alles-klar @aaronweaver I think this broke the nginx image build.
> 
> I agree the build is broken when pulling locally; looks like `python:2-slim` (`Dockerfile.django`) is lacking the following packages `curl` (or `wget`, smaller footprint), `gnupg`, and `git`, needed in `Dockerfile.nginx`.
> Should they be added to `Dockerfile.nginx`? If so, I have code ready for PR fixing it that way.

I don't think it's a good idea to install all missing packages if the goal is to build a small image. This can become very complex. Maybe we should create a base image and use it to build the django and nginx image? This would remove the dependency between these two images.

**Comment by ptrovatelli** [comment]
@alles-klar @aaronweaver  for the record: 
- nginx image: size is stable 191MB
- django image: slimmed from 1.31GB to 599MB (that is from https://github.com/DefectDojo/django-DefectDojo/pull/1105 , tested right now). This is nice :)

**Pull request merged**
