### PR TITLE
Add dynamic Test_Type for Generic parser

### PR DESCRIPTION
**Pull request by damiencarol**
Implement new interface for parser to customize Test_Type.

- [x] Add feature to customize test_type (useful to use generic type for multiple different parser and have a different de-duplication algorithm for each test_type)
- [x] Don't force active/verified value 

image

### CODE REVIEW

**Comment by Maffooch** [comment]
This looks good to me, but the dedupe test appears to be a logic failure rather than a deployment failure

**Comment by valentijnscholten** [comment]
Might be related to active/verified changes?

**Comment by damiencarol** [comment]
Some code was changed (in good) by Stephan to support better dynamic Test_type, I think some integration tests need modifications, the PR is not ready

**Comment by damiencarol** [comment]
mmm. this is weird. I checked and it's a fail in another parser :/  "Immuniweb Scan"
Relaunching the unit tests

**Comment by devGregA** [comment]
@damiencarol  is this ready to be moved from draft to PR?

**Comment by devGregA** [comment]
@damiencarol  are you still working / interested in this one?

**Comment by kiblik** [comment]
This can be closed because it was merged in https://github.com/DefectDojo/django-DefectDojo/pull/7471

**Pull request closed without merging**
