### PR TITLE
 Move GitHub issue templates to newer GitHub workflow - fixes  #977

### LINKED ISSUE #977: Better GitHub issues templates
**Is your feature request related to a problem? Please describe**
I'm always frustrated when using the issue template provided in DefectDojo, either when opening an issue or reading issues submitted by others.

**Describe the solution you'd like**
As a contributor submitting an issue, I want distinct questions when proposing an idea or reporting a bug so that I can have a better guidance  and user experience.
As a maintainer, I want feature requests to be directly labelled as `enhancement` so that I can save time and if need be prioritize on investigating other issues that can be bugs.

**Describe alternatives you've considered**
Setting up manually the new templates via the GitHub issue template builder.

**Additional context**
Demonstration in [my fork of the repository](https://github.com/ppiotr3k/django-DefectDojo/issues), feel free to play with it :wink: 
This issue illustrates how a feature request could be, except for the auto `enhancement` labeling.

Selection menu when opening a new issue:
image

Selecting a *bug report* (includes information requested in current issue template):
image

Selecting a *feature request*:
image

Selecting a *security issue* (includes pointer to disclosure policy as in current issue template):
image

### PR DESCRIPTION
**Pull request by ppiotr3k**
GitHub has a newer template builder and workflow for GitHub issues.
Ref.: https://help.github.com/en/articles/about-issue-and-pull-request-templates

Move issue template to `.github/ISSUE_TEMPLATE` for a cleaner root tree.
Separate enhancements and bug reports, for better contribution experience.
Add a _fake_ security issue template, pointing to the disclosure policy.
Update formatting style of issue templates to follow GitHub recommendations.

Fixes  #977

-------
Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [X] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.) :arrow_right: not applicable
- [X] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR. :arrow_right: not applicable
- [X] Add applicable tests to the unit tests. :arrow_right: not applicable

### CODE REVIEW

**Comment by ppiotr3k** [comment]
Apologies for the dirty PR; no idea how those already merged commits from `aaronweaver` landed here.

**Comment by ppiotr3k** [comment]
Another proposition: regarding the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md), maybe its content could be directly included in the *security issue* template? It would remove another file from the project root directory. I can do that in this PR, let me know.

Unless you want to keep it in the root directory for additional visibility? Could also make sense.
I'm not quite sure what to do, thus looking for your guidance. Thanks in advance.

**Comment by aaronweaver** [comment]
@ppiotr3k This is great, I wasn't aware of this feature so thanks for taking the time to create it.

**Comment by ppiotr3k** [comment]
> @ppiotr3k This is great, I wasn't aware of this feature so thanks for taking the time to create it.

Thank you @aaronweaver, I'm so glad you like it, much appreciated, makes me truly happy :relieved:

I very much like this project and I know you guys put a tremendous effort in it. As I imagine you are currently very busy with stabilizing the 1.5.4 release (Docker/Kubernetes), and migrating the code base to Python 3, I don’t want to bother too much with ideas at the moment.

So I’m trying to contribute on *side topics*, with short-term outcomes, that IMHO can help current and future end-users, contributors and maintainers to have a better experience with the project (ex: documentation, automated checks, testings, linting, etc.), trying to make it easier where I see fit, and with respect to the work of the maintainers.

**Pull request merged**
