### PR TITLE
[Fix] API - Tool Product Settings (#6170)

### PR DESCRIPTION
**Pull request by jpbowie**
Corrected issue #6170 by making the product editable in the Tool_Product_Settings model.

### CODE REVIEW

**Comment by Maffooch** [comment]
@jpbowie I don't believe this is the appropriate fix for this. The issue is stating that the product ID is appearing to be ignored in the POST request of the API. Could this be an issue with the API endpoint rather than the model itself?

Also please base your changes against the `dev` branch

**Comment by jpbowie** [comment]
I forgot to change the request to the dev branch, sorry.  I think the change makes the Tool_Product_Settings model consistent with other models that have a product foreign key relationship.  The uneditable product with a default value of 1 as assigned in the model also explains why no matter what product value the user provided, it was always assigned to product 1.

**Comment by jpbowie** [comment]
I think I found a way to allow the product to be specified in the API and saved by the serializer without the changes to the model.  Will this work?

**Review by Maffooch — APPROVED** [review]
Yup this is much better! Thanks :)

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
