### PR TITLE
Add endpoints to Qualys dedupe settings

### PR DESCRIPTION
**Pull request by Maffooch**
issues spanning  multiple endpoints were being swallowed by reimport

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved.

**Review by damiencarol — APPROVED** [review]

**Comment by alles-klar** [comment]
@Maffooch Why do you added  the endpoints hashcode default config? We have a separate logic for endpoint deduplication: DEDUPE_ALGO_ENDPOINT_FIELDS. We may need to fix the bug here and not falling back to the "old" logic and adding the endpoint to the hashcode calculation.

**Comment by Maffooch** [comment]
@alles-klar I do not see how to enable the matching of the endpoints using `DEDUPE_ALGO_ENDPOINT_FIELDS `. Is it enabled by default?

**Comment by alles-klar** [comment]
Yes, but default takes only host and path for duplication.

**Comment by damiencarol** [comment]
@Maffooch do you mind working on another PR that move forward this path?

**Pull request merged**
