### PR TITLE
Fix sslyze XML parser for undefined value

### PR DESCRIPTION
**Pull request by H4ckd4ddy**
In some cases, sslyze export does no contain checked key, and result in crash during import

### CODE REVIEW

**Comment by Maffooch** [comment]
Hello @H4ckd4ddy and thank you for your contribution. Pull requests are only accepted to the dev branch, so please submit there instead.

**Comment by H4ckd4ddy** [comment]
Hello @Maffooch, thanks, I moved

**Comment by madchap** [comment]
Hi @H4ckd4ddy 

Could you please clean up your PR's commit a bit? It should only contain commits and files change that pertain to it.

Cheers.

**Comment by H4ckd4ddy** [comment]
Hi @madchap,
Sorry, I close this one to open a new clean PR
Cheers

**Pull request closed without merging**
