### PR TITLE
Changed variable NODE_URL to fix bug #1753

### PR DESCRIPTION
**Pull request by AlexanderTyutin**
**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is flake8 compliant 
- [ ] Your code is python 3.5 compliant
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by AlexanderTyutin** [comment]
Just to understand, is there any user group of this project? For example, I have some questions about usage in real environment and have some scripts to share with the community :) But I don't know what is the best place to put it and ask the question which is off topic for issues in this project :)

**Comment by valentijnscholten** [comment]
The README has all the info, i.e. the Slack channel link.

**Comment by AlexanderTyutin** [comment]
The message when I'm trying to go into the Slack channel from README link

```
This invite link is no longer active.
If you have an @owasp.org or @owasp.com email address, you can still create an account.

If not, please check with the person who shared the invite link with you to ask for an invitation.
```

**Comment by valentijnscholten** [comment]
Today a new invite app was deployed: https://owasp-slack.herokuapp.com/ We'll update the README.

**Comment by valentijnscholten** [comment]
Can you rebase your PR against dev? master is very old.

**Comment by AlexanderTyutin** [comment]
@valentijnscholten Really I'm not so good with Git so I created new PR https://github.com/DefectDojo/django-DefectDojo/pull/1902 in dev to fix initial bug https://github.com/DefectDojo/django-DefectDojo/issues/1753 with Node.js (instead of rebase). There is just one line changed.

**Pull request closed without merging**
