### PR TITLE
Log to stdout

### PR DESCRIPTION
**Pull request by kiblik**
Fix for #8120

### CODE REVIEW

**Comment by kiblik** [comment]
At the time, when I opened this PR, I was doing multiple tests with `log-master`, `logto`, `logto2`, ... to be able to achieve that Errors will be logged to `stderr` and everything else to `stdout`.
I checked many online resources (like https://github.com/unbit/uwsgi/issues/1601) but had no success.

I hoped I would have time in the future to come back with a fresh mind and test some new approaches but I had never time.

If I'm not wrong, `log-master = True` (a.k.a. `--log-master`) will push all logs only to`stdout`. If it is a suitable solution, I might test it one more time (to be sure about my previous sentence) and I can offer it as solution (change draft PR to open PR).

**Comment by dschniepp** [comment]
I quickly [asked](https://github.com/DefectDojo/django-DefectDojo/issues/8120#issuecomment-2310425165) in the issue #8120 if still somebody else works on it, and prefers a different solution. From my point that sounds definitely like a valid approach and according to the discussion, currently the only one, which is easily implementable. The only question is, do we add just another flag or do we switch to `.ini` file like mozilla does https://github.com/mozilla/remote-settings/commit/a9f4da48944b8b3d8f59a235aa4cd0c1f6931387.

**Comment by kiblik** [comment]
So after a small test: Yes, `log-master` redirects all application logs to `stdout` (instead of `stderr`). In my opinion, it might not be best but better than all logs in `stderr`.
However, `log-master` does not work for `celery(worker|beat)`. I tried `--logfile /dev/stdout` but without any luck.
Unfortunately, I do not have the capacity to investigate alternatives. But I will be happy if somebody is willing to help here.

**Comment by barucijah** [comment]
@kiblik I have tried with --logfile=stdout and logs became info logs as they should be. 
Would you like to test it on your side?

**Comment by kiblik** [comment]
Not sure if I'm doing sth wrong or if I'm testing with wrong methods but when I apply this: https://github.com/DefectDojo/django-DefectDojo/pull/9708/commits/0fc5d0815896453724da73c62efaa9249d9d4b24
I still see logs like 
```
[12/Sep/2024 16:42:19] INFO [celery.beat:632] beat: Starting...
```
in stderr, not in stdout.

**Comment by barucijah** [comment]
@kiblik I tested my custom image on the instance deployed in Kubernetes. I tried to check the files, but I could not open them. However, I see in my Monitoring tool that logs are now shown as INFO, and before they were shown as ERRORS.
Here is an example of my change for the beat:
`exec celery --app=dojo \
    beat \
  --logfile=stdout \
  --pidfile=/var/run/defectdojo/celery-beat.pid \
  --schedule=/var/run/defectdojo/celerybeat-schedule`

**Comment by Maffooch** [comment]
It looks like there has not been any activity here for a while. In order to keep the list of pull requests in a manageable state, we are closing this one for now. If we are making a mistake here, please reopen the pull request, and leave us a note 😄

**Pull request closed without merging**
