### PR TITLE
add support django i18n

### PR DESCRIPTION
**Pull request by epochfairy**
modify: settings.dist.py
templeates: base.html，
add: locale
image

### CODE REVIEW

**Comment by valentijnscholten** [comment]
How does this work? When I look at the Djano docs, they suggest using the `translate` tags in template to implement i8n. But this PR doesn't change any templates. Is it using some kind of generic "match and replace" logic to replace certain strings in http responses or in the output of template rendering? How does it know it needs to change the word "Login" on the login button, but not the word "Login" in a (english) description of a finding for example?

**Comment by valentijnscholten** [comment]
BTW any non hotfix PRs should be based against `dev` as instructed in the PR template.

**Comment by epochfairy** [comment]
Or you can realize internationalization

**Pull request closed without merging**
