### PR TITLE
Add limited staff access to authorized users

### PR DESCRIPTION
**Pull request by cody-m-tibco**
An extension of #2615  to allow staff access to users authorized to a specific product. This allows for many teams to use the same instance by restricting users to the product provided to them by a true staff user. Once the product is set up, the product manager can add/remove anyone from their product as they see fit. 

@valentijnscholten @dsever

- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Review by devGregA — APPROVED** [review]

**Comment by BhaskiBuzz** [comment]
Hi @madchap @valentijnscholten could you please let me know how to provide staff access only to specific product. I am using v1.12.0. There is no option to restrict staff user to only for certain product. The user with staff access is able to view and control all the products exist in Defectdojo.

**Comment by valentijnscholten** [comment]
you can add a users authorized user and use the boolean setting to have authorized users given staff access to that product

**Comment by BhaskiBuzz** [comment]
Hi @valentijnscholten
I am not sure where is the boolean setting to have authorized users given staff access to that product.
image
As shown in the image, if I select staff checkbox, the user is getting access to all the products.

**Comment by valentijnscholten** [comment]
look for DD_AUTHORIZED_USERS_ALLOW_STAFF

**Comment by BhaskiBuzz** [comment]
Thanks @valentijnscholten

**Pull request merged**
