### PR TITLE
Issue 2720 semgrep integration

### PR DESCRIPTION
**Pull request by xee5ch**
This template is for your information. Please clear everything when submitting your pull request.

**Note: DefectDojo is now on Python3.6 and Django 2.2.x. Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ ] Your code is flake8 compliant.
- [ ] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

Moderators: Labels currently accepted for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- performance
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies
- New Migration (when the PR introduces a DB migration)
- settings_changes (when the PR introduces changes or new settings in settings.dist.py)

# Contributors: Git Tips
## Rebase on dev branch
If the dev branch has changed since you started working on it, please rebase your work after the current dev.

On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
 git mergetool
 git rebase --continue
 ```

When everything's fine on your local branch, force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

To cancel everything: 
```
git rebase --abort
```

## Squashing commits
```
git rebase -i origin/dev
```
- Replace `pick` by `fixup` on the commits you want squashed out
- Replace `pick` by `reword` on the first commit if you want to change the commit message
- Save the file and quit your editor

Force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

### CODE REVIEW

**Comment by Maffooch** [comment]
Hi @xee5ch, thank you for the contribution! Below is a great example of how we like new import scanners to be implemented. Please note the additional PR's in we require the be submitted in our sample scan and documentation repos. Let us know if you have any questions!

#2612

**Comment by xee5ch** [comment]
> Hi @xee5ch, thank you for the contribution! Below is a great example of how we like new import scanners to be implemented. Please note the additional PR's in we require the be submitted in our sample scan and documentation repos. Let us know if you have any questions!

I will definitely let you know @Maffooch. I still have it labelled as draft as I have not completed it.

I will need to spin up local test env for me to check sanity, write up tests, add docs, and add sample files. I know I need to complete tests before primetime, and I already added scan files (this is in PR DefectDojo/sample-scan-files#59). Once I remove draft tag, I will update the docs accordingly on the issue as well (it does not show link in draft state it seems) and bump the guilty parties. :-)

**Comment by xee5ch** [comment]
Given we are moving forward in #2781, I will close this for now.

**Comment by daghan** [comment]
Semgrep team member here. @xee5ch, we'd love to send you a "thank you" shirt. Can you DM me via our community slack (r2c.dev/slack)?

**Pull request closed without merging**
