### PR TITLE
Update Jira Integration docs for Jira Server

### PR DESCRIPTION
**Pull request by jefQuery**
Fixes to documentation snags I ran into while scoping or performing the Jira integration against a Jira Server instance
Done on DD v2.4.1 (in case docs are actually correct in the latest release and I should just upgrade)

### CODE REVIEW

**Comment by devGregA** [comment]
Well hello there @jefQuery ;)

**Review by devGregA — CHANGES_REQUESTED** [review]
@jefQuery  please submit changes to dev per https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by jefQuery** [comment]
Gregggg, it's been too long! Let's catch up soon

**Comment by jefQuery** [comment]
Also, sorry about the contrib mistake

**Review by mtesauro — APPROVED** [review]
Approved.

**Comment by devGregA** [comment]
no prob, happens all the time. GET _ _ _  _ _ _ _ _ !!! @jefQuery 😂

**Pull request merged**
