### PR TITLE
Remaining cherry-pick for release/1.6.0

### PR DESCRIPTION
**Pull request by madchap**
Pushing to my fork first, giving a chance to review.

### CODE REVIEW

**Comment by madchap** [comment]
Force-pushed to `reword` commit messages.

**Comment by madchap** [comment]
I am greeted with a `internal server error`, so I guess something didn't go as expected.

**Comment by madchap** [comment]
My bad, leftover `settings.py`... proceeding with more tests...

**Comment by madchap** [comment]
Seem to be getting some datatable errors, which do not impact functionality

image

**Comment by valentijnscholten** [comment]
I think there are PRs missing here.

**Comment by madchap** [comment]
Yes.. at least #2357. Pushing...

**Comment by madchap** [comment]
> Seem to be getting some datatable errors, which do not impact functionality
> 
> image

So apparently, something is off with

```
-rw-r--r-- 1 fblaise users 3057182 May 19 23:20 /home/fblaise/datatables.min.js_16
-rw-r--r-- 1 fblaise users 2187220 May 19 23:20 /home/fblaise/datatables.min.js_dev
```

Copying the `dev` js over to release, the js error is gone. Yet, #2366 which supersedes #2311 from that standpoint is in here.

**Comment by madchap** [comment]
Superseded by #2398

**Pull request closed without merging**
