### PR TITLE
Feature/jira overhaul (first pass at some JIRA updates)

### PR DESCRIPTION
**Pull request by Apipia**
# Jira Overhaul (First pass)
The changes here can be summarized into three bullets:

- Product level Push All Issues setting now does something (not sure it did before). And that something is to maintain parity of findings and JIRA issues automatically.
- Added **Push to JIRA** option to importing and re-importing scans. 
- Updated the API to contain the same logic/options.

## Push All Issues
The logic is pretty simple: If this is checked, anytime and issue that belongs to the product where this is enabled, it will push to JIRA while updating/saving this finding. The product **push all issues** help text has been updated:
image

In order to make this obvious to the user when editing/adding a finding, the checkbox for push to jira will look like this:
image
It is checked and disabled, informing the user that this will happen since the product has push all issues enabled. This was added in all of the locations I could find where one can edit a finding. Locations are:

- [x] Editing a finding
- [x] Promoting a finding
- [x] adding a finding
- [x] adding and ad-hoc finding
- [x] Bulk updating Findings (I couldn't figure out how to grey-out and check the box but it'll still push them to JIRA if you have push all issues enabled)
- [x] Importing and re-importing (Didn't use to exist here at all before)

## Import & Re-import
Form now contains push to jira checkbox
image
The rest of the logic I pretty much already covered, just wanted to show the updated form.

## API Changes
Added a push_to_jira option.
image
Endpoints changed:

- [x] Editing a finding (PUT)
- [x] Creating a new finding (POST)
- [x] Importing and re-importing
- [ ] Stub findings. (PUT/POST)

## Engagements
I noticed that there's a push to JIRA checkbox in engagements. I wasn't sure what this meant and after looking at the code it appears it's for engagement-epic mapping. I decided to make this a little more clear:
image
This will never be checked and greyed out like the others, since it technically does something entirely different.

### This is ready for review
Still need to add it stub findings and I'm still testing all of these to make sure they work appropriately. I'll need to test for a product that has push_all_issues enabled, one that doesn't, and one that doesn't have any JIRA settings enabled. 

Let me know if there are any concerns or required changes. 🤓
- Anthony

Reference: #1973

### CODE REVIEW

**Comment by valentijnscholten** [comment]
First impressions: 
- lots of work, thanks for that
- is there anyway we could have some unit / integration tests around this?
- the retrieval of the jira_conf for a project can be made a little bit more elegant I think, see `Finding.jira_conf_new()`.

```
    # newer version that can work with prefetching
    def jira_conf_new(self):
        try:
            return self.test.engagement.product.jira_pkey_set.all()[0].conf
        except:
            return None
            pass
```

You can call that method, or just only use the `self.test.engagement.product.jira_pkey_set.all()[0].conf ` part of even better `self.test.engagement.product.jira_pkey_set.first().conf`

On certain cases this will reduce the amount of quries during (re)import which we don't want to make any slower than it already is ;-)

**Comment by Apipia** [comment]
Alright I'll take a look at that!

**Comment by Apipia** [comment]
In my efforts to add functionality to the API for push to jira I became aware that using the API is not so great. Creating a finding using the POST on the finding endpoint has issues. You can easily send it information that breaks things. Might be something worth improving soon. Working on the API code in Django is very difficult to understand, I was quite lost. Take a look at the code I added in FindingCreateSeralizer, maybe there's a better way?

**Comment by Apipia** [comment]
I would appreciate some serious scrutiny on this code review. I messed with things I'm not sure I quite understood completely. Thanks @valentijnscholten for your help!

**Comment by madchap** [comment]
> is there anyway we could have some unit / integration tests around this?

It seems the 1st option would be to mock the necessary stuff with something like mockito.

Option 2: I am trying to get a free cloud jira instance, so that we could truly do serious testing.

**Comment by madchap** [comment]
We successfully got a free open-source JIRA license! :tada: 

More to come. But this definitely should be used to make JIRA tests.

**Comment by valentijnscholten** [comment]
Great! From what I remember the cloud api is different from the self-hosted api, but i'm not 100% sure.

**Comment by madchap** [comment]
@Apipia would you like to try writing tests against that jira cloud instance? If so, please PM me your email address on the OWASP Slack. Thanks :)

**Comment by Apipia** [comment]
@madchap Is this going to be blocked until there are Unit tests? Because I'm probably not going to get a chance to work on those quite as freely. The JIRA logic improvements was work related, an ask from my team, but I'm told that writing unit tests would have outside of my work time.

**Comment by madchap** [comment]
That's an odd statement from your team :-) We'd obviously prefer them, yet I don't know if at this time, given the current JIRA implementation, we'd be in a serious position to impose :)

I personally have not had a chance to test your just PR yet, which is why I have not given it an approval or even meaningful comments. Hopefully soon.

**Comment by catalinvr** [comment]
Guys, do you have any updates regarding jira integration?

**Comment by madchap** [comment]
So, I gave this a shot.

First, could you please rebase? :)

Second, I got this when I update a finding in DefectDojo. I am expecting to have the jira updated with the new stuff, but I got this in the logs:

```
uwsgi_1         | 2020-03-30T22:06:58.031027340Z [pid: 150|app: 0|req: 176/176] 172.30.1.1 () {62 vars in 1957 bytes} [Mon Mar 30 22:06:57 2020] POST /finding/1486/edit => generated 0 bytes in 255 msecs (HTTP/1.1 302) 8 headers in 403 bytes (1 switches on core 0)
celeryworker_1  | 2020-03-30T22:06:58.030951604Z Traceback (most recent call last):
celeryworker_1  | 2020-03-30T22:06:58.030956525Z   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1  | 2020-03-30T22:06:58.030960967Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2020-03-30T22:06:58.030965043Z   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celeryworker_1  | 2020-03-30T22:06:58.030968874Z     return self.run(*args, **kwargs)
celeryworker_1  | 2020-03-30T22:06:58.030972462Z TypeError: update_issue_task() missing 1 required positional argument: 'push_to_jira'
```

**Comment by madchap** [comment]
Nevermind, it was my bad... had not recompiled the celery images.. oups! Working as expected I guess than :+1: (UI side anyways)

**Comment by Apipia** [comment]
Looks like the merge-conflict I resolved (which was on a model) is causing some migration related errors. I'm not 100% how to solve this.

CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0033_remove_finding_duplicate_list, 0032_push_all_issues_help_text in dojo).
To fix them run 'python manage.py makemigrations --merge'

Should I just run that makemigrations merge command and commit/push?

**Comment by valentijnscholten** [comment]
First you need to rebase. If your own dev is equal to the official dev, you can run `git rebase origin/dev` while on your JIRA branch. Could be messy because it looks like you merged dev into your jira branch.

**Comment by Apipia** [comment]
> First you need to rebase. If your own dev is equal to the official dev, you can run `git rebase origin/dev` while on your JIRA branch. Could be messy because it looks like you merged dev into your jira branch.

Oh I thought I did that?
Alright I can try rebasing it again..

**Comment by madchap** [comment]
I just stumbled upon this, and I don't know if this is due to the PR or not, but if the product is set to to push all issues, then it is impossible to use the apiv2 endpoint `/jira_finding_mappings`. I tried only with `PATCH` right now, since I have a use-case at hand (and since nothing exists right now in dojo to edit a finding to associate a JIRA issue with an existing finding..).

What do you think @Apipia ?

**Comment by madchap** [comment]
I am having some similar issues on another instance, so I don't think it's related.

**Pull request closed without merging**
