### PR TITLE
API v2 Bash Client for CI/CD

### PR DESCRIPTION
**Pull request by wurstbrot**
Via slack, people asked me multiple times for a CI/CD example.

I do know that the quality can be enhanced, but as there is no better APIv2 client right now (as far as I know), this is a starting point.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
FYI I submitted a PR with a (basic) APIv2 version for the Python API wrapper.

**Comment by wurstbrot** [comment]
For reference: https://github.com/aaronweaver/defectdojo_api/pull/23

**Comment by devGregA** [comment]
@aaronweaver  going to leave this one for you and @mtesauro more of y'alls expertise than mine.

**Comment by aaronweaver** [comment]
@valentijnscholten @devGregA This looks fine although I'm wondering if it should be in the core branch or if we create a client repo?

**Comment by adracea** [comment]
@aaronweaver The Defect Dojo API is currently in your personal repo , maybe we should make things a bit more formal and have it moved to a repo as part of Defect Dojo ?

**Comment by aaronweaver** [comment]
@adracea That's been on my list to do!

**Comment by aaronweaver** [comment]
@wurstbrot I created a [repo](https://github.com/DefectDojo/API-v2-Bash-Client) for this and gave you rights to merge.

**Comment by wurstbrot** [comment]
@aaronweaver thank you. I pushed the initial commit.

**Pull request closed without merging**
