### PR TITLE
Benchmark v2

### PR DESCRIPTION
**Pull request by shipko**
**Description**

In this PR was improving functional of ASVS pages. 
What was improved:
1. Auto save checklist when we  check the boxes. 
2. Add missing notes for checks.
3. Improvements in design.
4. Change design in benchmark block on product page.
5. Optimize code

### CODE REVIEW

**Comment by Maffooch** [comment]
@shipko this is terrific! Love the notes section. 

I only have two nitpicky things that would be nice to haves:
- Update the currently selected level in the header when the level is changed. It think this would have to be an Ajax thing to get updated counts and percentages, so maybe not worth the effort of adding a a new endpoint just for that)
  - image
- The progress bar is a little misleading being totally colored in
- It would be really neat to display progress bars/percentage for all levels (thinking from a ciso perspective in presenting numbers to c suite)
  - image

**Comment by Maffooch** [comment]
This is crudely thrown together via the dev tools, but this is sorta what I am talking about
image

**Comment by shipko** [comment]
@Maffooch I understanded you.
But not agree with your idea.  
This is some point with my vision:
1. The currently UI is already overloaded. Your suggestion is adding more.
2. Currently progress bar is not representing currently status of asvs checking. We see "0.8% Complele", but what is complete? I changed it to three color bars. Once you will see, it will be enough to understand currently situation in project 
3. Do you think that CISO will see product page? I think with this page will be working team leads, PMs, developers and AppSec. If they will want to see metrics by some levels they can change level on asvs page. Metrics will be loaded by ajax without reload page :)

**Comment by shipko** [comment]
@Maffooch I have problem with accesslint and checks. Can you help me?

**Comment by Maffooch** [comment]
Good counterpoints. Agreed my suggestion may not be the best approach for the project.

> @Maffooch I have problem with accesslint and checks. Can you help me?

Just ricked the failing test. There a a handful of tests that fail erratically,  but are seldom due to code changes. I'll keep an eye on them until everything is passing

**Comment by shipko** [comment]
@damiencarol @mtesauro hi, guys!
Please, review my PR. I want to be sure that DD community is approving my vision and PR

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by mtesauro** [comment]
I'm good with this - wanted to give @damiencarol a chance to review it.

Since we have the 2 needed approvals, if Damien doesn't provide feedback we can always merge later.

**Pull request merged**
