### PR TITLE
User: allow superuser (no staff) to list and view users

### PR DESCRIPTION
**Pull request by kiblik**
Superuser (who is not the staff) was able to edit and delete users however he wasn't able to list and view them.

### CODE REVIEW

**Comment by kiblik** [comment]
Btw, this can happen in multiple places in DD.

**Comment by StefanFl** [comment]
@Maffooch It is slighty different, users who are not **Active** cannot login. That's the way to deactivate a users without deleting the user object.

I personally see **Staff** literally, people who are employees of the company and therefore have some more permissions than users who are not **Staff** (external users who have access to DD but are not employees). This reflects very good how DD works currently and is easy to explain. 

The new authorization is about permissions regarding products and product types. It is not designed to address the all other areas, eg. viewing/editing users or test types.

@kiblik I still don't understand your use case, why you need to have superusers that are not staff. DD works fine as long as superusers are staff as well. If we break that up, we should be consequent and check all occurrences of `user.is_staff` to see if we need to add an `or user.is_superuser`

**Comment by StefanFl** [comment]
There is a new issue to make sure superusers are staff users as well: #5271

**Comment by valentijnscholten** [comment]
This is from the offcial django docs:
image

So the staff flag controls whether a user can login to the admin site. It works like that in my instance and the demo instance:

image

If the user has no permissions, he/she can't do anything. But it does allow them login, which makes no sense. The "staff" thing has caused us nothing but confusion. And we're not the only ones if you google for "django staff admin superuser" permission for example: https://stackoverflow.com/questions/20469174/whats-the-difference-between-staff-admin-superuser-in-django

**Comment by StefanFl** [comment]
I am with you @valentijnscholten, we should get rid of the staff users. The admin portal should not be relevant for any user. In our next meeting I want to discuss a different approach, where you can give users or groups the permissions to do selected administrative tasks. The good thing is, we can use the Django permission as the backend for it.

**Comment by StefanFl** [comment]
Screenshot doesn't work for me as well

**Comment by StefanFl** [comment]
@devGregA  To be honest, I don't get what your use case is, when users can see a page where they cannot do anything. But I think we need to understand the use cases, before we can decide how to design a new solutions. Thinking of roles like "security staff" help, because it makes it clearer what these people want to do with DefectDojo.

**Comment by devGregA** [comment]
I will have to check if the pr made it in, but it was an env variable that blocked the actual URL. @Maffooch did that get submitted? @valentijnscholten  I'm confused on your statement. If a superuser is both staff and superuser they will have full access to django admin because they are superuser. Staff doesn't play a part if I understand you. You can go to django admin as staff, but have no permissions, and we don't use any of the functions in django admin (unless there is a PR I missed, which is very possible). We used to use it for the password reset form, which we've since implemented as part of the actual dojo UI.

**Comment by valentijnscholten** [comment]
Looks like we crossposted. Although we spent limited amount of time to think about "security team" roles, I think the roles we have in place are a good start for those scenario's. For example the authorization migration script migrates `staff` users into being `global owner` which means they can manage all products and permissions, but not the configuration of Defect Dojo itself. Not sure about tools, credentials, etc. So maybe we need another permission or global role. But let's not call it staff as it confuses everyone as it's a Django internal permission.

**Comment by devGregA** [comment]
@valentijnscholten Not all security people are developers. That is definitely the minority of our users, even though I would generalize and say they are more technically inclined. People get in to trouble with Dojo when we don't put in good guard rails, and choose to do any administration from django admin, which no one really should be for the intended use case of dojo.

Again, I'm not opposed to doing away with the staff status, using a different model, etc, but I do want to preserve the use case.

On intended usage, I'm not overly concerned, and I'm not opposed to your suggested solution, but specifically on intended usage, I believe our mistake was in lack of documentation. Django was created as content management system for news organizations that were 'perfectionists' and didn't want to use wordpress. The point I'm trying to get to is that specifically in regards to intended use of django, is that we are so far outside intended use, and have been since inception, that I don't think it makes sense to measure dojo against django. Has it caused confusion?  Absolutely, and we should address that. 

Regarding the django admin portal, a narrow view of staff was used because in django 1.0 managing permissions was a nightmare. So we only used the password reset form. I've provided screenshots, and tested that users with only 'staff' permission (not superuser) do not have access to django admin. They can login, like you mentioned, but they see nothing by default and have no access. Maybe you have non-standard usage around admin that gives staff extra permission? I do think we should block django admin as a default, because for the majority of users, it poses a risk in regards to bricking their instance. I understand that there maybe a usage that is beneficial, which is why we try so hard to not kill use cases, but I do think the default should be what favors the  majority of the community, which can be overwritten and still accessed by flipping the environment variable.

**Pull request closed without merging**
