### PR TITLE
Fix Bundler parser

### PR DESCRIPTION
**Pull request by manuel-sommer**
See #9024

### CODE REVIEW

**Comment by manuel-sommer** [comment]
Please review @cneill @grendel513 @Maffooch @mtesauro

**Review by Maffooch — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Comment by manuel-sommer** [comment]
@mtesauro and @grendel513 friendly reminder :-)

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Comment by manuel-sommer** [comment]
please merge @grendel513

**Pull request merged**
