### PR TITLE
Fix push close and re-open from DDJ to JIRA

### PR DESCRIPTION
**Pull request by kareem-DA**
This is a fix for updating issues in JIRA from DDJ.  On DDJ 1.6.5, when an issue is closed or re-opened, DDJ doesn't update existing JIRA issues.  This ticket will set the push_to_jira flag when an update that has a JIRA ticket changes status.  

Also included are a couple minor logging updates to log issues when DDJ tries to update a JIRA ticket and there is a problem with the update.  This change will log the event and send the response from JIRA.

This template is for your information. Please clear everything when submitting your pull request.

**Note: DefectDojo is now on Python3.5 and Django 2.2.x Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [X] Your code is flake8 compliant.
- [X] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

Current accepted labels for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- performance
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies
- New Migration

# Git Tips
## Rebase on dev branch
If the dev branch has changed since you started working on it, please rebase your work after the current dev.

On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
 git mergetool
 git rebase --continue
 ```

When everything's fine on your local branch, force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

To cancel everything: 
```
git rebase --abort
```

## Squashing commits
```
git rebase -i origin/dev
```
- Replace `pick` by `fixup` on the commits you want squashed out
- Replace `pick` by `reword` on the first commit if you want to change the commit message
- Save the file and quit your editor

Force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

### CODE REVIEW

**Comment by kareem-DA** [comment]
O.K.  I think I got this right this time.

**Comment by valentijnscholten** [comment]
When editing a finding, the user can choose whether to use `push_to_jira` or not. I am wondering if it should be the same for close finding? Or should both just automatically push?

**Comment by kareem-DA** [comment]
I would think that we would want external ticketing systems to be kept in sync with the state of findings here.  It is important for a user, who isn't paying attention to the content of this system, knows if a finding has been closed or reopened.  It a user thinks that the fixed an issue and closes a ticket, that will push from JIRA back to DDJ (if the webhook is enabled).  We look at the issue later and see that it hasn't been fix properly, the user needs to get an updated that there is still a issue, right?

**Comment by Apipia** [comment]
I think I agree with @valentijnscholten. The point of `push_all_issues` in the settings is to do this automatically no matter what. The way that all of the other actions (like editing a finding) are done by checking if `push_all_issues` is enabled at the product level and, if it isn't, use a checkbox to then determine if we push the issue. 
It's probably better to allow the users to decide how they want to implement their JIRA integration rather than force a specific workflow upon them. 

> I would think that we would want external ticketing systems to be kept in sync with the state of findings here
This is a choice we give to the users with the product-level `push_all_issues` checkbox.

**Comment by Maffooch** [comment]
+1 on the point @Apipia made.

**Comment by valentijnscholten** [comment]
does it already work with 1.6.5 if you have push_all_to_jira enabled for a product?

**Comment by Apipia** [comment]
> does it already work with 1.6.5 if you have push_all_to_jira enabled for a product?

It doesn't work for /close or /open with push_to_jira enabled. A Checkbox might be easily added to closing (since it takes you to a page where you have to supply a note) but for opening, that might be more difficult. Opening a finding doesn't take to you any intermediate view, it just takes you to the finding but now it's opened. Maybe a pop-up? ("DO you want to push to jira?") if push_all_issues isn't already enabled?

Might be more difficult that I thought to implement pushing to jira on opening/closing a finding. I guess it was never really there and it never really worked. 

Side note: If you open or close a finding by clicking "Open Finding" or "Close Finding", then edit the finding (making no changes), it will THEN update it in JIRA. since the code in the /edit view does check for jira and has a checkbox.

**Comment by kareem-DA** [comment]
O.K.  I can redo this.  How about if push_all_issues and the existing finding already has an issue in JIRA

push_all_issues_enabled = finding.test.engagement.product.jira_pkey_set.first().push_all_issues
if push_all_issues_enabled and JIRA_Issue.objects.filter(finding=finding).exists():
    finding.save(push_to_jira=True)
else:
    finding.save()

This won't fix the issue that an issue can't be updated if push_all_issues isn't already set, but at least some of the tickets will get fixed

**Comment by valentijnscholten** [comment]
I think if push all to jira is enabled, then indeed it should gets pushed to JIRA when closed or (re)opened.
Anything else probably needs either to present the user a choice, which could be another PR if you want.


> > does it already work with 1.6.5 if you have push_all_to_jira enabled for a product?
> 
> It doesn't work for /close or /open with push_to_jira enabled. A Checkbox might be easily added to closing (since it takes you to a page where you have to supply a note) but for opening, that might be more difficult. Opening a finding doesn't take to you any intermediate view, it just takes you to the finding but now it's opened. Maybe a pop-up? ("DO you want to push to jira?") if push_all_issues isn't already enabled?
> 
> Might be more difficult than I thought to implement pushing to jira on opening/closing a finding. I guess it was never really there and it never really worked.
> 
> Side note: If you open or close a finding by clicking "Open Finding" or "Close Finding", then edit the finding (making no changes), it will THEN update it in JIRA. since the code in the /edit view does check for jira and has a checkbox.

I don't follow you, does it or does it not work when push_all_to_jira is checked/enabled?

**Comment by Apipia** [comment]
image
image
When clicking either of those, is _does not_ touch JIRA in any way.

Following either of those clicks by editing the finding, making no changes, and saving it, _will then_ update the item in JIRA.

**Comment by kareem-DA** [comment]
O.K.  This time a little better thought out.  Still learning.  Not each project has a JIRA_PKey. 
Found the query for jpkey a little earlier in the code, so I am modeling after that section. Try to get the JIRA config for a finding.  If it fails, save the finding.  If it is successful. check if push_all_issues is True and there is a JIRA already created.  If so, save the finding with push to jira else save the finding.

try:
    jpkey = JIRA_PKey.objects.get(product=finding.test.engagement.product)
    if jpkey.push_all_issues and JIRA_Issue.objects.filter(finding=finding).exists():
        finding.save(push_to_jira=True)
    else:
        finding.save()   
except JIRA_PKey.DoesNotExist:
    finding.save()

**Pull request merged**
