### PR TITLE
Nessus: store only standard protocol names

### PR DESCRIPTION
**Pull request by kiblik**
Fix https://github.com/DefectDojo/django-DefectDojo/issues/5356

Parser use protocol names from `svc_name` only if it is a well-known name of the schema.
In other cases, the protocol will be `tcp` or `udp`

Note: Change was prepared only for `nessus xml`. `nessus csv`, `nessus_was xml` and `nessus_was csv` weren't changed because the example of a report is missing.

### CODE REVIEW

**Comment by Maffooch** [comment]
@kiblik please see https://github.com/DefectDojo/django-DefectDojo/tree/master/dojo/unittests/scans/nessus_was

**Comment by kiblik** [comment]
> @kiblik please see https://github.com/DefectDojo/django-DefectDojo/tree/master/dojo/unittests/scans/nessus_was

@Maffooch, I know where `nessus_was xml` example reports are. I just wanted to be sure that it will be created on the real problem from the real report. Not just an edited version based on my thoughts.

**Review by Maffooch — APPROVED** [review]
Gotcha makes sense

**Comment by valentijnscholten** [comment]
Can we try to get some example reports or do an educated guess? I think it can get quite confusing if there are too many differences between the parsing of different report formats. Looking at the code change I think it should be easy to port it to the other report formats?

**Comment by kiblik** [comment]
If "educated guess" is not too risky, I have no problem doing it and preparing a parser for `nessus_was xml`.

And what about `nessus* csv`?

**Comment by kiblik** [comment]
Result of "educated guess": Nessus WAS is for _Web Application Scanning_ so there will not be protocol other than "http" or "https"

**Comment by kiblik** [comment]
Btw, is it not a better idea to merge nessus-parser and nessus_was-parser into one? I checked differences and it looks there are only `row.get(...)` or `if '...' in row:` so there is nothing to break

**Comment by valentijnscholten** [comment]
> Btw, is it not a better idea to merge nessus-parser and nessus_was-parser into one? I checked differences and it looks there are only `row.get(...)` or `if '...' in row:` so there is nothing to break

Sounds like a good idea, although I don't know Nessus reports to well. Might be better to do in a separate PR anyway?

**Comment by kiblik** [comment]
So can we merge this PR and consolidation of `nessus*` will be done separately?

**Comment by valentijnscholten** [comment]
I guess. Can you create an issue that lists the things left to be changed/fixed?

**Comment by kiblik** [comment]
Issue created, can we merge this?

**Review by valentijnscholten — APPROVED** [review]

**Comment by valentijnscholten** [comment]
Done, thanks for you contributions @kiblik

**Pull request merged**
