### PR TITLE
add new parser - njsscan

### PR DESCRIPTION
**Pull request by ansidorov**
njsscan is a static application testing (SAST) tool that can find insecure code patterns in your node.js applications using simple pattern matcher from libsast and syntax-aware semantic code pattern search tool semgrep.

It could be found at: https://github.com/ajinabraham/njsscan

### CODE REVIEW

**Comment by damiencarol** [comment]
@ansidorov the PR is good but did you considered using the SARIF output format (`--sarif --output results.sarif `) of `njsscan`?
Adding a new parser makes us maintain it.

**Comment by ansidorov** [comment]
Am I correct in assuming that the SARIF parser is suitable for all utilities that support the sarif output format?
If so, there really isn't much point in having a separate parser.

**Comment by damiencarol** [comment]
@ansidorov you're right. it's why I focus some of my time on maintaining/improving the SARIF parser.

**Comment by ansidorov** [comment]
OK, thank you very much.
I'll close this Pull Request then. 
However, it would be nice to somehow mark additionally that for all utilities that support SARIF format this parser can be used.

**Comment by damiencarol** [comment]
@ansidorov thanks for your feedback, I will add more comments in the parser doc soon to explain that.

**Comment by StefanFl** [comment]
njsscan's output is not compliant to the SARIF specification, an issue has been opened: https://github.com/ajinabraham/njsscan/issues/76

**Pull request closed without merging**
