### PR TITLE
Add all existing finding notes to the JIRA when created

### PR DESCRIPTION
**Pull request by coheigea**
Tested locally correctly.

Fixes: https://github.com/DefectDojo/django-DefectDojo/issues/6434

### CODE REVIEW

**Review by Maffooch — CHANGES_REQUESTED** [review]
Great change! We need some unit tests here though. 

This would be a good place to add them. Be sure to read the block comment up top for use of  the VCR recording (mimics the response from the jira server)

https://github.com/DefectDojo/django-DefectDojo/blob/c101e47b294863877cd68a82d0cc60f8017b45b1/unittests/test_jira_import_and_pushing_api.py#L14-L32

**Comment by coheigea** [comment]
@Maffooch It looks like modifying test_import_with_push_to_jira_add_comment in that file to set push_to_jira=false on the initial import, then add the comment and push to JIRA, should work. However, I don't think I can add a test without:

# if you need some credentials for the Defect Dojo JIRA Cloud instance, contact one of the moderators

**Comment by coheigea** [comment]
@Maffooch @damiencarol How can we move forward with getting this merged?

**Comment by Maffooch** [comment]
@coheigea This totally slipped through the cracks. Sorry about that! I will add a test for this today.

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
