### PR TITLE
GHA: Test multiple k8s versions

### PR DESCRIPTION
**Pull request by dsever**
Added into minikube config to test k8s v.1.16.0 and  v.1.20.0

### CODE REVIEW

**Comment by madchap** [comment]
Supersedes #3934

**Comment by valentijnscholten** [comment]
I think it also fixes a bug, not just added tests?

**Review by valentijnscholten — APPROVED** [review]
we need to merge this before GHA will run the new workflow definition.

**Review by damiencarol — APPROVED** [review]

**Comment by madchap** [comment]
> we need to merge this before GHA will run the new workflow definition.

Actually, I think we should merge https://github.com/DefectDojo/django-DefectDojo/pull/3948 before, and so that we see this is safe.

**Pull request merged**
