### PR TITLE
:bug: fix semgrep severity logic #11218

### PR DESCRIPTION
**Pull request by manuel-sommer**

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by mtesauro** [comment]
Whoops, did that approval a bit early.

I'll check back to see if my haste was wasted or not :wink:

**Comment by mtesauro** [comment]
Nope. All's well

**Review by Maffooch — APPROVED** [review]

**Comment by bsterne** [comment]
Hi all, I'm the reporter of this bug. Thanks for picking this up. I don't think the logic is correct here in the PR.
https://semgrep.dev/docs/writing-rules/rule-syntax#required

> One of the following values: INFO (Low severity), WARNING (Medium severity), or ERROR (High severity). The severity key specifies how critical are the issues that a rule potentially detects. Note: Semgrep Supply Chain differs, as its rules use CVE assignments for severity. For more information, see Filters section in Semgrep Supply Chain documentation.

So there may be some additional cases to consider, but I think the full logic is something closer to:
```
    if upper_value == "ERROR":
        return "High"
    if upper_value == "WARNING":
        return "Medium"
    if upper_value == "INFO":
        return "Low"
```

Where are the tests for this? I think we should be looking at actual Semgrep reports and reasoning about the formatting of the findings there. I'm happy to work with you on this if you would like help. Thanks again.

**Review by blakeaowens — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Comment by bsterne** [comment]
@blakeaowens @cneill @mtesauro @Maffooch this PR is wrong. Is someone willing to acknowledge my comment:
https://github.com/DefectDojo/django-DefectDojo/pull/11219#issuecomment-2465815944

**Comment by manuel-sommer** [comment]
> @blakeaowens @cneill @mtesauro @Maffooch this PR is wrong. Is someone willing to acknowledge my comment: [#11219 (comment)](https://github.com/DefectDojo/django-DefectDojo/pull/11219#issuecomment-2465815944)

Hi @bsterne, did you consider the whole method in your comment? https://github.com/DefectDojo/django-DefectDojo/pull/11219/files#diff-6675ec51a8162a810df97675f8c510909e9627872f60ad527c84bd8bd3e5473dR132

**Comment by bsterne** [comment]
Yes, I did consider the whole method when I made the comment. I'm referencing the [Semgrep docs](https://semgrep.dev/docs/writing-rules/rule-syntax#required) that say:
> One of the following values: INFO (Low severity), WARNING (Medium severity), or ERROR (High severity).

In other words, Semgrep INFO maps to "Low" severity, not "Info" severity, as this PR has it. That is for [code and secrets](https://semgrep.dev/docs/kb/rules/understand-severities#semgrep-code-and-secrets) findings. 

For [supply chain findings](https://semgrep.dev/docs/kb/rules/understand-severities#semgrep-supply-chain), there are Critical, High, Medium, or Low as possible options. That's according to their docs. I'm currently looking at a set of supply chain findings (see: [semgrep-sca-results.json](https://github.com/user-attachments/files/17689726/semgrep-sca-results.json)) that have `"sca-severity": "MODERATE"`, so I think we need to pass in a different field to `convert_severity` based on what type of report it is.

**Comment by manuel-sommer** [comment]
I fixed the Info to Low mapping.

**Comment by Maffooch** [comment]
I believe this fix covers both cases and is implicitly context related (i.e. code and secret reports will not have both Info and low severities). @manuel-sommer great work here

**Pull request merged**
