### PR TITLE
:bug: date is None when importing and reimporting, issue #9712

### PR DESCRIPTION
**Pull request by manuel-sommer**
see issue #9712

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@Maffooch, it looks like this same problem applies also to other scanners. (E.g. look at Qualys Scan and import https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/qualys/monthly_pci_issue6932.csv)

**Comment by manuel-sommer** [comment]
Basically: models.DateField may not be None

**Comment by manuel-sommer** [comment]
@Maffooch, if there is not really a way to catch this fundamental problem in a more elegant way, I can also fix other parsers.

**Comment by Maffooch** [comment]
@manuel-sommer maybe this issue could be fixed in the importer rather than in every single parser? I would think it would be a simple if statement to check if the finding date field is none. If so, insert today's date

**Comment by manuel-sommer** [comment]
> @manuel-sommer maybe this issue could be fixed in the importer rather than in every single parser? I would think it would be a simple if statement to check if the finding date field is none. If so, insert today's date

Ah, I tried it differently but not yet that way. Gotta take a look to find the right place. 👀

**Comment by manuel-sommer** [comment]
Could you take a look @Maffooch ?

**Comment by Maffooch** [comment]
This looks fine generally. Tests are failing as it looks like there are instances of overwriting a date from a finding. I think you need to have the condition "if there is not a scan scan date supplied at import time, and not on supplied from the report at the parser level, then supply todays date at the importer level"

**Comment by manuel-sommer** [comment]
@Maffooch, I spent some time and looked into it, but did not figure out exactly on how to fix it. I get your point, but don't have enough time to debug it. Feel free to close this PR and fix it in a new PR.

**Pull request closed without merging**
