### PR TITLE
Add DTSA to vulnid

### PR DESCRIPTION
**Pull request by manuel-sommer**
https://security-tracker.debian.org/tracker/data/missing-epochs --> Search for DTSA

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by mtesauro** [comment]
@manuel-sommer OK, I have to ask, where are you finding all these?  None of them surprised me that they exist but I'm super curious if these are being reported by a tool you're using or if you're just searching around to find them.

Sorry, my curiosity is getting the better of me. :smile:

**Comment by manuel-sommer** [comment]
A mixture of both. Multiple of them were found through tools, so I advanced my research for future occurances of other findings.

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]
> Sorry, my curiosity is getting the better of me. 😄

I have been very curious as well 😂 you're quite the detective @manuel-sommer

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
