### PR TITLE
Findings metrics filter in product overview

### PR DESCRIPTION
**Pull request by H4ckd4ddy**
Hi,

First of all, thank you for your work, this tool seems to be more and more popular :)

We have a small problem in our workflow, we do not understand why findings metrics in the product overview take only unverified findings.

This configuration lets think that there is no active findings on this product.

We suggest displaying all active findings and using the metrics page for advanced filters.

Thanks by advance

### CODE REVIEW

**Comment by madchap** [comment]
Hi,

Please rebase your PR on the newest `dev` branch. Thanks.

**Comment by Maffooch** [comment]
Hello @H4ckd4ddy, if you wouldn't mind, could you open a new PR that is originally based off the dev branch. Basing off master and then trying to push to dev creates a super wonky commit log. Thanks!

**Comment by valentijnscholten** [comment]
Hi, can you rebase against dev? We know there are some inconsitencies in the metrics. Today we merged another improvement: #2216
Further improvements will be done in #2215 once we agree on definitions of "active", "verified", "closed", etc.

**Comment by H4ckd4ddy** [comment]
Ok, thanks, I  close this one, and open a new PR

**Pull request closed without merging**
