### PR TITLE
add license parser to trivy scan

### PR DESCRIPTION
**Pull request by abheeshtan**
**Description**

Trivy allows for license scan and the report will be provided in json format. The changes are made to parse the license report

### CODE REVIEW

**Comment by Maffooch** [comment]
Hi @abheeshtan 

Please add to the unit tests to run that new sample report. Also base your PR against the dev branch

**Comment by abheeshtan** [comment]
> Hi @abheeshtan
> 
> Please add to the unit tests to run that new sample report. Also base your PR against the dev branch

@Maffooch unit tests are added, and the PR is based against the dev branch.

**Comment by Maffooch** [comment]
```
2023-02-15T17:40:15.8633792Z [36muwsgi_1         |[0m ======================================================================
2023-02-15T17:40:15.8634108Z [36muwsgi_1         |[0m FAIL: test_license_scheme (unittests.tools.test_trivy_parser.TestTrivyParser.test_license_scheme)
2023-02-15T17:40:15.8634369Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-02-15T17:40:15.8634555Z [36muwsgi_1         |[0m Traceback (most recent call last):
2023-02-15T17:40:15.8634825Z [36muwsgi_1         |[0m   File "/app/unittests/tools/test_trivy_parser.py", line 182, in test_license_scheme
2023-02-15T17:40:15.8635036Z [36muwsgi_1         |[0m     self.assertEqual("HIGH", finding.severity)
2023-02-15T17:40:15.8635218Z [36muwsgi_1         |[0m AssertionError: 'HIGH' != 'High'
2023-02-15T17:40:15.8635342Z [36muwsgi_1         |[0m - HIGH
2023-02-15T17:40:15.8635466Z [36muwsgi_1         |[0m + High
2023-02-15T17:40:15.8635579Z [36muwsgi_1         |[0m 
2023-02-15T17:40:15.8635690Z [36muwsgi_1         |[0m 
2023-02-15T17:40:15.8635941Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-02-15T17:40:15.8636102Z [36muwsgi_1         |[0m Ran 2263 tests in 449.881s
2023-02-15T17:40:15.8636212Z [36muwsgi_1         |[0m 
2023-02-15T17:40:15.8636396Z [36muwsgi_1         |[0m FAILED (failures=1, skipped=364)
```

**Comment by gietschess** [comment]
hi @abheeshtan ,
we'd also be interested into this feature. any chances to get that test fixed?

**Review by damiencarol — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Pull request merged**
