### PR TITLE
Adding Betterscan.io as a Scan Type

### PR DESCRIPTION
**Pull request by marcinguy**
**Description**

Adding Betterscan.io as a new "Scan Type"

https://github.com/DefectDojo/django-DefectDojo/issues/7354

Used current SARIF implementation in new parser and also new file, since in the future there could be Betterscan changes

**Test results**

Use SARIF parsing, so I assume no need for test.

**Documentation**

Not needed

### CODE REVIEW

**Comment by Maffooch** [comment]
Hi @marcinguy please see the [how to write a parse guide](https://documentation.defectdojo.com/contributing/how-to-write-a-parser/) for other requirements we have for new parsers

**Comment by marcinguy** [comment]
> Hi @marcinguy please see the [how to write a parse guide](https://documentation.defectdojo.com/contributing/how-to-write-a-parser/) for other requirements we have for new parsers

@Maffooch Thank you. Will check it.

**Comment by damiencarol** [comment]
@marcinguy we already have a SARIF parser. what is the value of this new SARIF parser?

**Comment by marcinguy** [comment]
@damiencarol Hi, thank you for your message. 

I was asked for support for DefectDojo.

I can make a new format for Betterscan and it can be added here, but I also support SARIF.

The only value, I think, will be that it will be seen in DefectDojo and save me explaining that SARIF can be used for DefectDojo. I guess that was not clear to everybody.

Do you have other ideas how to add Scan Type of ”Betterscan" to DefectDojo"?

Original issue: https://github.com/DefectDojo/django-DefectDojo/issues/7354

Thanks,

**Comment by italvi** [comment]
@marcinguy why not simply add it to the Label of the SARIF importer, s.t. it will be shown in the UI? https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/sarif/parser.py#L24. Furthermore you could also adjust the Documentation https://github.com/DefectDojo/django-DefectDojo/blob/master/docs/content/en/integrations/parsers.md#sarif

**Comment by marcinguy** [comment]
@italvi Great idea. So I will modify https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/sarif/parser.py#L24 to return `return ["Betterscan.io"]`

Thanks,

**Comment by italvi** [comment]
@marcinguy I just tried it myself: You have to adjust the scan_label at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/sarif/parser.py#L21, s.t. `return ["SARIF", "Betterscan.io"]`. Then you can choose "Betterscan.io" in the import field:
image

Furthermore, if you scroll down in the import scan results site you will see: 
image

You could also add something like:
```python
def get_description_for_scan_types(self, scan_type):
        if scan_type == "Betterscan.io":
            return "Import Betterscan.io report. Currently only SARIF Format is supported."
        return "SARIF report file can be imported in SARIF format."
```

S.t. the text in the UI will not be "Betterscan.io SARIF report file can be imported in SARIF format."

**Comment by marcinguy** [comment]
@italvi Awesome. Thank you very much.

Create new PR for this change here, thought it would be the easiest way:

https://github.com/DefectDojo/django-DefectDojo/pull/7452

**Comment by Maffooch** [comment]
succeeded by #7452

**Pull request closed without merging**
