### PR TITLE
PEP8 and minor readability improvements

### PR DESCRIPTION
**Pull request by secfigo**
- [x] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by secfigo** [comment]
API for this will be added next week

**Comment by secfigo** [comment]
Thanks @maennel :) just pulled in those changes.

**Comment by secfigo** [comment]
Looks like some issue with kombu

**Comment by maennel** [comment]
Seems to be related to this bug here: https://github.com/celery/celery/issues/4748

**Comment by secfigo** [comment]
Thanks @maennel they released a 4.1.1 and it fixed the issue. 

@aaronweaver  @devGregA for your review :)

**Comment by aaronweaver** [comment]
Looks good. @devGregA Merge ok?

**Pull request merged**
