### PR TITLE
Advance ASFF report #8462

### PR DESCRIPTION
**Pull request by manuel-sommer**
**Description**
Advance the ASFF report according to the linked issue description.

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@Maffooch and @madchap please review.

**Comment by kiblik** [comment]
Isn't it easier to use this?
```python
if item.get("Remediation"):
    mitigation=item.get("Remediation").get("Recommendation").get("Text")
    references=item.get("Remediation").get("Recommendation").get("Url")
else:
    mitigation=None
    references=None
result.append(
    Finding(
        title=item.get("Title"),
        description=item.get("Description"),
        date=dateutil.parser.parse(item.get("CreatedAt")),
        mitigation=mitigation,
        references=references,
        severity=self.get_severity(item.get("Severity")),
        active=True,  # TODO manage attribute 'RecordState'
        unique_id_from_tool=item.get("Id"),
    )
)
```

**Comment by manuel-sommer** [comment]
I thought also like this, but I did not want to write "None" into the mitigation as it could be interpreted wrong from developers who fix it.

**Comment by kiblik** [comment]
> I thought also like this, but I did not want to write "None" into the mitigation as it could be interpreted wrong from developers who fix it.

In my opinion, `mitigated` and `references` are defined as `models.XXXField(..., null=True, blank=True, ...)` so they are `None` by default. But I understand where your note is going. I would like to know the opinions also other people from the community.

**Comment by manuel-sommer** [comment]
I tested it, works fine.

**Comment by manuel-sommer** [comment]
Please review @madchap, @Maffooch

**Review by damiencarol — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by manuel-sommer** [comment]
Please review @cneill

**Review by cneill — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
