### PR TITLE
fix for multi vuln ids when reimporting scans

### PR DESCRIPTION
**Pull request by hblankenship**
**Description**
[sc-5982]
Resolves https://github.com/DefectDojo/django-DefectDojo/issues/10198

To re-iterate, when reimporting scans into DefectDojo, vulnerability_ids were getting duplicated with each reimport. This fix implements the same method used by the apiv2 finding helper in the baseimporter.

**Test results**

Tested mutiple scan types to ensure vulnerability ids were still handled correctly and that duplicates were removed on reimport. This will not clear duplicate vulnerability ids until a reimport is done after this fix.

### CODE REVIEW

**Comment by kiblik** [comment]
I'm not sure that this is the best idea. If I may suggest, I would:
- Add db_mig which would drop `(finding,vuln_id)` duplicities (for inspiration: https://gist.github.com/victorono/cd9d14b013487b8b22975512225c5b4c)
- Add db constraint to avoid this situation in the future: `class Meta: constraints = [models.UniqueConstraint(fields=['finding', 'vulnerability_id'])]`
- Do not remove all existing entries related to finding but
  - Remove only unnecessary `Vulnerability_Id.objects.filter(finding=finding).exclude(vulnerability_id__in=finding.unsaved_vulnerability_ids).delete()`
  - Call DB only for the creation of new entries, outside of the for loop (to save db calls) `Vulnerability_Id.objects. bulk_create([Vulnerability_Id(finding=finding, vulnerability_id=vulnerability_id) for vulnerability_id in finding.unsaved_vulnerability_ids])`

**Comment by kiblik** [comment]
If there is an issue with duplicates during processing, I suppose `set()` might help here.
The best would be to define `unsaved_vulnerability_ids` as the `set`. But for a quick fix, at least using `bulk_create(set(...))` would remove duplicates.

**Comment by Maffooch** [comment]
This is not feedback on the approach taken here, but this function is used in other places to set the vulnerability IDs correctly. It should be used directly instead of copy/pasting code from it
https://github.com/DefectDojo/django-DefectDojo/blob/2234848f02f243b5250894fccb6fc05ccaa1bc0d/dojo/finding/helper.py#L645C5-L645C27

**Comment by hblankenship** [comment]
dropping this PR for bugfix PR

**Pull request closed without merging**
