### PR TITLE
[feat/login-form] Allowing login forms to be hidden

### PR DESCRIPTION
**Pull request by natebwangsut**
Aesthetic enhancement, when integrating with OAuth services, usually the application would redirect to external page for authentication purpose and username/password input form created a login process confusion.

- Allowing input form to be hidden (showing by default)

### CODE REVIEW

**Comment by valentijnscholten** [comment]
First thought: should there be only one setting either this one or the existing CLASSIC_AUTH_ENABLED? The latter hides the login button which should be done also if the login form is hidden?

**Comment by natebwangsut** [comment]
I had the same thought originally but say if the form can still be useful (e.g. external authentication service where it can be use with API call while a username need to be submitted?) it can be rare case but I prefer the flexibility of configuration.

For the login button with `CLASSIC_AUTH_ENABLED`, do you reckon that it should be hidden as well if the form is hidden ?

**Comment by valentijnscholten** [comment]
I was thinking the same about passing the username to IdP. Currently not happening, but maybe in the future. 
Hiding login button without form would be best.

**Comment by natebwangsut** [comment]
I've added a commit which would hide a login button if the form is disabled

**Review by valentijnscholten — APPROVED** [review]

**Review by madchap — APPROVED** [review]
Cool, thanks for the PR :-)

**Pull request merged**
