### PR TITLE
Bug Fix: Add get_object_or_404 to view_test

### PR DESCRIPTION
**Pull request by JacobMagdziarz**

### CODE REVIEW

**Comment by Maffooch** [comment]
Hello @JacobMagdziarz would you mind opening this PR from dev initially instead of rebasing from master to dev? The commit history would be really wacky otherwise!

**Comment by valentijnscholten** [comment]
yes, with a correctly submitted PR it could get merged quite fast I think.

**Comment by Maffooch** [comment]
Closing due to lack of response. A new PR would have to be made anyways with the correct base branch to cleanup commit history.

**Comment by JacobMagdziarz** [comment]
Sorry about that. I'll do a new PR from dev. Thanks.

**Pull request closed without merging**
