### PR TITLE
Update python alpine images

### PR DESCRIPTION
**Pull request by gietschess**
**Description**

Describe the feature / bug fix implemented by this PR.
* Update python alpine images to alpine3.18. With python version 3.11.4 python stopped releasing new tags for alpine3.16.
* Updated the postgres client pkg to the lastest available (15) for alpine3.18 as we're already testing with postgres16.
* Added distro to the target and django-debian dockerfile; otherwise  `DEFECT_DOJO_OS=alpine ./dc-build.sh` fails with error `target not found`

**Test results**

[django-defectdojo-integration-tests-1.log](https://github.com/DefectDojo/django-DefectDojo/files/12806361/django-defectdojo-integration-tests-1.log)

**Checklist**

This checklist is for your information.

- [X] Make sure to rebase your PR against the very latest `dev`.
- [X] Features/Changes should be submitted against the `dev`.
- [ ] Bugfixes should be submitted against the `bugfix` branch.
- [X] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [X] Your code is flake8 compliant.
- [X] Your code is python 3.11 compliant.
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by Maffooch** [comment]
@gietschess images are built each time a PR is submitted. Is this PR really necessary?

**Comment by gietschess** [comment]
Hi @Maffooch ,
there are plenty new image versions for the python alpine 3.11.x image but as long as the alpine version is fixed renovate seems not creating PRs as long as its not pushed with a `3.11.x-alpine3.16` tag again.

Otherwise maybe `3.11-alpine@sha256:...` could be used as image tag here?

**Comment by Maffooch** [comment]
I think your suggestion below is the way to go:
> Otherwise maybe 3.11-alpine@sha256:... could be used as image tag here?

This would be consistent with how the Debian images are being built:
https://github.com/DefectDojo/django-DefectDojo/blob/be2ef1a1c8c5a5def79f81f4df456b1332bc8f3f/Dockerfile.nginx-debian#L8

**Comment by mtesauro** [comment]
Closing as stale

**Pull request closed without merging**
