### PR TITLE
Merge master into release 1.6.0

### PR DESCRIPTION
**Pull request by valentijnscholten**
In the new (git flow based) branching/release model, our branches should never be behind master. At least not for a long time or for many commits.

image

Currently `dev` and also `release/1.6.0` are 62 commits behind. This PR resolves that for the `release/1.6.0` branch. After the release, the release branch will be merged to `master`, but also to `dev` as per git flow and the plantuml diagram by @madchap 

The step in this PR is only needed one-time because in the past we didn't have a clear branching/releasing model.

Does this make sense?

### CODE REVIEW

**Comment by mtesauro** [comment]
I'm for anything that gets us sync with the new branching model.  Thanks for doing this work.

**Comment by madchap** [comment]
IIUC correctly, RC is not merging back to `dev`, since anything that comes to RC comes from `dev` in the first place. This is also for the diagram depicts at https://github.com/DefectDojo/django-DefectDojo/blob/dev/BRANCHING-MODEL.md .. the dotted arrow line back to `dev` is not a "merge" line, just a "come back" line as per its comment ("release done").

**Comment by madchap** [comment]
Also, if going straight to https://github.com/DefectDojo/django-DefectDojo/compare/release/1.6.0...master?expand=1 it does seem to give the same merge results as this PR.

14 files changed for 61 commits. 

I will draft the PR directly from the 2 branches, it is probably better to do it directly across GH "local branches" than through an intermediary PR.

**Comment by valentijnscholten** [comment]
Why are you trying to recreated the PR I already did? And where I fixed merged conflicts, and fixed the yarn install, etc?

**Comment by valentijnscholten** [comment]
> IIUC correctly, RC is not merging back to `dev`, since anything that goes to RC comes from `dev` in the first place. This is what for the diagram depicts at https://github.com/DefectDojo/django-DefectDojo/blob/dev/BRANCHING-MODEL.md .. the dotted arrow line back to `dev` is not a "merge" line, just a "come back" line as per its comment ("release done").

Yeah, that was why I said I think that's not ideal. Recently we have merged some bugfixes for 1.6.0 into dev. How do we know which ones have been merged into 1.6.0? We should follow git flow and do release bugfixes on the release branch. Then merge release branch into dev.

**Comment by madchap** [comment]
> How do we know which ones have been merged into 1.6.0? We should follow git flow and do release bugfixes on the release branch. Then merge release branch into dev.

I look at the commits on a given branch to see what have been cherry-picked and relate it to what appears on the related milestone. But I think this may not be sustainable.

**Pull request merged**
