### PR TITLE
Include tags in reports

### LINKED ISSUE #1378: Include tags in reports
**Is your feature request related to a problem? Please describe**
When executing a report for an engagement, findings' tags do not show up in the reports.

**Describe the solution you'd like**
An extra column could be added to list the tags of the findings.

### PR DESCRIPTION
**Pull request by dr3dd589**
fix #1378 

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by madchap** [comment]
I haven't really looked in the report code, but I see filenames are all PDFs? (which I have yet to see as a report type? Am I missing something?)

**Comment by dr3dd589** [comment]
No, just generate the report in HTML.

**Comment by NRGLine4Sec** [comment]
@dr3dd589 Do you think it's possible to add the ability to export report as PDF as I suggest in #1299 ?

**Comment by Maffooch** [comment]
@dr3dd589 Would you be able to implement these changes across all reporting templates? When I made modifications to reports, I would filter the the directory by file name containing "report" and modify all files where applicable. Thanks in advance.

**Comment by dr3dd589** [comment]
@Maffooch done thanks! @NRGLine4Sec I can try that but as Greg said there were problems when this functionality was implemented that's why it is removed.

**Comment by Maffooch** [comment]
@dr3dd I hate to be a stickler, but the following reports need to be updated as well.
- asciidoc_report
- custom_asciidoc_report_endpoints
- custom_asciidoc_report_findings
- endpoint_pdf_report
- product_endpoint_pdf_report
- product_pdf_report
- product__type_pdf_report

**Comment by dr3dd589** [comment]
thanks again! didn't notice there is too many reports template.

**Pull request merged**
