### PR TITLE
Improve DD_DEDUPLICATION_ALGORITHM_PER_PARSER DD_HASHCODE_FIELDS_PER_SCANNER

### PR DESCRIPTION
**Pull request by Gby56**
Addressing https://github.com/DefectDojo/django-DefectDojo/issues/7867

This is improving the customization via env variables for hashcode field configurations, and deduplication algorithms, to allow for unknown scanners (not hardcoded in `settings.dist.py`)

### CODE REVIEW

**Comment by kiblik** [comment]
@Gby56, thanks for this PR.
If you are changing this, do you mind replacing `print` with `logger.info`?
It will require to add also this to the top of file:
```python
import logging
logger = logging.getLogger(__name__)
```

**Comment by Gby56** [comment]
Good idea ! Yes I thought about it before, but couldn't see it used at all in the file so I went straight for print haha

**Comment by kiblik** [comment]
> Good idea ! Yes I thought about it before, but couldn't see it used at all in the file so I went straight for print haha

It is used in the most cases in the rest of the project. I have no idea why it wasn't here.
Thank you.

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
