### PR TITLE
 Add Ability to Manage Findings Tag with Api v2

### PR DESCRIPTION
**Pull request by propersam**
#1340 

- [X] Your code is flake8 compliant 
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.

### CODE REVIEW

**Comment by propersam** [comment]
you can perform any of the following request to control finding tags:
GET
POST
DELETE

on this newly added endpoint:

*http://127.0.0.1:8080/api/v2/findings/:id/tags/*

data format to pass in for POST  or DELETE will be an array of tags:
{
"tags": ["tag1", "tag2", "tag3"]
}

**Comment by propersam** [comment]
> @propersam GET and POST work wonderfully. The DELETE function seems to be missing the data field though. It returns a 400 error for an empty tag list.

I kind of did that on purpose....

it does not seem logical to pass in an empty tag list to Delete method..

also if the tag you entered is not a part of the available tags...it return 400 error as well

**Comment by Maffooch** [comment]
That part makes sense. I didn't word that very well. The issue is there is no text box to enter the payload. All there is an ID field.

**Comment by propersam** [comment]
DELETE method receives the same data format as POST...
e.g.
{
	"tags": ["tag1", "tag2"]
}

to delete 'tag1' and 'tag2'

**Comment by propersam** [comment]
For the sake of understandable documentation there have been an update...
a new end point as been added..

http://127.0.0.1:8080/api/v2/findings/:id/remove_tags/

this endpoint cn take PUT or PATCH method..
and receive data format:

{
"tags": ["tag1", "tag2"]
}

Delete method is no more supported on *http://127.0.0.1:8080/api/v2/findings/:id/tags/* endpoint

**Pull request merged**
