### PR TITLE
Add new parser - Legitify

### PR DESCRIPTION
**Pull request by damianpr**
New parser for `Legitify` tool.

For more information, [Legitify](https://github.com/Legit-Labs/legitify)

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by damianpr** [comment]
Dear @Maffooch, @blakeaowens , @hblankenship 
I would be grateful if you could kindly review the PR. In order to move forward and get the parser out as soon as possible.

Thank you in advance

**Review by Maffooch — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Comment by mtesauro** [comment]
@damianpr If you want it sooner then 2.39.0 which would be the first week in October, you'll need to rebase this PR against the bugfix branch which has a release every week between monthly minor releases.

You've got the needed number of approvals so I wanted to check before I merged this.

**Comment by damianpr** [comment]
hi @mtesauro, I've successfully rebased the PR against the `bugfix` branch as requested. It should now be aligned with the latest changes from the `bugfix` branch. Let me know if anything else is needed before merging.
Thanks.

**Comment by mtesauro** [comment]
@damianpr Sorry, I was in a hurry and wasn't all that clear above.

What I should have said is that this PR is going against the dev brandh, I'll need you to switch that to the bugfix branch:
image

For example, here's a PR - #10840 that is going against the bugfix branch:
image

Make sense?

**Comment by Maffooch** [comment]
Rebasing is the hard part, I got the target branch update 😄

**Pull request merged**
