### PR TITLE
Checkboxes to disable checklists, questionnaires and credentials

### PR DESCRIPTION
**Pull request by StefanFl**
Checklists, questionnaires and credentials can be disabled with checkboxes in the System Settings. This makes the user interface less crowded, if these features are not used. Default is still enabled, so nothing changes for the users, until the settings are actively changed.

I sneaked in a change of a documentation URL for product members and product type members, to avoid a separate small PR.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
My first reaction would be  "shouldn't we just call them enable checklists, enable questionaires, etc.?" Enabled by default.

**Comment by StefanFl** [comment]
You are right @valentijnscholten, would be much better. I will change later in the afternoon.

**Comment by StefanFl** [comment]
All three checkboxes are named "Enable ..." now and are checked by default.

**Review by valentijnscholten — APPROVED** [review]

**Comment by valentijnscholten** [comment]
merging as is to avoid having to maintain the migration while everyone is on holiday

**Pull request merged**
