### PR TITLE
feat(unittest): Not avoid PLW1514

### PR DESCRIPTION
**Pull request by kiblik**
It might be better to fix based on recommendations - not avoid it.

### CODE REVIEW

**Comment by Maffooch** [comment]
I elected to avoid the encoding due the testing of removal of the `\00` char a few lines into the test. I wasn't sure if the attempting to encode that null char would break something, or if we wanted to the encode that the file at all

@dogboat what do you think would be the best approach here?

**Comment by dogboat** [comment]
I think this should be fine. Encodings are super weird but I tested out reading the file explicitly as utf-8 locally and it loads the chars as expected; unsaved requests get the null byte as expected, and it's stripped out/replaced where it should be. We could add something like `self.assertTrue("\x00" in finding.unsaved_response)` to each of the checks if we want to make sure that stays preserved, dunno why I didn't do that previously.

**Comment by kiblik** [comment]
> I think this should be fine. Encodings are super weird but I tested out reading the file explicitly as utf-8 locally and it loads the chars as expected; unsaved requests get the null byte as expected, and it's stripped out/replaced where it should be. We could add something like `self.assertTrue("\x00" in finding.unsaved_response)` to each of the checks if we want to make sure that stays preserved, dunno why I didn't do that previously.

I would prefer `self.assertIn("\x00", finding.unsaved_response)` (I tried to offer it in #10817 as well). But why not?

Will you prepare it or should I? As part of this PR or will you open new one?

**Review by Maffooch — APPROVED** [review]
If there `AssertIn` change has been made already as part of #10817, then I thing this one is good to go

**Review by cneill — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
