### PR TITLE
Checkmarx parser aggregation and deduplication with query id

### PR DESCRIPTION
**Pull request by jcaillon**
Hello,

The goal of this PR is to fix the aggregation mechanism for the checkmarx parser.

## Details of the issue

At the moment, when we import a checkmarx report, the deduplication mechanism can find duplicates among the findings of this report. This is explained in this issue: #3958.
However it does not make much sense to find duplicates inside a single report because the "Checkmarx Scan" already implements a way to deduplicate similar findings by aggregating them into a single finding (each individual finding description gets merged into the aggregated finding description). This happens because we use different discriminants for the hash code of the dedup algo and disciminants for the findings aggregation algo. 

In this PR the aggregation key has been updated to match the dedup key so there is no possibility to find duplicate inside a single report (findings will be correctly aggregated instead of being created and marked as duplicates). Also added an extra information to the each checkmarx findings which is the query ID used in checkmarx (put it in vuln_id_from_tool field).

So this PR does not exactlty fix the issue #3958 but instead it makes it irrelevant because it can not happen anymore (we can't have duplicate inside a single report).

I have also slightly improved the format of the description for aggregated findings so the end user can better identify each original findings that were aggregated (c.f. screenshots below).

## Reproducing the original issue

I've done the tests with the .xml pushed in the PR.

Import the report:

image

2 findings are marked as duplicate because they have the same hashcode in the dedup algo (cwe/severity/file):

image

Now if we reimport the same report:

image

## Tests with the changes

Import the report:

image

Nothing is marked as duplicated. The aggregation algo is doing its work and aggegates the 2 findings that were previouslt marked as duplicated.

This is how it looks for the CVE id 346

image

For non aggregated results we have the standard description:

image

Now reimporting the report does not cause any issues (notice the reimport counter):

image

FYI this is the same report using the **Checkmarx Scan detail** scan type:

image

with an example of a finding details:

image

All unit tests are running fine

image

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Looks like a well thought PR! I don't know enough of Checkmarx to approve, so I'll leave it for the others to review.

**Comment by Maffooch** [comment]
I love finding aggregation. Some people think it messes up the metrics though. Can you add a feature flag similar to the one used on the Qualys WAS parser? 

https://github.com/DefectDojo/django-DefectDojo/blob/1a1cf79d303046e6c21bbc2cb591058b1b875001/dojo/settings/settings.dist.py#L1295

**Comment by jcaillon** [comment]
Actually in the case of defect dojo the aggregation enable/disable is already handled through 2 different scan type:

- Checkmarx Scan will do findings aggregation
- Checkmarx Detailed Scan will not aggregate anything

The changes done will not modify the behavior of the current aggregation because it was already using title as aggregation key which is equivalent to the query ID (but the latter will be more consistant overall).

**Review by Maffooch — APPROVED** [review]
Okay great looks good!

**Comment by jcaillon** [comment]
@Maffooch after some discussions with @ptrovatelli I changed this PR a bit: the hashcode fields now remain unchanged (to avoid asking the users to rebuild hashcode for existing checkmarx tests) and instead the aggregation key has been changed to match the dedup key.
The result is the same, i.e. can't have duplicates in a single report. But now the issues that were wrongfully flagged as duplicated are now simply aggregated.
I have updated the PR description to make it more clear.

**Comment by jcaillon** [comment]
PR rebased on dev

**Review by damiencarol — APPROVED** [review]
LGTM

**Pull request merged**
