### PR TITLE
findings: add support for metadata

### PR DESCRIPTION
**Pull request by xens**
This commit adds support for metadata on findings.

This is the first PR of a series linked to https://github.com/DefectDojo/django-DefectDojo/issues/2854

### CODE REVIEW

**Comment by Maffooch** [comment]
This looks good! Are you planning a new migration for each PR in the future?

**Comment by xens** [comment]
To be honest I don't know. If there's some best-practices regarding migrations I'd be happy to follow them.

**Comment by Maffooch** [comment]
Not really a best practice, but I would rather have one migration instead of a handful of them. That would require all model changes happen in the same PR though.

**Comment by xens** [comment]
Yeah makes sense, that's also what I did for this PR packing all migrations together.

**Comment by Maffooch** [comment]
hi @xens a PR with the same number migration was merged yesterday. Can you update this one to accommodate?

**Review by valentijnscholten — APPROVED** [review]

**Comment by xens** [comment]
> hi @xens a PR with the same number migration was merged yesterday. Can you update this one to accommodate?

@Maffooch rebased and edited ! (looks like that the pipelines are timing out don't know if you can restart them ?)

**Review by Maffooch — APPROVED** [review]
Looks like it was just cached as still running, but they are all passing now. Happens to me all the time!

**Pull request merged**
