### PR TITLE
APIv2: Allow updating users and set is_superuser

### PR DESCRIPTION
**Pull request by iwalton3**
This allows updating user profiles via the API and additionally allows setting the user's superuser status.

### CODE REVIEW

**Comment by madchap** [comment]
I think you won the privilege to fix 2 flake8 issues spotted by the GH action. Thanks in advance :)

**Comment by valentijnscholten** [comment]
Thanks! If you really want to add value to the test, you'll have to check the result after the update call :-)

**Comment by iwalton3** [comment]
@valentijnscholten It looks like the class the test inherits from (RESTEndpointTest) verifies the change.

**Review by valentijnscholten — APPROVED** [review]
ah yes, forgot about that! approving.

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
