### PR TITLE
SonarQube: support multiple SQ projects for one product

### PR DESCRIPTION
**Pull request by kiblik**
# Idea

Right now, DD supports to [store multiple SQ configurations (SQ Tool Config + Project Key)](https://github.com/DefectDojo/django-DefectDojo/blob/31801d9341255915b6023ea552e6e32e920b60fc/dojo/models.py#L1539-L1550), however:
- UI allows configuring only one SQ config
- SQ parser automatically uses the only first config - Check [this](https://github.com/DefectDojo/django-DefectDojo/blob/31801d9341255915b6023ea552e6e32e920b60fc/dojo/tools/sonarqube_api/importer.py#L48), [this](https://github.com/DefectDojo/django-DefectDojo/blob/31801d9341255915b6023ea552e6e32e920b60fc/dojo/tools/sonarqube_api/updater.py#L108) or [this](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/sonarqube_api/updater_from_source.py#L33)

Usecase (which should be solved by this PR): Allow to pull results from different SQ projects in one product - one SQ project = one engagement

# Parser 

Logic of parser:
  1. No SQ Tool Config - fail (from api_client)
  2. One SQ Tool Config, No Product SQ Config - use product name as key
  3. Multiple SQ Tool Configs, No Product SQ Config - fail (from api_client)
  4. One Product SQ Config, No Project key, No selected Product SQ config - use it and use product name as key
  5. One Product SQ Config, With Project key, No selected Product SQ config - use it
  6. Multiple Product SQ Configs, No selected Product SQ config - fail (from importer)
  7. Selected Product SQ config, No Project key -  use it and use product name as key
  8. Selected Product SQ config, With Project key - use it

SQ Tool Config = URL + API-key/user+pass
Product SQ Config = Project Key + SQ Tool Config

Logic of reimport/updater: 
If Product SQ Config was used, config id is saved in test -> it will be reused in case of reimport

# DB migration

- If sb hasn't set SonarQube config until now, the first one was used by default. So we are going to "hardcode" it because the empty config is not allowed anymore
- Test will store SQ config - it will be reused during re-upload (retest)

# GUI

| What/Where | Before | After |
| --- | --- | --- |
| All Products - Add+view SQ | image | image |
| Product Tab - Add+view SQ | image | image |
| View Product - add+view SQ | image | image |
| Add/Edit Product | image | image |
| Add SQ | x | image |
| View SQ | x | image |
| Edit SQ | x | image |
| Delete SQ | x | image |
| Add/Edit/Import Test | image| image |
| View Test | image | image |
| Filter - Eng | image | image |

# API

| What/Where | After |
| --- | --- |
| Add SQ | image |
| (re)import Scan | image |
| Tests | image |

### CODE REVIEW

**Comment by kiblik** [comment]
@damiencarol, can you check this idea? If it is ok, I will fix and also add much more unittests

**Comment by devGregA** [comment]
@kiblik  I'm worried this bends the dojo model too far of a product. This is just from a cursory review, but generally products are 1 to 1 mapping for projects in other tools, wether it be sonar, checkmarx, appscan, etc. I'm wondering if it makes more sense to bump your architecture hierarchy . i.e. I **think** what you're really trying to make is a product org into a product. If you made your product a product org, that may work better for your use case.

**Comment by kiblik** [comment]
> @kiblik I'm worried this bends the dojo model too far of a product. This is just from a cursory review, but generally products are 1 to 1 mapping for projects in other tools, wether it be sonar, checkmarx, appscan, etc. I'm wondering if it makes more sense to bump your architecture hierarchy . i.e. I **think** what you're really trying to make is a product org into a product. If you made your product a product org, that may work better for your use case.

@devGregA, thanks for the feedback.
I suppose this is different case-by-case even in SonarQube. The definitions of "project", "app", "product", "repo", "portfolio", "module", ... are very unclear (check also [this](https://owasp.slack.com/archives/C2P5BA8MN/p1621615818019900?thread_ts=1621596811.018300&cid=C2P5BA8MN), it is not only my opinion). Especially in SQ (if you are using Enterprise Edition), there is [one more layer](https://docs.sonarqube.org/latest/project-administration/managing-applications/) in this terminology.
This PR doesn't break or deny 1-to-1 mapping. But in our case, it is necessary to have reports from multiple SQ projects in one DD product. Our products are split into many small repositories (with small components) mapped into many SQ projects.

**Comment by devGregA** [comment]
@kiblik agreed, we've also talked about creating nested products / product types or creating a new object, but we haven't find a perfect flexible model. Let me pull down the PR and play with it a little bit? Can you give me a couple days?

**Comment by kiblik** [comment]
> @kiblik agreed, we've also talked about creating nested products / product types or creating a new object, but we haven't find a perfect flexible model. Let me pull down the PR and play with it a little bit? Can you give me a couple days?

And can I say no? 😄 Definitely, please pull it and test it 😃

**Comment by kiblik** [comment]
Hi @devGregA, How is it going? Is it possible to approve this PR? Thanks

**Comment by devGregA** [comment]
Sorry, for the delay. Haven't forgotten about this. Need a couple more days.

Greg Anderson
DefectDojo Project Leader
***@***.***

**Comment by devGregA** [comment]
@Maffooch could you please pull test and provide feedback?

**Comment by kiblik** [comment]
I fixed also #4817

Wrong SQ Tool config:
Screenshot 2021-07-22 at 12 53 54

Right SQ Tool config:
Screenshot 2021-07-22 at 12 54 52

Wrong Product SQ config:
Screenshot 2021-07-22 at 13 21 36

Right Product SQ config:
Screenshot 2021-07-22 at 13 23 03

**Review by Maffooch — COMMENTED** [review]
This is super cool! Wonderful job.

**Review by devGregA — APPROVED** [review]

**Comment by devGregA** [comment]
@kiblik  thanks for hanging in there on this. approved and merging.

**Review by Maffooch — APPROVED** [review]

**Comment by devGregA** [comment]
Need to renumber the migration, but we'll do that. In a couple minutes

**Pull request merged**
