### PR TITLE
Remove filterwarnings for RemovedInDjango50Warning

### PR DESCRIPTION
**Pull request by kiblik**

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Comment by kiblik** [comment]
@grendel513, can I ask for approval and merge, please?

**Review by grendel513 — APPROVED** [review]

**Comment by mtesauro** [comment]
@kiblik was about to merge then looked at the conflicts. Pretty sure I know how to resolve them but figured I'd give you a chance since this is your PR :smiley:

**Comment by kiblik** [comment]
It is ready

**Comment by kiblik** [comment]
This PR removes also `warnings.filterwarnings("ignore", message="unclosed file .+")`.
It accidentally popped up back but removal was already accepted in #9498

**Pull request merged**
