### PR TITLE
Trustwaveloader

### PR DESCRIPTION
**Pull request by ekelson-bcove**
Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder

### CODE REVIEW

**Comment by nabaaron** [comment]
@ekelson-bcove This looks great, thanks for the PR. Would you happen to have a sanitized Trustwave file that I can use for testing and CI tests?

**Comment by aaronweaver** [comment]
@ekelson-bcove The files need a little pep8 work.

Found violations: dojo/forms.py
	E231 @ 247:49 - missing whitespace after ','
	W291 @ 248:51 - trailing whitespace
	W291 @ 249:57 - trailing whitespace
Found violations: dojo/tools/trustwave_csv/__init__.py
	E265 @ 1:1 - block comment should start with '# '
	W291 @ 3:23 - trailing whitespace
Found violations: dojo/tools/trustwave_csv/parser.py
	E225 @ 12:9 - missing whitespace around operator
	E231 @ 12:18 - missing whitespace after ':'
	E231 @ 13:24 - missing whitespace after ':'
	E231 @ 14:21 - missing whitespace after ':'
	E231 @ 15:23 - missing whitespace after ':'
	E231 @ 16:23 - missing whitespace after ':'
	E231 @ 17:16 - missing whitespace after ':'
	E231 @ 18:17 - missing whitespace after ':'
	E231 @ 19:21 - missing whitespace after ':'
	E231 @ 20:15 - missing whitespace after ':'
	E302 @ 23:1 - expected 2 blank lines, found 1
	E225 @ 26:18 - missing whitespace around operator
	E225 @ 30:17 - missing whitespace around operator
	E225 @ 31:21 - missing whitespace around operator
	E712 @ 54:44 - comparison to False should be 'if cond is False:' or 'if not cond:'
	E265 @ 65:9 - block comment should start with '# '
	E712 @ 66:46 - comparison to True should be 'if cond is True:' or 'if cond:'
	E225 @ 67:22 - missing whitespace around operator
	W291 @ 68:29 - trailing whitespace
	W293 @ 72:1 - blank line contains whitespace
	E302 @ 73:1 - expected 2 blank lines, found 1
	E231 @ 75:37 - missing whitespace after ':'
	E231 @ 75:49 - missing whitespace after ':'
	E231 @ 75:60 - missing whitespace after ':'
	E231 @ 75:74 - missing whitespace after ':'
	E231 @ 75:86 - missing whitespace after ':'
	E225 @ 76:22 - missing whitespace around operator
	W293 @ 77:1 - blank line contains whitespace
	E225 @ 80:26 - missing whitespace around operator
	E302 @ 84:1 - expected 2 blank lines, found 1
	W293 @ 97:1 - blank line contains whitespace
	E225 @ 98:17 - missing whitespace around operator
	W293 @ 102:1 - blank line contains whitespace
	W293 @ 103:1 - blank line contains whitespace
	W293 @ 104:1 - blank line contains whitespace
	E303 @ 105:9 - too many blank lines (3)
	W291 @ 105:29 - trailing whitespace
	E225 @ 107:24 - missing whitespace around operator
	E225 @ 108:25 - missing whitespace around operator
	E225 @ 109:28 - missing whitespace around operator
	W293 @ 110:1 - blank line contains whitespace
	E231 @ 111:22 - missing whitespace after ','
	E225 @ 113:30 - missing whitespace around operator
	E225 @ 115:41 - missing whitespace around operator
	E225 @ 116:41 - missing whitespace around operator
	E225 @ 117:42 - missing whitespace around operator
	E225 @ 118:45 - missing whitespace around operator
	E225 @ 119:39 - missing whitespace around operator
	E225 @ 123:44 - missing whitespace around operator
	E225 @ 125:40 - missing whitespace around operator
	E231 @ 126:48 - missing whitespace after ','
	E225 @ 130:43 - missing whitespace around operator
	W293 @ 131:1 - blank line contains whitespace
	W293 @ 159:1 - blank line contains whitespace
	W293 @ 167:1 - blank line contains whitespace
	W291 @ 168:26 - trailing whitespace
	W293 @ 169:1 - blank line contains whitespace
	E303 @ 171:13 - too many blank lines (2)
	W291 @ 171:36 - trailing whitespace
	W293 @ 178:1 - blank line contains whitespace
	W293 @ 180:1 - blank line contains whitespace
	W293 @ 184:1 - blank line contains whitespace
	W293 @ 186:1 - blank line contains whitespace
	E303 @ 187:9 - too many blank lines (4)
	W293 @ 189:1 - blank line contains whitespace
	W391 @ 189:1 - blank line at end of file

**Comment by ekelson-bcove** [comment]
Fixed pep8 issues and found a few print statements.  Didn't go after other code I did not alter as did not want to introduce complexity

**Comment by ekelson-bcove** [comment]
Gist with CSV template: https://gist.github.com/eik18/9f93712d2da4d2f0405712705a40cd51

**Comment by aaronweaver** [comment]
Thanks @ekelson-bcove

**Pull request merged**
