### PR TITLE
fixed encoding error(non ascii characters) in method compute_hash_cod…

### PR DESCRIPTION
**Pull request by jssnull**
…e class dojo.models.Finding

Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes should include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
I'm not familiar with encoding of strings in Python, but I assume you're creating this PR to fix some issue/problem you run into?

**Comment by devGregA** [comment]
Hmm my concern is that this maybe break folks instances who update in regards to dedupe. Let me noodle on this.

**Comment by adracea** [comment]
I'll try and test the changes this PR implies and check to see if it makes any difference from the current state of the compure_hash_code function

**Comment by jssnull** [comment]
> I'm not familiar with encoding of strings in Python, but I assume you're creating this PR to fix some issue/problem you run into?

Hi, 
for example: if we try to use this endpoint using non ascii characters like ñ in finding name:  /test/1/add_findings
it will give us this error: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)

Then we have to convert to unicode string to avoid this kind of errors.

**Comment by ptrovatelli** [comment]
@jssnull  what's your environment? I do not reproduce on docker / mysql, dev branch freshly pulled, images freshly build.  
```
docker build  -t defectdojo/defectdojo-build -f Dockerfile.build .
docker build  -t defectdojo/defectdojo-django -f Dockerfile.django .
docker build  -t defectdojo/defectdojo-nginx -f Dockerfile.nginx .
```

ñ character put in title:

special_char

**Pull request closed without merging**
