### PR TITLE
Don't copy inexistent certs folder in Dockerfile.django

### PR DESCRIPTION
**Pull request by uncycler**
When building Dockerfile.django with DOCKER_BUILDKIT=1 option in docker, the build fails with:

failed to solve with frontend dockerfile.v0: failed to build LLB: lstat /var/lib/docker/tmp/buildkit-mount548069851/certs: no such file or directory

- [X] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ ] Your code is flake8 compliant.
- [ ] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by dsever** [comment]
@uncycler I added this option intentionally, see https://github.com/DefectDojo/Documentation/blob/master/docs/social-authentication.rst#saml-20 

Idea is to enable generic way of inserting of private CA serts that are not included inside of certifi

**Comment by uncycler** [comment]
@dsever Maybe just adding a certs directory with a readme.txt. We could put it inside /docker so it don't clobber the root. What do you think?

**Comment by dsever** [comment]
You mean just to have some content, not to break the build? If yes than I can add readme.txt and some instructions to it.

**Comment by uncycler** [comment]
I update the PR to add a placeholder.

**Review by madchap — APPROVED** [review]
lgtm.

**Review by valentijnscholten — APPROVED** [review]
ah great, I was thinking about a placeholder also but didn't see the PR was already updated with that. approving..

**Pull request merged**
