### PR TITLE
Easy single-container run scripts (enhancement #1903)

### PR DESCRIPTION
**Pull request by AlexanderTyutin**
**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is flake8 compliant 
- [ ] Your code is python 3.5 compliant
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
I think it can be helpful to people to have this, it will require maintenance though.

**Comment by AlexanderTyutin** [comment]
Also prepared documentation [here](https://github.com/AlexanderTyutin/Documentation/blob/master/docs/running-in-single-container.rst)

**Comment by alles-klar** [comment]
I don't know if we really need another setup method. We already have bash, docker-compose and kubernetes/helm. For a demo we have the demosite. It will be very hard to maintain als these methods. I agree that we have so improve the documentation and maybe simplify the setup but I don't think another container solves this problem.

**Comment by madchap** [comment]
I have never had much of an issue just doing `docker-compose up`, so I am not leaning towards having an extra method either.

However, improving documentation could be it.

We're also working on having more regular and frequent releases, so it should ease the process too. I believe quite some frustration stemmed from the fact people had to use `dev`, which not everyone wants to do.

**Comment by AlexanderTyutin** [comment]
@alles-klar Maybe the demo app is cool but I see this caption for long time 
image

And this is the first reason of my tryings to get quick and ready environment to put first data and show it in my company.

The next reason is that we don't use docker-compose. And the third reason is that when we was tried to run defectDojo in local K8s we've got tons of errors in nginx and the question "why we need 5 containers if we do not have such huge amount of vulnerabilities and services" :)

But if these scripts are off-top and there is no need with them the maintainers may feel free to close the issue :) I'll put it in my github library because they are really helpful for me and my environment.

**Comment by valentijnscholten** [comment]
I am also more leaning towards improving the existing docker(-compose) setup instead of a new single container variant. Especially since the single container scripts seem to involve multiple manual steps for initializing things.

**Comment by alles-klar** [comment]
> @alles-klar Maybe the demo app is cool but I see this caption for long time

You are right, but there is a person working on it. Should be available soon. 
> 
> And this is the first reason of my tryings to get quick and ready environment to put first data and show it in my company.
> 
> The next reason is that we don't use docker-compose. And the third reason is that when we was tried to run defectDojo in local K8s we've got tons of errors in nginx and the question "why we need 5 containers if we do not have such huge amount of vulnerabilities and services" :)

Docker is designed to have one process per container. One reason for this is scalability. But I agree that it is may a bit of overhead for a simple demo. 

Did you deploy DefectDojo in K8s with the helm? Should be very straight forward. There is also a  	"KUBERNETES.md" which includes some documentation.

> 
> But if these scripts are off-top and there is no need with them the maintainers may feel free to close the issue :) I'll put it in my github library because they are really helpful for me and my environment.

Would be sad to waste your effort. Feel free to add your scripts here: https://github.com/DefectDojo/Community-Contribs

**Comment by alles-klar** [comment]
https://github.com/DefectDojo/Community-Contribs/pull/10

**Pull request closed without merging**
