### PR TITLE
Added amd64 build config for Apple Silicon

### PR DESCRIPTION
**Pull request by corrupt**
**Description**

Added a matrix dimension for the buildx platform parameter to build both amd64 and arm64 images.

**Test results**

Without Docker Hub secrets, I cannot test. But the workflow change is really straight-forward.

**Documentation**
As far as I can see there is no architecture mentioned in the docs. If anything, this will make the tutorial in `Docker.md` work on Apple Silicon.

### CODE REVIEW

**Comment by Maffooch** [comment]
Since there is no change to the image name, how will users know which platform they would be getting from docker hub? Or is docker smart enough to just figure it out? I am unsure how this works with docker

**Comment by corrupt** [comment]
> Since there is no change to the image name, how will users know which platform they would be getting from docker hub? Or is docker smart enough to just figure it out? I am unsure how this works with docker

That's the whole point. Docker will always pull the image that is compatible to your architecture unless you force it to do otherwise. Buildx will create a single manifest containing all target architectures automatically. The result will look something like this on Docker Hub.

image

**Comment by Maffooch** [comment]
Dang that is cool! Will give time for @mtesauro to look at

**Review by Maffooch — APPROVED** [review]
Did some research and this should be fine

**Review by devGregA — APPROVED** [review]

**Comment by damiencarol** [comment]
@devGregA @Maffooch I see this one has been merged but no new images in DockerHub. Did we missed something?

**Comment by corrupt** [comment]
> @devGregA @Maffooch I see this one has been merged but no new images in DockerHub. Did we missed something?

It's been merged into `dev`. I assume we'll have for it to merge into `master`.

**Comment by Maffooch** [comment]
Yes, the images are pushed to docker hub from master

Unfortunately, building on arm64 a total failure :/ I ended up reverting so the release could be completed. Details on the runs below:
https://github.com/DefectDojo/django-DefectDojo/actions/runs/4346888907

**Comment by corrupt** [comment]
That seems to be an oversight on my part. I forgot to add multi-arch builds to the debian-based images but did add them for the alpine-based ones which fail now. Does it make sense to create a new PR? I cannot test the workflow before merge. Debian images should work, alpine I'll have to investigate.

**Comment by ManAnRuck** [comment]
@corrupt did you have any updates or some issues. I'm just asking to maybe support if possible

**Pull request merged**
