### PR TITLE
fix/gitlab-container-datetime: ts parsing

### PR DESCRIPTION
**Pull request by natebwangsut**
Fix datetime parsing

- better wordings for GitLab API fuzzing + GitLab container scan

### CODE REVIEW

**Comment by natebwangsut** [comment]
@damiencarol I've discovered time parsing bug and fixed it

**Review by Maffooch — APPROVED** [review]

**Review by valentijnscholten — DISMISSED** [review]
This will brake scripts using the scan_type value in the API and also will create a duplicate entry in the Test_Type entry with the new scan_type value. So if you really want to change the scan_type value you need to include a database migration and a piece of documentation under breaking changes in the release notes.

**Comment by natebwangsut** [comment]
@valentijnscholten i'll remove the changes on wording to different PR, I'll make another PR solely for the migration changes

**Review by StefanFl — CHANGES_REQUESTED** [review]
Please add a check of the date in at least one of the unit tests.

**Comment by natebwangsut** [comment]
@StefanFl hi, I've added a unit test to check the field

**Review by StefanFl — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Comment by damiencarol** [comment]
@valentijnscholten could you take another look? the contributor have fixed your comment.

**Comment by natebwangsut** [comment]
@valentijnscholten kind reminder if you have anything to add to the PR, im willing to submit a change for it.

**Pull request merged**
