### PR TITLE
:bug: fix migration

### PR DESCRIPTION
**Pull request by manuel-sommer**
@mtesauro, @Maffooch, @dsever could you please review the PR fast? It is a fix for release v2.31.0 upcomming on monday.

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@cneill please review this PR, it is a db migration fix for v 2.31.0

**Comment by manuel-sommer** [comment]
Hotfix @mtesauro

**Comment by manuel-sommer** [comment]
@Maffooch please review this PR as it fixes a broken migration for v2.31.0 on comming Monday.

**Comment by manuel-sommer** [comment]
@mtesauro please review this Migration fix

**Comment by manuel-sommer** [comment]
@blakeaowens , could you please take a look at this fix? It is a hotfix for the Release today.

**Review by blakeaowens — APPROVED** [review]

**Comment by manuel-sommer** [comment]
@Maffooch please merge before this release.

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
