### PR TITLE
Disable not supported notifications

### PR DESCRIPTION
**Pull request by dsever**
It is misleading for a user to see an option to configure a particular type of notification even it is not supported by the system (not configured).  This PR hides from the user all types of notifications that are not allowed by the admin. 

Tests are added but still, some of them are missing:

- [x] when a particular notification is disabled

- [ ] tests for product level notifications (1/2)

- [x]  tests for system notifications

https://user-images.githubusercontent.com/7211879/147072674-59015d9a-3f99-4728-86f3-945d56e595a9.mp4

### CODE REVIEW

**Review by StefanFl — APPROVED** [review]
Great PR

**Review by damiencarol — APPROVED** [review]

**Comment by damiencarol** [comment]
@dsever it's a good work. I see you still have a task not done. Is your PR complete?

**Comment by dsever** [comment]
What do you think, do we need more tests?

**Comment by damiencarol** [comment]
It seems it's too late :D

**Pull request merged**
