### PR TITLE
Fix BulkEdit severity dropdown after #4766

### PR DESCRIPTION
**Pull request by Maffooch**
After #4766, all select fields were dynamically converted to select picker fields. It did not work so well for those that were contained within a drop down. 

Before:
https://user-images.githubusercontent.com/46459665/135797454-84f9fcdc-3046-4e63-8cc0-1b095b790490.mov

After:
https://user-images.githubusercontent.com/46459665/135798169-3f636d72-c21b-4f0a-9fa3-b91e4abf0dae.mov

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Nice, just in time. Back then I "knew" there was something with the PR, but couldn't scientifically prove it :-)

**Comment by valentijnscholten** [comment]
@Maffooch `view_test.thml` needs the same changes, that page still doesn't use the same codebase for listing findings.

**Review by valentijnscholten — COMMENTED** [review]
.

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
.

**Review by valentijnscholten — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
