### PR TITLE
Update Qualys_Infrascan_Webgui parser.py

### PR DESCRIPTION
**Pull request by tvtongerloo**
Catching "No registered hostname" as non-valid value for fqdn, falling back to IP address to be used for the endpoint; otherwise you get an endpoint called "No registered hostname" and findings are aggregated incorrectly.

Raw XML report extract example (actual public IP has been replaced with 127.0.0.1):

`<IP value="127.0.0.1" name="No registered hostname">`
`<OS><![CDATA[Linux 2.6]]></OS>`
`<INFOS>`
`<CAT value="Information gathering">`
`<INFO number="6" severity="1">`
`<TITLE><![CDATA[DNS Host Name]]></TITLE>`
`<LAST_UPDATE><![CDATA[2018-01-04T17:39:37Z]]></LAST_UPDATE>`
`<PCI_FLAG>0</PCI_FLAG>`
`<DIAGNOSIS><![CDATA[The fully qualified domain name of this host, if it was obtained from a DNS server, is displayed in the RESULT section.]]></DIAGNOSIS>`
`<CONSEQUENCE><![CDATA[N/A]]></CONSEQUENCE>`
`<SOLUTION><![CDATA[N/A]]></SOLUTION>`
`<RESULT format="table"><![CDATA[IP address Host name 127.0.0.1 No registered hostname]]></RESULT>`
`</INFO>`

### CODE REVIEW

**Review by damiencarol — CHANGES_REQUESTED** [review]
@tvtongerloo could you add some unit tests with the data you provide?
Basically, it's just:
1. add file to add in `dojo/unitests/tools/qualys_infrascan_web_gui/` folder
2. add a unit test in `dojo/unitests/tools/test_qualys_infrascan_webgui_vulnerabilities.py` that use this file and check endpoints

**Comment by valentijnscholten** [comment]
@tvtongerloo can you base your PR against `dev` please?

**Comment by damiencarol** [comment]
@tvtongerloo I added your modifications in https://github.com/DefectDojo/django-DefectDojo/pull/3907

**Comment by ptrovatelli** [comment]
the unit test data is present but the code is misssing. 

@damiencarol should we close this one in favor of https://github.com/DefectDojo/django-DefectDojo/pull/3907?

**Comment by damiencarol** [comment]
@ptrovatelli yes

**Pull request closed without merging**
