### PR TITLE
GitHub Action for kubernetes tests

### PR DESCRIPTION
**Pull request by dsever**
Github workflow for k8s helm deployment on the top of the minikube

Builds docker images
Deploying matrix of config 
Tests deployment within the k8s

### CODE REVIEW

**Comment by madchap** [comment]
Might want to rename that PR :)

**Comment by dsever** [comment]
@madchap sure, was in plan, but context shifting has done its own

**Review by valentijnscholten — APPROVED** [review]
wonderful!

**Comment by valentijnscholten** [comment]
This needs to go into master before it will work.

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
