### PR TITLE
Added Api v2 Feature For Report Generation

### PR DESCRIPTION
**Pull request by propersam**
After Trying to add Ability to generate report through Api as requested in Issue #1352 .  I discovered that this would be a very huge enhancement capability for defect-Dojo if reports can be generated in JSON format straight from Api without the GUI. So I took my time to get this done as best as I can.

When submitting a pull request, please make sure you have completed the following checklist:

- [X] Your code is flake8 compliant 
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by propersam** [comment]
To Generate a JSON Report:

You need to make a POST request.. to any of the following valid endpoints:

http://127.0.0.1:8000/api/v2/product_types/:id/generate_report/
http://127.0.0.1:8000/api/v2/products/:id/generate_report/
http://127.0.0.1:8000/api/v2/engagements/:id/generate_report/
http://127.0.0.1:8000/api/v2/endpoints/:id/generate_report/
http://127.0.0.1:8000/api/v2/tests/:id/generate_report/
http://127.0.0.1:8000/api/v2/findings/generate_report/

the Post data can receive any of the following boolean fields:
(Post data is optional default values of 'false' are already initialised)

{
"include_finding_notes":true,
"include_executive_summary": true,
"include_table_of_contents": false,
"include_finding_images": true
}

**Comment by Maffooch** [comment]
Hey @propersam I get the following errors for each of the API requests: 
KeyError at /api/v2/tests/1/generate_report/
"Got KeyError when attempting to get a value for field `engagement_name` on serializer `ExecutiveSummarySerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'engagement_name'."

**Comment by propersam** [comment]
I think I pushed a fix now....

**Comment by propersam** [comment]
it wasn't there before...came in with my last push...but it's fixed now. I also go another issue about test_environment.name.. that attribute is not always set..so it's not available for some products, engagements etc..hence causing an invalid attribute error as well...but i've put a check on that now

... all other things seem to work fine nw...

**Pull request merged**
