### PR TITLE
Update Nuclei importer maintaining backwards compatibility

### PR DESCRIPTION
**Pull request by igorgomeszup**
This update makes DefectDojo able to import the new Nuclei template format while maintaining compatibility with the previous version.

### CODE REVIEW

**Comment by StefanFl** [comment]
Hi @igorgomeszup, thank you for this PR. Please provide a unit test for the new format as well, so that we have tests for both behaviours.

**Comment by igorgomeszup** [comment]
> 

Hey @StefanFl I added the unit tests with the new format.

**Comment by StefanFl** [comment]
@igorgomeszup I have just seen your PR wants to merge the changes into `master`. Please rebase your development branch so that it will merge into `dev`

**Comment by StefanFl** [comment]
@igorgomeszup I quickly rebased it, so that we can have it in our next release on Tuesday.

**Review by StefanFl — APPROVED** [review]

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
Thanks. I think we should work with "real" reports. So 2 reports, 1 new and 1 old. The current many findings report seems created by hand? The solution would be to split the report up into 2 files.

**Comment by valentijnscholten** [comment]
@igorgomeszup I see you requested my review, but I already reviewed it (and requested changes, see above for a small request)

**Comment by StefanFl** [comment]
@igorgomeszup Can you quickly move the additional tests for the new format in a separate file or shall I do it? There will be a DefectDojo release tomorrow and it would be great to have this PR in the next release, otherwise it will be another month.

**Review by damiencarol — APPROVED** [review]

**Comment by damiencarol** [comment]
I fully agree with @valentijnscholten . Please keep real reports as much as possible. And at least split different version in different files.

**Review by damiencarol — DISMISSED** [review]
Please split new use cases in a different file.

**Comment by StefanFl** [comment]
@valentijnscholten, @damiencarol There are 2 unit tests now, one for the old format and one for the new format, please re-review.

**Comment by vulnz** [comment]
image
nuclei 2.6.1

image

**Comment by valentijnscholten** [comment]
Did you use the `dev` branch of DD? This PR is not in any release yet.

**Comment by vulnz** [comment]
thanks @valentijnscholten 
do you know approximate release date?
do you know how to update defectdojo (dockerised version)
thanks.

**Pull request merged**
