### PR TITLE
add checkmarx parser unit tests

### PR DESCRIPTION
**Pull request by ptrovatelli**
it's not covering the hot topics of the moment (deduplication, hash computing, database inserting) but it's a starter for checkmarx unit tests. 
To go further, would you advise adding some smoke tests or do you think it can be easily done with unitests? 
Thanks

### CODE REVIEW

**Comment by devGregA** [comment]
Hi @ptrovatelli, would it be possible to put the sample scans here: https://github.com/DefectDojo/sample-scan-files to keep the core code base as lean as possible?

**Comment by ptrovatelli** [comment]
@devGregA all the other unit test scan files are here with the unit tests. How can we access files from another git repo in the unit tests?

**Comment by aaronweaver** [comment]
@devGregA you ok with merging? I agree we'd rather pull for the repo but we can do that with the GSOC candidates and in the meantime have coverage for checkmarx.

**Comment by ptrovatelli** [comment]
OK, so what I can do is clone that repo in unit-tests.sh so that the scans are accessible for all tests?

**Comment by devGregA** [comment]
@aaronweaver good with merging

**Pull request merged**
