### PR TITLE
fix: Bugcrowd API Import uses legacy dedupe instead of unique id from tool

### LINKED ISSUE #8993: Bugcrowd api import does not deduplicate using unique id from tool
**Be informative**
I have implemented that API importer, but I think it was not clear how to name the keys for the `DEDUPLICATION_ALGORITHM_PER_PARSER`. 

I noticed on our defectdojo instance that findings would keep creating and the total number would explode. It's using the legacy algorithm apparently, so I figured out the fix.

**Bug description**
It's pretty self-explanatory, when using the reimporter especially, and using deduplication, the findings keep appearing even though you're just supposed to see submissions from 1 bugcrowd program 1:1.

**Steps to reproduce**
1. Create a Tool config for bugcrowd, make sure your defectdojo system config enabled deduplication
2. Configure a product to have that API config
3. Trigger a first finding import with that Bugcrowd API Import
4. Go to the engagement, and do a reimport of the test
5. Witness the number of findings climbing, and not a whole lot are marked duplicates, some are detected similar but that's it, even though their do have the unique id from tool field populated !

**Expected behavior**
Reimporting should simply keep a 1:1 mapping of what's shown in Bugcrowd submissions (with duplicate submissions removed of course, that's a sanity filter to avoid noise in Dojo)

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

Will address in a simple PR asap

### PR DESCRIPTION
**Pull request by Gby56**
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/8993 (I think, but parser name and scan type names are confusing/not aligned...)

### CODE REVIEW

**Comment by mtesauro** [comment]
@Gby56 
Thanks for the contribution. Please make PRs against the dev branch, not master.

For details see: https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by Gby56** [comment]
Woops sorry I forgot ! Done

**Review by mtesauro — APPROVED** [review]
Approved

**Review by blakeaowens — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Comment by Gby56** [comment]
Could this PR make it in 2.28.2 btw ?

**Review by Maffooch — APPROVED** [review]
Seems like a bugfix worthy PR

**Pull request merged**
