### PR TITLE
fix jira add/edit configuration

### LINKED ISSUE #3162: Editing / Adding JIRA configuration broken due to missing import
Since #3106 adding and editing JIRA configurations is broken:

```
[04/Nov/2020 09:12:14] ERROR [dojo.jira_link.views:293] name 'settings' is not defined
```
image

I think some code parts where copied from `utils.py` to other files, but the accompanying imports where not copied. 

affects `jira_link/views.py` and `tool_type/views.py`

image

### PR DESCRIPTION
**Pull request by valentijnscholten**
fixes adding / editing JIRA config which is broken in 1.9.0 and 1.9.1
fixes #3162 #3163

### CODE REVIEW

**Comment by Maffooch** [comment]
Is the workflow file intended to be changed here? Otherwise looks fine.

**Comment by valentijnscholten** [comment]
> Is the workflow file intended to be changed here? Otherwise looks fine.

good spot. I rebased, but forgot the change base branch in the PR, looks better now.

**Comment by valentijnscholten** [comment]
Added another commit to stop the JIRA setup code from swallowing exceptions.

**Review by Maffooch — APPROVED** [review]
Our hotfix is getting a little chunky ;)

**Pull request merged**
