### PR TITLE
Return dedupe to a "working" state

### PR DESCRIPTION
**Pull request by Maffooch**
**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

In response to #1478, deduplication now allows line numbers specified as 'None' to be valid, and therefore a candidate for deduplication. This is NOT a final solution, nor as a distraction or mitigation of the bigger problem. This is purely meant as a temporary method for users that are accustomed to the previous implementation.  

- [ ] Your code is flake8 compliant 
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by Maffooch** [comment]
The close_old_findings feature has been reintroduced, but does not do anything. I had never used it before axing it, so not exactly sure how it suppose to work. The original code is in the same place as before. Just needs a little makeover.

**Comment by madchap** [comment]
Didn't work in my specific case at least.

**Comment by Maffooch** [comment]
@madchap could you provide a little info as to why it’s not working? What scanner are you using? Are there any values that are not provided?

**Comment by wurstbrot** [comment]
@Maffooch while deduplication works again, close_old_finding doesn't.
See https://github.com/DefectDojo/django-DefectDojo/issues/1572

**Pull request merged**
