### PR TITLE
Fix broken documentation links in installation.md

### PR DESCRIPTION
**Pull request by savek-cc**
Fix broken documentation links

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Comment by devGregA** [comment]
I think this is broken because dev has not made it into master. These links exist in dev.

**Comment by devGregA** [comment]
Oh I see, but it breaks it in prod.... Not really sure what to do about that as it will create merge conflicts. I guess we could submit doc changes to dev and prod at the same time?

**Review by devGregA — CHANGES_REQUESTED** [review]
looking into how best to handle due to the above.

**Comment by devGregA** [comment]
I believe the solution is to switch the actions workflow to master instead of dev https://github.com/DefectDojo/django-DefectDojo/blob/master/.github/workflows/gh-pages.yml#L6. Thinking over best way to get fixed immediately.

**Comment by valentijnscholten** [comment]
Earlier we decided to build the docs from dev so we can see the latest and spot any errors on github pages. So if we change these "broken" links to point to dev, we will be fine I think.

**Review by valentijnscholten — CHANGES_REQUESTED** [review]
@savek-cc the docs are built from dev so links should best be to the dev branch. Can you update the PR?

**Comment by savek-cc** [comment]
768px-Acoustic_modem

**Pull request closed without merging**
