### PR TITLE
Reopen closed findings

### PR DESCRIPTION
**Pull request by alles-klar**
If a finding is found again, the old finding will be reopend.

On behalf of DB Systel GmbH

---

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [x] Your code is python 3.5 compliant
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [x] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by Maffooch** [comment]
@alles-klar could you correct this conflict? I don't want to break your contrib.

**Comment by valentijnscholten** [comment]
What if I were to say I like it but the best review is a testcase?

**Comment by valentijnscholten** [comment]
The reverse part of this functionality is where a finding gets closed because it is no longer present in the scan that is imported. In that case there's also a notification (alert) created. Might be best to do the same here?

Code from serializers.py:

```
                title = 'An old finding has been closed for "{}", engagement {}.' \
                        .format(test.engagement.product.name, test.engagement.name)
                url = reverse('view_finding', args=(old_finding.id, ))
                description = 'See {}'.format(old_finding.title)
                create_notification(event='other',
                                    title=title,
                                    url=url,
                                    description=description,
                                    icon='bullseye',
                                    objowner=self.context['request'].user)
```

**Comment by alles-klar** [comment]
@valentijnscholten Is there still a todo from your point of view? There is already a notice created:
```
        existing_finding.notes.create(author=existing_finding.reporter,
                                      entry="This finding has been automatically re-openend as it was found in recent scans.")
```

**Pull request merged**
