### PR TITLE
JIRA Webhook support Finding transition to Accept/False positive status

### PR DESCRIPTION
**Pull request by twsagarcia**
**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [x] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [x] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by twsagarcia** [comment]
The functionality is an extension of current webhook logic to transition the finding as Risk Accepted or False Positive according to the resolution provided in the Jira ticket. 

Resolutions that will be mapped as Accepted / False positive needs to be configured in Jira Configuration page.
image

This an addition to current logic which remains with no changes if no extra configuration is applied.

I am not sure about the procedure to update the documentation... I guess it should be updated after the PR is approved, so later on I will proceed to update the following documentation resource:
https://github.com/DefectDojo/Documentation/blob/f5d780ce8729dc79d2843136bff96b457cffa0c3/docs/features.rst

**Comment by Maffooch** [comment]
Hey @twsagarcia wanted to touch base with you. Im still working on getting a JIRA config working with DefectDojo so that this can be tested out. Didn't want you to think you were being ignored!

**Comment by twsagarcia** [comment]
@Maffooch Thanks for taking your time reviewing this. Let me know if you need some help to configure it.

**Comment by Maffooch** [comment]
Hey @twsagarcia I finally have a server capable of using the webhook. However, I'm pretty sure I am doing something wrong. I was thinking the names mapped to Accepted and False Positive would correspond to the status of the finding, but could not get anything to come out of it. Could you steer me in the right direction?

**Comment by twsagarcia** [comment]
> Hey @twsagarcia I finally have a server capable of using the webhook. However, I'm pretty sure I am doing something wrong. I was thinking the names mapped to Accepted and False Positive would correspond to the status of the finding, but could not get anything to come out of it. Could you steer me in the right direction?

Hi @Maffooch, sorry for the late reply. 

Let me explain. The names mapped to Accepted and False Positive are not related to DefectDojo. They are Jira Resolutions.
A Jira "Resolution" specifies the reason an issue is closed and it can change by configuration depending of how your Jira is configured.

I meant these fields in a Jira issue detail:
image
or:
image


I saw interesting to extend current webhook functionality to get the Jira issue resolution and according to the mapping provided in the Jira configuration within Defect Dojo, to transition the Defect Dojo Finding properly. Before this, the Finding was always transitioned to mitigated.

I hope this clarifies a bit better the intended functionality.

**Comment by Maffooch** [comment]
Hmm. Im not all that familiar with jira yet. I don't have that resolution status and couldn't find where to enable it. How did you get them?

**Comment by twsagarcia** [comment]
> 
> 
> Hmm. Im not all that familiar with jira yet. I don't have that resolution status and couldn't find where to enable it. How did you get them?

It depends on your Jira instance and/or project workflow configuration. I am not an expert but a Jira Administrador would do easily.
https://confluence.atlassian.com/adminjiraserver073/working-with-workflows-861253510.html#ConfiguringWorkflow-Addingatransition
https://confluence.atlassian.com/adminjiracloud/configuring-statuses-resolutions-and-priorities-776636333.html

When you try to close an issue, doesn't show up a popup like this?
image

**Pull request merged**
