### PR TITLE
:sparkles: advance parser docs to provide sample scan data

### PR DESCRIPTION
**Pull request by manuel-sommer**
Add Sample Scan Data section to multiple docs files.

### CODE REVIEW

**Comment by manuel-sommer** [comment]
FYI: I used a script to add all these md files. I checked also all these links with the skript that they don't return 404.

**Comment by manuel-sommer** [comment]
Hi @mtesauro , 
it would be nice if you could merge this fast, that I don't need to resolve conflicts too often if any documentation changes.

**Comment by kiblik** [comment]
For me, it looks like dots `.` at the end of sentences are breaking links.
Maybe using standard markdown `[xxx](https://xxx.xx)` might be a better idea.

**Comment by mtesauro** [comment]
Agreed about the periods (.) breaking the links but otherwise a great update to the docs.

**Comment by manuel-sommer** [comment]
Thank you for the comment @kiblik . I fixed it. 
Ready to review.

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by cneill — APPROVED** [review]
Thanks for adding these!

**Review by grendel513 — APPROVED** [review]

**Comment by mtesauro** [comment]
@manuel-sommer Mind fixing the conflict so we can merge this now that it has 4 approvals?  

Thanks!

**Review by blakeaowens — APPROVED** [review]

**Comment by manuel-sommer** [comment]
@mtesauro could you merge this? Ruff linter will be fixed in PR https://github.com/DefectDojo/django-DefectDojo/pull/9364

**Pull request merged**
