### PR TITLE
dojo/importers/importer/importer.py - Change "None" string to "Info" from cvss module when a CVSS vector string should evaluate to "Info"

### PR DESCRIPTION
**Pull request by ninp0**
**Description**

Importing the cvss module via:
```
from cvss import CVSS3
```
_and_ given a CVSS vector string such as:
```
cvss_vector_str = 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N'
```

the following severity calculation returns string values of, "None" instead of the expected string values of "Info":
```
            cvss_obj = CVSS3(cvss_vector_str)
            severities = cvss_obj.severities()
            print(severities)
             ('None', 'None', 'None')
            print(severities[0])
            'None'
            print(type(severities[0]))
            <class 'str'>
```
 
**Test results**

This is quite a small change, however, if you want me to update `unittests/test_importers_importer.py`, please provide recommendations on the preferred approach.

**Checklist**

This checklist is for your information.

- [X ] Make sure to rebase your PR against the very latest `dev`.
- [ X] Features/Changes should be submitted against the `dev`.
- [ X] Bugfixes should be submitted against the `bugfix` branch.
- [ X] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [X ] Your code is flake8 compliant.
- [ X] Your code is python 3.11 compliant.
- [X ] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by ninp0** [comment]
yeowzah - should I have submitted the PR to dev instead of bugfix?  To be transparent, I branched from dev instead of bugfix.

**Review by cneill — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by ninp0** [comment]
One more review approval - any takers? 
_/\_

**Review by grendel513 — APPROVED** [review]

**Comment by ninp0** [comment]
Thanks guys - I appreciate \o

**Pull request merged**
