### PR TITLE
Async Import: Fix group_by flag

### PR DESCRIPTION
**Pull request by Maffooch**
Add `user` kwarg to finding group assignment helper method to all for the `group_by` flag to work during async imports. The requirement for a kwarg is because the `get_current_user()` crum function does not return anything when the context is async

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by valentijnscholten** [comment]
Not sure if this will scale as every piece of code doing something with the current user is affected. Might be for now it's only this case. Is the audit log affected? Ideally the current user is passed on to a celery task when it's created. This was something I looked at in the past, something like this: https://stackoverflow.com/questions/46792488/passing-user-object-in-celery-using-django

**Comment by Maffooch** [comment]
Yeah that could be a good idea. Could be added in as kwarg. Could be added here https://github.com/DefectDojo/django-DefectDojo/blob/f9b802abb659a14b12ad83f28c5b68dead267dc4/dojo/decorators.py#L25

**Comment by Maffooch** [comment]
@valentijnscholten I added the changes to the decorator, but it required a lot more changes, I think it should be more scalable from here though as we can rely on arbitrary kwargs

**Comment by valentijnscholten** [comment]
This was not exactly what I meant, but it also works :-) Might be good enough for now.
If we wanted to make it transparent / compatible with any code running outside celery tasks, we could let tasks inherit from a base task which puts the user value into the place where `get_current_user` expects it: https://stackoverflow.com/questions/32141103/middleware-for-celery-tasks

**Pull request merged**
