### PR TITLE
Fix warning in Outpost24 parser

### PR DESCRIPTION
**Pull request by damiencarol**

### CODE REVIEW

**Comment by valentijnscholten** [comment]
what is this fixing? a warning in the log only? sounds like something for `dev` instead of `master`?

**Comment by damiencarol** [comment]
will rebase. yes it's a warning in the logs.

**Comment by mtesauro** [comment]
FWIW, this looks good to me once it's rebased to dev

**Comment by damiencarol** [comment]
switched to `dev`

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
