### PR TITLE
docker-compose fails with settings.py

### PR DESCRIPTION
**Pull request by wurstbrot**
For dev env. it is given to copy the settings.py.

I could not make it work without the copy step in docker-compose test env., too.

### CODE REVIEW

**Comment by ptrovatelli** [comment]
you're right. we hardly notice because it's enough to copy the file once, then it always works!

**Comment by ptrovatelli** [comment]
it's odd though; i'm pretty sure this was only required for dev env, due to a permission issue with the docker volume. in release mode it's done in Dockerfile.django: 
```
RUN \
  cp dojo/settings/settings.dist.py dojo/settings/settings.py
```
this needs further analysis...

**Comment by ptrovatelli** [comment]
@wurstbrot  see comments in https://github.com/DefectDojo/django-DefectDojo/pull/1473

**Comment by wurstbrot** [comment]
I do think it is required. I tried a try run
git clone
cd django...
git checkout dev
docker-compose up --build

I get the following:
```
celeryworker_1  | 
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "manage.py", line 10, in <module>
celeryworker_1  |     execute_from_command_line(sys.argv)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
celeryworker_1  |     utility.execute()
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
celeryworker_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 336, in run_from_argv
celeryworker_1  |     connections.close_all()
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 219, in close_all
celeryworker_1  |     for alias in self:
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 213, in __iter__
celeryworker_1  |     return iter(self.databases)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
celeryworker_1  |     res = instance.__dict__[self.name] = self.func(instance)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 147, in databases
celeryworker_1  |     self._databases = settings.DATABASES
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 79, in __getattr__
celeryworker_1  |     self._setup(name)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 66, in _setup
celeryworker_1  |     self._wrapped = Settings(settings_module)
celeryworker_1  |   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 157, in __init__
celeryworker_1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
celeryworker_1  |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 985, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
celeryworker_1  | ImportError: No module named 'dojo.settings.settings'
```

**Comment by ptrovatelli** [comment]
@wurstbrot  you need to remove the override link too: 
`docker-compose.override.yml`

this is fixed in https://github.com/DefectDojo/django-DefectDojo/pull/1479

**Comment by wurstbrot** [comment]
See my comment in https://github.com/DefectDojo/django-DefectDojo/pull/1479

**Comment by ptrovatelli** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/1483 should fix this

**Comment by ptrovatelli** [comment]
@wurstbrot are you OK to close this one? thanks!

**Comment by wurstbrot** [comment]
haven't tested it but I belive you ;)

**Pull request closed without merging**
