### PR TITLE
Add endpoint_status creation script

### PR DESCRIPTION
**Pull request by Maffooch**
Add an endpoint status creation script per the moderator meeting. Will be adding a note into the release draft as well.
associated [documentation](https://github.com/DefectDojo/Documentation/pull/144)

- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]

**Comment by valentijnscholten** [comment]
I suggest to merge it right now so you can add a download link to it in the documentation PR so people can start using already now even before 1.9.0 is there and without the need to clone the repo/dev branch.

**Comment by Maffooch** [comment]
Where should I add it in the documentation? In the 1.9.0 release section?

**Comment by valentijnscholten** [comment]
yeah where you added it already. bonus might be to put a warning at 1.8.0 as well that basically they should wait for 1.9.0 or run the script after every import :-)

**Comment by Maffooch** [comment]
Done!

**Pull request merged**
