### PR TITLE
SonarQube API Import: set dedup algo

### PR DESCRIPTION
**Pull request by kiblik**
DD was closing and creating the same findings because the default dedup algorithm doesn't check `file_path` and `line`

### CODE REVIEW

**Comment by damiencarol** [comment]
@kiblik thanks for this PR, we are facing this issue at my day job.

**Review by damiencarol — APPROVED** [review]

**Comment by kiblik** [comment]
I'm going to add also unittest for changing of `hash_code`

Btw, it is getting answer for [this question](https://github.com/DefectDojo/django-DefectDojo/blob/c548d60ccabdb9146c78490e05c11cb4205cd9df/dojo/unittests/test_deduplication_logic.py#L12)

**Comment by kiblik** [comment]
However, I'm still thinking about the performance impact.

**Comment by kiblik** [comment]
I'm going to split it because `hash_code`s will be more complex a questionable topic

**Review by StefanFl — APPROVED** [review]

**Comment by StefanFl** [comment]
@damiencarol Is your approval still valid?

**Comment by valentijnscholten** [comment]
recalculating hash_code will open pandora's box regarding deduplication, so we can't approve that currently.

**Comment by kiblik** [comment]
When I saw the results of unittest I realised it will open Pandora's box. Because of this, I removed the `hash_code` recalculation and I keep here only setting of dedup algo for SonarQube.

**Comment by damiencarol** [comment]
@kiblik  so could change the description also ?

**Comment by damiencarol** [comment]
@valentijnscholten I'm merging this as @kiblik removed the hashcode part.

**Pull request merged**
