### PR TITLE
Correct wording on copy text, add more places to copy

### PR DESCRIPTION
**Pull request by Maffooch**
- Correct the wording on the copy operation on engageements
- Add to the number of places that an object can be copied from

### CODE REVIEW

**Comment by StefanFl** [comment]
@Maffooch: Why is this checkbox `Done` needed?

**Comment by StefanFl** [comment]
@damiencarol see https://owasp.slack.com/archives/GQKK61742/p1658870922995239

**Comment by Maffooch** [comment]
I needed some kind of form to prevent a misclick of the copy button from actually copying anything without a second confirmation. Instead of making a new form for this specific page, I used the `DoneForm` that only has a checkbox that has a required field

**Comment by StefanFl** [comment]
> I needed some kind of form to prevent a misclick of the copy button from actually copying anything without a second confirmation. Instead of making a new form for this specific page, I used the DoneForm that only has a checkbox that has a required field

Ok

**Review by StefanFl — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
