### PR TITLE
Downgrade to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by dsever**
Downgrade ubuntu to 18.04 in GH k8s actions

### CODE REVIEW

**Comment by StefanFl** [comment]
Hi @dsever, great to see the GH actions working again. Just out of interest: Why don't we go to Ubuntu 20.04, which is also an LTS version?

**Comment by dsever** [comment]
> Hi @dsever, great to see the GH actions working again. Just out of interest: Why don't we go to Ubuntu 20.04, which is also an LTS version?

To be honest have no idea why 20.04 in combination with minikube is causing  this issues. So quick win to enable k8s deployment test is to downgrade ubuntu version for the runners

**Comment by StefanFl** [comment]
Ok, sounds good to me

**Review by StefanFl — APPROVED** [review]
Ubuntu 18.04 will get updates for another 2 years. Enough time to refine the solution.

**Pull request merged**
