### PR TITLE
Don't create two notifications when an engagement is added

### PR DESCRIPTION
**Pull request by coheigea**
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/6575

### CODE REVIEW

**Comment by Maffooch** [comment]
Where is the other notification being added?

**Comment by coheigea** [comment]
@Maffooch Here: https://github.com/DefectDojo/django-DefectDojo/blob/2.12.0/dojo/utils.py#L1747

**Review by Maffooch — APPROVED** [review]
Those signals can be real sneaky sometimes

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
