### PR TITLE
Calm the deduplication of MsDefender

### PR DESCRIPTION
**Pull request by manuel-sommer**
I removed some information in the description. This information is already described within the endpoints to calm the deduplication of MsDefender ['title', 'description']. The problem is that the description changes as soon as a client gets a new IP Address.

### CODE REVIEW

**Comment by manuel-sommer** [comment]
Retriggering the unittests:

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by grendel513** [comment]
@manuel-sommer - removing this from the description may mean the information is lost.  For example, if the endpoint is deleted (either on purpose or by mistake) the information will no longer be known - additionally, other parsers act the same way, providing as much information as possible in the description.  Just want to make sure this was considered.

**Comment by manuel-sommer** [comment]
The machineid is still present within the finding. This information does not change and stays persistent eventhough the IP addresses will change. I know that also other parsers act like this, but in this case it just causes a lot of flickering.

**Review by grendel513 — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Pull request merged**
