### PR TITLE
new parser for Coverity API

### PR DESCRIPTION
**Pull request by damiencarol**
Add a new parser and unit tests for a new parser.

This is a push upstream from our prod

https://www.synopsys.com/software-integrity/security-testing/static-analysis-sast.html

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
The code looks good to me for this one - not sure what's going on with the k8s GHA tests so you may want to get @madchap 's eye on this one also.

**Comment by damiencarol** [comment]
@mtesauro will re-launch the K8s tests

**Comment by damiencarol** [comment]
@mtesauro GHA for K8s where fixed in another PR. I rebased my branch on last dev as they where conflicts and the tests are all green now.
Ready for review.

**Comment by mtesauro** [comment]
Yup, looks good to me. :+1:

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
