### PR TITLE
docker-compose and helm: Add variables for celeryworker prefork and uwsgi thread/procs control

### PR DESCRIPTION
**Pull request by madchap**
- uwsgi: add 2 variables for processes and threads number
- celery: add variables for control over pool type and related config

The defaults remain the same as used to be.

When configured, this allows to remove some bottlenecks when using some docker-compose variant in production (e.g. boost celery for dedup operations when there are tons of findings, the default I put got me out of my misery with over half a million findings) and the uwsgi connections too, when you start to have several pipelines tackling dojo in parallel.

A bit of doc in companion PR at https://github.com/DefectDojo/Documentation/pull/125

### CODE REVIEW

**Comment by madchap** [comment]
Tested docker-compose, looks good.
Have not tested the helm stuff. @ccojocar maybe you can take a look?

**Review by ccojocar — APPROVED** [review]

**Review by ccojocar — APPROVED** [review]

**Comment by ccojocar** [comment]
LGTM

**Comment by madchap** [comment]
fyi @dsever - minor changes in the helm configmap.

**Review by valentijnscholten — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
