### PR TITLE
ASFF Parser: Respect `active` status based on `RecordState` field

### PR DESCRIPTION
**Pull request by manuel-sommer**

### CODE REVIEW

**Review by cneill — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Why is Kubernetes Deployment failing?

**Comment by mtesauro** [comment]
That PostgresHA test has been super flakey of late - not sure why as well.

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by devGregA — APPROVED** [review]

**Comment by manuel-sommer** [comment]
@devGregA could you please merge this?

**Pull request merged**
