### PR TITLE
feat(clair parser): parse component name and version

### PR DESCRIPTION
**Pull request by alles-klar**
On behalf of DB Systel GmbH

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]
LGTM

**Comment by valentijnscholten** [comment]
are these fields always present, or do they need a safer way to read them from the dict?

**Comment by damiencarol** [comment]
@valentijnscholten @madchap As I understand how Clair works, it's how the tool works. First it detect the component+version, second, it check with vuln data to produce a finding. You can't have a finding without a component.
For me this pull request is a must have. Users of Clair will see as normal to see component in the UI.

**Comment by madchap** [comment]
Yea, seems it's ok.

https://github.com/arminc/clair-scanner/blob/master/clair.go#L18-L20 and https://github.com/arminc/clair-scanner/blob/master/clair.go#L93

**Review by madchap — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]
Thanks. Would be nice if we could update more parsers to set these fields.

**Comment by damiencarol** [comment]
I will take a look @valentijnscholten

**Pull request merged**
