### PR TITLE
feat(GHA): Add SHA pinning

### PR DESCRIPTION
**Pull request by kiblik**
Official documentation recommends SHA pinning: https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Also, renovate [supports this syntax](https://docs.renovatebot.com/modules/manager/github-actions/).

### CODE REVIEW

**Comment by mtesauro** [comment]
This makes total sense to me :+1:

**Review by mtesauro — APPROVED** [review]
Approved

**Review by blakeaowens — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Review by cneill — APPROVED** [review]
From Renovate's documentation, it's not clear to me if it will automatically bump e.g. `v4.4.3` to `v4.4.4` or if it stays pinned to that specific tag forever, only updating the SHA underpinning that tag changes. If it's the latter, it might make sense to pin to e.g. `# v4` instead of `# v4.4.3`.

Since this is definitely an improvement either way, I'm okay to approve and we can keep an eye on it to see how it behaves.

**Comment by kiblik** [comment]
@cneill, it looks like versions are not locked https://github.com/DefectDojo/django-DefectDojo/pull/11410/
So we are good :)

**Comment by cneill** [comment]
> @cneill, it looks like versions are not locked #11410 So we are good :)

Excellent!

**Pull request merged**
