### PR TITLE
:hammer: restructure json in scout suite unittests

### PR DESCRIPTION
**Pull request by manuel-sommer**

### CODE REVIEW

**Comment by cneill** [comment]
While you're tidying up these files, could you also rename them to `.json` instead of `.js`?

**Comment by manuel-sommer** [comment]
> While you're tidying up these files, could you also rename them to `.json` instead of `.js`?

The problem is then, that it looks like the content itself is invalid due to the first line `scoutsuite_results =` as it doesn't follow the json standard. Shall I do it nevertheless?

**Comment by cneill** [comment]
> > While you're tidying up these files, could you also rename them to `.json` instead of `.js`?
> 
> The problem is then, that it looks like the content itself is invalid due to the first line `scoutsuite_results =` as it doesn't follow the json standard. Shall I do it nevertheless?

Apologies, I missed that bit in the big diff and didn't realize the parser was referencing a JS file produced as part of an HTML report.

**Review by cneill — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
