### PR TITLE
Enhance Kubescape parser

### PR DESCRIPTION
**Pull request by a-ruff**
**Description**

This Pull Request introduces several key enhancements to the kubescape parser, aiming to fix current issues such as : 
- Deduplication is not working.
- Findings are being created even if no issues is detected by the scanner.

Feel free to provide any suggestions or feedback for further improvements; If any part of the code is unclear, I can add explanatory comments or even rewrite sections for better clarity and understanding.

Key Changes :

1. Do not create a finding for "passed" controls

- In current Kubescape json output format an attribute indicate for each control if the control "passed" or "failed". If the control has failed that indicate an insecure misconfiguration. In my opinion, we should only create a DefectDojo finding when a control has failed.
- Nevertheless, I have noticed from the test file that the old format ("/scans/kubescape/many_findings.json") doens't contains the status for each control. Therefore for retro compatibility, I have added a condition to still create the finding if control["status"]["status"] doesn't exist.
- Other test files have the status attribute. As a result, "/scans/kubescape/with_a_failure.json" now create 3 findings because 3 controls have failed, and "/scans/kubescape/results.json" doesn't create any finding because all control have passed.

2. Richer finding title.

- The parser now constructs the title using a combination of resource ID, and the name of the failing control. Example : `Ensure Memory Limits Are Set - Pod Pod1`.

3. Detailed vulnerability description.

- The parser now creates a more readable description about each vulnerability, including category, and a link to the full details of the failing control.
- If available, the parser will parse the mitigation and the detailed description from the uploaded report.

4. Shifting rules and vulnerable resource json objects to step-to-reproduct section.

- This output is very verbose so I'm moving it from the description to the step-to-reproduce section. Let me know if you think it should be deleted instead.

5. Better severity definition

- Severity is now mapped from the scoreFactor attribute of each control instead of using the severity of the first "prioritizedResource" which was less consistent. 

6. A Deduplication algorithm configured and working

- The parser was using legacy deduplication algorithm which was not working because the field "file_path" or the endpoint was not set.
- I have configured the parser to use DEDUPE_ALGO_HASH_CODE with title and component_name as hash fields.

6. Updated tests 

- The test class "TestOrtParser" has been renamed to "TestKubescapeParser". 
- The test result for samples "/scans/kubescape/with_a_failure.json" and "/scans/kubescape/results.json" have been updated. Indeed, the parser is now creating findings when the result of a control is "failed", so the number of findings has decreased.

**Screenshots**

Screenshot 2024-06-10 at 14 46 00
Screenshot 2024-06-10 at 14 46 15
Screenshot 2024-06-10 at 14 46 19
Screenshot 2024-06-10 at 14 46 33
Screenshot 2024-06-10 at 14 46 43

**Test results**

```
System check identified no issues (0 silenced).
test_parse_file_has_many_findings (unittests.tools.test_kubescape_parser.TestKubescapeParser.test_parse_file_has_many_findings) ... ok
test_parse_file_has_many_results (unittests.tools.test_kubescape_parser.TestKubescapeParser.test_parse_file_has_many_results) ... ok
test_parse_file_with_a_failure (unittests.tools.test_kubescape_parser.TestKubescapeParser.test_parse_file_with_a_failure) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.950s

OK
```

**Documentation**

Please update any documentation when needed in the [documentation folder](https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs))

**Checklist**

This checklist is for your information.

- [x] Make sure to rebase your PR against the very latest `dev`.
- [x] Features/Changes should be submitted against the `dev`.
- [x] Bugfixes should be submitted against the `bugfix` branch.
- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.11 compliant.
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [x] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [x] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by mtesauro** [comment]
@a-ruff I haven't looked at the code changes since this is still in draft but, based on the description, this should like a great improvement to this parser. I'm looking forward to this coming out of draft status :+1:

**Comment by mtesauro** [comment]
I did notice that you changes settings.dist.py - please look the comment at the top of that file as that can help you avoid GH Action test failures:

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L8

**Comment by a-ruff** [comment]
Thank you for your feedback @mtesauro. I have updated the checksum. This PR is ready for review!

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Comment by a-ruff** [comment]
The check "Detect Merge Conflicts" was failing. Following [rebase instructions](https://github.com/DefectDojo/django-DefectDojo/blob/76e11c21e88fb84b67b6da27c78fbbe1899e7e78/.github/pull_request_template.md?plain=1#L51) resolved the issue. I have also updated the setting check-sum again.

**Comment by mtesauro** [comment]
@a-ruff I re-kicked that test and it's now passing - that's one from Github that fails from time to time for no reason that I can figure out.

Anyway, you're tests are good now :+1:

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
