### PR TITLE
WIP: Notification profile

### PR DESCRIPTION
**Pull request by dsever**
https://user-images.githubusercontent.com/7211879/151444224-31c9fc3c-1925-4f23-b85e-349a7a42fad4.mp4

It implements single template for notifications that is applied automatically during the user creation (GUI only)

@StefanFl can you please take a look...do you have better idea how to do it?

TODO:

- [x] API support
- [x] adapt unittest
- [x] integrations tests

### CODE REVIEW

**Review by StefanFl — CHANGES_REQUESTED** [review]
Just a small comment, the rest is great.

**Comment by StefanFl** [comment]
@dsever Is this PR still a draft or ready for review?

**Comment by dsever** [comment]
> @dsever Is this PR still a draft or ready for review?

sorry @StefanFl  now i see the comment, it is still draft. I still have tests to fix, and introduce new tests for  API calls

**Comment by dsever** [comment]
@StefanFl I think it is ready.

**Review by Maffooch — APPROVED** [review]
Looks pretty solid to me

**Comment by StefanFl** [comment]
I will have a look at it as soon as possible

**Review by StefanFl — APPROVED** [review]
Looks good to me, great work @dsever

**Pull request merged**
