### PR TITLE
Fix Typo and duplicate code error 

### PR DESCRIPTION
**Pull request by ankit2001**
This PR aims to resolve issues #3991 and #4052.

I have fixed the typo in models.py and duplicate code in a_counts, earlier there were 2 elif having same conditions due to that total value for a_count was always zero. I have changed it according to the condition.

@damiencarol  please review the PR and suggest me changes.
Thanks.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Thanks for the PR. I think this should be based against dev. In dev the typo is already fixed I believe.

**Comment by ankit2001** [comment]
Thanks @valentijnscholten  for the review. I was just trying to fix the issues #4052 , and #3991, which are labeled as issues in the repo . I have fixed duplicate code also with typo part.

**Comment by valentijnscholten** [comment]
Yes, that's good. But you should create a branch from `dev` in your repo and use that to create a PR against the `dev` branch in this repo. Your current PR here is based off `master`.

**Comment by ankit2001** [comment]
Ohh sorry , i didn't go through the branching model. Thanks for the link.
I have done the required changes. Now you can review the PR @valentijnscholten .

**Review by valentijnscholten — APPROVED** [review]
No problem, thanks for the PR!

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
