### PR TITLE
Finding hot edit

### PR DESCRIPTION
**Pull request by Sh1nZ0u**
Description

Add hot actions on finding_view page - some buttons for status change. All buttons update status and page using ajax.
Add localization to finding_view.html

Before
before

After
after

ajax_update

### CODE REVIEW

**Comment by Maffooch** [comment]
hi @Sh1nZ0u 
Thank you for the contribution! I am a little weary of this feature due to the ease of accidental status changes. A secondary confirmation message is not too much different than the actions already found in the drop down or editing the finding directly though. I am not sure of the best approach here

**Comment by shipko** [comment]
@Maffooch @Sh1nZ0u hi!
Thanks for this PR. 
Sorry @Maffooch but I don't agree with you. The current UX of handling found bugs is quite complex and requires a lot of overhead. In my experience, my colleagues have complained about just that. I see that this functionality speeds up this rather routine activity. Of course, I am not the maintainer of this project, but it seems to me that such functionality is necessary here

**Comment by damiencarol** [comment]
> hi @Sh1nZ0u Thank you for the contribution! I am a little weary of this feature due to the ease of accidental status changes. A secondary confirmation message is not too much different than the actions already found in the drop down or editing the finding directly though. I am not sure of the best approach here

I backup this comment, people will click too fast on these buttons.

**Comment by Maffooch** [comment]
Maybe putting those hot actions in this drop down menu would accommodate both concerns?
image

**Comment by Maffooch** [comment]
Thanks again for your contribution! Unfortunately, we are closing as this is not in line with the style and flow of other operations in DefectDojo

**Pull request closed without merging**
