### PR TITLE
README: add wishlist

### PR DESCRIPTION
**Pull request by valentijnscholten**

### CODE REVIEW

**Comment by madchap** [comment]
I am not convinced. I think we should possibly give users the option to thumb things up or down and such, even without talking about promising anything.

**Comment by valentijnscholten** [comment]
It's all nice all those ideas for voting etc, but we will never have time for those. This wishlist is not meant as a way for users to submit their wishes, they can use github issues for that. It's meant as a way for the team to show what we think / wish for to be implemented. But I'm open to alternatives, as long as it's not something we will never be able to maintain.

**Review by Maffooch — COMMENTED** [review]
I think this a good idea! It might be a good idea to include something like "these items are nothing more than thoughts and wishes. However, we encourage contributors to propose design plans for current wishes or new ones"

Something like that but more elegant

**Comment by valentijnscholten** [comment]
Elegant is not compatible with me, so feel free to commit something to this PR.

**Comment by devGregA** [comment]
I think this is a good edition, but I'm not sure the readme is the right place. Maybe we consider publishing a rough roadmap?

**Comment by valentijnscholten** [comment]
there is a rough roadmap also in the README since a few weeks.

**Review by madchap — APPROVED** [review]
Let's push it for now, does not hurt.

**Pull request merged**
