### PR TITLE
API-bugfix: Endpoint_status - do not fail if date is missing

### PR DESCRIPTION
**Pull request by kiblik**
Fix for #7336

### CODE REVIEW

**Comment by Maffooch** [comment]
@kiblik I am going to base this against the bug fix branch so it can go into the bug release on Monday

**Comment by kiblik** [comment]
> @kiblik I am going to base this against the bug fix branch so it can go into the bug release on Monday

@Maffooch, should I rebase it from `bugfix` branch?

**Comment by Maffooch** [comment]
Yes

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
