### PR TITLE
HCL AppScan on Cloud SAST results parser

### PR DESCRIPTION
**Pull request by xpert98**
## :warning: Note on feature completeness :warning:

We are narrowing the scope of acceptable enhancements to DefectDojo in preparation for v3. Learn more here:
https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Description**
New parser for HCL AppScan on Cloud SAST results.

**Test results**
Unit tests (and samples) added.  Tests pass.

**Documentation**
Documentation file added

**Checklist**

This checklist is for your information.

- [X] Make sure to rebase your PR against the very latest `dev`.
- [X] Features/Changes should be submitted against the `dev`.
- [ ] Bugfixes should be submitted against the `bugfix` branch.
- [X] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [X] Your code is flake8 compliant.
- [X] Your code is python 3.11 compliant.
- [X] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [X] Add applicable tests to the unit tests.
- [X] Add the proper label to categorize your PR.

**Extra information**

### CODE REVIEW

**Comment by manuel-sommer** [comment]
#11162

**Comment by mtesauro** [comment]
@xpert98 Thanks for the parser contribution.

I've kicked off the GH action tests to see how those go but you'll definitely need to fix the ruff linter issues before we'll start reviewing this PR.

**Comment by xpert98** [comment]
Updates implemented based on the linter results.

**Comment by mtesauro** [comment]
@xpert98 Thanks for fixing the ruff issues.

I just re-kicked off the tests - wait till those finish and, assuming they're green, you'll just need to fix the merge conflicts.

Nice work so far... :+1:

**Comment by xpert98** [comment]
Should settings.dist.py be left out of the commit in order to pass the test?

**Comment by xpert98** [comment]
@mtesauro Any advice on how to proceed?  It appears to me like the rest framework unit test failure is unrelated to my parser (but happy to make any adjustments if it is related)

**Comment by kiblik** [comment]
Hi @xpert98
- Regarding unit test, can you try to rebase (or merge from dev)? It really looks irrelevant but you never know.
- Regarding `settings.dist.py`. The edit of this file is correct and it can be performed in PR. But the hash needs to be recalculated with every edit of this file (merge/rebase from `dev` might require recalculation as well - if the file was edited in the meantime)

**Pull request closed without merging**
