### PR TITLE
:bug: reset description in progpilot after each finding

### PR DESCRIPTION
**Pull request by manuel-sommer**
see discussion in https://github.com/DefectDojo/django-DefectDojo/issues/10044

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Comment by manuel-sommer** [comment]
ah, lol. Thank you for the commit @cneill, you are right.

**Comment by nAgga3** [comment]
Would it be possible to approve the bug fix?

**Review by blakeaowens — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Comment by nAgga3** [comment]
Good morning, @manuel-sommer unfortunately the fix does not resolve the parser issue. Unfortunately, the same behavior continues to occur that when there is a vulnerability of the "Security Misconfiguration" type, information from the previous vulnerability is brought and that when there are multiple vulnerabilities of the "Security Misconfiguration" type, it only brings information from a single one.

Sorry for my insistence

**Comment by manuel-sommer** [comment]
Hi @nAgga3 , did you test the latest version (2.34.4)?
I checked the code and did not see any inconsistencies. Please be more specific, e.g. make screenshots or upload a sample file. To me, this is fixed.

**Pull request merged**
