### PR TITLE
Remove unused setup.py

### PR DESCRIPTION
**Pull request by madchap**
As discussed in the last maintainer meeting, this file seems to be superfluous. We're not building any `defectdojo`  package either.

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]

**Comment by valentijnscholten** [comment]
`setup.py` is still used by the setup.bash install method, I thought we decided that should all be removed together in one ago?

**Comment by damiencarol** [comment]
I think you're right @valentijnscholten , this script is still used for legacy-setup.bash

**Comment by valentijnscholten** [comment]
For this usecase we may even want to keep maintaining a `setup.py`: https://owasp.slack.com/archives/C014H3ZV9U6/p1613934621008200 (somebody installing defect dojo from git via pip to reuse our code in some way)

**Comment by damiencarol** [comment]
@valentijnscholten to make it work, we need that our setup.py read requirements.txt add add dependencies based on it.

**Comment by madchap** [comment]
Reviving this old PR discussion. setup.bash is now EOL. Do we feel it's something to flag for 2.0.0?

**Comment by mtesauro** [comment]
FWIW, godojo doesn't use setup.py - https://github.com/DefectDojo/godojo/search?q=setup.py

**Comment by damiencarol** [comment]
@madchap this PR need a rebase.

**Review by damiencarol — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
