### PR TITLE
Renamed development_environment to environment 

### PR DESCRIPTION
**Pull request by JoseRoman**
`/dev_env` --------> `/environment`
`development_environment` ---> `environment`
`dev_env.html` --------> `environment.html`
`new_dev_env.html` ---> `new_environment.html`
`add_dev_env` ---------> `add_environment`

As someone relatively new to the application and the code base, I thought that development_environment was a weird name and some might argue not appropriate for the purpose it served. 

I didn't change any of the API routes on purpose since I wasn't sure how the team normally handled route changes. I can easily make that change if we want to change it just to have the same name all across. 

Any feedback is welcomed.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Just to be sure, you need to update the migration file :-)

**Comment by madchap** [comment]
Hey @JoseRoman 

Just came across this, and the db migration file still needs to be updated. Can you please give it a bump?

Cheers!

**Comment by valentijnscholten** [comment]
@JoseRoman if you want this to be included in the next release, could you mark this PR as ready for review and/or complete it?

**Comment by madchap** [comment]
This PR now requires quite some conflict resolution. @JoseRoman please let us know if you're interested in putting it up to date or not. If not or radio silence, we may just close the PR. Thank you for your understanding!

**Comment by JoseRoman** [comment]
Hi @madchap, I completely understand. I will resolve all conflicts tomorrow (12/11). Apologies for being MIA for so long.

**Pull request closed without merging**
