### PR TITLE
[FIX] JQuery Error on Edit Finding

### PR DESCRIPTION
**Pull request by X0x1RG9f**
When editing a finding, a click on the "See Alerts" button at the right corner of the webpage will cause a JQuery JavaScript Error. Removing JQuery usage and using JS trim instead.

### CODE REVIEW

**Review by Maffooch — APPROVED** [review]

**Comment by Maffooch** [comment]
Helm charts will not pass because `X0x1RG9f:X0x1RG9f-fix8` is based from `master`

**Comment by damiencarol** [comment]
@X0x1RG9f could you rebase on last `dev` ? the failing test was fixed in dev.

**Comment by Maffooch** [comment]
Got a whole bunch of extra stuff in here now :/

**Review by coheigea — APPROVED** [review]
LGTM, tested the error and that the fix works.

**Comment by devGregA** [comment]
@blakeaowens no need to test, if the JS change looks safe to you, please just let me know.

**Comment by blakeaowens** [comment]
> 

Change looks fine to me.

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
