### PR TITLE
Allow marking Qualys WAS security weaknesses as findings.

### PR DESCRIPTION
**Pull request by iwalton3**
This is a compromise between #3348 and #3150. Some users may want to include the "Security Weakness" findings from Qualys as findings, while others may want to make them informational. (Note that the minimum finding level is left at Low. That was not changed from #3348, but may be a subject of contention between users.)

This PR improves the logic for determining this and adds a `QUALYS_WEAKNESS_IS_VULN` boolean toggle to settings to allow you to opt-in to having "Security Weakness" have a severity.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Can you also add a `DD_QUALYS_WEAKNESS_IS_VULN`? Or maybe even make the name more explicit to indicate it affects the web parser, but not the infra parser?

**Comment by iwalton3** [comment]
I have fixed the naming and added an environment variable.

**Comment by devGregA** [comment]
@cody-m-tibco please review.

**Comment by valentijnscholten** [comment]
@iwalton3 could you resolve the conflicts please?

**Review by valentijnscholten — APPROVED** [review]

**Review by madchap — APPROVED** [review]
lgtm

**Comment by valentijnscholten** [comment]
thanks @iwalton3 
@madchap @damiencarol @Maffooch still happy to merge this?

**Review by damiencarol — CHANGES_REQUESTED** [review]
We should have a unit test that shows the parser modification.
As it modifies how the parser works, could you add a unit test that shows the weakness as finding when we activate this option?

**Comment by iwalton3** [comment]
> We should have a unit test that shows the parser modification.
> As it modifies how the parser works, could you add a unit test that shows the weakness as finding when we activate this option?

I added a unit test for this.

**Review by damiencarol — APPROVED** [review]

**Pull request merged**
