### PR TITLE
:bug: fix deduplication for trivy, #9290

### PR DESCRIPTION
**Pull request by manuel-sommer**
see issue #9290

### CODE REVIEW

**Review by grendel513 — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Comment by FuzzyGophers** [comment]
Hi, all, now that this is in :dev... what is a projected timeline for it to hit "mainline"?

**Comment by mtesauro** [comment]
@FuzzyGophers We release from dev monthly so the Feb release - 2.31.0 - should be the first Monday of Feb.

**Comment by FuzzyGophers** [comment]
> @FuzzyGophers We release from dev monthly so the Feb release - 2.31.0 - should be the first Monday of Feb.

Thank you for the insight!

**Pull request merged**
