### PR TITLE
Shuffle tests

### PR DESCRIPTION
**Pull request by kiblik**
Test robustness of unittests. They should pass in any order.

### CODE REVIEW

**Comment by Maffooch** [comment]
I ran into some pickling errors with parallel turned out. I am not really sure what we would need to do to get that working. If shuffle works here, I think that would still make for a pretty big win 😀

**Comment by kiblik** [comment]
> I ran into some pickling errors with parallel turned out. I am not really sure what we would need to do to get that working. If shuffle works here, I think that would still make for a pretty big win 😀

Yes, I was pleasantly surprised by it as well.
I do not see some easy fix for `--parallel` so I will keep only `--shuffle` here and I will try to fix `--parallel` in separate PR.

**Review by mtesauro — APPROVED** [review]
Approved

**Review by cneill — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Comment by Maffooch** [comment]
@kiblik I think tests were passing here by coincidence like the last time we tried something like this.. Very frustrating... We're going to revert for now, and then fix more widely in the future. Once those fixes are applied, we can enable shuffle again

I found something out about this one
> I ran into some pickling errors with parallel turned out. I am not really sure what we would need to do to get that working.

The error raises from an exception/stacktrace during the test that is not able to be pickled. I think exceptions are intended to be handled, and then the test will fail via the assertions.

**Comment by kiblik** [comment]
> @kiblik I think tests were passing here by coincidence like the last time we tried something like this.. Very frustrating... We're going to revert for now, and then fix more widely in the future. Once those fixes are applied, we can enable shuffle again
> 
> I found something out about this one
> 
> > I ran into some pickling errors with parallel turned out. I am not really sure what we would need to do to get that working.
> 
> The error raises from an exception/stacktrace during the test that is not able to be pickled. I think exceptions are intended to be handled, and then the test will fail via the assertions.

I suppose the problem with pickling is mainly in `--parallel` (#10408). But I agree that `--shuffle` is not behaving "well". I planned to offer to exclude `unittests.test_rest_framework` and run it separately without `--shuffle`. But full revert is probably better idea for now.

**Pull request merged**
