### PR TITLE
Finding groups: (Auto) Group By and more enhancements

### PR DESCRIPTION
**Pull request by valentijnscholten**
Finding Group enhancements:
- Allow to auto group on import/reimport (by component_name for example)
- Fix sla display bug for empty groups
- Allow edit of finding group on edit_finding page
- Allow group by component name/version/filepath via bulk edit

Main feature is automatic grouping, so in the UI or API a `group_by` field has been added. Setting `group_by` to `component_name` on import or reimport will add all new findings automatically to a group based on the `component_name` field.
If `push_to_jira` or `push_all` is enabled, the groups will be pushed to JIRA.

There's also the possibility on the edit finding page now to modify the group for a finding.

While doing this PR I thought of some more things we could/should do for the finding groups, but ideally we get some more feedback first :-)

### CODE REVIEW

**Comment by madchap** [comment]
I could make it crash

```
Template error:
In template /app/dojo/templates/base.html, error at line 341
   '<' not supported between instances of 'NoneType' and 'int'
   331 :                                         <span>Calendar</span>
   332 :                                     </a>
   333 :                                 </li>
   334 :                             {% endif %}
   335 :                             {% if request.user.is_staff %}
   336 :                                 <li>
   337 :                                     <a href="#"><i class="fa fa-hospital-o fa-fw"> </i> <span>Questionnaires</span><span
   338 :                                             class="glyphicon arrow"></span></a>
   339 :                                     <ul class="nav nav-second-level">
   340 :                                         <li><a href="{% url 'questionnaire' %}">All Questionnaires </a></li>
   341 :                                          <li><a href="{% url  'questions' %}">All Questions </a></li>
   342 : 
   343 :                                     </ul>
   344 :                                     <!-- /.nav-second-level -->
   345 :                                 </li>
   346 :                             {% endif %}
   347 :                                 <li id="menu_configuration">
   348 : 				                    <a href="#" aria-expanded="false" aria-label="Configuration">
   349 :                                         <i class="fa fa-cog fa-fw"></i>
   350 :                                         <span>Configuration</span>
   351 :                                     </a>


Traceback:

File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py" in sensitive_variables_wrapper
  36.             return func(*func_args, **func_kwargs)

File "./dojo/authorization/authorization_decorators.py" in _wrapped
  39.         return func(request, *args, **kwargs)

File "./dojo/test/views.py" in view_test
  169.     return render(request, 'dojo/view_test.html',

File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py" in render
  36.     content = loader.render_to_string(template_name, context, request, using=using)

File "/usr/local/lib/python3.8/site-packages/django/template/loader.py" in render_to_string
  62.     return template.render(context, request)

File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  171.                     return self._render(context)

File "/usr/local/lib/python3.8/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/usr/local/lib/python3.8/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py" in render
  309.                 return nodelist.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py" in render
  309.                 return nodelist.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py" in render
  209.                     nodelist.append(node.render_annotated(context))

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py" in render
  309.                 return nodelist.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in render
  987.             output = self.filter_expression.resolve(context)

File "/usr/local/lib/python3.8/site-packages/django/template/base.py" in resolve
  698.                 new_obj = func(obj, *arg_vals)

File "./dojo/templatetags/display_tags.py" in group_sla
  246.     return finding_sla(group)

File "./dojo/templatetags/display_tags.py" in finding_sla
  256.     find_sla = finding.sla_days_remaining()

File "./dojo/models.py" in sla_days_remaining
  2370.         return self.sla_days_remaining_internal

File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py" in __get__
  80.         res = instance.__dict__[self.name] = self.func(instance)

File "./dojo/models.py" in sla_days_remaining_internal
  2367.         return min([find.sla_days_remaining() for find in self.findings.all()])

Exception Type: TypeError at /test/2
Exception Value: '<' not supported between instances of 'NoneType' and 'int'

```

**Comment by valentijnscholten** [comment]
> I could make it crash.

_He who break its, shall fix it_

I'll take a look, thanks for the sample files.

**Comment by valentijnscholten** [comment]
Thanks @madchap, could reproduce. Problem was with findings of `Info` severity, which don't have an "SLA Days Remaining value" (and SLA Start Date). This is now fixed, also added some missed prefetches. Could you retest / confirm?

**Comment by madchap** [comment]
Well done

image

Question about groups of 1 finding. Should we maybe just pass on creating a group?

image

**Comment by valentijnscholten** [comment]
The main usecase, I think, is to report findings per component to JIRA. So even if there's only one now, it makes sense to report as a group. On a next reimport there might be 2 vulns inside a component and then we could just update the existing jira issues for the group.

**Review by madchap — APPROVED** [review]

**Comment by valentijnscholten** [comment]
Merging this as we need to deploy from dev and dogfood it. It's behind a feature flag, so should be good!

**Pull request merged**
