### PR TITLE
upd: [helm] resource optimization

### PR DESCRIPTION
**Pull request by Bagautdino**
```markdown
# Pull Request: Allocate Dedicated Resources for dbMigrationChecker Container

## Overview
This Pull Request introduces a critical fix related to the resource allocation for the `dbMigrationChecker` container in the `defectdojo` chart. Previously, the `dbMigrationChecker` container incorrectly inherited resource limits from the `uwsgi` container, which could lead to potential performance and reliability issues.

## Changes
The resource allocation configuration for the `dbMigrationChecker` container has been decoupled from the `uwsgi` container. This ensures that `dbMigrationChecker` has its own dedicated resources, thereby preventing any unintended resource sharing or conflicts.

### Modifications in `helpers.tpl`
- **Previous Configuration**: Resource values for the `dbMigrationChecker` container were inherited from `.Values.django.uwsgi.resources`.
  ```yaml
  {{- toYaml .Values.django.uwsgi.resources | nindent 10 }}
  ```
- **New Configuration**: Resource values are now independently set under `.Values.dbMigrationChecker.resources`.
  ```yaml
  {{- toYaml .Values.dbMigrationChecker.resources | nindent 10 }}
  ```

### Modifications in `values.yaml`
- **Previous Configuration**: The `dbMigrationChecker` container was enabled without specific resource allocations.
  ```yaml
  dbMigrationChecker:
    enabled: true
  ```

- **New Configuration**: Added explicit resource requests and limits for the `dbMigrationChecker` container.
  ```yaml
  dbMigrationChecker:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
  ```

## Impact
- **Performance Stability**: Ensuring dedicated resources for the `dbMigrationChecker` container improves the overall stability and performance of the operations related to database migrations.
- **Resource Management**: This change allows for better management of Kubernetes resources, ensuring that critical components such as `dbMigrationChecker` have sufficient resources to operate effectively without affecting other components.

### CODE REVIEW

**Comment by mtesauro** [comment]
@kiblik FYI: I figured you'd want :eyes: on this

**Comment by kiblik** [comment]
> @kiblik FYI: I figured you'd want 👀 on this

It looks like a good idea. I will test it locally (to check exact values). But I like it.
Thank you @Bagautdino

**Comment by mtesauro** [comment]
@kiblik 

> It looks like a good idea. I will test it locally (to check exact values).

I'll wait for you to test and respond before this is merged just in case.

**Review by mtesauro — APPROVED** [review]
Approved

**Review by kiblik — APPROVED** [review]
Values are reasonable for me.

**Review by Maffooch — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Pull request merged**
