### PR TITLE
Allow for external DB

### LINKED ISSUE #504: support external databases when using docker
### Issue Type 
- [x] Enhancement

### Description
When using docker, I would like to be able to bring my own database.

It appears that https://github.com/DefectDojo/django-DefectDojo/blob/master/setup.bash#L40
uses defaults (including a default hardcoded root password)

setup.bash is ran when building using this Dockerfile https://github.com/DefectDojo/django-DefectDojo/blob/master/Dockerfile#L14

It would be ideal to provide these to the provision script in some way

### PR DESCRIPTION
**Pull request by t3h2mas**
Allow using env variables to set the database in the docker build. The flow shouldn't change if env vars are not used. 

No documentation has been provided, as I didn't see a fitting place in `docs`, anyone have any feedback for this?

Would close #504

### CODE REVIEW

**Comment by devGregA** [comment]
@t3h2mas it looks like CI tests are failing for this PR

**Comment by t3h2mas** [comment]
Found the issue @devGregA

**Comment by devGregA** [comment]
@aaronweaver I'm good with this. Let me know your thoughts/concerns

**Comment by devGregA** [comment]
@t3h2mas congrats on getting your first PR merged!

**Pull request merged**
