### PR TITLE
Add support for dynamic test import for Veracode

### PR DESCRIPTION
**Pull request by jpbowie**
Added ability to import dynamic flaws from a Veracode XML scan report.  Hopefully addresses enhancement request #4606.

### CODE REVIEW

**Review by damiencarol — CHANGES_REQUESTED** [review]
Could you add unit tests that shows the new data?

**Comment by jpbowie** [comment]
Unit tests for dynamic flaws have been added.

**Review by damiencarol — APPROVED** [review]

**Comment by damiencarol** [comment]
@jpbowie awesome!. But you will need to rebase on last dev commit because we had some errors in integration tests fixed by #5038

**Comment by damiencarol** [comment]
seems ok now. @valentijnscholten merged the fix

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
