### PR TITLE
Translation & refactor test, product

### PR DESCRIPTION
**Pull request by shipko**
Yet another part of translation for some part product and test modules. 

Also I refactored imports for test/views.py

### CODE REVIEW

**Comment by shipko** [comment]
@StefanFl, @damiencarol, please help me with "Lint Helm chart" failing checks

**Comment by StefanFl** [comment]
@shipko You have to rebase your branch to the current dev branch. The helm chart in your branch is too old.

**Comment by damiencarol** [comment]
> @shipko You have to rebase your branch to the current dev branch. The helm chart in your branch is too old.

I agree, just rebase

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
