### PR TITLE
:bug: Yarn Audit: Add CI importer support

### PR DESCRIPTION
**Pull request by manuel-sommer**
see #6495

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Review by grendel513 — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Comment by Maffooch** [comment]
@manuel-sommer I did not notice the conflicts when I approved. Everything else looked good to me though!

**Comment by manuel-sommer** [comment]
No problem, conflicts have been resolved @Maffooch. You can merge :-)

**Comment by manuel-sommer** [comment]
Ready to merge

**Pull request merged**
