### PR TITLE
update minikube version

### LINKED ISSUE #1403: Minikube is blowing up
**Bug description**
When broker ares being run by Travis CI, the Minikube server cannot be accessed. The test continues to run until timeout. Maybe updating will resolve this issue?

**Steps to reproduce**
1. Submit a PR for travis to test
2. See many error messages

**Expected behavior**
Travis is happy

**Screenshots**
Screen Shot 2019-07-22 at 2 56 00 PM

### PR DESCRIPTION
**Pull request by dr3dd589**
fix #1403 

**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and closed.**

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant 
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

### CODE REVIEW

**Comment by dr3dd589** [comment]
on updating version, it passes all test on my DD repo [travis](https://travis-ci.org/dr3dd589/django-DefectDojo) but fails to launch again in some of the tests don't know why.

**Comment by Maffooch** [comment]
@dr3dd I'm going to close and reopen this to wake Travis again. Want to ensure these tests passed because of your changes and not luck.

**Comment by dr3dd589** [comment]
yeah, but if it is working correctly sometime and sometime not then maybe it is an issue in minikube not in our programme. I saw some issue on minkube like this and it is related to some sort of network problem maybe don't know but will figure it out.

**Comment by dr3dd589** [comment]
btw, you can restart the Travis build without closing it there is functionality for that.

**Comment by Maffooch** [comment]
@dr3dd589 That's the point of testing twice :)

Whats the secret of restarting without open/close?

**Comment by dr3dd589** [comment]
you can go to Travis build page and the right upper corner there is an option to restart or rebuild the test. without closing the PR.

**Comment by Maffooch** [comment]
All I have in that little drop down is "requests". Maybe I don't have permission to restart some one else's  build?

**Comment by dr3dd589** [comment]
that's strange I can restart and rebuild any of the PR again.

**Comment by dr3dd589** [comment]
like just one did for https://github.com/DefectDojo/django-DefectDojo/pull/1405

**Comment by dr3dd589** [comment]
you are right it's failing again in PostgreSQL test.

**Comment by Maffooch** [comment]
Looks you're my guy with the connections then.

Postgres tests failed on this build. Looks like it is an issue on their end like you said. I guess we can wait it out and just monitor incoming PR's and rerun until they pass

**Comment by dr3dd589** [comment]
we can create an issue on their repo about this?

**Comment by Maffooch** [comment]
I have not seen any minikube issues in the last few days. Think it's fixed? Should we upgrade anyway?

**Comment by dr3dd589** [comment]
yeah, I don't think so. we can close this one. We can do this in future if there is any problem.

**Pull request closed without merging**
