### PR TITLE
Add the ability to disable SLA notifications on a product basis

### PR DESCRIPTION
**Pull request by coheigea**
**Description**

Add a config switch to products to disable SLA notification breaches to override the global settings. Sometimes you might want to allow a specific product to go over SLA, or the product itself might be in development, and then you then don't want to be getting SLA breach notifications.

Also clarified the misleading description for SLA breach notifications when linked to JIRA.

**Test results**

None

### CODE REVIEW

**Comment by mtesauro** [comment]
This isn't a criticism - when I saw this, I wondered why you didn't just make a custom SLA with crazy big values and use that.

I guess I'm curious about the use case.

Perhaps you're wanting them to technically exceed the SLA but not get pestered with Alerts.  Anyway, mind explaining why my super-long SLA values wouldn't work?

**Review by Maffooch — COMMENTED** [review]
This one makes sense to me. Every org has that one application that moves super slow.
Migration needs a bump tho

**Comment by Maffooch** [comment]
Sure

**Comment by coheigea** [comment]
@Maffooch Done.

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by coheigea** [comment]
How do I go about getting two additional reviews?

**Review by cneill — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Pull request merged**
