### PR TITLE
system settings through apiv2

### PR DESCRIPTION
**Pull request by manuel-sommer**
This PR extends the API capabilities of DefectDojo. As of yet, not all System Configurations are accessible through the API. Thus, this PR advances DefectDojo's API capabilities to e.g. configure DefectDojo in an automatic way through IaC.

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Thanks. Would it be better to just use the built in "ModelSerializer" so we don't have to have all the custom code / listing / mapping of fields?

**Comment by manuel-sommer** [comment]
@valentijnscholten Thanks for the comment. Is it fine like this?

**Comment by valentijnscholten** [comment]
Thanks. Does it work as expect with POST updating all fields and PATCH allowing update of a subset of fields? I think evertyhing related to tags can be removed from this serializer.

**Comment by manuel-sommer** [comment]
@valentijnscholten I tested POST and PATCH. It worked fine.

**Review by valentijnscholten — APPROVED** [review]

**Review by madchap — APPROVED** [review]
Looks simple :) Cheers.

**Pull request merged**
