### PR TITLE
Fix IP address/host decoding in Nessus CSV parser (#3655)

### PR DESCRIPTION
**Pull request by damiencarol**
Work:
 - [x] add more unit tests to show bug #3655 
 - [x] add test that check findings attributes
 - [x] add more findings attributes (CVSSv3, component name+version)
 - [x] git ride of pandas 

Many unit tests where added with reports generated from Nessus Pro 8.13.1 (257)

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]
Thanks. Some suggestions:
- Update the title so it reflects that the parser itself also got updated/fixed
- Update the description to mention you generated some real reports and used it for the tests and parser updates.

**Comment by damiencarol** [comment]
Added the Haso Code deduplication algorythm as discussed with @valentijnscholten IRL (and tested it also :D )

**Comment by valentijnscholten** [comment]
if the endpoints are needed for the hash codes, might be better to have dedicated PR for that. I think switching to the hash code algorithm might impact hoe deduplication works with findings with similar endpoints or overlapping endpoints.
also I think if you have endpoints on the findings, you don't need the file_path, but not sure.

**Comment by damiencarol** [comment]
@valentijnscholten tested it. I removed the file_path attributes because as you said rightfully, as I added endpoints and configured hash code algo we don't need it.
For now I configured these attributes: `'Nessus Scan': ['title', 'severity', 'cve', 'cwe', 'endpoints']`

**Comment by valentijnscholten** [comment]
yes, but it changes behaviour. so better do that in a separate PR.

**Comment by damiencarol** [comment]
Ok I'm splitting it.

**Comment by madchap** [comment]
Good stuff - need to fix the conflict though :-)

**Review by madchap — APPROVED** [review]

**Comment by damiencarol** [comment]
Rebased and removed pandas.

**Pull request merged**
