### PR TITLE
:sparkles: add kubescape, #7060

### PR DESCRIPTION
**Pull request by manuel-sommer**
#7060

### CODE REVIEW

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by manuel-sommer** [comment]
FYI: I did not shorten the result files due to their complex nesting and referenced resourceID inside the JSON.

**Review by blakeaowens — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Comment by manuel-sommer** [comment]
Do we get this into the next release @mtesauro ?

**Comment by teyhouse** [comment]
> Do we get this into the next release @mtesauro ?
I would be very helpful to have this ASAP

**Review by cneill — APPROVED** [review]

**Pull request merged**
