### PR TITLE
hotfix: do not reopen false positives and out_of_scope on behalf of SDA SE

### PR DESCRIPTION
**Pull request by wurstbrot**
This PR closes https://github.com/DefectDojo/django-DefectDojo/pull/2526
This PR is regarding https://github.com/DefectDojo/django-DefectDojo/issues/2525

- [x] Your code is flake8 compliant.
- [x] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted).
- [x] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

# Git Tips
## Rebase on dev branch
If the dev branch has changed since you started working on it, please rebase your work after the current dev.

On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
 git mergetool
 git rebase --continue
 ```

When everything's fine on your local branch, force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

To cancel everything: 
```
git rebase --abort
```

## Squashing commits
```
git rebase -i origin/dev
```
- Replace `pick` by `fixup` on the commits you want squashed out
- Replace `pick` by `reword` on the first commit if you want to change the commit message
- Save the file and quit your editor

Force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

### CODE REVIEW

**Comment by Maffooch** [comment]
Please fix Flake8. Logic of PR looks good.

**Comment by wurstbrot** [comment]
@Maffooch sorry, done.

**Comment by valentijnscholten** [comment]
Thanks for the tests. What I really meant was integration / end-to-end test. So run import, change status of findings to false_p / out_of_scope, run import again, check expected result. But maybe other are comfortable with the PR as is, I myself am not using deduplication.

**Comment by wurstbrot** [comment]
@valentijnscholten Will this be merged?

**Comment by wurstbrot** [comment]
Small reminder: This PR fixes a broken functionality which worked before. Therefore, a merge would be nice to get the original functionality back.

**Comment by Maffooch** [comment]
Hi @wurstbrot apologies for the wait. Most of the mods here are on vacation for the month. Things will return to normal in the coming weeks. Thank you for being patient!

**Pull request merged**
