### PR TITLE
numerical ordering for multiple pages

### PR DESCRIPTION
**Pull request by manuel-sommer**
Part1 followup for https://github.com/DefectDojo/django-DefectDojo/pull/8234

I will do another followup for https://github.com/DefectDojo/django-DefectDojo/pull/8234 as I would like to understand more how numerical filtering works to finish this.

### CODE REVIEW

**Comment by manuel-sommer** [comment]
Could you take a look at this @mtesauro? Maybe, we can merge this fast that we get it on the road in this release.

**Comment by manuel-sommer** [comment]
retrigger unittests

**Comment by manuel-sommer** [comment]
Ready for review @mtesauro

**Comment by mtesauro** [comment]
@manuel-sommer See #10045 - I believe this also covers what you're working on here.

**Comment by manuel-sommer** [comment]
@mtesauro, yeah it is simmilar but on a different spot. Let's merge this as well and then we can finish the rest. Thank you for notifying.

**Comment by manuel-sommer** [comment]
Reminder, please don't forget to review.

**Review by blakeaowens — APPROVED** [review]

**Review by blakeaowens — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
