### PR TITLE
Rearrange for cvssv3

### PR DESCRIPTION
**Pull request by madchap**
Addresses #3823 - The useful cvssv3 javascript pop-up is certainly underutilized as it's buried down the field. Bringing it up next to severity so one is actually tempted to give findings a vector string.

Edit:

image

View - pop-over severity if exists and remove the panel.

image

### CODE REVIEW

**Comment by damiencarol** [comment]
could we switch to label `CVSS v3` exactly ?

**Comment by madchap** [comment]
Or something like that to avoid the new row?

image

**Comment by madchap** [comment]
> could we switch to label `CVSS v3` exactly ?

Sure.

**Comment by Maffooch** [comment]
Well that was not when I tried to do :/ got the migrations in order but the unit tests wouldn't recognize it so I tried to merge dev into this branch and got them switched.. May need to revert if that's the best idea.

**Comment by valentijnscholten** [comment]
Maybe just make a new one that fixes it

**Pull request merged**
