### PR TITLE
Importer: Add OASIS SARIF format #3445

### PR DESCRIPTION
**Pull request by damiencarol**
## OASIS SARIF format parser
SARIF represents a leap forward in the usability of static analysis tools. Many organizations in the safety and security communities use several competing tools on their code. SARIF will allow them to combine and compare the results more easily to gain a sharper picture of the issues in their code that need to be addressed. Engineering teams will be able to easily access a broad range of potential defects and vulnerabilities in compliance with privacy and accessibility standards. SARIF will support the development of products whose code spans languages and operating systems.

[OASIS TC](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=sarif)
[Official Spec](https://github.com/oasis-tcs/sarif-spec)

### Sample Files
4 example files come from the specification itself
1 report comes from [LGTM.com](LGTM.com) web site scans of master branch

#### A. SARIF reports could contain more than one "test".
But to keep this pull request simple, all findings are merged in one test

#### B. The current code supports a simple version for CWE but no CVE
SARIF support for CVE / CWE is limited/not well defined.
SARIF specification doesn't describe exactly in detail how it could work. So the current code assumes these requirements:
1) the CWE is one of the `tags` properties is the format `foo/bar/cwe-999` (case insensitive)
You can see an example report in a unit test 
2) We need more data/reports to improve this part (more reports from different tools

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Thanks. Is there any way we can store/show what scanner is being imported? Maybe set `test.title`?

**Comment by damiencarol** [comment]
@valentijnscholten will work on that. I have few ideas. Basicaly SARIF carry a lot of details about the system that generated the report.
What do you wanna see in this title ?

**Comment by damiencarol** [comment]
@valentijnscholten I added the Test title data.
Could you assign this PR to me and review it?
Also, the `Integration tests` fail is the last commit. But it's a chrome related issue, no link with my modifications.

**Comment by valentijnscholten** [comment]
This format is interesting. I didn't know about it. Still thinking about how to best integrate it in defect dojo. Maybe we just merge this as a first iteration and gain some experience. In the end we may want to map the tool name / title to a specific test type in defect dojo so all tests of the same type can be grouped / deduplicated etc.

**Comment by damiencarol** [comment]
@valentijnscholten interresting point of view. Honestly from an implementation perspective I managed it like just another format to support. so My patch is ok :D 
What you describe is more linked to the fact that more than one tool use the same format. So there should be a concept of "Tool" + "version" and some features around that.
Just to be clear, the dudplication works with this integration as I followed and implemented "file_path"+"line" + "title" + "cwe"

**Comment by madchap** [comment]
I see no problem integrating a first iteration as it stands today. The parser could possibly also support a zip file upload, which would then be extracted and imported if several sarif files are to be processed?

It could be the first parser to eventually be a sort of meta-parser.

**Review by madchap — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
