### PR TITLE
A bit fancier release-drafter template

### PR DESCRIPTION
**Pull request by madchap**
This would go hand in hand with more attention to labels when some issues come in.

### CODE REVIEW

**Comment by ptrovatelli** [comment]
will it work if merged on dev or should it be merged to master?

**Comment by madchap** [comment]
I believe it to be a `master` thing, like dependabot.

**Comment by ptrovatelli** [comment]
cause this PR is based on dev :)

**Comment by madchap** [comment]
Well, I am obeying the rules :-D

**Comment by ptrovatelli** [comment]
Is there a way we can see what it's doing?

**Comment by ptrovatelli** [comment]
if not i'm fine with merge and see; can't be worse :)

**Comment by madchap** [comment]
You'd have the sample example I took directly out of https://github.com/marketplace/actions/release-drafter.

release-drafter will generate a draft and add each PR to it. Then it's up to us to check it out, and eventually amend it then. So if it's not to our liking, we can always change it on the fly.

I'd really like for this to get merged during `-rc6`.

**Comment by ptrovatelli** [comment]
are you planning to use actions or the deprecated github app? i suggest we go for actions which is not deprecated
that doc states that we need a workflow file too under .github/workflows/release-drafter.yml . 
there must be way to test release drafter on your own repository: if you add the proper workflow you should see the actions and releases appear on your repo here https://github.com/madchap/django-DefectDojo/actions/new

**Comment by madchap** [comment]
> are you planning to use actions or the deprecated github app? i suggest we go for actions which is not deprecated

actions. We need to ask a leader to remove the app, as it was probably installed before to avoid any conflict.

> that doc states that we need a workflow file too under .github/workflows/release-drafter.yml .
> there must be way to test release drafter on your own repository: if you add the proper workflow you should see the actions and releases appear on your repo here https://github.com/madchap/django-DefectDojo/actions/new

Yes, it is working fine.

**Comment by valentijnscholten** [comment]
let's hope this is a sign of a new release coming ;-)

**Pull request merged**
