### PR TITLE
travis: remove non-k8s tests, reduce matrix for k8s

### PR DESCRIPTION
**Pull request by valentijnscholten**
As discussed / proposed on Slack:
- Travis tets are extremely slow
- The non-k8s tests are running fine in GitHub Actions

The plan was to let both Travis and GitHub actions run alongside eachother for a couple of weeks. But waiting times for Travis are currently up to 3-4 hours sometimes, which breaks the feedback loop we need.

This PR:
- disables/removes all non-k8s tests / steps from the travis build
- reduces the build matrix for k8s tests to alleviate the strain on travis and reduce our waiting times.

Proposed for after the release of 1.9.0

### CODE REVIEW

**Comment by valentijnscholten** [comment]
image

**Comment by madchap** [comment]
As the k8s GHA is come through, do we want to push this PR even further?

**Comment by valentijnscholten** [comment]
ideally yes, but we could merge this one today. and let the k8s tests run for a week or so to be sure they're all ok. and they fail if something is wrong in unit tests or migrations or...

**Comment by valentijnscholten** [comment]
merged as we no longer have choices as travis already hangs for 20+ hours and travis-ci.org is being phased out.

**Pull request merged**
