### PR TITLE
Make titlecasing for finding title configurable

### PR DESCRIPTION
**Pull request by StephanPillhofer**
New feature to optionally disable titlecasing for the title of findings.

This implements/fixes https://github.com/DefectDojo/django-DefectDojo/issues/9241

### CODE REVIEW

**Comment by StephanPillhofer** [comment]
recalculated settings hash to fix failing unit tests

**Comment by StephanPillhofer** [comment]
I do understand your fears of wrong hashcodes.

However enabling this configuration option would allow DefectDojo to be used with so many other languages other than English out of the box. Titlecasing only works in English and causes errors in most other languages.

Do you maybe have an idea how to make the config more "hidden" or harder to accidentally change? I can also include documentation about the implications of changing this config (in code and in the official docs)

In the end it would be sad to limit DefectDojo to English findings only, especially if this missing config is the only thing holding it back. (for German e.g.)

Thank you for your thoughts!

**Comment by Maffooch** [comment]
> Another idea could be to always create the titlecase version of the title of the finding right before it get's hashed, no matter the current setting. Therfore, even if the setting is changed just to play with it, the resulting hash will still be the same.

Just to be sure I understand this correctly, are you saying something like this?
```
orignial_title = self.title
 # Title Casing
from titlecase import titlecase
self.title = titlecase(self.title[:511])
...
>> Do the hash code stuff
...
if not settings.FINDING_TITLECASING_ENABLED:
    self.title = original_title
```

**Comment by StephanPillhofer** [comment]
I had a different solution in mind when writing my comment but I now realize that that wouldn't have worked.

So yes, something like you wrote could solve the hashing issue:

```
...

orignial_title = self.title
 # Title Casing
from titlecase import titlecase
self.title = titlecase(self.title[:511])

...

if dedupe_option:
    if (self.hash_code is not None):
        deduplicationLogger.debug("Hash_code already computed for finding")
    else:        
        self.hash_code = self.compute_hash_code()
        deduplicationLogger.debug(
            "Hash_code computed for finding: %s", self.hash_code)
        if not settings.FINDING_TITLECASING_ENABLED:
            self.title = original_title

...
```

**Comment by mtesauro** [comment]
Closed as stale

**Comment by StephanPillhofer** [comment]
Since this PR has been closed, can I assume that such a feature will not be approved in the future? Otherwise I could update this PR with the changes discussed above.

**Comment by mtesauro** [comment]
@StephanPillhofer The PR was closed as stale as part of a general review of PRs which hadn't seen activity in a while.

Such a feature could be considered in the future. The key issue is that such a change would need to happen in the 'view' layer of DefectDojo - in the Django templates so that the title change is only done for UI operations and the title stored in the DB is left unchanged. If the PR changes how titles are stored in the DB, there's some seriously negative side effects for existing DefectDojo instances.

Due to the fact that title is frequently used in the deduplication hash codes, making a change to how those are stored is a problem for existing calculated dedup hashes for anyone already using DefectDojo.  For people with large numbers of findings, recalculating hashes can represent a significant time/resource issue. The largest one I know of with public numbers is: 
image
(full deck [here](https://www.slideshare.net/slideshow/intro-to-defectdojo-at-owasp-switzerland/246800332))

I understand that in your case, you're current running with the titlecase code commented out so a change wouldn't impact your instance but most users won't be in that situation. We could wrap those lines in an if but there's an on going support issue for a new `DD_something` setting for a small portion of the community with may be impacted by this. 

So, we're open to a PR which addresses the issue your having but it would have to consider the impact on the other members of the community currently using DefectDojo - especially because its very possible to make a change which appears to not have any side effects but actually breaks deduplication for users silently or at least with no easy to notice warning.

As DefectDojo has gained popularity over the years, we've had to be more careful about changes which impact those currently using the applications.

Hope that helps explain our thinking around this.

**Pull request closed without merging**
