### PR TITLE
Fix parser horusec

### PR DESCRIPTION
**Pull request by srburton**
**I'm doing this update because when trying to import a report from Horusec you get the following error:**

WhatsApp Image 2022-07-01 at 14 06 30

**I noticed that the reports of the new version of Horusec the "line" comes empty where it ends up breaking the parser of the integer:**

WhatsApp Image 2022-07-01 at 14 09 19

Screenshot_2

### CODE REVIEW

**Review by coheigea — CHANGES_REQUESTED** [review]
Can you add a unit test to unittests/tools/test_horusec_parser.py for it?

**Review by renatosazup — APPROVED** [review]

**Review by Maffooch — CHANGES_REQUESTED** [review]
Please fix Flake8 and add unit tests

**Comment by renatosazup** [comment]
Ok @Maffooch

**Review by mtesauro — APPROVED** [review]
Approved

**Review by renatosazup — APPROVED** [review]

**Review by renatosazup — APPROVED** [review]

**Comment by damiencarol** [comment]
@srburton @renatosazup : the comment of @Maffooch is still there, we need a unit test with a report that don't have the line (empty value) to show that the fix works.

**Comment by srburton** [comment]
@damiencarol added unit test!

**Comment by Maffooch** [comment]
@srburton Thanks for the new scan report!

Please test against it in the horusec unit test file [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/tools/test_horusec_parser.py)

**Comment by srburton** [comment]
@Maffooch check my fix, please?

**Review by renatosazup — APPROVED** [review]

**Review by Maffooch — APPROVED** [review]

**Comment by Maffooch** [comment]
@damiencarol leaving merge to you if it looks good

**Pull request merged**
