### PR TITLE
Dockerfile improvements

### PR DESCRIPTION
**Pull request by madchap**
- Do not run celery as uid 0 (drop C_FORCE_ROOT)
- Add ARG to pass what uid or username we want. Sane defaults.
- No need to change /var/run permissions, move to subdir for app.
- Actually add a user. Looks better, could avoid issues?
- ~Add media volume~

The nginx .conf files had to be changed to point to the more proper /var/run sub-directory.

- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ ] Your code is flake8 compliant.
- [ ] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

### CODE REVIEW

**Comment by mtesauro** [comment]
@madchap I like the use of ARGS in the dockerfiles.  It's also interesting how you did the TLS.  I've handled that differently with docker-compose installs (aka not k8s) by using a bind mount to the host for the TLS certs + the nginx config - makes changes to either not require 'getting into' the container.  Depending on how container savvy someone is, docker exec or docker cp might be too much.  Like [here](https://github.com/DefectDojo/Community-Contribs/blob/master/CentOS-7-deploy/dojo/docker-compose.yml#L18).  

Finally, have you tested celery as non-root?  I remember fighting that back when DefectDojo was usually just installed on a VM aka 5+ years ago.

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by madchap** [comment]
TLS was not done by me, I think it was @alles-klar maybe?

This PR is just about cleaning-up stuff that have been bothering me, like the celery root, the chmod 777, etc. No change in functionality and everything still appears to work on my end.

**Review by valentijnscholten — DISMISSED** [review]
I don't know all the ins and outs of Docker, but it looks good. Has to be if Docker meastro Matt approves it ;-)

**Comment by alles-klar** [comment]
@mtesauro I generate the TLS stuff on the fly because in my setup the traffic is re-encrypted at the load balancer and authentication is by other mechanism. The load balancer has a trusted certificate. 

Copy the TLS key in the docker container is the worst you can do because, normally docker images are public and not really protected. So if you want a trusted certificate in your container, you have to mount it at runtime.

**Comment by dsever** [comment]
Guys https://github.com/DefectDojo/django-DefectDojo/pull/2839/files#diff-8a9c34cc57f6de963b3642f80677b780R83 this RUNs could be one docker layer. No need for 3 of them.

**Comment by madchap** [comment]
> Guys https://github.com/DefectDojo/django-DefectDojo/pull/2839/files#diff-8a9c34cc57f6de963b3642f80677b780R83 this RUNs could be one docker layer. No need for 3 of them.

Suggestion applied.

**Comment by madchap** [comment]
Unrelated error in integration, about regulations:

```
======================================================================
ERROR: test_create_regulation (__main__.RegulationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/Regulations_unit_test.py", line 22, in test_create_regulation
    driver.find_element_by_link_text("Regulations").click()
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Regulations"}
  (Session info: headless chrome=85.0.4183.102)
```

**Comment by dsever** [comment]
> ERROR: test_create_regulation (__main__.RegulationTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "tests/Regulations_unit_test.py", line 22, in test_create_regulation
>     driver.find_element_by_link_text("Regulations").click()
>   File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
>     return self.find_element(by=By.LINK_TEXT, value=link_text)
>   File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Regulations"}
>   (Session info: headless chrome=85.0.4183.102)
> ```

This was merged at the beginning of this week, with passed tests

**Comment by valentijnscholten** [comment]
I think the whole travis build crashed / was aborted, let's see when we run it again.

**Comment by madchap** [comment]
Seems good after the relaunch. @valentijnscholten care to merge?

**Comment by madchap** [comment]
Alright this time.

**Comment by mtesauro** [comment]
Woohoo! :-)

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
