### PR TITLE
fix(Risk_Acceptance): Remove redundancy in strings of Treatments

### PR DESCRIPTION
**Pull request by kiblik**
Make strings translatable and remove redundancy

### CODE REVIEW

**Comment by Maffooch** [comment]
Have you check if the API needs to be updated? I cannot tell without doing some testing

https://github.com/DefectDojo/django-DefectDojo/blob/501d172aee0c165c8ed8efe1c9fe496a006f437b/dojo/api_v2/serializers.py#L1479C1-L1485C72

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Comment by kiblik** [comment]
> Have you check if the API needs to be updated? I cannot tell without doing some testing
> 
> https://github.com/DefectDojo/django-DefectDojo/blob/501d172aee0c165c8ed8efe1c9fe496a006f437b/dojo/api_v2/serializers.py#L1479C1-L1485C72

Yes, it works.

**Comment by kiblik** [comment]
Btw, Django 5.0 supports more [flexible form (not just list of tuples but using of a dict)](https://docs.djangoproject.com/en/5.0/releases/5.0/#more-options-for-declaring-field-choices).
After [upgrade to 5.0](https://github.com/DefectDojo/django-DefectDojo/pull/10409) I would rewrite all models to dicts like here.

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
