### PR TITLE
Bandit parser: implement scanner confidence

### PR DESCRIPTION
**Pull request by damiencarol**
## Work

- [x] implement scanner confidence
- [x] fix some formatting in description
- [x] remove useless attribute to 'N/A' or useless value

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]

**Review by ptrovatelli — APPROVED** [review]

**Comment by ptrovatelli** [comment]
lgtm except the failed integration test :)

**Comment by damiencarol** [comment]
@ptrovatelli changed how the title is managed so it broke the integration tests. fixed now :)

**Comment by damiencarol** [comment]
@ptrovatelli could you take a look?

**Review by mtesauro — APPROVED** [review]
The code part of this looks fine to me - not sure why the integration test is still failing.  It was for product_type which you didn't touch with these code changes and the odd timeout for the font awesome is a sad thing to break a integration test on.  Hard to tell if that was the exact cause. I think that test failure was transitive/an anomaly and am good approving this

Hit me up on Slack @damiencarol if I was wrong about why the test failed - otherwise, I trust you do commit this if you're comfortable with the changes also.

**Comment by valentijnscholten** [comment]
Sometimes the tests fail due to a timeout or GitHubAction issue. You can restart them by clicking on them and on the top right more or less there's a "Re-Run all jobs".

**Pull request merged**
