### PR TITLE
Upgrade to FontAwesomeFree 6.2.1

### PR DESCRIPTION
**Pull request by blakeaowens**
Added FontAwesomeFree 6.2.1 to requirements, Replaced stylesheet references in base.html, Removed all references to old FontAwesome syntax, for example `fa fa-[icon-name]` versus `fa-solid/fa-regular/fa-brands fa-[icon-name]`

[sc-76]

### CODE REVIEW

**Comment by damiencarol** [comment]
Screenshots!!!!

**Comment by blakeaowens** [comment]
Screenshot 2022-12-20 at 6 46 24 PM

Screenshot 2022-12-20 at 6 47 04 PM

Screenshot 2022-12-20 at 6 49 16 PM

Screenshot 2022-12-20 at 6 49 33 PM

**Comment by Maffooch** [comment]
dedupe test may be looking for a certain icon In the html that has now changed. Not totally sure tho. Run locally to determine if the failure is due to GHA or if the test itself is failing

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

**Pull request merged**
