### PR TITLE
remove xlrd

### PR DESCRIPTION
**Pull request by manuel-sommer**
It looks like xlrd is not really used.

### CODE REVIEW

**Comment by kiblik** [comment]
I believe some tools can detect these obsolete packages. It might be a good idea to add it as one of GitHub checks

**Comment by manuel-sommer** [comment]
This is also what I thought, but did not dive deeper regarding such tools and GH checks

**Comment by mtesauro** [comment]
I can only find this in requirements.txt and unit test tools output files so that's likely the reason we removed it's use.

**Review by mtesauro — APPROVED** [review]
Approved

**Review by Maffooch — APPROVED** [review]

**Review by cneill — APPROVED** [review]

**Review by grendel513 — APPROVED** [review]

**Pull request merged**
