### PR TITLE
fix import for SonarQube findings without 'htmlDesc'

### PR DESCRIPTION
**Pull request by ikrenyi1**
fix import for SonarQube findings without 'htmlDesc'

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Can you update the unit test to have at least one case that covers this missing attribute?

**Comment by ikrenyi1** [comment]
i've added a relevant test

**Review by valentijnscholten — APPROVED** [review]
thanks. didn't realize it needed a whole new api test

**Comment by Maffooch** [comment]
Small changes here for unit tests
```
2021-09-27T21:29:18.7942574Z [36muwsgi_1         |[0m ======================================================================
2021-09-27T21:29:18.7943760Z [36muwsgi_1         |[0m FAIL: test_parser (dojo.unittests.tools.test_sonarqube_importer.TestSonarqubeImporterExternalRule)
2021-09-27T21:29:18.7945145Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2021-09-27T21:29:18.7945811Z [36muwsgi_1         |[0m Traceback (most recent call last):
2021-09-27T21:29:18.7946553Z [36muwsgi_1         |[0m   File "/usr/local/lib/python3.8/unittest/mock.py", line 1325, in patched
2021-09-27T21:29:18.7947285Z [36muwsgi_1         |[0m     return func(*newargs, **newkeywargs)
2021-09-27T21:29:18.7948101Z [36muwsgi_1         |[0m   File "/app/dojo/unittests/tools/test_sonarqube_importer.py", line 254, in test_parser
2021-09-27T21:29:18.7949004Z [36muwsgi_1         |[0m     self.assertEqual('Dead stores should be removed', finding.title)
2021-09-27T21:29:18.7950056Z [36muwsgi_1         |[0m AssertionError: 'Dead stores should be removed' != 'Remove this useless assignment to local variable "currentValue".'
2021-09-27T21:29:18.7950914Z [36muwsgi_1         |[0m - Dead stores should be removed
2021-09-27T21:29:18.7951651Z [36muwsgi_1         |[0m + Remove this useless assignment to local variable "currentValue".
```

**Comment by kiblik** [comment]
@Maffooch, I fixed this check. Can you run tests, please?

**Review by damiencarol — APPROVED** [review]

**Comment by kiblik** [comment]
Is it possible to merge this PR, please? Thanks

**Pull request merged**
