### PR TITLE
Deduplication Algorithm for RustyHog 

### PR DESCRIPTION
**Pull request by manuel-sommer**
#5826

Screenshot from 2022-01-27 09-51-16

This only deduplicates Choctaw Hog. I have tried various settings, but Gottingen Hog and Essex Hog were never deduplicated. 
@damiencarol, could you give me input here?

### CODE REVIEW

**Comment by damiencarol** [comment]
It could be a bug in the de-duplication algorithm selection. I need to pull your PR to test it.

**Comment by valentijnscholten** [comment]
What is in the debug logs? None of these scanners seem to have dedupe settings, which I think means the legacy algo is used which won't dedupe if there is no file_path or no line number for the finding.

**Comment by manuel-sommer** [comment]
Hi @valentijnscholten 
All these three scanners are subscanners of the Rusty Hog scanner. 
https://github.com/newrelic/rusty-hog
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/rusty_hog/parser.py 
That's why I have set deduplication for Rusty Hog.

**Comment by valentijnscholten** [comment]
ok. This thing read like a bug report instead of a PR, that's what got me confused.

**Comment by manuel-sommer** [comment]
Here the bug report: https://github.com/DefectDojo/django-DefectDojo/issues/5826 

Indeed this is a PR, but I need input on how to continue here. Also, I have already asked in the slack channel.

**Comment by damiencarol** [comment]
@manuel-sommer this scanner use the new interface for parsers. if you can check which dedup algo is used

**Comment by manuel-sommer** [comment]
This PR is closed because of PR #5903

**Pull request closed without merging**
