### PR TITLE
Authorization V2: Global roles

### PR DESCRIPTION
**Pull request by StefanFl**
Users can be assigned a global role in the _Edit User_ dialog. A global role gives a user access to all Product Types and Products, including the underlying data, with permissions according to the respective role.

A use case for a global role could be the Chief Information Security Officer of a company who needs an overview of all systems. If he gets the global role `Reader`, he can see the findings for all products and also all metrics.

### CODE REVIEW

**Comment by StefanFl** [comment]
When we have global roles for users, we should have global roles for the newly invented groups as well.

**Comment by StefanFl** [comment]
The global role is now in a model class on its own, to be more flexible for future enhancements

**Comment by StefanFl** [comment]
... and there is a nice API now as well. No more changes from my side unless there are further change requests from reviewers.

**Comment by StefanFl** [comment]
This PR has to wait for #4603, because global roles need to be tied to Role model class.

**Comment by StefanFl** [comment]
All changes needed after moving roles into a model have been implemented now.

**Review by madchap — APPROVED** [review]

**Review by valentijnscholten — APPROVED** [review]

**Pull request merged**
