### PR TITLE
Set Product name non unique

### PR DESCRIPTION
**Pull request by dsever**
This pull request removed  requirement for Product name to be unique, and moves requirement to (product_type, name).

Why: there are situations in companies where  multiple product are named the same, but in different units, so we do believe that  is more natural to preserve  constraint on (name, prod_type)

### CODE REVIEW

**Comment by valentijnscholten** [comment]
This will break everything in my company and probably elsewhere. Product name must be unique.

**Comment by dsever** [comment]
@valentijnscholten  can we somehow test it, or can you explain internals that are using product_name as unique? I wanted to test upgrade, but I'm missing dataset that can be in use.

**Comment by devGregA** [comment]
I agree with @valentijnscholten. I believe it is much easier to accommodate naming products in a unique manner rather than introducing confusion on metrics and matching filters.

**Comment by valentijnscholten** [comment]
All my Jenkins pipeline scripts are finding product if by using product name, same for downstream dashboards and other data aggregation scripts. Of course I can fix those, but I'm pretty sure there will be many more people.

**Comment by dsever** [comment]
Thanks guys, for your view. Than I will close this PR, we will than probably use it for our internal use case only.

**Comment by Hijerboa** [comment]
Perhaps this is something that could be added as an optional setting which is disabled by default?

**Comment by StefanFl** [comment]
I agree with @valentijnscholten and @devGregA. Since @dsever accepted their opinion, I close this PR.

**Pull request closed without merging**
