### PR TITLE
remove docker-compose override file with incorrect content

### PR DESCRIPTION
**Pull request by ptrovatelli**
This file is supposed to be a symbolic link, which is by default not present. 
It was mistakenly commited with in content the name of the destination.

### CODE REVIEW

**Comment by wurstbrot** [comment]
My steps:

- git clone
- cd django...
- git checkout dev
- rm docker-compose.override.yml
- docker-compose up --build

By performing that steps, I get the following error (I assume that is what this PR is about):
uwsgi_1         | Internal Server Error: /login
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 145, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 143, in _get_response
uwsgi_1         |     response = response.render()
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/response.py", line 106, in render
uwsgi_1         |     self.content = self.rendered_content
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/response.py", line 83, in rendered_content
uwsgi_1         |     content = template.render(context, self._request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
uwsgi_1         |     return self.template.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 171, in render
uwsgi_1         |     return self._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
uwsgi_1         |     return compiled_parent._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/library.py", line 192, in render
uwsgi_1         |     output = self.func(*resolved_args, **resolved_kwargs)
uwsgi_1         |   File "./dojo/templatetags/display_tags.py", line 96, in dojo_current_hash
uwsgi_1         |     repo = git.Repo(search_parent_directories=True)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/git/repo/base.py", line 183, in __init__
uwsgi_1         |     raise InvalidGitRepositoryError(epath)
uwsgi_1         | git.exc.InvalidGitRepositoryError: /app

**Comment by ptrovatelli** [comment]
@wurstbrot that is something different. i also had this error which is due to another PR merged recently and your docker images not being up to date
i have fixed this with, before starting: 
`docker-compose build`

**Comment by ptrovatelli** [comment]
@wurstbrot this is different but I don't know what that is... probably linked to a recent commit related to git in requirements file; I didn't have this specific error though

**Comment by ptrovatelli** [comment]
i'm using: 
```
docker-compose build
docker-compose up
```
not sure if it may change something

**Comment by ptrovatelli** [comment]
@wurstbrot ok i have it now. this happens with a fresh checkout. may need to logout in order to reproduce. 
I'd say it's related to 1654a6a9fafbd77fef94b96bb3f081f3c77b0438 or 9197e3fb6d75264f219b06911d6180fa6da92070 although it's strange that travis doesn't pick that problem up...

**Comment by ptrovatelli** [comment]
dev mode works:
```
docker/setEnv.sh dev
docker-compose up
```

release mode produces the issue. 
```
docker/setEnv.sh release
docker-compose up
```

By accidentally leaving the dev symbolic link we had hidden that problem. But the application is not meant to work in dev mode in production.

**Comment by ptrovatelli** [comment]
I think this is related to https://github.com/DefectDojo/django-DefectDojo/pull/1440
@dr3dd589  could you try and make your pull work in "release" mode please? 
Please see discussions above regarding dev vs release docker mode
In dev mode, due to the docker volume being mounted, /app in a git repository (includes a .git folder)
In release mode, it was never the case : there isn't a git repository in the django docker image thus the error above. 
Solution: 
- change Dockerfile.django to include .git in the image
- change the way to check for version for it to work without a .git folder

Thanks!

**Comment by ptrovatelli** [comment]
sweet I was able to fail travis in that case :)

**Comment by dr3dd589** [comment]
thanks! @ptrovatelli I added a try/except to handle this if it there is no git repo in the directory then just return release mode info.

**Pull request merged**
