### PR TITLE
Revert of (#6475)

### PR DESCRIPTION
**Pull request by damiencarol**

### CODE REVIEW

**Comment by Maffooch** [comment]
Why revert bleach? I think the correct reversion is #6167

**Comment by manuel-sommer** [comment]
Hi @damiencarol , do you want to you want to close #6761 with this PR?
Please could you also revert #6701 with this PR?

**Comment by Maffooch** [comment]
Maybe a better solution would be to determine why bleach is sanatizing the markdown fields rather than reverting to older versions

**Comment by Maffooch** [comment]
Fixed by #6848

**Pull request closed without merging**
