### PR TITLE
feat: added GitLab API fuzzing report parser

### PR DESCRIPTION
**Pull request by natebwangsut**
Adding GitLab Coverage Fuzzing report parser

https://docs.gitlab.com/ee/user/application_security/coverage_fuzzing

### CODE REVIEW

**Review by damiencarol — CHANGES_REQUESTED** [review]

**Comment by natebwangsut** [comment]
the CI error seems unrelated to the PR, can you rerun the tests ?

**Comment by damiencarol** [comment]
I confirm the pb is not related to this PR it may need a rebase.

**Comment by natebwangsut** [comment]
@damiencarol do you think I need a rebase onto current dev? other than that do you think its good to go?

**Comment by damiencarol** [comment]
@natebwangsut easier to rebase

**Comment by natebwangsut** [comment]
@damiencarol I've rebased the PR

**Review by damiencarol — APPROVED** [review]

**Review by damiencarol — APPROVED** [review]

**Comment by StefanFl** [comment]
@natebwangsut, @damiencarol Do we need additional settings for `HASHCODE_FIELDS_PER_SCANNER` or `DEDUPLICATION_ALGORITHM_PER_PARSER` to avoid problems with re-imports?

**Comment by damiencarol** [comment]
@StefanFl it's up to @natebwangsut . Do you want to add a custom configuration for the parser?
I'm good with pushing the parser as-is. having a default configuration is better but it require to test and implement it.

**Comment by StefanFl** [comment]
A lot of parsers have a custom setting at least for `DEDUPLICATION_ALGORITHM_PER_PARSER`, because the legacy algorithm often doesn't work for reimports. But I approve and merge it now and then make a test how it behaves.

**Review by StefanFl — APPROVED** [review]

**Pull request merged**
