### PR TITLE
Bugfix/swagger apiv2

### LINKED ISSUE #2487: Swagger apiv2 not corresponding correctly in some paths
**Bug description**
I am using the doc provided by the swagger, bit so some path with the problem.
The API is working fine, however, in some actions the request_body and response are wrong

**Paths with the same issue**
```
POST /endpoints/{id}/generate_report/
POST ​/engagements​/{id}​/accept_risks​/
POST ​/engagements​/{id}​/close​/
POST ​/engagements​/{id}​/generate_report​/
POST ​/engagements​/{id}​/reopen​/
POST ​/findings​/accept_risks​/
POST ​/findings​/generate_report​/
GET, POST, PATCH ​/findings​/{id}​/notes​/
PATCH ​/findings​/{id}​/remove_note​/
PUT, PATCH ​/findings​/{id}​/remove_tags​/
GET, POST ​/findings​/{id}​/tags​/
POST ​/product_types​/{id}​/generate_report​/
POST ​/tests​/{id}​/accept_risks​/
POST ​/tests​/{id}​/generate_report​/
```

**Screenshots** (optional)
Screenshot 2020-06-05 at 15 26 14
Screenshot 2020-06-05 at 15 26 46

### PR DESCRIPTION
**Pull request by edersonbrilhante**
This PR will fix #2487 

Screenshot 2020-06-05 at 15 34 55
Screenshot 2020-06-05 at 15 35 03

### CODE REVIEW

**Comment by valentijnscholten** [comment]
Hi, thanks for looking into this. Having correct/consistent swagger docs is very helpful and allows for autogenerating of api wrappers (hopefeully). I do notice the PR contains lots of changes that are only code formatting changes. This makes it hard to see what actually changed. And will also generate commits on files that actually haven't changed, making it harder to see which code/line was changed when.
Is there any chance you could adjust the PR to only contain changes that are more than just code formatting changes?

**Comment by edersonbrilhante** [comment]
I can remove the changes that fixes the format for review. After that, I can fix the format again and make push to git. Is this ok?

**Comment by valentijnscholten** [comment]
I'd rather not have any formatting changes at all. Just a few would be OK, but now we have like 50 or so.

**Comment by edersonbrilhante** [comment]
I agree, but with that, we never fix the legacy, :(. 
I changed as you asked me :)

**Comment by valentijnscholten** [comment]
True, but not sure if these lines are "too long" in the current widescreen world we live in.
Thanks for the update. Looks like I have to close and reopen it to trigger the travis build.

**Comment by valentijnscholten** [comment]
There's some flake8 violations:
```
Found violations: dojo/api_v2/views.py
	W293 @ 99:1 - blank line contains whitespace
	W291 @ 100:26 - trailing whitespace
	E231 @ 101:29 - missing whitespace after ','
	W291 @ 109:26 - trailing whitespace
	E231 @ 110:29 - missing whitespace after ','
	W291 @ 210:22 - trailing whitespace
	W291 @ 214:23 - trailing whitespace
	W291 @ 242:22 - trailing whitespace
	E231 @ 246:24 - missing whitespace after ','
	W291 @ 246:34 - trailing whitespace
	E231 @ 321:23 - missing whitespace after ','
	W291 @ 321:33 - trailing whitespace
```

**Comment by edersonbrilhante** [comment]
@valentijnscholten Thanks. I hope now the PR is fine :)

**Comment by edersonbrilhante** [comment]
Can someone review it?

**Pull request merged**
