### PR TITLE
Mark Hadolint findings as static

### PR DESCRIPTION
**Pull request by christophe226**
Fix issue DefectDojo#4730.

Issue description: Hadolint parser has no specific configuration regarding static/dynamic status of its findings. So it uses the default status, i.e. "dynamic", whereas Hadolint is a SAST, not a DAST. For consistency, Hadolint findings should be "static", not "dynamic". This wrong "dynamic" value has impacts on deduplication.

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]

**Review by StefanFl — APPROVED** [review]

**Comment by damiencarol** [comment]
@christophe226 we had some pb in the `dev` branch. could you rebase your PR on last dev?

**Comment by devGregA** [comment]
@damiencarol  am I missing something? I don't see any rebase issues?

**Comment by valentijnscholten** [comment]
The rebase or merge is needed to make the test suite work again.

**Comment by valentijnscholten** [comment]
On the other hand the functional tests, i.e. unit tests are OK and integratin tests and nothing affecting K8s so let's merge anyway :-)

**Pull request merged**
