### PR TITLE
Changes to facilitate ptvsd remote debugging

### PR DESCRIPTION
**Pull request by madchap**
Please submit your pull requests to the 'dev' branch.

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
- [ ] Model changes should include the necessary migrations in the dojo/dd_migrations folder.
- [ ] Add applicable tests to the unit tests.

Rebase includes @dr3dd589 latest changes for bleach related display.

### CODE REVIEW

**Comment by madchap** [comment]
Changes in `manage.py` seem to break invocations of many targets -- except `shell` (see referenced issue #1052 ). The workaround is then to manually do a `export DD_DEBUG=off` from the command line. I would welcome someone knowledgeable to explain if possible.

**Comment by valentijnscholten** [comment]
I am not knowledgable in this are, but I do like that we try to support debugging.

**Comment by madchap** [comment]
This last commit fixes #1052 as far as I am concerned. This is working pretty good for me anyway.

I have seen an article that apparently mentioned hotreloading could also work with ptvsd (despite all other sites saying otherwise), as django spawns 2 instances? I tried like the n00b I am, but these environment variables are not present as-is and I have not dug any deeper. FYI: https://ytec.nl/blog/debugging-django-vscode-without-using-noreload 

cc @devGregA let me know if there is anything else that I could do. Thanks.

**Comment by madchap** [comment]
Whatever I was thinking before was wrong. Now checking earlier if the socket is already in use to avoid reaching the `ptvsd.enable_attach()` code.

**Pull request closed without merging**
