### PR TITLE
Questionnaire Renaming and Fixes

### LINKED ISSUE #2418: Survey Edit - Internal 500 error
**Bug description**
Once you go to the questionnaire menu and select any predefine questionnaires.
Like Access Control, or any other predefined template. it generates an Internal 500 error

**Steps to reproduce**
1. Go to 'Questionnaire' (from the menu)
2. Click on 'View all Questionnaires'
3. Scroll down to 'Select any define template'
4. See error (Internal 500 Error)

**Expected behavior**
The template should open and we should be able to select the questions for the template.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Ubuntu 18.04]
 - DefectDojo Commit Message: DEV (414e10fd8b7aa51a27edfdce8a02ad3a512fe45c)

**Screenshots** (optional)
image

**Console logs** (optional)
Internal Server Error: /questionnaire/4/edit
Traceback (most recent call last):
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/dojo/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/survey/views.py", line 275, in edit_survey
    "name": "Edit Survey",
  File "/opt/dojo/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/dojo/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/dojo/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/opt/dojo/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_questionnaire' not found. 'delete_questionnaire' is not a valid view function or pattern name.
[pid: 29212|app: 0|req: 12/33] x.x.x.x () {54 vars in 1094 bytes} [Sat May 23 21:08:32 2020] GET /questionnaire/4/edit => generated 27 bytes in 62 msecs (HTTP/1.1 500) 7 headers in 370 bytes (1 switches on core 0)

**Additional context** (optional)

### PR DESCRIPTION
**Pull request by JoseRoman**
- Updated messages that still said "Survey"
- Updated breadcrumbs 
- Updated views.py functions
- Updated HTML file names

Fixes #2418

### CODE REVIEW

**Comment by valentijnscholten** [comment]
@JoseRoman if you want this to be included in the next release, could you mark this PR as ready for review and/or complete it?

**Comment by fzipi** [comment]
Hey @JoseRoman , can you resolve the conflict so this one can be merged? Thanks!

**Comment by valentijnscholten** [comment]
@Maffooch don't want to put work on your plate but maybe it's almost done and you could finish it up as @JoseRoman seems to have "disappeared".

**Review by Maffooch — APPROVED** [review]
Just ran through all the endpoints and fixed the conflicts. Seems good enough for now.

**Comment by JoseRoman** [comment]
Apologies for being MIA @valentijnscholten @Maffooch. I'll make sure my other existing PR is updated and taken care of. 

Thank you for fixing the the access lint issues @Maffooch

**Pull request merged**
