### PR TITLE
Fix: Review Finding Without Jira Ticket But With Jira Config

### LINKED ISSUE #1081: Cannot Update Finding As Soon as Jira is Configured
## Bug description
When trying to close a finding an exception is thrown because the system is trying to update the (non-existing) Jira ticket.

Looking at the code gives me the impression that a Jira Issue is mandatory as soon as one enables a Jira config.

Looks like `j_issue = JIRA_Issue.objects.get(finding=finding)` is throwing an exception which is not handled properly.

## Steps to reproduce
1. Setup Jira for a product
2. Create a finding
3. Create a review, settings do not matter
4. Send POST requests => Exception

## Expected behavior
There shouldn't be an error only because you don't have a Jira ticket connected to a finding.

## Deployment method
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

## Environment information
 - Operating System: Ubuntu / Docker
 - DefectDojo version: master / 2b5d417: Update README.md [2019-04-12 14:49:15 -0500]

## Console logs
```
uwsgi_1         | Starting new HTTPS connection (1): jira.XXX.de:443
uwsgi_1         | https://jira.XXX.de:443 "GET /rest/api/2/serverInfo HTTP/1.1" 200 None
uwsgi_1         | https://jira.XXX.de:443 "GET /rest/api/2/field HTTP/1.1" 200 None
uwsgi_1         | Internal Server Error: /finding/1/defect_review
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/finding/views.py", line 365, in defect_finding_review
uwsgi_1         |     j_issue = JIRA_Issue.objects.get(finding=finding)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
uwsgi_1         |     self.model._meta.object_name
uwsgi_1         | DoesNotExist: JIRA_Issue matching query does not exist.
```

## Possible solution for that:
Put everything in try except blocks. It helps in this case, but I'm sure there are more cases, at least in `views.py`. I'm not deep enough into the code that I find a more generic solution like a `load_jira_issue()` function that catches the exceptions and returns `None` instead. It would be easier to handle, but I'm not sure where to put that. I'm willing to create a PR, but I think a major contributor should have a look first to find a more generic solution.

Here is a possible fix for  `finding/views.py` line 350+
```python
            # Jira ticket update
            try:
                if defect_choice == "Close Finding":
                    jira = get_jira_connection(finding)
                    if jira:
                        j_issue = JIRA_Issue.objects.get(finding=finding)
                        issue = jira.issue(j_issue.jira_id)
                        # If the issue id is closed jira will return Reopen Issue
                        resolution_id = jira_get_resolution_id(jira, issue,
                                                            "Reopen Issue")
                        if resolution_id is None:
                            resolution_id = jira_get_resolution_id(
                                jira, issue, "Resolve Issue")
                            jira_change_resolution_id(jira, issue, resolution_id)
                            new_note.entry = new_note.entry + "\nJira issue set to resolved."
                else:
                    # Re-open finding with notes stating why re-open
                    jira = get_jira_connection(finding)
                    j_issue = JIRA_Issue.objects.get(finding=finding)
                    issue = jira.issue(j_issue.jira_id)
                    resolution_id = jira_get_resolution_id(jira, issue,
                                                        "Resolve Issue")
                    if resolution_id is not None:
                        jira_change_resolution_id(jira, issue, resolution_id)
                        new_note.entry = new_note.entry + "\nJira issue re-opened."
            except:
                pass
```

**Thanks for your effort!**

### PR DESCRIPTION
**Pull request by sbani**
Hi,

I tried to create a PR compatible to your `CONTBUTION.md`, but I'm not a 100% sure if I did everything needed. Please give me a hint, if I'm missing something. I'm happy to update my code where it's needed.

You can see the differences easier with `git diff -w`

---

This commit fixes an issue during finding review. As soon as you have
Jira configured, but no Jira ticket appended, an exception was thrown
because the system wanted to close the Jira ticket at the same time.
The Jira ticket is now no longer required - you can close the finding
without a related Jira ticket.

Closes #1081

### CODE REVIEW

**Comment by sbani** [comment]
I hope that's better.

**Comment by valentijnscholten** [comment]
Yes. Am I correct to assume you have also tested this locally?

**Comment by sbani** [comment]
I tested it locally without JIRA config and with JIRA config. Without and with the fix. I haven't tested sending updates to a JIRA instance.
It should be enough because I can reproduce the error and I can use the fix without an error. 

But I'm honest, I'm not 100% sure because it's my first PR for this project and I'm not feeling comfortable saying it's tested well enough.

**Comment by devGregA** [comment]
@sbani congrats on you first PR! Reviewing

**Comment by sbani** [comment]
Thank you all for your effort

**Pull request merged**
