### PR TITLE
npm audit scan: make dedupe work with hashes in paths

### LINKED ISSUE #4306: npm audit: dedupe fails for git dependencies
Whenever a dependency is installed via git, npm audit obscures the name and replaces it with a hash in the path attribute. This hash is different for every run, consufing the dedupe algo in defect dojo:

run x:

```
      "findings": [
        {
          "version": "1.3.4",
          "paths": [
            "c748e76b6a1b63450590f72e14f9b53ad357bc64632ff0bda73d00799c4a0a91>send>mime",
            "express>serve-static>send>mime"
          ],
          "dev": false,
          "optional": false,
          "bundled": false
        }
      ],
```

run x +1:
```
      "findings": [
        {
          "version": "1.3.4",
          "paths": [
            "7f888b06cc55dd893be344958d300da5ca1d84eebd0928d8bcb138b4029eff9f>send>mime",
            "express>serve-static>send>mime"
          ],
          "dev": false,
          "optional": false,
          "bundled": false
        }
      ],
```

### PR DESCRIPTION
**Pull request by valentijnscholten**
fixes #4306

Whenever a dependency is installed via git, npm audit obscures the name and replaces it with a hash in the path attribute. This hash is different for every run, consufing the dedupe algo in defect dojo:

run x:

```
      "findings": [
        {
          "version": "1.3.4",
          "paths": [
            "c748e76b6a1b63450590f72e14f9b53ad357bc64632ff0bda73d00799c4a0a91>send>mime",
            "express>serve-static>send>mime"
          ],
          "dev": false,
          "optional": false,
          "bundled": false
        }
      ],
```

run x +1:
```
      "findings": [
        {
          "version": "1.3.4",
          "paths": [
            "7f888b06cc55dd893be344958d300da5ca1d84eebd0928d8bcb138b4029eff9f>send>mime",
            "express>serve-static>send>mime"
          ],
          "dev": false,
          "optional": false,
          "bundled": false
        }
      ],
```

We could remove the file_path from the dedupe settings, but that may lead to confusion as well. So I decided to replace all these hashes with a static value to that it's always the same: `censored_by_npm_audit>send>mime`.

updated unit tests

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]

**Comment by damiencarol** [comment]
@valentijnscholten your PR is excellent but considering how this parser manage the `file_path` attribute give me the filling that we should modify the de-duplication configuration for this one to rely on something else.

**Comment by valentijnscholten** [comment]
Yeah, I was thinking the same. But still might be good to have a predictable/constant file path between runs.

**Review by damiencarol — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved.

But that done, I should note I don't use npm audit and, even though I'll be approval #2, it looks like @valentijnscholten was potentially reconsidering this PR so I'll not merge this in case he has changes he wants to make.

**Comment by valentijnscholten** [comment]
Although we may decide to remove filepath from the hashcode fields, some people might still want to use it that way, so I am proceeding with merging this PR.

**Pull request merged**
