### PR TITLE
Adding GH action on dev branch

### PR DESCRIPTION
**Pull request by madchap**
Explicitly adding workflow on dev too.
GH doc seems to say it has to be on the branch, but I think/thought it's only on the default branch. Would not make sense otherwise.
But for the sake of troubleshooting I guess..

### CODE REVIEW

**Comment by madchap** [comment]
I guess not in the end. It works on other test repos, not sure what's wrong here.

**Comment by madchap** [comment]
Correction -- so re-opening.

**Comment by madchap** [comment]
Somewhat unrelated, but while performing tests, our "branching" diagram fails to produce png/svg, because the github action uses a too old version of plantuml and there is something too "new" in there. 

So a linked PR https://github.com/cloudbees/plantuml-github-action/pull/4 there to bump the version.

Otherwise, the workflow file needs to be present in branches where you want it to trigger, and not only the default branch.

**Comment by mtesauro** [comment]
Are you wanting a review on this cause it LGTM? Let me know.

**Comment by madchap** [comment]
No, it's all good.. but still needs to approvals to merge on dev ;-)

**Pull request merged**
