### PR TITLE
Rustyhog: Make JIRA/Confluence URLs clickable in description

### PR DESCRIPTION
**Pull request by valentijnscholten**
image

### CODE REVIEW

**Comment by valentijnscholten** [comment]
No rebase was needed, just needed to change the base branch value on the PR above.

**Review by Maffooch — APPROVED** [review]

**Review by mtesauro — APPROVED** [review]
Approved

Nice to see a PR from Val! :+1:

**Comment by Maffooch** [comment]
I did not realize tests were failing. Here are the issues

```
2023-01-16T17:51:38.9908799Z [36muwsgi_1         |[0m ======================================================================
2023-01-16T17:51:38.9909466Z [36muwsgi_1         |[0m FAIL: test_parse_file_with_multiple_vuln_has_multiple_finding_essexhog_content (unittests.tools.test_rusty_hog_parser.TestRustyhogParser.test_parse_file_with_multiple_vuln_has_multiple_finding_essexhog_content)
2023-01-16T17:51:38.9909780Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-01-16T17:51:38.9910009Z [36muwsgi_1         |[0m Traceback (most recent call last):
2023-01-16T17:51:38.9910473Z [36muwsgi_1         |[0m   File "/app/unittests/tools/test_rusty_hog_parser.py", line 120, in test_parse_file_with_multiple_vuln_has_multiple_finding_essexhog_content
2023-01-16T17:51:38.9910937Z [36muwsgi_1         |[0m     self.assertIn("**Confluence URL:** https://confluence.com/pages/viewpage.action?pageId=12345", findings[0].description)
2023-01-16T17:51:38.9911905Z [36muwsgi_1         |[0m AssertionError: '**Confluence URL:** https://confluence.com/pages/viewpage.action?pageId=12345' not found in "**This string was found:** ['-----BEGIN EC PRIVATE KEY-----']\n**Confluence URL:** [https://confluence.com/pages/viewpage.action?pageId=12345](https://confluence.com/pages/viewpage.action?pageId=12345)\n**Confluence Page ID:** 12345"
2023-01-16T17:51:38.9912048Z [36muwsgi_1         |[0m 
2023-01-16T17:51:38.9912297Z [36muwsgi_1         |[0m ======================================================================
2023-01-16T17:51:38.9912972Z [36muwsgi_1         |[0m FAIL: test_parse_file_with_multiple_vuln_has_multiple_finding_gottingenhog_content (unittests.tools.test_rusty_hog_parser.TestRustyhogParser.test_parse_file_with_multiple_vuln_has_multiple_finding_gottingenhog_content)
2023-01-16T17:51:38.9913414Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-01-16T17:51:38.9913640Z [36muwsgi_1         |[0m Traceback (most recent call last):
2023-01-16T17:51:38.9914109Z [36muwsgi_1         |[0m   File "/app/unittests/tools/test_rusty_hog_parser.py", line 93, in test_parse_file_with_multiple_vuln_has_multiple_finding_gottingenhog_content
2023-01-16T17:51:38.9914532Z [36muwsgi_1         |[0m     self.assertIn("**JIRA url:** https://jira.com/browse/TEST-123", findings[0].description)
2023-01-16T17:51:38.9915246Z [36muwsgi_1         |[0m AssertionError: '**JIRA url:** https://jira.com/browse/TEST-123' not found in "**This string was found:** ['password: jeans']\n**JIRA Issue ID:** TEST-123\n**JIRA location:** Issue Description\n**JIRA url:** [https://jira.com/browse/TEST-123](())"
2023-01-16T17:51:38.9915389Z [36muwsgi_1         |[0m 
2023-01-16T17:51:38.9915693Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-01-16T17:51:38.9915903Z [36muwsgi_1         |[0m Ran 2247 tests in 628.618s
2023-01-16T17:51:38.9916041Z [36muwsgi_1         |[0m 
2023-01-16T17:51:38.9916250Z [36muwsgi_1         |[0m FAILED (failures=2, skipped=364)
```

**Comment by mtesauro** [comment]
LOL. I got caught by that as well - just too excited to see a PR by @valentijnscholten

**Comment by valentijnscholten** [comment]
Yeah Greg asked me to pentest the PR approval flow ;-)

**Pull request merged**
