### PR TITLE
RENAMED: Finding.is_Mitigated to is_mitigated

### PR DESCRIPTION
**Pull request by valentijnscholten**
came across this annoying typo and decided to fix it. 
let me know what you think, might be nitpicking, might be good for readability!

### CODE REVIEW

**Review by damiencarol — APPROVED** [review]

**Comment by madchap** [comment]
This would probably need a heads-up in the release notes. I - for one - am going to be impacted with regards to scripts outside of DefectDojo.

**Comment by madchap** [comment]
Adding the `Breaking Changes` label. It's bending the label's arm a bit, dunno. Better suggestion?

**Review by madchap — APPROVED** [review]

**Comment by valentijnscholten** [comment]
hmm thought might not be too big an issue for the API, but maybe we should do this in v2.0 where some other breaking changes might take place?

**Comment by madchap** [comment]
Removing my approval for now to avoid a too quick merge. Let's take it on slack?

**Comment by madchap** [comment]
Sounds like this one will need to make it in sooner to avoid potential future headaches...

**Pull request merged**
