### PR TITLE
Feat(cloud-sql-proxy): Migrate from gce-proxy to cloud-sql-proxy to enable termination of proxy sidecar after initializer job completion

### PR DESCRIPTION
**Pull request by 1azunna**
**Description**

### Helm Chart Updates
- Updated the CloudSQL proxy containers to use cloud-sql-proxy instead of gce-proxy which provides a way to gracefully terminate the cloud-sql-proxy via a `/quitquitquit` endpoint. 
- Updated the initializer script to terminate cloudsql proxy sidecar on `EXIT`

**Test results**
Helm Telmplate renders valid yaml templates

**Documentation**

Please update any documentation when needed in the [documentation folder](https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs))

**Checklist**

This checklist is for your information.

- [x] Make sure to rebase your PR against the very latest `dev`.
- [x] Features/Changes should be submitted against the `dev`.
- [ ] Bugfixes should be submitted against the `bugfix` branch.
- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.11 compliant.
- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [ ] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [ ] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

**Extra information**

Please clear everything below when submitting your pull request, it's here purely for your information.

Moderators: Labels currently accepted for PRs:
- Import Scans (for new scanners/importers)
- enhancement
- performance
- feature
- bugfix
- maintenance (a.k.a chores)
- dependencies
- New Migration (when the PR introduces a DB migration)
- settings_changes (when the PR introduces changes or new settings in settings.dist.py)

# Contributors: Git Tips
## Rebase on dev branch
If the dev branch has changed since you started working on it, please rebase your work after the current dev.

On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
 git mergetool
 git rebase --continue
 ```

When everything's fine on your local branch, force push to your `myOrigin` remote:
```
git push myOrigin --force-with-lease
```

To cancel everything:
```
git rebase --abort
```

## Squashing commits
```
git rebase -i origin/dev
```
- Replace `pick` by `fixup` on the commits you want squashed out
- Replace `pick` by `reword` on the first commit if you want to change the commit message
- Save the file and quit your editor

Force push to your `myOrigin` remote:
```
git push myOrigin --force-with-lease
```

### CODE REVIEW

**Comment by cneill** [comment]
If we were to add the features currently included for GKE to support EKS, AKS, etc, the helm chart would grow endlessly with cloud provider-specific details. To avoid cluttering the chart with features that may not be relevant for all Dojo users, and that reviewers may not be able to test before merging, we are considering breaking out these sorts of features in the [Community-Contribs](https://github.com/DefectDojo/Community-Contribs) repository.

If you have any thoughts on this approach and/or its implementation, please let us know. For now, I'd suggest breaking out the changes not related to `cloud-sql-proxy` into their own PR.

**Comment by mtesauro** [comment]
@cneill I agree with that approach - it's hard for use to test all the possible deployments that can happen for k8s so it makes sense to have the main ones in this repo and the cloud provider specific ones in the Community Contrib repo.

That way if I only care about GKE, then I take the one from this repo, add in the GKE stuff from Community contribs and I'm good to go.

If you only care about EKS, then you'd do the same but grab the AWS stuff you want from community contribs.

Yeah, the more I think about that the better that is as we can have more trust in our tests of the main parts of helm here if we push the vendor specific stuff out to community contribs.

I don't know about you but keeping up with one cloud vendor's churn is more than enough for me.

**Comment by 1azunna** [comment]
As for the QuitQuitQuit script, the alternative would be using curl. There's no curl binary in the defectdojo images which means users would have to use a custom image. We could add an `exec $@` to the end of the `entrypoint-initializer.sh` to all us run command after the initializer script. This way we can terminate sidecars used in the k8s Job.

**Comment by 1azunna** [comment]
Any updates on whether this will be merged or not?

**Comment by mtesauro** [comment]
Closed as stale

**Pull request closed without merging**
