### PR TITLE
:sparkles: merge veracode

### PR DESCRIPTION
**Pull request by manuel-sommer**
merge veracode source clear with veracode

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@Maffooch, the unittests with "fixtures = ['dojo_testdata.json']" fail because dojo_testdata.json contains Veracode Scan, but I don't know the real cause why it fails. What do I have to do to fix the unittests?

**Comment by Maffooch** [comment]
I think the failing tests could be related to the creation of the `Veracode Scan` test type in the migration

Also curious about the `Veracode SourceClear Scan` that is being referenced in the migration, but not anywhere else in the code

**Comment by manuel-sommer** [comment]
> I think the failing tests could be related to the creation of the Veracode Scan test type in the migration

Then, I will just fix the failing tests. 

> Also curious about the Veracode SourceClear Scan that is being referenced in the migration, but not anywhere else in the code

The Veracode Source Clear Scan is in the migration as the exisiting Veracode Source Clear Scan parser is migrated to Veracode Scan to have one parser for the vendor Veracode with multiple scanners. This is also what I have done in the past with e.g. OpenVAS CSV and OpenVAS XML or Clair Klar Scan and Clair Scan

**Comment by manuel-sommer** [comment]
@Maffooch or @kiblik, could you please help here? I am completely stuck on how to resolve the unittest problem here.

**Comment by Maffooch** [comment]
@manuel-sommer I do not see anything glaringly obvious here. I can try to make some in the future to pull this down and just play around with it, but I cannot make strong commitment to that

**Comment by manuel-sommer** [comment]
These two new failing unittests are weird. They don't have anything to do with this PR.

**Comment by manuel-sommer** [comment]
Shall I close this PR @mtesauro because of https://github.com/DefectDojo/django-DefectDojo/discussions/9690 ?

**Pull request closed without merging**
